import type { ArticleQuiz } from "@/lib/article";

export const ARTICLE_QUIZ_EXTRA: Record<number, ArticleQuiz[]> = {
  1: [
    { q: "Bare סוּס is…", he: "סוּס", choices: ["Indefinite — a horse / horse", "The horse", "Two horses"], answer: "Indefinite — a horse / horse", why: "No article." },
    { q: "הַסּוּס is…", he: "הַסּוּס", choices: ["The horse", "A horse", "Horses"], answer: "The horse", why: "Article." },
    { q: "A proper name is definite…", choices: ["Without הַ", "Only with הַ", "Never"], answer: "Without הַ", why: "Egypt, YHWH, Israel." },
    { q: "Which is a proper name (definite by itself)?", choices: ["מִצְרַיִם", "מֶלֶךְ", "סוּס"], answer: "מִצְרַיִם", why: "Egypt." },
    { q: "“Your book” is definite because of…", choices: ["The possessive suffix", "The dual ending", "An invisible הַ"], answer: "The possessive suffix", why: "Third kind of definite." },
    { q: "English must sometimes add “a” because…", choices: ["Hebrew has no indefinite article", "Hebrew forgot the word", "Every noun is definite"], answer: "Hebrew has no indefinite article", why: "Translation, not a missing letter." },
    { q: "הַ in the class vocab list means…", he: "הַ", choices: ["the", "and", "in"], answer: "the", why: "Class particle." },
    { q: "Strip the article before you look the noun up. הַמָּקוֹם →", he: "הַמָּקוֹם", choices: ["מָקוֹם", "הַמָּקוֹם", "מְקֹמוֹת"], answer: "מָקוֹם", why: "Lexical form." },
    { q: "Is יְהוָה indefinite without הַ?", he: "יְהוָה", choices: ["No — it is a name, so definite", "Yes — bare means “a”", "It is a verb"], answer: "No — it is a name, so definite", why: "Proper names." },
    { q: "In one verse you can have a bare noun and an articular noun. That means…", choices: ["Indefinite next to definite — read each prefix", "Both must be “the”", "The pointing is wrong"], answer: "Indefinite next to definite — read each prefix", why: "Ps 24:8 מֶלֶךְ … הַכָּבוֹד." },
    { q: "Most prefixed ה letters you meet will be…", choices: ["The article", "The interrogative ה", "A root letter"], answer: "The article", why: "Train that expectation, then check the spelling." },
    { q: "אֵשׁ without the article is…", he: "אֵשׁ", choices: ["Fire / a fire — indefinite", "The fire", "The woman"], answer: "Fire / a fire — indefinite", why: "Class lemma אֵשׁ. Article would be הָאֵשׁ." },
  ],
  2: [
    { q: "הַלֵּב is…", he: "הַלֵּב", choices: ["The heart — הַ + dagesh in ל", "A heart", "Hearts"], answer: "The heart — הַ + dagesh in ל", why: "Regular article." },
    { q: "הַמָּקוֹם is…", he: "הַמָּקוֹם", choices: ["The place", "A place", "Places"], answer: "The place", why: "Dagesh in מ." },
    { q: "הַכֹּהֵן is…", he: "הַכֹּהֵן", choices: ["The priest — article + dagesh in כ", "A priest", "Priests"], answer: "The priest — article + dagesh in כ", why: "Begadkephat forte from the article." },
    { q: "The dagesh of the regular article is…", choices: ["Forte — it doubles the first letter", "Always lene only", "A שׁ-dot"], answer: "Forte — it doubles the first letter", why: "That is why gutturals refuse it." },
    { q: "הַשָּׁמַיִם has dagesh in ש, so the article is…", he: "הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Regular הַ", "Compensatory הָ", "Seghol הֶ"], answer: "Regular הַ", why: "ש can take dagesh." },
    { q: "הַכּוֹכָבִים (the stars) is…", he: "הַכּוֹכָבִים", choices: ["Regular article on a masculine plural", "Dual of star", "No article"], answer: "Regular article on a masculine plural", why: "הַ + ִים. Strip both." },
    { q: "Citation form in the vocab game for “sea” is…", choices: ["יָם — not הַיָּם and not בַּיָּם", "הַיָּם", "בַּיָּם"], answer: "יָם — not הַיָּם and not בַּיָּם", why: "Class needs the same lemma." },
    { q: "הַדָּבָר is…", he: "הַדָּבָר", choices: ["The word — הַ + dagesh in ד", "A word", "Words"], answer: "The word — הַ + dagesh in ד", why: "Regular." },
    { q: "If you see pathach under ה and dagesh in the next letter, name it…", choices: ["Regular article", "Virtual doubling", "Conjunction"], answer: "Regular article", why: "Default picture." },
    { q: "הַזָּהָב vs זָהָב. The difference is…", he: "הַזָּהָב", choices: ["The article (definite gold)", "A new root", "Plural"], answer: "The article (definite gold)", why: "Class lemma זָהָב." },
    { q: "הַכֶּסֶף is…", he: "הַכֶּסֶף", choices: ["The silver — regular article", "Indefinite silver", "The gold"], answer: "The silver — regular article", why: "כֶּסֶף plus הַ." },
    { q: "Begadkephat with the article: the old lene…", choices: ["Becomes forte — same mark, doubling job", "Is erased", "Moves to ה"], answer: "Becomes forte — same mark, doubling job", why: "הַבַּיִת." },
  ],
  3: [
    { q: "הָאִשָּׁה is…", he: "הָאִשָּׁה", choices: ["The woman — compensatory on א", "Virtual doubling", "No article"], answer: "The woman — compensatory on א", why: "הָ." },
    { q: "הָעָם uses הָ because…", he: "הָעָם", choices: ["ע refuses dagesh (compensatory)", "ע takes dagesh forte", "It is bump ו"], answer: "ע refuses dagesh (compensatory)", why: "Also a vowel-changing noun." },
    { q: "הָרָקִיעַ (the expanse) is compensatory because…", he: "הָרָקִיעַ", choices: ["It begins with ר", "It begins with ב", "It is dual"], answer: "It begins with ר", why: "ר = no dagesh, vowel lengthens." },
    { q: "הַחֹדֶשׁ (the month) is typically…", he: "הַחֹדֶשׁ", choices: ["Virtual doubling — הַ before ח", "Compensatory הָ", "Seghol הֶ"], answer: "Virtual doubling — הַ before ח", why: "Pathach stays." },
    { q: "Which vowel is under the article in הֶעָנָן?", he: "הֶעָנָן", choices: ["Seghol", "Pathach", "Qamets"], answer: "Seghol", why: "Name it out loud: ה-seghol." },
    { q: "Which vowel is under the article in הַחֶרֶב?", he: "הַחֶרֶב", choices: ["Pathach", "Qamets", "Seghol"], answer: "Pathach", why: "Virtual doubling." },
    { q: "Which vowel is under the article in הָאֵשׁ?", he: "הָאֵשׁ", choices: ["Qamets", "Pathach", "Seghol"], answer: "Qamets", why: "Compensatory." },
    { q: "Gutturals excluding ר take vocal shewa.", choices: ["False — they take a hateph instead; they may take silent shewa", "True", "Only א does"], answer: "False — they take a hateph instead; they may take silent shewa", why: "ר follows ordinary shewa rules." },
    { q: "Can ר take dagesh from the article?", choices: ["No", "Yes, forte", "Only lene"], answer: "No", why: "All gutturals and ר refuse dagesh." },
    { q: "הֶהָרִים vs הָהָר. The plural uses seghol because…", he: "הֶהָרִים", choices: ["Unaccented הָ after the article", "Mountains are feminine", "It is bump"], answer: "Unaccented הָ after the article", why: "Same rule as הֶעָנָן." },
    { q: "Pick the compensatory form.", choices: ["הָעִיר", "הַהֵיכָל", "הֶחָכָם"], answer: "הָעִיר", why: "ע, qamets." },
    { q: "Pick the virtual-doubling form.", choices: ["הַהֵיכָל", "הָאִישׁ", "הֶעָנָן"], answer: "הַהֵיכָל", why: "He, pathach." },
  ],
  4: [
    { q: "הַיְלָדִים vs הַיָּם — י in the first has…", choices: ["Vocal shewa and no dagesh", "Dagesh and qamets", "Hateph"], answer: "Vocal shewa and no dagesh", why: "That is why dagesh drops." },
    { q: "Lexical form of הַמְרַגְּלִים is not on the article particle list. You still…", he: "הַמְרַגְּלִים", choices: ["Strip הַ and ִים, then hunt the singular", "Leave the whole form in the lexicon", "Call it a verb only"], answer: "Strip הַ and ִים, then hunt the singular", why: "Same method as every noun." },
    { q: "אֲרוֹן with the article is typically…", he: "הָאָרוֹן", choices: ["הָאָרוֹן — another vowel-changing noun", "הַאֲרוֹן with hateph kept", "הֶאֲרוֹן"], answer: "הָאָרוֹן — another vowel-changing noun", why: "Learn the pair with אֶרֶץ, עַם, גַּן, הַר." },
    { q: "Does sqnmlwy always drop dagesh?", choices: ["Frequently, not as a machine. Check the pointing you see.", "Always, without exception", "Never"], answer: "Frequently, not as a machine. Check the pointing you see.", why: "Name what is on the page." },
    { q: "הָעָם is both compensatory and…", he: "הָעָם", choices: ["A noun whose own pathach lengthened", "A dual", "The conjunction"], answer: "A noun whose own pathach lengthened", why: "Two changes." },
    { q: "Look up הָהָר under…", he: "הָהָר", choices: ["הַר", "הָר", "הֶהָרִים"], answer: "הַר", why: "Indefinite singular." },
    { q: "Look up הַגָּן under…", he: "הַגָּן", choices: ["גַּן", "גָּן", "הַגַּן"], answer: "גַּן", why: "The qamets is from the article sitting there." },
    { q: "In Gen 2:10 הַגָּן, ג has dagesh because…", he: "הַגָּן", ref: "Gen 2:10", choices: ["ג can take the article’s forte", "ג is a guttural", "It is lene only and the article is missing"], answer: "ג can take the article’s forte", why: "Regular article + vowel change in the noun." },
    { q: "הֶהָרִים should not be looked up as a new lemma הֶהר. Look up…", he: "הֶהָרִים", choices: ["הַר", "הֶהָר", "רִים"], answer: "הַר", why: "Article spelling + plural." },
    { q: "People with the article is…", he: "הָעָם", choices: ["הָעָם", "הַעַם", "הָעַם with pathach on ע"], answer: "הָעָם", why: "Both vowels are qamets." },
    { q: "Boys with the article, plural: the י has…", he: "הַיְלָדִים", choices: ["Vocal shewa, no dagesh", "Dagesh forte", "Silent shewa only"], answer: "Vocal shewa, no dagesh", why: "הַיְ." },
    { q: "When the first vowel of a noun surprises you after הַ / הָ, first…", choices: ["Check whether it is one of the short pair-list nouns", "Assume a new root", "Ignore it"], answer: "Check whether it is one of the short pair-list nouns", why: "אֶרֶץ, עַם, גַּן, הַר, אֲרוֹן." },
  ],
  5: [
    { q: "וְאִשָּׁה is…", he: "וְאִשָּׁה", choices: ["And a woman — default shewa", "Bump shureq", "The article"], answer: "And a woman — default shewa", why: "א is not a bump letter." },
    { q: "וּפַרְעֹה uses shureq because…", he: "וּפַרְעֹה", choices: ["פ is a bump letter", "פ is a guttural", "It is hateph match"], answer: "פ is a bump letter", why: "ב מ פ." },
    { q: "וְהָאִשָּׁה is…", he: "וְהָאִשָּׁה", choices: ["And the woman — ו + article", "And a woman", "The woman only"], answer: "And the woman — ו + article", why: "Default ו, then compensatory article." },
    { q: "וַאֲנָשִׁים matches which hateph?", he: "וַאֲנָשִׁים", choices: ["Hateph pathach → pathach on ו", "Hateph seghol", "Hateph qamets"], answer: "Hateph pathach → pathach on ו", why: "אֲ → וַאֲ." },
    { q: "וָלֶחֶם is…", he: "וָלֶחֶם", ref: "Gen 45:23", choices: ["And bread — qamets ו on a short / accented word", "Bump on ל", "The article"], answer: "And bread — qamets ו on a short / accented word", why: "לֶחֶם is initially accented." },
    { q: "וְכֶסֶף in Gen 24:35 is default shewa because…", he: "וְכֶסֶף", ref: "Gen 24:35", choices: ["כ is not a bump letter", "כ is מ", "It should have been וּ"], answer: "כ is not a bump letter", why: "Beside וּבָקָר in the same list." },
    { q: "וְזָהָב is…", he: "וְזָהָב", ref: "Gen 24:35", choices: ["And gold — default וְ", "Bump וּ", "Article הַ"], answer: "And gold — default וְ", why: "ז is not B/M/P." },
    { q: "Two bump letters in a row still each take…", choices: ["Shureq וּ on the conjunction if it is the prefix", "Shewa", "Qamets"], answer: "Shureq וּ on the conjunction if it is the prefix", why: "The rule is about the first letter of the host word." },
    { q: "Class vocab lists the conjunction as…", he: "וְ", choices: ["וְ — and, but, also, even, then", "וּ only", "וֵ only"], answer: "וְ — and, but, also, even, then", why: "Class particle." },
    { q: "וֵאלֹהִים is not the ordinary hateph match. Ordinary would have been…", he: "וֵאלֹהִים", choices: ["וֶאֱלֹהִים", "וַאֲלֹהִים", "וּאֱלֹהִים"], answer: "וֶאֱלֹהִים", why: "The special form drops the hateph and uses tsere." },
    { q: "וָצֹאן (and sheep) is the qamets-ו spelling on a…", he: "וָצֹאן", choices: ["Monosyllabic noun", "Bump letter", "Guttural article"], answer: "Monosyllabic noun", why: "Same family as וָלֶחֶם, וָבֹהוּ." },
    { q: "If the host word begins with vocal shewa, ו is usually…", choices: ["וּ", "וְ", "וִ always"], answer: "וּ", why: "Then check the יְ contraction." },
  ],
  6: [
    { q: "Gen 1:1 has הַשָּׁמַיִם and הָאָרֶץ. That pair is…", he: "הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Regular article + compensatory/vowel-change article", "Two virtual doublings", "No articles"], answer: "Regular article + compensatory/vowel-change article", why: "Week 3 on line one of the Torah." },
    { q: "וְאֵת in Gen 1:1 is…", he: "וְאֵת", ref: "Gen 1:1", choices: ["Default conjunction on the object marker", "The article", "Bump shureq"], answer: "Default conjunction on the object marker", why: "וְ + אֵת." },
    { q: "הַיּוֹם as “today” is still…", he: "הַיּוֹם", choices: ["The article on יוֹם, used like “this day”", "A new lemma hayom", "Indefinite"], answer: "The article on יוֹם, used like “this day”", why: "Special use, same prefix." },
    { q: "Vocative הַמֶּלֶךְ still looks like…", he: "הַמֶּלֶךְ", choices: ["The ordinary article on מֶלֶךְ", "Compensatory הָ", "No prefix"], answer: "The ordinary article on מֶלֶךְ", why: "Context supplies “O king.”" },
    { q: "לַיַּבָּשָׁה (to the dry land) is the same preview as לָאוֹר: …", he: "לַיַּבָּשָׁה", choices: ["Preposition + article, ה dropped, dagesh on י", "Conjunction + noun", "Indefinite"], answer: "Preposition + article, ה dropped, dagesh on י", why: "Gen 1:10. Next chapter drills it." },
    { q: "Jonah 1:9 הַיָּם וְאֶת הַיַּבָּשָׁה. Both nouns have…", he: "הַיָּם", ref: "Jonah 1:9", choices: ["The regular article", "Compensatory הָ", "No article"], answer: "The regular article", why: "י and י. Pathach + dagesh." },
    { q: "When prefixes stack, read them…", choices: ["Left to right in English order of sense: and/the/noun — but the Hebrew is prefix-prefix-noun from the right", "Only the last letter", "Backwards from the root first always"], answer: "Left to right in English order of sense: and/the/noun — but the Hebrew is prefix-prefix-noun from the right", why: "וְהָאָרֶץ: ו, article, noun." },
    { q: "Study often groups…", choices: ["Nouns with the article and ו", "Only article spelling, no nouns", "Only names"], answer: "Nouns with the article and ו", why: "The course can read them in one week. Games stay separate." },
    { q: "Game Recognize for the article still wants the citation forms…", choices: ["הַ and וְ, plus class nouns (יָם not הַיָּם)", "Every prefixed spelling as its own lemma", "Only English"], answer: "הַ and וְ, plus class nouns (יָם not הַיָּם)", why: "This grammar path is where the spellings are drilled." },
    { q: "הַדְּבָרִים הָאֵלֶּה — both words are definite. The second is definite because…", he: "הָאֵלֶּה", ref: "Deut 6:6", choices: ["It also has the article (demonstrative with הַ)", "It is a name", "It is dual"], answer: "It also has the article (demonstrative with הַ)", why: "These words. Article on both." },
    { q: "A superlative flavor of the article (the good → the best) still looks like…", choices: ["Ordinary הַ / הָ / הֶ on the adjective or noun", "A new prefix שֶׁ only", "The dual"], answer: "Ordinary הַ / הָ / הֶ on the adjective or noun", why: "Context, not a new mark." },
    { q: "If you cannot yet name the article’s vowel, you can still…", choices: ["See the ה, call it “the,” then come back for הָ vs הַ vs הֶ", "Skip the word", "Call it ו"], answer: "See the ה, call it “the,” then come back for הָ vs הַ vs הֶ", why: "Catch first, spelling second." },
  ],
};
