/**
 * Vocal/silent shewa and qamets / qamets hatuf diagnosis drills.
 * Words and “why” follow the BBH 3rd-ed. notes (Adeola Adegbolagun).
 */

export type ClassifyKind = "shewa" | "qamets";
export type ShewaAnswer = "vocal" | "silent";
export type QametsAnswer = "qamets" | "hatuf";
export type ClassifyAnswer = ShewaAnswer | QametsAnswer;

export type ClassifyItem = {
  id: string;
  kind: ClassifyKind;
  word: string;
  hit: string;
  markOn: string;
  gloss: string;
  syllables: string;
  answer: ClassifyAnswer;
  lead: string;
  why: string;
  book: string;
  chapter: number;
  verse: number;
  he: string;
  en: string;
  verseHit: string;
};

export const CLASSIFY_SHEWA: ClassifyItem[] = [
  {
    id: "bereshit-vocal",
    kind: "shewa",
    word: "בְּרֵאשִׁית",
    hit: "בְּ",
    markOn: "the shewa under bet",
    gloss: "in beginning of",
    syllables: "בְּ | רֵא | שִׁית",
    answer: "vocal",
    lead: "Where in the word does this shewa sit — the first letter, the middle, or the end?",
    why: "A shewa at the beginning of a word is always vocal. בְּ is the open first syllable.",
    book: "Gen",
    chapter: 1,
    verse: 1,
    he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ",
    en: "In the beginning God created the heavens and the earth.",
    verseHit: "בְּרֵאשִׁית",
  },
  {
    id: "samuel-vocal",
    kind: "shewa",
    word: "שְׁמוּאֵל",
    hit: "שְׁ",
    markOn: "the shewa under shin",
    gloss: "Samuel",
    syllables: "שְׁ | מוּ | אֵל",
    answer: "vocal",
    lead: "Can a Hebrew word begin with a silent shewa?",
    why: "Initial shewa is always vocal. Silent shewa would leave the word with no opening vowel.",
    book: "1Sam",
    chapter: 3,
    verse: 10,
    he: "וַיֹּאמֶר שְׁמוּאֵל דַּבֵּר כִּי שֹׁמֵעַ עַבְדֶּךָ",
    en: "Samuel said, “Speak, for your servant is listening.”",
    verseHit: "שְׁמוּאֵל",
  },
  {
    id: "lekha-vocal",
    kind: "shewa",
    word: "לְךָ",
    hit: "לְ",
    markOn: "the shewa under lamed",
    gloss: "to you",
    syllables: "לְ | ךָ",
    answer: "vocal",
    lead: "This lamed is a prefixed preposition. Is its shewa the first vowel of the word?",
    why: "Prefix לְ opens the word, so its shewa is vocal.",
    book: "Gen",
    chapter: 17,
    verse: 8,
    he: "וְנָתַתִּי לְךָ וּלְזַרְעֲךָ אַחֲרֶיךָ אֵת אֶרֶץ מְגֻרֶיךָ",
    en: "I will give to you and to your offspring after you the land of your sojournings.",
    verseHit: "לְךָ",
  },
  {
    id: "devar-vocal",
    kind: "shewa",
    word: "דְּבַר",
    hit: "דְּ",
    markOn: "the shewa under dalet",
    gloss: "word of (construct)",
    syllables: "דְּ | בַר",
    answer: "vocal",
    lead: "Is this shewa on the first letter of the form?",
    why: "Construct דְּבַר begins with vocal shewa. Initial shewa is always vocal.",
    book: "Deut",
    chapter: 5,
    verse: 5,
    he: "אָנֹכִי עֹמֵד בֵּין־יְהוָה וּבֵינֵיכֶם בָּעֵת הַהִוא לְהַגִּיד לָכֶם אֶת־דְּבַר יְהוָה",
    en: "I was standing between YHWH and you at that time to declare to you the word of YHWH.",
    verseHit: "דְּבַר",
  },
  {
    id: "melakhim-vocal",
    kind: "shewa",
    word: "הַמְּלָכִים",
    hit: "מְּ",
    markOn: "the shewa under mem",
    gloss: "the kings",
    syllables: "הַמּ | מְ | לָ | כִים",
    answer: "vocal",
    lead: "Look at the mem. Does it carry dagesh forte — a doubling dagesh?",
    why: "Shewa under a consonant with dagesh forte is vocal. The first mem (dagesh) closes הַמּ; the second mem takes that shewa and opens מְ.",
    book: "2Sam",
    chapter: 11,
    verse: 1,
    he: "וַיְהִי לִתְשׁוּבַת הַשָּׁנָה לְעֵת צֵאת הַמְּלָכִים",
    en: "At the turn of the year, the time when kings go out to battle.",
    verseHit: "הַמְּלָכִים",
  },
  {
    id: "devarim-vocal",
    kind: "shewa",
    word: "הַדְּבָרִים",
    hit: "דְּ",
    markOn: "the shewa under dalet",
    gloss: "the words",
    syllables: "הַדּ | דְ | בָ | רִים",
    answer: "vocal",
    lead: "The article is הַ plus a doubled first root letter. Does this dalet have dagesh forte?",
    why: "Dalet is doubled by the article. First dalet closes הַדּ; second dalet takes vocal shewa.",
    book: "Deut",
    chapter: 1,
    verse: 1,
    he: "אֵלֶּה הַדְּבָרִים אֲשֶׁר דִּבֶּר מֹשֶׁה אֶל־כָּל־יִשְׂרָאֵל",
    en: "These are the words that Moses spoke to all Israel.",
    verseHit: "הַדְּבָרִים",
  },
  {
    id: "shophetim-vocal",
    kind: "shewa",
    word: "שֹׁפְטִים",
    hit: "פְ",
    markOn: "the shewa under pe",
    gloss: "judges",
    syllables: "שֹׁ | פְ | טִים",
    answer: "vocal",
    lead: "Name the vowel immediately before this shewa. Is that vowel long, and is its syllable accented?",
    why: "The shewa follows unaccented holem (changeable long o). A shewa after an unaccented long vowel is vocal.",
    book: "Judg",
    chapter: 2,
    verse: 16,
    he: "וַיָּקֶם יְהוָה שֹׁפְטִים וַיּוֹשִׁיעוּם מִיַּד שֹׁסֵיהֶם",
    en: "YHWH raised up judges, and they saved them from the hand of those who plundered them.",
    verseHit: "שֹׁפְטִים",
  },
  {
    id: "yishmeu-vocal",
    kind: "shewa",
    word: "וַיִּשְׁמְעוּ",
    hit: "מְ",
    markOn: "the shewa under mem",
    gloss: "and they heard",
    syllables: "וַיִּשְׁ | מְ | עוּ",
    answer: "vocal",
    lead: "Two shewas sit in a row in this word. Is the highlighted one the first of the pair, or the second?",
    why: "When two shewas are contiguous inside a word, the first is silent and the second is vocal. This is the second (under mem).",
    book: "Gen",
    chapter: 3,
    verse: 8,
    he: "וַיִּשְׁמְעוּ אֶת־קוֹל יְהוָה אֱלֹהִים מִתְהַלֵּךְ בַּגָּן",
    en: "They heard the voice of YHWH God walking in the garden.",
    verseHit: "וַיִּשְׁמְעוּ",
  },
  {
    id: "malkah-silent",
    kind: "shewa",
    word: "מַלְכָּה",
    hit: "לְ",
    markOn: "the shewa under lamed",
    gloss: "queen",
    syllables: "מַלְ | כָּה",
    answer: "silent",
    lead: "What vowel sits immediately before this shewa — and is that vowel long or short?",
    why: "A shewa is silent if the previous vowel is short. Pathach under mem is short, so the shewa closes מַלְ. This is the notes’ word “queen.”",
    book: "Esth",
    chapter: 1,
    verse: 9,
    he: "גַּם וַשְׁתִּי הַמַּלְכָּה עָשְׂתָה מִשְׁתֵּה נָשִׁים",
    en: "Vashti the queen also made a feast for the women.",
    verseHit: "הַמַּלְכָּה",
  },
  {
    id: "mitsrayim-silent",
    kind: "shewa",
    word: "מִצְרַיִם",
    hit: "צְ",
    markOn: "the shewa under tsade",
    gloss: "Egypt",
    syllables: "מִצְ | רַיִם",
    answer: "silent",
    lead: "The vowel before this shewa is hireq. Is hireq a short vowel or a long vowel?",
    why: "Hireq is short, so the shewa is silent and closes מִצְ.",
    book: "Exod",
    chapter: 20,
    verse: 2,
    he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם",
    en: "I am YHWH your God, who brought you out from the land of Egypt.",
    verseHit: "מִצְרַיִם",
  },
  {
    id: "yishmeu-silent",
    kind: "shewa",
    word: "וַיִּשְׁמְעוּ",
    hit: "שְׁ",
    markOn: "the shewa under shin",
    gloss: "and they heard",
    syllables: "וַיִּשְׁ | מְ | עוּ",
    answer: "silent",
    lead: "Two shewas sit side by side. Is the highlighted shewa the first of that pair, or the second?",
    why: "The first of two contiguous shewas is silent (and it also follows short hireq). The second, under mem, is vocal.",
    book: "Gen",
    chapter: 3,
    verse: 8,
    he: "וַיִּשְׁמְעוּ אֶת־קוֹל יְהוָה אֱלֹהִים מִתְהַלֵּךְ בַּגָּן",
    en: "They heard the voice of YHWH God walking in the garden.",
    verseHit: "וַיִּשְׁמְעוּ",
  },
  {
    id: "yaladt-silent",
    kind: "shewa",
    word: "וְיֹלַדְתְּ",
    hit: "תְּ",
    markOn: "the shewa under the last tav",
    gloss: "and you shall bear",
    syllables: "וְ | יֹ | לַדְתְּ",
    answer: "silent",
    lead: "Is this shewa the last pointing in the word?",
    why: "A shewa at the end of a word is silent — the notes’ exception to “not after a short vowel ⇒ vocal.”",
    book: "Gen",
    chapter: 16,
    verse: 11,
    he: "הִנָּךְ הָרָה וְיֹלַדְתְּ בֵּן וְקָרָאת שְׁמוֹ יִשְׁמָעֵאל",
    en: "Behold, you are pregnant and shall bear a son; you shall call his name Ishmael.",
    verseHit: "וְיֹלַדְתְּ",
  },
  {
    id: "midbar-silent",
    kind: "shewa",
    word: "מִדְבָּר",
    hit: "דְ",
    markOn: "the shewa under dalet",
    gloss: "wilderness",
    syllables: "מִדְ | בָּר",
    answer: "silent",
    lead: "Hireq sits under mem, then this shewa. Is hireq short or long?",
    why: "Shewa after short hireq is silent and closes מִדְ. That closed syllable is why the next bet takes dagesh lene.",
    book: "Exod",
    chapter: 3,
    verse: 1,
    he: "וּמֹשֶׁה הָיָה רֹעֶה אֶת־צֹאן יִתְרוֹ חֹתְנוֹ אַחַר הַמִּדְבָּר",
    en: "Moses was shepherding the flock of Jethro his father-in-law, behind the wilderness.",
    verseHit: "הַמִּדְבָּר",
  },
  {
    id: "avraham-silent",
    kind: "shewa",
    word: "אַבְרָהָם",
    hit: "בְ",
    markOn: "the shewa under bet",
    gloss: "Abraham",
    syllables: "אַבְ | רָ | הָם",
    answer: "silent",
    lead: "Pathach is the vowel right before this shewa. Short or long?",
    why: "Shewa after short pathach is silent, closing אַבְ.",
    book: "Gen",
    chapter: 17,
    verse: 5,
    he: "וְלֹא־יִקָּרֵא עוֹד אֶת־שִׁמְךָ אַבְרָם וְהָיָה שִׁמְךָ אַבְרָהָם",
    en: "No longer shall your name be called Abram; your name shall be Abraham.",
    verseHit: "אַבְרָהָם",
  },
  {
    id: "yisrael-silent",
    kind: "shewa",
    word: "יִשְׂרָאֵל",
    hit: "שְׂ",
    markOn: "the shewa under sin",
    gloss: "Israel",
    syllables: "יִשְׂ | רָ | אֵל",
    answer: "silent",
    lead: "The vowel before this shewa is hireq. Long or short?",
    why: "Silent shewa after short hireq closes יִשְׂ.",
    book: "Gen",
    chapter: 32,
    verse: 29,
    he: "לֹא יַעֲקֹב יֵאָמֵר עוֹד שִׁמְךָ כִּי אִם־יִשְׂרָאֵל",
    en: "Your name shall no longer be said Jacob, but Israel.",
    verseHit: "יִשְׂרָאֵל",
  },
  {
    id: "mishpat-silent",
    kind: "shewa",
    word: "מִשְׁפָּט",
    hit: "שְׁ",
    markOn: "the shewa under shin",
    gloss: "judgment",
    syllables: "מִשְׁ | פָּט",
    answer: "silent",
    lead: "What vowel immediately precedes this shewa, and is it long or short?",
    why: "Hireq is short, so the shewa is silent and closes מִשְׁ.",
    book: "Deut",
    chapter: 16,
    verse: 18,
    he: "שֹׁפְטִים וְשֹׁטְרִים תִּתֶּן־לְךָ בְּכָל־שְׁעָרֶיךָ אֲשֶׁר יְהוָה אֱלֹהֶיךָ נֹתֵן לְךָ לְשְׁבָטֶיךָ וְשָׁפְטוּ אֶת־הָעָם מִשְׁפַּט־צֶדֶק",
    en: "You shall appoint judges and officers in all your gates… and they shall judge the people with righteous judgment.",
    verseHit: "מִשְׁפַּט",
  },
  {
    id: "shamata-silent-guttural",
    kind: "shewa",
    word: "שָׁמַעְתָּ",
    hit: "עְ",
    markOn: "the shewa under ayin",
    gloss: "you heard",
    syllables: "שָׁ | מַעְ | תָּ",
    answer: "silent",
    lead: "Ayin is a guttural. Can a guttural take vocal shewa? What vowel sits immediately before this shewa?",
    why: "A guttural cannot take vocal shewa, but it can take silent shewa. Pathach is short, so עְ is silent and closes מַעְ. The notes’ form שָׁמַעְתָּ.",
    book: "Gen",
    chapter: 3,
    verse: 17,
    he: "וּלְאָדָם אָמַר כִּי שָׁמַעְתָּ לְקוֹל אִשְׁתֶּךָ",
    en: "And to the human he said, “Because you listened to the voice of your wife…”",
    verseHit: "שָׁמַעְתָּ",
  },
  {
    id: "reuben-vocal-resh",
    kind: "shewa",
    word: "רְאוּבֵן",
    hit: "רְ",
    markOn: "the shewa under resh",
    gloss: "Reuben",
    syllables: "רְ | אוּ | בֵן",
    answer: "vocal",
    lead: "This shewa sits on resh, at the beginning of the name. Do gutturals allow that? Does resh?",
    why: "Unlike the gutturals, ר can take vocal shewa. Initial shewa is always vocal — including under resh.",
    book: "Gen",
    chapter: 29,
    verse: 32,
    he: "וַתַּהַר לֵאָה וַתֵּלֶד בֵּן וַתִּקְרָא שְׁמוֹ רְאוּבֵן",
    en: "Leah conceived and bore a son, and she called his name Reuben.",
    verseHit: "רְאוּבֵן",
  },
];

export const CLASSIFY_QAMETS: ClassifyItem[] = [
  {
    id: "dabar-first",
    kind: "qamets",
    word: "דָּבָר",
    hit: "דָּ",
    markOn: "the first qamets (under dalet)",
    gloss: "word, matter",
    syllables: "דָּ | בָר",
    answer: "qamets",
    lead: "Is the syllable of this qamets open or closed? Does the accent fall on it, or on the next syllable?",
    why: "דָּ is an open, pretonic syllable — the home of changeable long ā, not hatuf.",
    book: "Deut",
    chapter: 4,
    verse: 2,
    he: "לֹא תֹסִפוּ עַל־הַדָּבָר אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם",
    en: "You shall not add to the word that I command you.",
    verseHit: "הַדָּבָר",
  },
  {
    id: "dabar-last",
    kind: "qamets",
    word: "דָּבָר",
    hit: "בָר",
    markOn: "the second qamets (under bet)",
    gloss: "word, matter",
    syllables: "דָּ | בָר",
    answer: "qamets",
    lead: "Is this last syllable closed? Where is the accent of דָּבָר?",
    why: "בָר is a closed, accented syllable. Long qamets (ā) prefers that seat. Hatuf never takes the accent.",
    book: "Deut",
    chapter: 4,
    verse: 2,
    he: "לֹא תֹסִפוּ עַל־הַדָּבָר אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם",
    en: "You shall not add to the word that I command you.",
    verseHit: "הַדָּבָר",
  },
  {
    id: "bara-qamets",
    kind: "qamets",
    word: "בָּרָא",
    hit: "בָּ",
    markOn: "the first qamets (under bet)",
    gloss: "he created",
    syllables: "בָּ | רָא",
    answer: "qamets",
    lead: "Is בָּ open? Is the accent on this syllable or on רָא?",
    why: "Open, pretonic syllable → changeable long ā.",
    book: "Gen",
    chapter: 1,
    verse: 1,
    he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ",
    en: "In the beginning God created the heavens and the earth.",
    verseHit: "בָּרָא",
  },
  {
    id: "david-qamets",
    kind: "qamets",
    word: "דָּוִד",
    hit: "דָּ",
    markOn: "the qamets under dalet",
    gloss: "David",
    syllables: "דָּ | וִד",
    answer: "qamets",
    lead: "Is דָּ open? The accent is on וִד — so is this qamets pretonic?",
    why: "Open pretonic syllable → long ā.",
    book: "1Sam",
    chapter: 16,
    verse: 13,
    he: "וַיִּמְשַׁח אֹתוֹ בְּקֶרֶב אֶחָיו וַתִּצְלַח רוּחַ יְהוָה אֶל־דָּוִד",
    en: "He anointed him among his brothers, and the spirit of YHWH rushed upon David.",
    verseHit: "דָּוִד",
  },
  {
    id: "yad-qamets",
    kind: "qamets",
    word: "יָד",
    hit: "יָד",
    markOn: "the qamets under yod",
    gloss: "hand",
    syllables: "יָד",
    answer: "qamets",
    lead: "This is one closed syllable. Where must the accent sit in a one-syllable word?",
    why: "Closed and accented → long ā (yād). Hatuf only lives in a closed unaccented syllable.",
    book: "Gen",
    chapter: 22,
    verse: 12,
    he: "אַל־תִּשְׁלַח יָדְךָ אֶל־הַנַּעַר וְאַל־תַּעַשׂ לוֹ מְאוּמָה",
    en: "Do not stretch out your hand against the boy, and do not do anything to him.",
    verseHit: "יָדְךָ",
  },
  {
    id: "shamar-qamets",
    kind: "qamets",
    word: "שָׁמַר",
    hit: "שָׁ",
    markOn: "the qamets under shin",
    gloss: "he kept",
    syllables: "שָׁ | מַר",
    answer: "qamets",
    lead: "Is שָׁ open? The accent is on מַר. What kind of syllable is that for this qamets?",
    why: "Open, pretonic → long ā. (The last vowel is short pathach in a closed accented syllable.)",
    book: "1Kgs",
    chapter: 14,
    verse: 8,
    he: "אֲשֶׁר שָׁמַר מִצְוֺתַי וְאֲשֶׁר־הָלַךְ אַחֲרַי בְּכָל־לְבָבוֹ",
    en: "who kept my commandments and who followed me with all his heart.",
    verseHit: "שָׁמַר",
  },
  {
    id: "am-qamets",
    kind: "qamets",
    word: "עָם",
    hit: "עָם",
    markOn: "the qamets under ayin",
    gloss: "people",
    syllables: "עָם",
    answer: "qamets",
    lead: "One closed syllable. Accented or not?",
    why: "Closed and accented → long ā (ʿām). Hatuf cannot carry the accent.",
    book: "Exod",
    chapter: 19,
    verse: 5,
    he: "וִהְיִיתֶם לִי סְגֻלָּה מִכָּל־הָעַמִּים",
    en: "You shall be my treasured possession out of all the peoples.",
    verseHit: "הָעַמִּים",
  },
  {
    id: "hokmah-last",
    kind: "qamets",
    word: "חָכְמָה",
    hit: "מָה",
    markOn: "the last qamets (under mem)",
    gloss: "wisdom",
    syllables: "חָכְ | מָה",
    answer: "qamets",
    lead: "Is מָה the accented syllable? Open or closed?",
    why: "מָה is accented (and open with he as a vowel letter). That qamets is long ā. The first qamets in this same word is the hatuf.",
    book: "Prov",
    chapter: 9,
    verse: 10,
    he: "תְּחִלַּת חָכְמָה יִרְאַת יְהוָה וְדַעַת קְדֹשִׁים בִּינָה",
    en: "The beginning of wisdom is the fear of YHWH, and knowledge of the Holy One is understanding.",
    verseHit: "חָכְמָה",
  },
  {
    id: "hokmah-hatuf",
    kind: "qamets",
    word: "חָכְמָה",
    hit: "חָ",
    markOn: "the first qamets (under ḥet)",
    gloss: "wisdom",
    syllables: "חָכְ | מָה",
    answer: "hatuf",
    lead: "Look at חָכְ. Does that syllable end with a consonant? Does the accent fall there, or on מָה?",
    why: "חָכְ is closed and unaccented — the only seat of qamets hatuf (short o). Read ḥok-māh, not ḥak-māh.",
    book: "Prov",
    chapter: 9,
    verse: 10,
    he: "תְּחִלַּת חָכְמָה יִרְאַת יְהוָה וְדַעַת קְדֹשִׁים בִּינָה",
    en: "The beginning of wisdom is the fear of YHWH, and knowledge of the Holy One is understanding.",
    verseHit: "חָכְמָה",
  },
  {
    id: "kol-hatuf",
    kind: "qamets",
    word: "כָּל",
    hit: "כָּל",
    markOn: "the qamets under kaf",
    gloss: "all of, every",
    syllables: "כָּל",
    answer: "hatuf",
    lead: "Is כָּל־ a closed syllable? When it clings to the next word, does it carry the main accent?",
    why: "כָּל־ is a closed, unaccented (proclitic) syllable, so the vowel is hatuf — short o. This is the word that most often carries hatuf. Read kol, not kāl.",
    book: "Gen",
    chapter: 1,
    verse: 31,
    he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד",
    en: "God saw all that he had made, and behold, it was very good.",
    verseHit: "כָּל",
  },
  {
    id: "mikol-hatuf",
    kind: "qamets",
    word: "מִכָּל",
    hit: "כָּל",
    markOn: "the qamets under kaf",
    gloss: "from all of",
    syllables: "מִ | כָּל",
    answer: "hatuf",
    lead: "Kaf + qamets + lamed: is that syllable closed? Is the accent on this construct chain, or later?",
    why: "In מִכָּל־ the qamets under kaf is hatuf (short o) in a closed, unaccented syllable.",
    book: "Exod",
    chapter: 19,
    verse: 5,
    he: "וִהְיִיתֶם לִי סְגֻלָּה מִכָּל־הָעַמִּים",
    en: "You shall be my treasured possession out of all the peoples.",
    verseHit: "מִכָּל",
  },
  {
    id: "qodsho-hatuf",
    kind: "qamets",
    word: "קָדְשׁוֹ",
    hit: "קָ",
    markOn: "the first qamets (under qof)",
    gloss: "his holiness",
    syllables: "קָדְ | שׁוֹ",
    answer: "hatuf",
    lead: "Syllable קָדְ — open or closed? Accent on שׁוֹ or on קָדְ?",
    why: "Closed, unaccented קָדְ → hatuf. Read qod-shō, not qād-shō.",
    book: "Ps",
    chapter: 105,
    verse: 42,
    he: "כִּי זָכַר אֶת־דְּבַר קָדְשׁוֹ אֶת־אַבְרָהָם עַבְדּוֹ",
    en: "For he remembered his holy word, and Abraham his servant.",
    verseHit: "קָדְשׁוֹ",
  },
  {
    id: "okhlah-hatuf",
    kind: "qamets",
    word: "אָכְלָה",
    hit: "אָ",
    markOn: "the first qamets (under alef)",
    gloss: "food",
    syllables: "אָכְ | לָה",
    answer: "hatuf",
    lead: "Does אָכְ end with a consonant? Is the accent on לָה?",
    why: "Closed, unaccented אָכְ → hatuf. Read okh-lāh (“food”), not āk-lāh.",
    book: "Gen",
    chapter: 1,
    verse: 29,
    he: "לָכֶם יִהְיֶה לְאָכְלָה",
    en: "It shall be yours for food.",
    verseHit: "לְאָכְלָה",
  },
  {
    id: "qorban-hatuf",
    kind: "qamets",
    word: "קָרְבָּן",
    hit: "קָ",
    markOn: "the first qamets (under qof)",
    gloss: "offering",
    syllables: "קָרְ | בָּן",
    answer: "hatuf",
    lead: "Is קָרְ closed by resh? Does the accent fall on בָּן?",
    why: "Closed, unaccented קָרְ → hatuf. Read qor-bān, not qār-bān.",
    book: "Lev",
    chapter: 1,
    verse: 2,
    he: "אָדָם כִּי־יַקְרִיב מִכֶּם קָרְבָּן לַיהוָה",
    en: "When any of you brings an offering to YHWH.",
    verseHit: "קָרְבָּן",
  },
  {
    id: "qodshei-hatuf",
    kind: "qamets",
    word: "קָדְשֵׁי",
    hit: "קָ",
    markOn: "the first qamets (under qof)",
    gloss: "holy things of",
    syllables: "קָדְ | שֵׁי",
    answer: "hatuf",
    lead: "Is קָדְ closed by dalet? Does the accent fall later, on שֵׁי?",
    why: "Construct קָדְשֵׁי has hatuf in the closed, unaccented first syllable. Read qod-shē, not qād-shē.",
    book: "Lev",
    chapter: 22,
    verse: 2,
    he: "דַּבֵּר אֶל־אַהֲרֹן וְאֶל־בָּנָיו וְיִנָּזְרוּ מִקָּדְשֵׁי בְנֵי־יִשְׂרָאֵל",
    en: "Speak to Aaron and to his sons, that they keep themselves separate from the holy things of the sons of Israel.",
    verseHit: "מִקָּדְשֵׁי",
  },
  {
    id: "qodshekha-hatuf",
    kind: "qamets",
    word: "קָדְשֶׁךָ",
    hit: "קָ",
    markOn: "the first qamets (under qof)",
    gloss: "your holiness",
    syllables: "קָדְ | שֶׁ | ךָ",
    answer: "hatuf",
    lead: "Is קָדְ closed and unaccented, with the stress later in the word?",
    why: "Qamets hatuf in a closed, unaccented syllable. Read qod-she-khā.",
    book: "Exod",
    chapter: 15,
    verse: 13,
    he: "נָחִיתָ בְחַסְדְּךָ עַם־זוּ גָּאָלְתָּ נֵהַלְתָּ בְעָזְּךָ אֶל־נְוֵה קָדְשֶׁךָ",
    en: "You led in your ḥesed the people you redeemed; you guided them by your strength to your holy abode.",
    verseHit: "קָדְשֶׁךָ",
  },
];

export function itemsForKind(kind: ClassifyKind): ClassifyItem[] {
  return kind === "shewa" ? CLASSIFY_SHEWA : CLASSIFY_QAMETS;
}

export function formatClassifyRef(item: ClassifyItem): string {
  return `${item.book} ${item.chapter}:${item.verse}`;
}

export function answerLabel(item: ClassifyItem): string {
  if (item.kind === "shewa") return item.answer === "vocal" ? "Vocal shewa" : "Silent shewa";
  return item.answer === "hatuf" ? "Qamets hatuf (short o)" : "Qamets (long ā)";
}

function foldAnswer(raw: string): string {
  return raw
    .toLowerCase()
    .replace(/sheva|shva/g, "shewa")
    .replace(/qametz|kamets|kametz|qames/g, "qamets")
    .replace(/hatuph|hatof|hataf/g, "hatuf")
    .replace(/qatan|katan/g, "hatuf")
    .replace(/gadol/g, "long")
    .replace(/quiescent|nach|nah/g, "silent")
    .replace(/mobile|murmur|voiced/g, "vocal")
    .replace(/[^a-z]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Map typed text to a label, or null if it is empty / not yet a decision. */
export function parseClassifyInput(kind: ClassifyKind, raw: string): ClassifyAnswer | null {
  const t = foldAnswer(raw);
  if (!t) return null;
  if (kind === "shewa") {
    if (/\b(silent|zero)\b/.test(t)) return "silent";
    if (/\b(vocal|na)\b/.test(t)) return "vocal";
    if (t === "silent shewa" || t === "shewa silent") return "silent";
    if (t === "vocal shewa" || t === "shewa vocal") return "vocal";
    return null;
  }
  if (/\bhatuf\b/.test(t) || /\bshort o\b/.test(t) || t === "o" || t === "short") return "hatuf";
  if (/\blong a\b/.test(t) || t === "a" || t === "long" || t === "father") return "qamets";
  if (/\bqamets\b/.test(t)) return "qamets";
  return null;
}

export function classifyInputHits(item: ClassifyItem, raw: string): boolean {
  const parsed = parseClassifyInput(item.kind, raw);
  return parsed === item.answer;
}

export function liveClassify(item: ClassifyItem, raw: string): "empty" | "match" | "off" | "prefix" {
  const t = raw.trim();
  if (!t) return "empty";
  const parsed = parseClassifyInput(item.kind, t);
  if (parsed == null) return "prefix";
  return parsed === item.answer ? "match" : "off";
}
