import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on existence particles and chapter-9 nouns in the text. Masoretic examples. */
export const EXIST_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "Look — הִנֵּה",
    short: "Behold, here, now",
    rule:
      "הִנֵּה (and lighter הֵן) is a pointer: look, behold, here. It often marks a new sight or a surprise. It is not a verb and not the article. Gen 1:31 וְהִנֵּה־טוֹב מְאֹד — “and look: very good.” Class nouns around it are the thing you are being shown.",
    samples: [
      { word: "הִנֵּה", gloss: "behold, look", tag: "pointer", note: "Class. Also הִנְנִי “here I am.”", ref: "Gen 1:31" },
      { word: "הֵן", gloss: "behold, if", tag: "pointer", note: "Shorter cousin.", ref: "Gen 3:22" },
      { word: "הִנְנִי", gloss: "here I am", tag: "plus pronoun", note: "הִנֵּה + me.", ref: "Exod 3:4" },
      { word: "וְהִנֵּה", gloss: "and look", tag: "vav + pointer", note: "Chapter 5 vav still applies.", ref: "Gen 1:31" },
    ],
    verses: [
      { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד", en: "God saw all that he had made, and look — it was very good.", hit: "הִנֵּה", hitEn: "look", vocabId: "hinneh" },
      { ref: "Exod 3:4", he: "וַיֹּאמֶר הִנֵּנִי", en: "He said, “Here I am.”", hit: "הִנֵּנִי", hitEn: "Here I am", vocabId: "hinneh" },
      { ref: "Gen 22:1", he: "וַיֹּאמֶר אֵלָיו אַבְרָהָם וַיֹּאמֶר הִנֵּנִי", en: "He said to him, “Abraham,” and he said, “Here I am.”", hit: "אַבְרָהָם", hitEn: "Abraham", vocabId: "abraham" },
      { ref: "Isa 7:14", he: "הִנֵּה הָעַלְמָה הָרָה וְיֹלֶדֶת בֵּן", en: "Look, the young woman is pregnant and bearing a son.", hit: "הִנֵּה", hitEn: "Look", vocabId: "hinneh" },
    ],
    quiz: [
      { q: "הִנֵּה means…", he: "הִנֵּה", choices: ["Behold, look, here", "There is not", "Also"], answer: "Behold, look, here", why: "Class particle." },
      { q: "הִנֵּה is not…", choices: ["The article הַ or a verb “to see”", "A pointer", "Class vocab"], answer: "The article הַ or a verb “to see”", why: "Different lemma." },
      { q: "Gen 1:31 וְהִנֵּה־טוֹב מְאֹד shows…", ref: "Gen 1:31", choices: ["Look + good + very — three class words", "Only a number", "Only construct"], answer: "Look + good + very — three class words", why: "Maximum exposure." },
      { q: "הִנְנִי / הִנֵּנִי is…", he: "הִנֵּנִי", choices: ["Here I am — הִנֵּה plus “me”", "They are", "The dual of behold"], answer: "Here I am — הִנֵּה plus “me”", why: "Moses, Abraham." },
      { q: "הֵן is…", he: "הֵן", choices: ["A shorter “behold / if”", "They (always)", "The article"], answer: "A shorter “behold / if”", why: "Class." },
      { q: "When you see הִנֵּה, next…", choices: ["Look at the clause it introduces — that is the sight", "Skip the next noun", "Always add מִן"], answer: "Look at the clause it introduces — that is the sight", why: "Pointer." },
      { q: "Class name אַבְרָהָם often answers…", he: "אַבְרָהָם", choices: ["הִנֵּנִי", "מִן", "זֶה only"], answer: "הִנֵּנִי", why: "Here I am." },
      { q: "Do not parse הִנֵּה as…", choices: ["הַ + נֵה a noun", "A particle", "“Look”"], answer: "הַ + נֵה a noun", why: "One lemma." },
      { q: "וְהִנֵּה is simply…", he: "וְהִנֵּה", choices: ["And look — vav plus הִנֵּה", "The article on look", "A dual"], answer: "And look — vav plus הִנֵּה", why: "Chapter 5 vav still applies." },
      { q: "Isa 7:14 opens the sight with…", he: "הִנֵּה", ref: "Isa 7:14", choices: ["הִנֵּה", "אֵין", "יֵשׁ"], answer: "הִנֵּה", why: "Look…" },
      { q: "הִנֵּה can sit before…", choices: ["A whole clause, not only one noun", "Only numbers", "Only duals"], answer: "A whole clause, not only one noun", why: "Behold, X is happening." },
      { q: "Chapter 9 vocab you will keep meeting beside הִנֵּה includes…", choices: ["לֶחֶם, עַם, כָּבוֹד, בֹּקֶר", "Only Qal verbs", "Only dual endings"], answer: "לֶחֶם, עַם, כָּבוֹד, בֹּקֶר", why: "This chapter’s nouns live in the same verses." },
    ],
  },
  {
    id: 2,
    title: "There is / there is not",
    short: "יֵשׁ and אֵין",
    rule:
      "יֵשׁ “there is / there are.” אֵין “there is not / none.” They are particles of existence, not verbs with tense. English will still say “is/are.” Pair them in the mind: presence vs absence. They like a noun after them — often class vocab.",
    samples: [
      { word: "יֵשׁ", gloss: "there is, there are", tag: "existence", note: "Class.", ref: "Gen 28:16" },
      { word: "אֵין", gloss: "there is not, none", tag: "non-existence", note: "Class. Also אַיִן.", ref: "Gen 2:5" },
      { word: "אַיִן", gloss: "there is not", tag: "alt spelling", note: "Same lemma as אֵין.", ref: "Gen 2:5" },
      { word: "מָקוֹם", gloss: "place", tag: "class noun", note: "Often the thing יֵשׁ locates.", ref: "Gen 28:16" },
    ],
    verses: [
      { ref: "Gen 28:16", he: "וַיֹּאמֶר אָכֵן יֵשׁ יְהוָה בַּמָּקוֹם הַזֶּה", en: "He said, “Surely YHWH is in this place.”", hit: "יֵשׁ", hitEn: "is", vocabId: "yesh" },
      { ref: "Gen 2:5", he: "וְאָדָם אַיִן לַעֲבֹד אֶת־הָאֲדָמָה", en: "And there was no human to work the ground.", hit: "אַיִן", hitEn: "no", vocabId: "ein" },
      { ref: "Ps 14:1", he: "אָמַר נָבָל בְּלִבּוֹ אֵין אֱלֹהִים", en: "The fool says in his heart, “There is no God.”", hit: "אֵין", hitEn: "no", vocabId: "ein" },
      { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "אֱלֹהִים", hitEn: "God", vocabId: "elohim" },
    ],
    quiz: [
      { q: "יֵשׁ means…", he: "יֵשׁ", choices: ["There is, there are", "There is not", "Behold"], answer: "There is, there are", why: "Class." },
      { q: "אֵין means…", he: "אֵין", choices: ["There is not, none, nothing", "There is", "Also"], answer: "There is not, none, nothing", why: "Class." },
      { q: "יֵשׁ יְהוָה בַּמָּקוֹם is…", he: "יֵשׁ", ref: "Gen 28:16", choices: ["YHWH is (exists) in this place", "YHWH is not", "Look, a place"], answer: "YHWH is (exists) in this place", why: "Jacob at Bethel." },
      { q: "אֵין אֱלֹהִים is…", he: "אֵין אֱלֹהִים", ref: "Ps 14:1", choices: ["There is no God", "God is holy", "These are God"], answer: "There is no God", why: "The fool’s line — class אֱלֹהִים." },
      { q: "אַיִן is…", he: "אַיִן", choices: ["A spelling of אֵין", "A dual of יֵשׁ", "The article"], answer: "A spelling of אֵין", why: "hebrewAlts." },
      { q: "These particles do not…", choices: ["Conjugate like Qal verbs for person", "Take a noun nearby", "Mean existence / non-existence"], answer: "Conjugate like Qal verbs for person", why: "Particles." },
      { q: "Opposite pair to memorize…", choices: ["יֵשׁ / אֵין", "טוֹב / קָדוֹשׁ", "זֶה / מִי"], answer: "יֵשׁ / אֵין", why: "There is / there is not." },
      { q: "Gen 2:5 וְאָדָם אַיִן uses class…", ref: "Gen 2:5", choices: ["אָדָם and אֲדָמָה with אֵין", "Only a number", "Only זֶה"], answer: "אָדָם and אֲדָמָה with אֵין", why: "No human for the ground." },
      { q: "English “is” after יֵשׁ is…", choices: ["The existence idea, not a hidden Hebrew copula you must find", "Always הָיָה written", "The object marker"], answer: "The existence idea, not a hidden Hebrew copula you must find", why: "יֵשׁ does that job." },
      { q: "Do not confuse אֵין with…", choices: ["עַיִן “eye”", "The particle of non-existence", "Class vocab"], answer: "עַיִן “eye”", why: "Different letters, different lemma." },
      { q: "בַּמָּקוֹם הַזֶּה after יֵשׁ is…", ref: "Gen 28:16", choices: ["In this place — inseparable בְּ + article + demonstrative", "From a place", "A dual of place"], answer: "In this place — inseparable בְּ + article + demonstrative", why: "Ch. 6 and 8 in one phrase." },
      { q: "Look up יֵשׁ and אֵין…", choices: ["As themselves in the particle list", "Under היה only", "As duals of יש"], answer: "As themselves in the particle list", why: "Citation forms." },
    ],
  },
  {
    id: 3,
    title: "Also, or, alone, around",
    short: "Little words, big traffic",
    rule:
      "גַּם “also, even.” אוֹ “or.” לְבַד “alone.” סָבִיב “around.” They are small and everywhere. Train the eye to name them fast so the nouns can stay in focus.",
    samples: [
      { word: "גַּם", gloss: "also, even", tag: "particle", note: "Class.", ref: "Gen 3:6" },
      { word: "אוֹ", gloss: "or", tag: "particle", note: "Class.", ref: "Exod 21:4" },
      { word: "לְבַד", gloss: "alone", tag: "particle", note: "Class. Gen 2:18 לְבַדּוֹ.", ref: "Gen 2:18" },
      { word: "סָבִיב", gloss: "around", tag: "particle", note: "Class.", ref: "Gen 2:11" },
    ],
    verses: [
      { ref: "Gen 2:18", he: "לֹא־טוֹב הֱיוֹת הָאָדָם לְבַדּוֹ", en: "It is not good for the human to be alone.", hit: "לְבַדּוֹ", hitEn: "alone", vocabId: "levad" },
      { ref: "Gen 3:6", he: "וַתִּקַּח מִפִּרְיוֹ וַתֹּאכַל וַתִּתֵּן גַּם־לְאִישָׁהּ עִמָּהּ", en: "She took of its fruit and ate, and she also gave to her husband with her.", hit: "גַּם", hitEn: "also", vocabId: "gam" },
      { ref: "Gen 1:5", he: "וַיְהִי־עֶרֶב וַיְהִי־בֹקֶר יוֹם אֶחָד", en: "There was evening and there was morning, one day.", hit: "בֹקֶר", hitEn: "morning", vocabId: "boqer" },
      { ref: "Exod 16:4", he: "הִנְנִי מַמְטִיר לָכֶם לֶחֶם מִן־הַשָּׁמָיִם", en: "Look, I will rain down bread for you from heaven.", hit: "לֶחֶם", hitEn: "bread", vocabId: "lehem" },
    ],
    quiz: [
      { q: "גַּם means…", he: "גַּם", choices: ["Also, even", "Or", "Around"], answer: "Also, even", why: "Class." },
      { q: "אוֹ means…", he: "אוֹ", choices: ["Or", "Also", "None"], answer: "Or", why: "Class." },
      { q: "לְבַד means…", he: "לְבַד", choices: ["Alone, by oneself", "Around", "Behold"], answer: "Alone, by oneself", why: "Class." },
      { q: "סָבִיב means…", he: "סָבִיב", choices: ["Around, about", "Or", "There is"], answer: "Around, about", why: "Class." },
      { q: "לְבַדּוֹ in Gen 2:18 is…", he: "לְבַדּוֹ", ref: "Gen 2:18", choices: ["Alone (his) — לְבַד plus suffix", "There is not", "This day"], answer: "Alone (his) — לְבַד plus suffix", why: "Not good to be alone." },
      { q: "גַּם־לְאִישָׁהּ uses…", he: "גַּם", ref: "Gen 3:6", choices: ["Also + inseparable לְ + class אִישׁ / אִשָּׁה", "Only the article", "A number"], answer: "Also + inseparable לְ + class אִישׁ / אִשָּׁה", why: "She gave also to her husband." },
      { q: "בֹּקֶר is class vocab for…", he: "בֹּקֶר", choices: ["Morning", "Cattle בָּקָר", "Blessing"], answer: "Morning", why: "Do not mix with בָּקָר cattle." },
      { q: "לֶחֶם is…", he: "לֶחֶם", choices: ["Bread, food", "War", "Glory"], answer: "Bread, food", why: "Class ch. 9." },
      { q: "These particles should be named in…", choices: ["One glance, so the nouns stay in memory", "The verb chart only", "Construct chains only"], answer: "One glance, so the nouns stay in memory", why: "Speed for exposure." },
      { q: "לֹא־טוֹב … לְבַדּוֹ recycles…", ref: "Gen 2:18", choices: ["טוֹב (ch. 7) and לְבַד (ch. 9) and אָדָם (ch. 3)", "Only numbers", "Only duals"], answer: "טוֹב (ch. 7) and לְבַד (ch. 9) and אָדָם (ch. 3)", why: "Old words in a new particle frame." },
      { q: "גַּם is not…", choices: ["גַּן “garden”", "Also/even", "A particle"], answer: "גַּן “garden”", why: "One extra nun." },
      { q: "Look up לְבַדּוֹ as…", he: "לְבַדּוֹ", choices: ["לְבַד — then read the suffix", "בדד a new verb always", "The dual of בד"], answer: "לְבַד — then read the suffix", why: "Citation plus ending." },
    ],
  },
  {
    id: 4,
    title: "Chapter 9 nouns in the verse",
    short: "People, bread, glory, war",
    rule:
      "This chapter’s nouns are high-traffic: עַם people, לֶחֶם bread, כָּבוֹד glory, מִלְחָמָה war, מִשְׁפָּחָה family, עֵץ tree, בְּרָכָה blessing, חַטָּאת sin. Meet them inside the particles you just learned. Strip article, vav, and inseparable preps — then look up the singular.",
    samples: [
      { word: "עַם", gloss: "people", tag: "noun", note: "Class. Frequent.", ref: "Exod 19:5" },
      { word: "כָּבוֹד", gloss: "glory, honor", tag: "noun", note: "Class.", ref: "Ps 24:8" },
      { word: "מִלְחָמָה", gloss: "war, battle", tag: "noun", note: "Class.", ref: "Exod 15:3" },
      { word: "חַטָּאת", gloss: "sin, sin offering", tag: "noun", note: "Class.", ref: "Ps 51:5" },
      { word: "עֵץ", gloss: "tree, wood", tag: "noun", note: "Class.", ref: "Gen 2:9" },
    ],
    verses: [
      { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד", en: "Who is this king of glory?", hit: "הַכָּבוֹד", hitEn: "glory", vocabId: "kavod" },
      { ref: "Exod 19:5", he: "וִהְיִיתֶם לִי סְגֻלָּה מִכָּל־הָעַמִּים", en: "You shall be my treasured possession out of all the peoples.", hit: "הָעַמִּים", hitEn: "peoples", vocabId: "am" },
      { ref: "Exod 15:3", he: "יְהוָה אִישׁ מִלְחָמָה יְהוָה שְׁמוֹ", en: "YHWH is a man of war; YHWH is his name.", hit: "מִלְחָמָה", hitEn: "war", vocabId: "milhamah" },
      { ref: "Gen 2:9", he: "וַיַּצְמַח יְהוָה אֱלֹהִים מִן־הָאֲדָמָה כָּל־עֵץ נֶחְמָד", en: "YHWH God caused to sprout from the ground every tree that is pleasant.", hit: "עֵץ", hitEn: "tree", vocabId: "ets" },
    ],
    quiz: [
      { q: "עַם means…", he: "עַם", choices: ["People", "Tree", "Glory"], answer: "People", why: "Class." },
      { q: "הָעַמִּים is…", he: "הָעַמִּים", choices: ["The peoples — article + plural of עַם", "A dual of with", "The verb “stand”"], answer: "The peoples — article + plural of עַם", why: "Out of all the peoples." },
      { q: "כָּבוֹד means…", he: "כָּבוֹד", choices: ["Glory, splendor, honor", "Bread", "War"], answer: "Glory, splendor, honor", why: "King of glory." },
      { q: "מִלְחָמָה means…", he: "מִלְחָמָה", choices: ["War, battle", "Family", "Morning"], answer: "War, battle", why: "Class." },
      { q: "חַטָּאת means…", he: "חַטָּאת", choices: ["Sin, sin offering", "Blessing", "Cattle"], answer: "Sin, sin offering", why: "Class." },
      { q: "עֵץ means…", he: "עֵץ", choices: ["Tree, wood", "People", "Nose"], answer: "Tree, wood", why: "Class." },
      { q: "בְּרָכָה means…", he: "בְּרָכָה", choices: ["Blessing, gift", "Battle", "Vessel"], answer: "Blessing, gift", why: "Class. Not בָּרָא." },
      { q: "מִשְׁפָּחָה means…", he: "מִשְׁפָּחָה", choices: ["Family, clan", "Glory", "Bread"], answer: "Family, clan", why: "Class." },
      { q: "בָּקָר vs בֹּקֶר…", choices: ["Cattle vs morning — different vowels, different lemmas", "The same word", "Plural vs dual of one lemma"], answer: "Cattle vs morning — different vowels, different lemmas", why: "Do not mix them." },
      { q: "אַף can mean…", he: "אַף", choices: ["Nostril, nose, or anger", "Also (that is גַּם)", "Tree"], answer: "Nostril, nose, or anger", why: "Class noun. Context picks." },
      { q: "כְּלִי means…", he: "כְּלִי", choices: ["Vessel, implement, weapon", "All כֹּל", "Like כְּ"], answer: "Vessel, implement, weapon", why: "Class." },
      { q: "Strip הַכָּבוֹד to look up…", he: "הַכָּבוֹד", choices: ["כָּבוֹד", "הַכָּבוֹד as one lemma", "כָּבֵד the verb only"], answer: "כָּבוֹד", why: "Article off. Citation form." },
    ],
  },
];
