import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on Hebrew adjectives. Masoretic examples. Not a textbook reprint. */
export const ADJ_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "Four endings",
    short: "Same clothes as nouns",
    rule:
      "An adjective inflects for gender and number with the same endings you already know on nouns: טוֹב, טוֹבָה, טוֹבִים, טוֹבוֹת. It agrees with the noun it talks about. Masculine singular is endingless — that is the citation form in the lexicon and in class vocab.",
    samples: [
      { word: "טוֹב", gloss: "good (ms)", tag: "ms", note: "Citation form. Class vocab.", ref: "Gen 1:4" },
      { word: "טוֹבָה", gloss: "good (fs)", tag: "fs", note: "ָה like a feminine noun.", ref: "Gen 1:31" },
      { word: "טוֹבִים", gloss: "good (mp)", tag: "mp", note: "ִים.", ref: "Gen 1:31" },
      { word: "גָּדוֹל", gloss: "great, big", tag: "ms", note: "Class vocab.", ref: "Deut 7:21" },
      { word: "קָדוֹשׁ", gloss: "holy", tag: "ms", note: "Class vocab.", ref: "Lev 19:2" },
    ],
    verses: [
      { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "טוֹב", hitEn: "good", vocabId: "tov" },
      { ref: "Deut 7:21", he: "כִּי יְהוָה אֱלֹהֶיךָ בְּקִרְבֶּךָ אֵל גָּדוֹל וְנוֹרָא", en: "For YHWH your God is in your midst, a great and fearsome God.", hit: "גָּדוֹל", hitEn: "great", vocabId: "gadol" },
      { ref: "Lev 19:2", he: "קְדֹשִׁים תִּהְיוּ כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם", en: "You shall be holy, for I, YHWH your God, am holy.", hit: "קָדוֹשׁ", hitEn: "holy", vocabId: "qadosh" },
      { ref: "Ps 1:6", he: "כִּי־יוֹדֵעַ יְהוָה דֶּרֶךְ צַדִּיקִים וְדֶרֶךְ רְשָׁעִים תֹּאבֵד", en: "For YHWH knows the way of the righteous, but the way of the wicked perishes.", hit: "צַדִּיקִים", hitEn: "righteous", vocabId: "tsaddiq" },
    ],
    quiz: [
      { q: "Adjective endings match…", choices: ["Noun endings — gender and number", "Only the article", "Only dual"], answer: "Noun endings — gender and number", why: "טוֹב טוֹבָה טוֹבִים טוֹבוֹת." },
      { q: "The lexicon form of “good” is…", he: "טוֹב", choices: ["טוֹב — masculine singular", "טוֹבִים", "טוֹבָה"], answer: "טוֹב — masculine singular", why: "Class vocab." },
      { q: "An adjective agrees with its noun in…", choices: ["Gender and number", "Person only", "Tense"], answer: "Gender and number", why: "סוּס טוֹב, מַלְכָּה טוֹבָה." },
      { q: "טוֹב in Gen 1:4 is…", he: "טוֹב", ref: "Gen 1:4", choices: ["Masculine singular — “good”", "Feminine plural", "A preposition"], answer: "Masculine singular — “good”", why: "The light was good." },
      { q: "צַדִּיקִים in Ps 1:6 is…", he: "צַדִּיקִים", ref: "Ps 1:6", choices: ["Masculine plural of צַדִּיק", "Feminine singular", "A verb"], answer: "Masculine plural of צַדִּיק", why: "The righteous. Class lemma." },
      { q: "קָדוֹשׁ is class vocab for…", he: "קָדוֹשׁ", choices: ["Holy, set apart", "Evil", "Small"], answer: "Holy, set apart", why: "Chapter 7." },
      { q: "גָּדוֹל is…", he: "גָּדוֹל", choices: ["Great, big, large", "Near", "Few"], answer: "Great, big, large", why: "Class." },
      { q: "רַע is…", he: "רַע", choices: ["Bad, evil, wicked", "Holy", "Wise"], answer: "Bad, evil, wicked", why: "Opposite of טוֹב in many verses." },
      { q: "חָכָם is…", he: "חָכָם", choices: ["Wise, skillful", "Wicked", "Far"], answer: "Wise, skillful", why: "Class." },
      { q: "קָטֹן is…", he: "קָטֹן", choices: ["Small, young, insignificant", "Great", "Living"], answer: "Small, young, insignificant", why: "Class." },
      { q: "If the noun is feminine singular, the adjective should look like…", choices: ["…ָה (טוֹבָה)", "Endingless only", "ִים only"], answer: "…ָה (טוֹבָה)", why: "Agreement." },
      { q: "Look up טוֹבִים as…", he: "טוֹבִים", choices: ["טוֹב", "טוֹבִים as a new lemma", "טוֹבָה"], answer: "טוֹב", why: "Strip the plural ending." },
    ],
  },
  {
    id: 2,
    title: "Attributive",
    short: "The adjective rides behind",
    rule:
      "Attributive: the adjective describes the noun as a bundle — “the good king.” In Hebrew it usually follows the noun and takes the same definiteness: הַמֶּלֶךְ הַטּוֹב. Both have the article, or neither does. Read it as one phrase, not two sentences.",
    samples: [
      { word: "הַמֶּלֶךְ הַטּוֹב", gloss: "the good king", tag: "both definite", note: "Article on noun and adjective.", ref: "2 Kgs 18:3" },
      { word: "אֵל גָּדוֹל", gloss: "a great God", tag: "both indefinite", note: "No article on either.", ref: "Deut 7:21" },
      { word: "הַמְּאֹרֹת הַגְּדֹלִים", gloss: "the great lights", tag: "both definite", note: "Article on noun and adjective. Class גָּדוֹל.", ref: "Gen 1:16" },
      { word: "רַבָּה", gloss: "great (fs)", tag: "fs of רַב", note: "Class רַב.", ref: "Gen 6:5" },
    ],
    verses: [
      { ref: "Deut 7:21", he: "כִּי יְהוָה אֱלֹהֶיךָ בְּקִרְבֶּךָ אֵל גָּדוֹל וְנוֹרָא", en: "For YHWH your God is in your midst, a great and fearsome God.", hit: "גָּדוֹל", hitEn: "great", vocabId: "gadol" },
      { ref: "Gen 1:16", he: "וַיַּעַשׂ אֱלֹהִים אֶת־שְׁנֵי הַמְּאֹרֹת הַגְּדֹלִים", en: "God made the two great lights.", hit: "הַגְּדֹלִים", hitEn: "great", vocabId: "gadol" },
      { ref: "Gen 6:5", he: "וַיַּרְא יְהוָה כִּי רַבָּה רָעַת הָאָדָם בָּאָרֶץ", en: "YHWH saw that the evil of humankind was great on the earth.", hit: "רַבָּה", hitEn: "great", vocabId: "rab" },
      { ref: "Ps 1:1", he: "אַשְׁרֵי־הָאִישׁ אֲשֶׁר לֹא הָלַךְ בַּעֲצַת רְשָׁעִים", en: "Happy is the one who has not walked in the counsel of the wicked.", hit: "רְשָׁעִים", hitEn: "wicked", vocabId: "rasha" },
    ],
    quiz: [
      { q: "Attributive adjectives usually…", choices: ["Follow the noun and match definiteness", "Always come first", "Never take the article"], answer: "Follow the noun and match definiteness", why: "הַמֶּלֶךְ הַטּוֹב." },
      { q: "הַמֶּלֶךְ הַטּוֹב is…", he: "הַמֶּלֶךְ הַטּוֹב", choices: ["The good king — both have הַ", "The king is good (a sentence)", "A good king (indefinite)"], answer: "The good king — both have הַ", why: "Matching articles = one phrase." },
      { q: "אֵל גָּדוֹל in Deut 7:21 is…", he: "אֵל גָּדוֹל", ref: "Deut 7:21", choices: ["A great God — both indefinite, adjective after the noun", "The great God (both have הַ)", "Predicate only"], answer: "A great God — both indefinite, adjective after the noun", why: "Attributive pair." },
      { q: "If the noun has הַ and the adjective does not, suspect…", choices: ["Predicate, not attributive", "A dual", "A misspelling only"], answer: "Predicate, not attributive", why: "Mismatched article is a clue." },
      { q: "הַמְּאֹרֹת הַגְּדֹלִים is…", he: "הַגְּדֹלִים", ref: "Gen 1:16", choices: ["The great lights — both have הַ, adjective after the noun", "Great is the lights (predicate)", "A construct “lights of great”"], answer: "The great lights — both have הַ, adjective after the noun", why: "Matching articles. Class גָּדוֹל." },
      { q: "רַבָּה is the feminine of class…", he: "רַבָּה", choices: ["רַב great/many", "רַע", "רֹאשׁ"], answer: "רַב great/many", why: "Gen 6:5 the evil was great." },
      { q: "רְשָׁעִים is…", he: "רְשָׁעִים", choices: ["Masculine plural of רָשָׁע “wicked”", "Singular of רַע", "A name"], answer: "Masculine plural of רָשָׁע “wicked”", why: "Class." },
      { q: "Attributive “the holy people” needs…", choices: ["Article on both noun and adjective", "Article on the adjective only", "No articles"], answer: "Article on both noun and adjective", why: "Matching definiteness." },
      { q: "מְאֹד “very” is…", he: "מְאֹד", choices: ["An adverb, not an adjective with endings", "Feminine of טוֹב", "A dual"], answer: "An adverb, not an adjective with endings", why: "Class particle. It does not agree." },
      { q: "הַגְּדֹלִים is the mp of class…", he: "הַגְּדֹלִים", choices: ["גָּדוֹל — strip the article and the plural", "רַב only", "קָטֹן"], answer: "גָּדוֹל — strip the article and the plural", why: "Look it up as the ms citation form." },
      { q: "Gender of the adjective is chosen by…", choices: ["The noun, not English “it”", "Always masculine", "The verb"], answer: "The noun, not English “it”", why: "Agreement is Hebrew morphology." },
      { q: "Two adjectives on one noun still…", choices: ["Each agree and, if attributive, sit after it", "Must be construct", "Drop number"], answer: "Each agree and, if attributive, sit after it", why: "אֵל גָּדוֹל וְנוֹרָא." },
    ],
  },
  {
    id: 3,
    title: "Predicate",
    short: "The adjective makes a sentence",
    rule:
      "Predicate: the adjective is the news — “the king is good.” It often comes first, and it does not take the article even when the noun does: טוֹב הַמֶּלֶךְ. English supplies “is.” You already saw this in Gen 1:4 כִּי־טוֹב — “that it was good.”",
    samples: [
      { word: "כִּי־טוֹב", gloss: "that it was good", tag: "predicate", note: "No article on טוֹב.", ref: "Gen 1:4" },
      { word: "קָדוֹשׁ אֲנִי", gloss: "I am holy", tag: "predicate + pronoun", note: "Adjective then the subject.", ref: "Lev 19:2" },
      { word: "חָכָם", gloss: "wise", tag: "ms", note: "Can be predicate or attributive from the verse.", ref: "Prov 1:5" },
      { word: "לֹא־טוֹב", gloss: "not good", tag: "negated predicate", note: "Still no article on טוֹב.", ref: "Gen 2:18" },
    ],
    verses: [
      { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "טוֹב", hitEn: "good", vocabId: "tov" },
      { ref: "Lev 19:2", he: "קְדֹשִׁים תִּהְיוּ כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם", en: "You shall be holy, for I, YHWH your God, am holy.", hit: "קָדוֹשׁ", hitEn: "holy", vocabId: "qadosh" },
      { ref: "Prov 1:5", he: "יִשְׁמַע חָכָם וְיוֹסֵף לֶקַח", en: "Let the wise hear and add learning.", hit: "חָכָם", hitEn: "wise", vocabId: "hakam" },
      { ref: "Gen 2:18", he: "לֹא־טוֹב הֱיוֹת הָאָדָם לְבַדּוֹ", en: "It is not good for the human to be alone.", hit: "טוֹב", hitEn: "good", vocabId: "tov" },
    ],
    quiz: [
      { q: "A predicate adjective…", choices: ["Makes a sentence (“is good”) and usually has no article", "Must follow with matching הַ", "Is always dual"], answer: "Makes a sentence (“is good”) and usually has no article", why: "טוֹב הַמֶּלֶךְ." },
      { q: "English “is” in these clauses is…", choices: ["Supplied — Hebrew often has no separate “is”", "Always the verb הָיָה", "The article"], answer: "Supplied — Hebrew often has no separate “is”", why: "Predicate adjective does the job." },
      { q: "כִּי־טוֹב in Gen 1:4 is predicate because…", he: "כִּי־טוֹב", ref: "Gen 1:4", choices: ["טוֹב has no article and states what the light was", "Both words have הַ", "It is dual"], answer: "טוֹב has no article and states what the light was", why: "That it was good." },
      { q: "קָדוֹשׁ אֲנִי is…", he: "קָדוֹשׁ אֲנִי", ref: "Lev 19:2", choices: ["I am holy — predicate adjective + pronoun", "Holy I (construct chain)", "The holy I (attributive)"], answer: "I am holy — predicate adjective + pronoun", why: "For I am holy." },
      { q: "לֹא־טוֹב in Gen 2:18 is…", he: "לֹא־טוֹב", ref: "Gen 2:18", choices: ["Not good — predicate, negated", "The good (attributive)", "A name"], answer: "Not good — predicate, negated", why: "It is not good for the human to be alone." },
      { q: "If you see הַמֶּלֶךְ טוֹב (article on noun only)…", choices: ["Read “the king is good”", "Read “the good king”", "Read a dual"], answer: "Read “the king is good”", why: "Mismatched article → predicate." },
      { q: "חָכָם in Prov 1:5 can be…", he: "חָכָם", ref: "Prov 1:5", choices: ["“A wise man” used as a noun — adjectives can stand in for people", "Only a verb", "The article"], answer: "“A wise man” used as a noun — adjectives can stand in for people", why: "Substantive use. Next unit." },      { q: "Predicate vs attributive: first question…", choices: ["Does the adjective have the same article as the noun?", "Is it dual?", "Does it start with בְּ?"], answer: "Does the adjective have the same article as the noun?", why: "Match → attributive. Mismatch → predicate." },
      { q: "קְדֹשִׁים תִּהְיוּ uses…", he: "קְדֹשִׁים", ref: "Lev 19:2", choices: ["Plural adjective agreeing with “you shall be”", "A construct of קֹדֶשׁ only", "The object marker"], answer: "Plural adjective agreeing with “you shall be”", why: "Be holy ones." },
      { q: "Class vocab מְאֹד after an adjective means…", he: "מְאֹד", choices: ["Very, exceedingly", "Holy", "Few"], answer: "Very, exceedingly", why: "טוֹב מְאֹד." },
      { q: "A predicate adjective still agrees in…", choices: ["Gender and number with its subject", "Nothing — it is frozen", "Person of the English verb"], answer: "Gender and number with its subject", why: "Agreement does not turn off." },
      { q: "Gen 1:4 trains the eye for…", ref: "Gen 1:4", choices: ["Predicate טוֹב — “that it was good,” no article on the adjective", "The dual of light", "An inseparable prep"], answer: "Predicate טוֹב — “that it was good,” no article on the adjective", why: "Same verse you already know from the start of the book." },    ],
  },
  {
    id: 4,
    title: "As a noun, and “very”",
    short: "The adjective can stand alone",
    rule:
      "Hebrew often lets an adjective stand as a noun: צַדִּיק “a righteous one,” רְשָׁעִים “the wicked.” Endings still tell gender and number. מְאֹד “very” does not inflect — it just intensifies. Comparative ideas often use מִן (last chapter): טוֹב … מִן “better than.”",
    samples: [
      { word: "צַדִּיק", gloss: "righteous (one)", tag: "substantive", note: "Person or quality from the verse.", ref: "Ps 1:6" },
      { word: "רָשָׁע", gloss: "wicked (one)", tag: "substantive", note: "Class vocab.", ref: "Ps 1:1" },
      { word: "מְאֹד", gloss: "very", tag: "adverb", note: "No gender endings.", ref: "Gen 1:31" },
      { word: "זָקֵן", gloss: "old; an elder", tag: "adj / noun", note: "Class vocab does both.", ref: "Gen 24:1" },
    ],
    verses: [
      { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד", en: "God saw all that he had made, and look — it was very good.", hit: "מְאֹד", hitEn: "very", vocabId: "meod" },
      { ref: "Ps 1:6", he: "כִּי־יוֹדֵעַ יְהוָה דֶּרֶךְ צַדִּיקִים", en: "For YHWH knows the way of the righteous.", hit: "צַדִּיקִים", hitEn: "righteous", vocabId: "tsaddiq" },
      { ref: "Prov 1:5", he: "יִשְׁמַע חָכָם וְיוֹסֵף לֶקַח", en: "Let the wise hear and add learning.", hit: "חָכָם", hitEn: "wise", vocabId: "hakam" },
      { ref: "Gen 24:1", he: "וְאַבְרָהָם זָקֵן בָּא בַּיָּמִים", en: "Abraham was old, coming in days.", hit: "זָקֵן", hitEn: "old", vocabId: "zaqen" },
    ],
    quiz: [
      { q: "An adjective used as a noun is called…", choices: ["Substantive — “the righteous,” “the wicked”", "Always construct", "Always a verb"], answer: "Substantive — “the righteous,” “the wicked”", why: "Endings still count." },
      { q: "צַדִּיקִים in Ps 1:6 names…", he: "צַדִּיקִים", ref: "Ps 1:6", choices: ["People — the righteous ones", "A feminine singular quality only", "A preposition"], answer: "People — the righteous ones", why: "Way of the righteous." },
      { q: "מְאֹד in Gen 1:31…", he: "מְאֹד", ref: "Gen 1:31", choices: ["Very — does not take gender endings", "Feminine of טוֹב", "The article"], answer: "Very — does not take gender endings", why: "טוֹב מְאֹד. Class particle." },
      { q: "זָקֵן can be…", he: "זָקֵן", choices: ["The adjective “old” or the noun “elder”", "Only a verb “to be old”", "A dual of זֶה"], answer: "The adjective “old” or the noun “elder”", why: "Class vocab lists both." },
      { q: "Better than gold uses…", choices: ["מִן after the adjective", "Always מְאֹד", "The object marker"], answer: "מִן after the adjective", why: "Chapter 6 comparative still works here." },
      { q: "חָכָם as a subject means…", he: "חָכָם", choices: ["A wise person", "Wisdom as a fs noun חָכְמָה", "The verb “hear”"], answer: "A wise person", why: "Let the wise hear." },
      { q: "רַבִּים can mean…", he: "רַבִּים", choices: ["Many (people) — mp of רַב", "Only “great king”", "A name"], answer: "Many (people) — mp of רַב", why: "Substantive or attributive from the verse." },
      { q: "קָרוֹב and רָחוֹק are class opposites…", choices: ["Near / far", "Good / evil", "Holy / wicked"], answer: "Near / far", why: "Chapter 7 pair." },
      { q: "יָשָׁר means…", he: "יָשָׁר", choices: ["Upright, just", "Strange", "Little"], answer: "Upright, just", why: "Class." },
      { q: "זָר means…", he: "זָר", choices: ["Foreign, strange", "Living", "Old"], answer: "Foreign, strange", why: "Class." },
      { q: "חַי means…", he: "חַי", choices: ["Living, alive", "Evil", "Small"], answer: "Living, alive", why: "Class. Living God." },
      { q: "Maximum exposure: Gen 1:31 joins…", ref: "Gen 1:31", choices: ["טוֹב and מְאֹד — two class lemmas in one glance", "Only a number", "Only a name"], answer: "טוֹב and מְאֹד — two class lemmas in one glance", why: "Very good." },
    ],
  },
];
