import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on the construct chain. Masoretic examples. Not a textbook reprint. */
export const CONSTRUCT_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "X of Y",
    short: "Two nouns, one idea",
    rule:
      "A construct chain is “the X of Y”: דְּבַר־יְהוָה “the word of YHWH,” אִישׁ מִלְחָמָה “a man of war.” The first noun is construct (bound); the last is absolute (free). English “of” is often not a separate Hebrew word. The chain is definite if the last member is definite (name, article, or suffix).",
    samples: [
      { word: "דְּבַר־יְהוָה", gloss: "the word of YHWH", tag: "construct + name", note: "Definite because the name is definite.", ref: "Gen 15:1" },
      { word: "אִישׁ מִלְחָמָה", gloss: "a man of war", tag: "indefinite chain", note: "Last noun has no article.", ref: "Exod 15:3" },
      { word: "בְּרִית", gloss: "covenant", tag: "class noun", note: "Often in construct: covenant of…", ref: "Gen 9:9" },
      { word: "יָד", gloss: "hand, power", tag: "class noun", note: "Construct יַד.", ref: "Exod 14:31" },
    ],
    verses: [
      { ref: "Gen 15:1", he: "הָיָה דְבַר־יְהוָה אֶל־אַבְרָם", en: "The word of YHWH came to Abram.", hit: "דְבַר־יְהוָה", hitEn: "word of YHWH", vocabId: "dabar" },
      { ref: "Exod 15:3", he: "יְהוָה אִישׁ מִלְחָמָה יְהוָה שְׁמוֹ", en: "YHWH is a man of war; YHWH is his name.", hit: "אִישׁ מִלְחָמָה", hitEn: "man of war", vocabId: "ish" },
      { ref: "Gen 9:9", he: "וַאֲנִי הִנְנִי מֵקִים אֶת־בְּרִיתִי אִתְּכֶם", en: "And I — look — I am establishing my covenant with you.", hit: "בְּרִיתִי", hitEn: "covenant", vocabId: "berit" },
      { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד", en: "Who is this king of glory?", hit: "מֶלֶךְ הַכָּבוֹד", hitEn: "king of glory", vocabId: "melek" },
    ],
    quiz: [
      { q: "A construct chain is…", choices: ["X of Y — first noun bound, last noun free", "Always a verb plus object marker", "Two articles on one noun"], answer: "X of Y — first noun bound, last noun free", why: "Word of YHWH." },
      { q: "The last noun of the chain is called…", choices: ["Absolute", "Construct", "Maqqef"], answer: "Absolute", why: "It is free." },
      { q: "דְּבַר־יְהוָה is definite because…", he: "דְּבַר־יְהוָה", ref: "Gen 15:1", choices: ["The last member is a name", "The first has הַ", "It is dual"], answer: "The last member is a name", why: "A name is definite." },
      { q: "אִישׁ מִלְחָמָה is…", he: "אִישׁ מִלְחָמָה", ref: "Exod 15:3", choices: ["A man of war — indefinite chain", "The man of the war (both have הַ)", "A verb"], answer: "A man of war — indefinite chain", why: "No article on the last noun." },
      { q: "מֶלֶךְ הַכָּבוֹד is…", he: "מֶלֶךְ הַכָּבוֹד", ref: "Ps 24:8", choices: ["The king of glory — definite from the last article", "A king of a glory", "Predicate adjective"], answer: "The king of glory — definite from the last article", why: "Article on the last member defines the chain." },
      { q: "Do not put הַ on the construct noun when…", choices: ["The chain’s definiteness comes from the last member", "You always must", "It is a name"], answer: "The chain’s definiteness comes from the last member", why: "Not הַדְּבַר יְהוָה." },
      { q: "Class בְּרִית in בְּרִיתִי is…", he: "בְּרִיתִי", choices: ["My covenant — noun plus suffix (suffix makes it definite)", "Covenant of I", "A dual"], answer: "My covenant — noun plus suffix (suffix makes it definite)", why: "Suffix = definite." },
      { q: "English “of” in these phrases is…", choices: ["Usually not a separate Hebrew word", "Always מִן", "Always אֵת"], answer: "Usually not a separate Hebrew word", why: "The chain itself is “of.”" },
      { q: "יָד as class vocab will often appear as…", he: "יָד", choices: ["Hand / power, and in construct יַד", "Only a verb", "The article"], answer: "Hand / power, and in construct יַד", why: "Chapter 10." },
      { q: "Two class nouns in אִישׁ מִלְחָמָה…", ref: "Exod 15:3", choices: ["אִישׁ and מִלְחָמָה", "Only YHWH", "Only a number"], answer: "אִישׁ and מִלְחָמָה", why: "Ch. 3 and ch. 9." },
      { q: "A chain can have more than two nouns…", choices: ["Yes — still only the last is absolute", "No — illegal", "Only if dual"], answer: "Yes — still only the last is absolute", why: "All but the last are construct." },
      { q: "First question on two nouns in a row…", choices: ["Are they a chain (X of Y) or adjective + noun?", "Always a verb", "Always numbers"], answer: "Are they a chain (X of Y) or adjective + noun?", why: "Different jobs." },
    ],
  },
  {
    id: 2,
    title: "Masculine construct",
    short: "Vowels tighten",
    rule:
      "Masculine singular construct often shortens vowels: דָּבָר → דְּבַר, יָד → יַד, מָוֶת → מוֹת in some forms. Masculine plural ִים becomes ֵי: מְלָכִים → מַלְכֵי “kings of.” The consonants of the lemma are still there — look them up in the absolute singular.",
    samples: [
      { word: "דְּבַר", gloss: "word of", tag: "ms construct", note: "From דָּבָר.", ref: "Gen 15:1" },
      { word: "מַלְכֵי", gloss: "kings of", tag: "mp construct", note: "ִים → ֵי.", ref: "Ps 2:2" },
      { word: "מוֹת", gloss: "death of", tag: "construct", note: "From מָוֶת.", ref: "Josh 1:1" },
      { word: "יַד", gloss: "hand of", tag: "ms construct", note: "From יָד.", ref: "Exod 14:31" },
    ],
    verses: [
      { ref: "Ps 2:2", he: "יִתְיַצְּבוּ מַלְכֵי־אֶרֶץ", en: "The kings of the earth take their stand.", hit: "מַלְכֵי", hitEn: "kings of", vocabId: "melek" },
      { ref: "Josh 1:1", he: "וַיְהִי אַחֲרֵי מוֹת מֹשֶׁה עֶבֶד יְהוָה", en: "After the death of Moses, servant of YHWH…", hit: "מוֹת", hitEn: "death of", vocabId: "mavet" },
      { ref: "Exod 14:31", he: "וַיַּרְא יִשְׂרָאֵל אֶת־הַיָּד הַגְּדֹלָה", en: "Israel saw the great hand…", hit: "הַיָּד", hitEn: "hand", vocabId: "yad" },
      { ref: "Gen 1:2", he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם", en: "And the spirit of God was hovering over the face of the waters.", hit: "פְּנֵי", hitEn: "face of", vocabId: "panim" },
    ],
    quiz: [
      { q: "Masculine plural construct ending is…", choices: ["ֵי (from ִים)", "וֹת", "ַיִם"], answer: "ֵי (from ִים)", why: "מַלְכֵי." },
      { q: "מַלְכֵי־אֶרֶץ is…", he: "מַלְכֵי־אֶרֶץ", ref: "Ps 2:2", choices: ["Kings of the earth — construct + class אֶרֶץ", "The kings are earth", "A dual of king"], answer: "Kings of the earth — construct + class אֶרֶץ", why: "Look up מֶלֶךְ and אֶרֶץ." },
      { q: "מוֹת מֹשֶׁה is…", he: "מוֹת מֹשֶׁה", ref: "Josh 1:1", choices: ["The death of Moses — construct of מָוֶת + name", "Moses is death (predicate)", "A verb “die!”"], answer: "The death of Moses — construct of מָוֶת + name", why: "Definite: name." },
      { q: "דְּבַר is the construct of…", he: "דְּבַר", choices: ["דָּבָר", "דְּבַשׁ", "בָּרָא"], answer: "דָּבָר", why: "Vowels tighten. Lemma stays." },
      { q: "פְּנֵי is construct of class…", he: "פְּנֵי", choices: ["פָּנִים face", "פֹּה here as a verb", "The article"], answer: "פָּנִים face", why: "עַל־פְּנֵי." },
      { q: "Look up מַלְכֵי as…", he: "מַלְכֵי", choices: ["מֶלֶךְ", "מַלְכֵי as the only form", "מְלָאכָה"], answer: "מֶלֶךְ", why: "Singular citation." },
      { q: "Construct is not…", choices: ["A new lemma — it is a state of the same noun", "Bound to the next noun", "Often shorter in vowels"], answer: "A new lemma — it is a state of the same noun", why: "Same dictionary word." },
      { q: "עֶבֶד יְהוָה is…", he: "עֶבֶד יְהוָה", ref: "Josh 1:1", choices: ["Servant of YHWH", "YHWH is a servant (predicate)", "The article on servant"], answer: "Servant of YHWH", why: "Chain. Class name." },
      { q: "יָד / יַד is chapter 10 vocab for…", he: "יָד", choices: ["Hand, power", "Foot", "Stone"], answer: "Hand, power", why: "Class." },
      { q: "מָוֶת is…", he: "מָוֶת", choices: ["Death", "Covenant", "Wilderness"], answer: "Death", why: "Class." },
      { q: "If ֵי is on a noun before another noun…", choices: ["Likely mp construct “Xs of Y”", "Always dual", "Always a verb"], answer: "Likely mp construct “Xs of Y”", why: "Train that reflex." },
      { q: "הַיָּד הַגְּדֹלָה is NOT a construct chain because…", he: "הַיָּד הַגְּדֹלָה", ref: "Exod 14:31", choices: ["It is noun + attributive adjective (both have הַ)", "It is X of Y", "It is a relative clause"], answer: "It is noun + attributive adjective (both have הַ)", why: "The great hand. Ch. 7 still applies." },
    ],
  },
  {
    id: 3,
    title: "Feminine construct",
    short: "ָה often becomes ַת",
    rule:
      "Feminine singular ָה frequently becomes ַת in construct: תּוֹרָה → תּוֹרַת, מִלְחָמָה → מִלְחֶמֶת in some patterns, בְּרָכָה → בִּרְכַּת. Feminine plural וֹת often stays, with vowel work. You still look the word up as the absolute singular.",
    samples: [
      { word: "תּוֹרַת", gloss: "instruction of", tag: "fs construct", note: "From תּוֹרָה.", ref: "Ps 19:8" },
      { word: "בְּרִית", gloss: "covenant", tag: "fs-like", note: "Already ִית — construct may look similar.", ref: "Gen 9:9" },
      { word: "אֶרֶץ", gloss: "land of", tag: "segolate", note: "Construct אֶרֶץ / אֶרֶץ־.", ref: "Gen 13:12" },
      { word: "בַּיִת", gloss: "house of", tag: "construct בֵּית", note: "Class. מִבֵּית = from the house of.", ref: "Exod 20:2" },
    ],
    verses: [
      { ref: "Ps 19:8", he: "תּוֹרַת יְהוָה תְּמִימָה מְשִׁיבַת נָפֶשׁ", en: "The instruction of YHWH is complete, restoring the life.", hit: "תּוֹרַת", hitEn: "instruction of", vocabId: "torah" },
      { ref: "Gen 13:12", he: "אַבְרָם יָשַׁב בְּאֶרֶץ־כְּנָעַן", en: "Abram settled in the land of Canaan.", hit: "בְּאֶרֶץ־כְּנָעַן", hitEn: "in the land of Canaan", vocabId: "erets" },
      { ref: "Exod 20:2", he: "מֵאֶרֶץ מִצְרַיִם מִבֵּית עֲבָדִים", en: "From the land of Egypt, from the house of slaves.", hit: "מִבֵּית", hitEn: "from the house of", vocabId: "bayit" },
      { ref: "Deut 6:1", he: "וְזֹאת הַמִּצְוָה הַחֻקִּים וְהַמִּשְׁפָּטִים", en: "This is the command, the statutes, and the judgments…", hit: "הַמִּשְׁפָּטִים", hitEn: "judgments", vocabId: "mishpat" },
    ],
    quiz: [
      { q: "Feminine ָה in construct often becomes…", choices: ["ַת (תּוֹרַת)", "ִים", "ֵי only"], answer: "ַת (תּוֹרַת)", why: "Older feminine t shows up when bound." },
      { q: "תּוֹרַת יְהוָה is…", he: "תּוֹרַת יְהוָה", ref: "Ps 19:8", choices: ["The instruction of YHWH", "YHWH is instruction (predicate)", "A dual of Torah"], answer: "The instruction of YHWH", why: "Definite: name. Class תּוֹרָה." },
      { q: "Look up תּוֹרַת as…", he: "תּוֹרַת", choices: ["תּוֹרָה", "תּוֹרַת as a new lemma", "יוֹם"], answer: "תּוֹרָה", why: "Absolute singular." },
      { q: "בְּאֶרֶץ־כְּנָעַן is…", he: "בְּאֶרֶץ־כְּנָעַן", ref: "Gen 13:12", choices: ["In the land of Canaan — בְּ + construct אֶרֶץ + name", "From Canaan", "The Canaan is land"], answer: "In the land of Canaan — בְּ + construct אֶרֶץ + name", why: "Prep plus chain. Two class names/nouns." },
      { q: "מִבֵּית עֲבָדִים is…", he: "מִבֵּית", ref: "Exod 20:2", choices: ["From the house of slaves — מִן fused + construct בַּיִת", "In a house", "The object marker"], answer: "From the house of slaves — מִן fused + construct בַּיִת", why: "Class בַּיִת." },
      { q: "A name as the last member makes the whole chain…", choices: ["Definite", "Indefinite", "Dual"], answer: "Definite", why: "Land of Canaan = that land." },
      { q: "בְּרִית as class vocab is…", he: "בְּרִית", choices: ["Covenant", "Field", "Staff"], answer: "Covenant", why: "Chapter 10." },
      { q: "שָׂדֶה is…", he: "שָׂדֶה", choices: ["Field, pastureland", "Stone", "Enemy"], answer: "Field, pastureland", why: "Class. Construct שְׂדֵה / שְׂדֵה־." },
      { q: "אֶבֶן is…", he: "אֶבֶן", choices: ["Stone", "Flesh", "Month"], answer: "Stone", why: "Class." },
      { q: "Do not treat תּוֹרַת as a verb…", choices: ["It is a noun in construct", "It is Qal perfect", "It is the article"], answer: "It is a noun in construct", why: "Ending ַת on a known lemma." },
      { q: "Prep + construct is common…", choices: ["בְּ / לְ / מִן then the bound noun", "Illegal", "Only with dual"], answer: "בְּ / לְ / מִן then the bound noun", why: "In the land of… from the house of…" },
      { q: "Maximum exposure in Exod 20:2…", ref: "Exod 20:2", choices: ["מִן, אֶרֶץ, מִצְרַיִם, בַּיִת — all class", "Only an adjective", "Only a number"], answer: "מִן, אֶרֶץ, מִצְרַיִם, בַּיִת — all class", why: "Preps and nouns you already drill." },
    ],
  },
  {
    id: 4,
    title: "Chains in the wild",
    short: "Hand, field, wilderness, time",
    rule:
      "Chapter 10 nouns love construct: יָד hand, שָׂדֶה field, מִדְבָּר wilderness, בְּרִית covenant, חֶסֶד loyalty, עֵת time, חֹדֶשׁ month, מַטֶּה tribe/staff, גְּבוּל border. Read the chain, restore each lemma, say the English “of.” Fun test: if you can swap in “of” and it still makes sense, you found a chain.",
    samples: [
      { word: "חֶסֶד", gloss: "loyalty, steadfast love", tag: "class", note: "Often חֶסֶד יי.", ref: "Exod 34:6" },
      { word: "מִדְבָּר", gloss: "wilderness", tag: "class", note: "בַּמִּדְבָּר = in the wilderness.", ref: "Exod 3:1" },
      { word: "עֵת", gloss: "time", tag: "class", note: "A time of…", ref: "Eccl 3:1" },
      { word: "חֹדֶשׁ", gloss: "month, new moon", tag: "class", note: "Class.", ref: "Exod 12:2" },
    ],
    verses: [
      { ref: "Exod 34:6", he: "יְהוָה יְהוָה אֵל רַחוּם וְחַנּוּן אֶרֶךְ אַפַּיִם וְרַב־חֶסֶד וֶאֱמֶת", en: "YHWH, YHWH, a God merciful and gracious, slow to anger, and abundant in steadfast love and truth.", hit: "חֶסֶד", hitEn: "steadfast love", vocabId: "hesed" },
      { ref: "Eccl 3:1", he: "לַכֹּל זְמָן וְעֵת לְכָל־חֵפֶץ תַּחַת הַשָּׁמָיִם", en: "For everything a season, and a time for every matter under heaven.", hit: "וְעֵת", hitEn: "a time", vocabId: "et-time" },
      { ref: "Exod 12:2", he: "הַחֹדֶשׁ הַזֶּה לָכֶם רֹאשׁ חֳדָשִׁים", en: "This month shall be for you the head of months.", hit: "הַחֹדֶשׁ", hitEn: "month", vocabId: "hodesh" },
      { ref: "Gen 2:5", he: "וְכֹל שִׂיחַ הַשָּׂדֶה טֶרֶם יִהְיֶה בָאָרֶץ", en: "No shrub of the field was yet on the earth.", hit: "הַשָּׂדֶה", hitEn: "the field", vocabId: "sadeh" },
    ],
    quiz: [
      { q: "The “of” test: if English “of” fits…", choices: ["You likely have a construct chain", "You have a predicate adjective", "You have a yes/no הֲ"], answer: "You likely have a construct chain", why: "Word of, kings of, land of." },
      { q: "חֶסֶד is…", he: "חֶסֶד", choices: ["Loyalty, faithfulness, steadfast love", "Enemy", "Flesh"], answer: "Loyalty, faithfulness, steadfast love", why: "Class." },
      { q: "מִדְבָּר is…", he: "מִדְבָּר", choices: ["Wilderness, desert", "Covenant", "Death"], answer: "Wilderness, desert", why: "Class." },
      { q: "עֵת is…", he: "עֵת", choices: ["Time, point of time", "The object marker אֵת", "With אֵת"], answer: "Time, point of time", why: "Different lemma from the object marker." },
      { q: "Do not mix עֵת “time” with…", choices: ["אֵת the object marker / “with”", "יָד", "שָׂדֶה"], answer: "אֵת the object marker / “with”", why: "Different spelling, different job." },
      { q: "חֹדֶשׁ is…", he: "חֹדֶשׁ", choices: ["Month, new moon", "New (that is חָדָשׁ)", "Half"], answer: "Month, new moon", why: "Class. Not the adjective חָדָשׁ." },
      { q: "רֹאשׁ חֳדָשִׁים is…", he: "רֹאשׁ חֳדָשִׁים", ref: "Exod 12:2", choices: ["Head of months — construct + plural", "First adjective only", "A verb"], answer: "Head of months — construct + plural", why: "This month is for you the head of months." },
      { q: "הַשָּׂדֶה is…", he: "הַשָּׂדֶה", choices: ["The field — article on class שָׂדֶה", "Construct of field of", "A dual"], answer: "The field — article on class שָׂדֶה", why: "Absolute with article." },
      { q: "גְּבוּל is…", he: "גְּבוּל", choices: ["Border, boundary, territory", "Staff", "Flock"], answer: "Border, boundary, territory", why: "Class." },
      { q: "אֹיֵב is…", he: "אֹיֵב", choices: ["Enemy", "Stone", "Flesh"], answer: "Enemy", why: "Class." },
      { q: "בָּשָׂר is…", he: "בָּשָׂר", choices: ["Flesh, meat, skin", "Covenant", "Month"], answer: "Flesh, meat, skin", why: "Class." },
      { q: "Restore every construct to…", choices: ["The absolute singular in the lexicon / class list", "The English gloss only", "The dual always"], answer: "The absolute singular in the lexicon / class list", why: "That is the vocab you already drill." },
    ],
  },
];
