import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on independent pronouns, demonstratives, and question words. Masoretic examples. */
export const PRON_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "I, you, he",
    short: "Independent pronouns",
    rule:
      "Independent pronouns stand as their own words: אֲנִי / אָנֹכִי “I,” אַתָּה “you” (ms), הוּא “he,” הִיא “she,” אֲנַחְנוּ “we,” אַתֶּם “you” (mp), הֵם “they.” They often add emphasis or complete a predicate: קָדוֹשׁ אֲנִי. Hebrew verbs already hide their subject, so a written pronoun is doing extra work — stress, contrast, or a verbless clause.",
    samples: [
      { word: "אֲנִי", gloss: "I", tag: "1cs", note: "Class. Shorter cousin of אָנֹכִי.", ref: "Lev 19:2" },
      { word: "אָנֹכִי", gloss: "I", tag: "1cs", note: "Heavier “I.” Exod 20:2.", ref: "Exod 20:2" },
      { word: "אַתָּה", gloss: "you (ms)", tag: "2ms", note: "Class.", ref: "Gen 49:8" },
      { word: "הוּא", gloss: "he, it; that", tag: "3ms", note: "Also a far demonstrative “that.”", ref: "Deut 7:21" },
      { word: "הִיא", gloss: "she, it; that", tag: "3fs", note: "Sometimes spelled הִוא.", ref: "Gen 2:23" },
    ],
    verses: [
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ", en: "I am YHWH your God.", hit: "אָנֹכִי", hitEn: "I", vocabId: "anoki" },
      { ref: "Lev 19:2", he: "כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם", en: "For I, YHWH your God, am holy.", hit: "אֲנִי", hitEn: "I", vocabId: "ani" },
      { ref: "Gen 49:8", he: "יְהוּדָה אַתָּה יוֹדוּךָ אַחֶיךָ", en: "Judah, you — your brothers will praise you.", hit: "אַתָּה", hitEn: "you", vocabId: "attah" },
      { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "יִשְׂרָאֵל", hitEn: "Israel", vocabId: "israel" },
    ],
    quiz: [
      { q: "אֲנִי means…", he: "אֲנִי", choices: ["I", "You", "They"], answer: "I", why: "Class." },
      { q: "אָנֹכִי also means…", he: "אָנֹכִי", choices: ["I — a longer form", "We", "He"], answer: "I — a longer form", why: "Exod 20:2 I am YHWH." },
      { q: "אַתָּה is…", he: "אַתָּה", choices: ["You (masculine singular)", "She", "They"], answer: "You (masculine singular)", why: "Judah, you." },
      { q: "אַתֶּם is…", he: "אַתֶּם", choices: ["You (masculine plural)", "I", "She"], answer: "You (masculine plural)", why: "Class." },
      { q: "הוּא can be…", he: "הוּא", choices: ["He / it, and also “that”", "Only the copula “is” in English", "A preposition"], answer: "He / it, and also “that”", why: "Pronoun and far demonstrative." },
      { q: "הִיא is…", he: "הִיא", choices: ["She / it", "We", "You ms"], answer: "She / it", why: "Class." },
      { q: "אֲנַחְנוּ is…", he: "אֲנַחְנוּ", choices: ["We", "They", "I"], answer: "We", why: "Class." },
      { q: "הֵם / הֵמָּה is…", he: "הֵם", choices: ["They, those", "I", "You fs"], answer: "They, those", why: "Class." },
      { q: "A written independent pronoun often…", choices: ["Adds emphasis or completes a verbless clause", "Replaces the object marker", "Is the article"], answer: "Adds emphasis or completes a verbless clause", why: "The verb already has a subject." },
      { q: "Exod 20:2 starts with אָנֹכִי because…", he: "אָנֹכִי", ref: "Exod 20:2", choices: ["The speaker stresses “I” — YHWH himself", "It is a preposition", "It is dual"], answer: "The speaker stresses “I” — YHWH himself", why: "I am YHWH your God." },
      { q: "קָדוֹשׁ אֲנִי pairs a class adjective with…", ref: "Lev 19:2", choices: ["The pronoun “I”", "The article", "מִן"], answer: "The pronoun “I”", why: "I am holy." },
      { q: "Look these up as…", choices: ["Their own lemmas — they do not strip like nouns with הַ", "Always the verb “to be”", "Construct of אָב"], answer: "Their own lemmas — they do not strip like nouns with הַ", why: "Pronouns are citation forms." },
    ],
  },
  {
    id: 2,
    title: "This and these",
    short: "Near demonstratives",
    rule:
      "זֶה “this” (ms), זֹאת “this” (fs), אֵלֶּה “these.” They point to something near. Like adjectives they can sit after a noun and match gender/number/definiteness (הַיּוֹם הַזֶּה “this day”), or stand alone (“this is…”). הוּא / הִיא / הֵם can point farther: “that / those.”",
    samples: [
      { word: "זֶה", gloss: "this (ms)", tag: "near", note: "Class.", ref: "Ps 24:8" },
      { word: "זֹאת", gloss: "this (fs)", tag: "near", note: "Class.", ref: "Gen 2:23" },
      { word: "אֵלֶּה", gloss: "these", tag: "near pl", note: "Class.", ref: "Exod 1:1" },
      { word: "הַיּוֹם הַזֶּה", gloss: "this day", tag: "attributive", note: "Noun + matching demonstrative.", ref: "Deut 6:6" },
    ],
    verses: [
      { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד", en: "Who is this king of glory?", hit: "זֶה", hitEn: "this", vocabId: "zeh" },
      { ref: "Gen 2:23", he: "לְזֹאת יִקָּרֵא אִשָּׁה", en: "This one shall be called woman.", hit: "זֹאת", hitEn: "This", vocabId: "zot" },
      { ref: "Exod 1:1", he: "וְאֵלֶּה שְׁמוֹת בְּנֵי יִשְׂרָאֵל", en: "And these are the names of the sons of Israel.", hit: "אֵלֶּה", hitEn: "these", vocabId: "elleh" },
      { ref: "Deut 6:6", he: "וְהָיוּ הַדְּבָרִים הָאֵלֶּה אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", en: "These words that I command you this day shall be on your heart.", hit: "הָאֵלֶּה", hitEn: "These", vocabId: "elleh" },
    ],
    quiz: [
      { q: "זֶה is…", he: "זֶה", choices: ["This (masculine singular)", "These", "She"], answer: "This (masculine singular)", why: "Class." },
      { q: "זֹאת is…", he: "זֹאת", choices: ["This (feminine singular)", "They", "Who"], answer: "This (feminine singular)", why: "This one shall be called woman." },
      { q: "אֵלֶּה is…", he: "אֵלֶּה", choices: ["These", "I", "That (ms)"], answer: "These", why: "These are the names." },
      { q: "הַיּוֹם הַזֶּה is…", he: "הַיּוֹם הַזֶּה", choices: ["This day — noun and demonstrative both definite", "A day is this (predicate only)", "Dual of day"], answer: "This day — noun and demonstrative both definite", why: "Same article pattern as adjectives." },
      { q: "הַדְּבָרִים הָאֵלֶּה is…", he: "הַדְּבָרִים הָאֵלֶּה", ref: "Deut 6:6", choices: ["These words", "Those two words (dual)", "The word with object marker"], answer: "These words", why: "Class דָּבָר plus אֵלֶּה." },
      { q: "מִי זֶה מֶלֶךְ in Ps 24:8 stacks…", ref: "Ps 24:8", choices: ["Question מִי, demonstrative זֶה, class noun מֶלֶךְ", "Only a preposition", "The dual of king"], answer: "Question מִי, demonstrative זֶה, class noun מֶלֶךְ", why: "Who is this king?" },
      { q: "Far “that” often uses…", choices: ["הוּא / הִיא / הֵם", "זֶה only", "אֲנִי"], answer: "הוּא / הִיא / הֵם", why: "Same pronouns, pointing job." },
      { q: "A demonstrative standing first can mean…", choices: ["This is… / these are…", "Always a verb", "The article"], answer: "This is… / these are…", why: "וְאֵלֶּה שְׁמוֹת." },
      { q: "Agreement: זֹאת goes with…", choices: ["A feminine singular noun", "Masculine plural only", "Dual only"], answer: "A feminine singular noun", why: "Same as adjectives." },
      { q: "Class vocab “this” (ms) is…", choices: ["זֶה", "אֵלֶּה", "מָה"], answer: "זֶה", why: "Chapter 8." },
      { q: "אַחֵר means…", he: "אַחֵר", choices: ["Other, another", "This", "Who"], answer: "Other, another", why: "Class adjective in this chapter’s list." },
      { q: "Do not confuse זֶה with…", choices: ["שֶׁ the prefixed relative (next units)", "טוֹב", "מִן"], answer: "שֶׁ the prefixed relative (next units)", why: "Different lemmas." },
    ],
  },
  {
    id: 3,
    title: "Who, what, why",
    short: "Questions",
    rule:
      "מִי “who,” מָה / מַה “what,” לָמָּה / מַדּוּעַ “why.” הֲ in front of a clause asks a yes/no question and is not the article הַ (different vowel). The article is הַ with pathach; the interrogative is הֲ with ḥateph-pathach. Ps 24:8 מִי זֶה — “who is this?”",
    samples: [
      { word: "מִי", gloss: "who", tag: "question", note: "Class.", ref: "Ps 24:8" },
      { word: "מָה", gloss: "what", tag: "question", note: "Also מַה, מֶה.", ref: "Gen 4:10" },
      { word: "לָמָּה", gloss: "why", tag: "question", note: "Class. Also לָמָה.", ref: "Gen 4:6" },
      { word: "מַדּוּעַ", gloss: "why", tag: "question", note: "Class.", ref: "Exod 3:3" },
      { word: "הֲ", gloss: "yes/no question", tag: "interrogative", note: "Not the article הַ.", ref: "Gen 4:9" },
    ],
    verses: [
      { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד", en: "Who is this king of glory?", hit: "מִי", hitEn: "Who", vocabId: "mi" },
      { ref: "Gen 4:9", he: "וַיֹּאמֶר יְהוָה אֶל־קַיִן אֵי הֶבֶל אָחִיךָ וַיֹּאמֶר לֹא יָדַעְתִּי הֲשֹׁמֵר אָחִי אָנֹכִי", en: "YHWH said to Cain, “Where is Abel your brother?” He said, “I do not know. Am I my brother’s keeper?”", hit: "הֲשֹׁמֵר", hitEn: "Am I", vocabId: "ha-int" },
      { ref: "Gen 4:10", he: "וַיֹּאמֶר מֶה עָשִׂיתָ", en: "He said, “What have you done?”", hit: "מֶה", hitEn: "What", vocabId: "mah" },
      { ref: "Exod 3:3", he: "וַיֹּאמֶר מֹשֶׁה אָסֻרָה־נָּא וְאֶרְאֶה אֶת־הַמַּרְאֶה הַגָּדֹל הַזֶּה מַדּוּעַ לֹא־יִבְעַר הַסְּנֶה", en: "Moses said, “Let me turn aside and see this great sight — why the bush is not burned.”", hit: "מַדּוּעַ", hitEn: "why", vocabId: "maddua" },
    ],
    quiz: [
      { q: "מִי means…", he: "מִי", choices: ["Who", "What", "Why"], answer: "Who", why: "Class." },
      { q: "מָה / מַה means…", he: "מָה", choices: ["What", "Who", "These"], answer: "What", why: "Class." },
      { q: "לָמָּה and מַדּוּעַ both ask…", choices: ["Why", "Who", "Where only"], answer: "Why", why: "Two class lemmas." },
      { q: "הֲ on הֲשֹׁמֵר is…", he: "הֲשֹׁמֵר", ref: "Gen 4:9", choices: ["The yes/no question particle, not the article הַ", "The article “the keeper”", "A dual"], answer: "The yes/no question particle, not the article הַ", why: "Am I my brother’s keeper?" },
      { q: "How do you tell הֲ from הַ?", choices: ["Interrogative is ḥateph-pathach הֲ; article is pathach הַ (often with dagesh)", "They are identical always", "הֲ is only on names"], answer: "Interrogative is ḥateph-pathach הֲ; article is pathach הַ (often with dagesh)", why: "Vowel, and the article’s dagesh." },
      { q: "Ps 24:8 מִי זֶה uses two chapter-8 words plus…", ref: "Ps 24:8", choices: ["מֶלֶךְ and כָּבוֹד from the noun list", "Only a number", "Only מִן"], answer: "מֶלֶךְ and כָּבוֹד from the noun list", why: "Maximum exposure in one line." },
      { q: "מֶה עָשִׂיתָ is…", he: "מֶה", ref: "Gen 4:10", choices: ["What have you done?", "Who have you done?", "Why a bush?"], answer: "What have you done?", why: "מָה/מֶה = what." },
      { q: "A הֲ question expects…", choices: ["Yes or no (or a shocked “am I…?”)", "A name only", "A number"], answer: "Yes or no (or a shocked “am I…?”)", why: "Am I my brother’s keeper?" },
      { q: "Class vocab for “who” is…", choices: ["מִי", "מָה", "הֲ"], answer: "מִי", why: "Chapter 8." },
      { q: "Do not treat interrogative הֲ as…", choices: ["The definite article", "A question", "A particle"], answer: "The definite article", why: "Different lemma, different vowel." },
      { q: "מַדּוּעַ in Exod 3:3 asks…", he: "מַדּוּעַ", ref: "Exod 3:3", choices: ["Why the bush is not burned", "Who Moses is", "What gold is"], answer: "Why the bush is not burned", why: "Class “why.”" },
      { q: "Question words are class particles — look them up…", choices: ["As themselves, not stripped of a prefix they do not have", "Under the verb always", "As dual of מָה"], answer: "As themselves, not stripped of a prefix they do not have", why: "Citation = what you see, with spelling variants." },
    ],
  },
  {
    id: 4,
    title: "Who/which, that, because",
    short: "אֲשֶׁר, כִּי, שֶׁ",
    rule:
      "אֲשֶׁר links a clause: who, that, which. כִּי is a small word with a big job — because, that, indeed, but. שֶׁ is a prefixed relative (later style, also Qohelet and Song). None of these is a noun. Read them as glue between clauses, then name the class nouns around them.",
    samples: [
      { word: "אֲשֶׁר", gloss: "who, that, which", tag: "relative", note: "Class. Very frequent.", ref: "Exod 20:2" },
      { word: "כִּי", gloss: "that, because, indeed", tag: "conjunction", note: "Class. Context picks the gloss.", ref: "Gen 1:4" },
      { word: "שֶׁ", gloss: "who/which (prefixed)", tag: "relative prefix", note: "Class. Not זֶה.", ref: "Ps 124:6" },
    ],
    verses: [
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "אֲשֶׁר", hitEn: "who", vocabId: "asher" },
      { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "כִּי", hitEn: "that", vocabId: "ki" },
      { ref: "Deut 6:6", he: "וְהָיוּ הַדְּבָרִים הָאֵלֶּה אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", en: "These words that I command you this day…", hit: "אֲשֶׁר", hitEn: "that", vocabId: "asher" },
      { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד", en: "God saw all that he had made, and look — it was very good.", hit: "אֲשֶׁר", hitEn: "that", vocabId: "asher" },
    ],
    quiz: [
      { q: "אֲשֶׁר means…", he: "אֲשֶׁר", choices: ["Who, that, which — a relative glue", "I", "This (ms)"], answer: "Who, that, which — a relative glue", why: "Class. Extremely common." },
      { q: "In Exod 20:2 אֲשֶׁר points to…", he: "אֲשֶׁר", ref: "Exod 20:2", choices: ["YHWH — who brought you out", "Egypt as a verb", "The article"], answer: "YHWH — who brought you out", why: "Relative clause after the name." },
      { q: "כִּי in כִּי־טוֹב is…", he: "כִּי", ref: "Gen 1:4", choices: ["That (it was good) — not a noun", "Because gold", "Who"], answer: "That (it was good) — not a noun", why: "Class. Gloss from the verse." },
      { q: "כִּי can also mean…", he: "כִּי", choices: ["Because, but, indeed — pick from context", "Only “who”", "The object marker"], answer: "Because, but, indeed — pick from context", why: "One lemma, several English jobs." },
      { q: "שֶׁ is…", he: "שֶׁ", choices: ["A prefixed relative “who/which/that”", "The same as זֶה", "The article"], answer: "A prefixed relative “who/which/that”", why: "Class particle." },
      { q: "כָּל־אֲשֶׁר in Gen 1:31 is…", he: "כָּל־אֲשֶׁר", ref: "Gen 1:31", choices: ["All that (he had made) — כֹּל + אֲשֶׁר", "Every who of the article", "A dual"], answer: "All that (he had made) — כֹּל + אֲשֶׁר", why: "Two class lemmas glued." },
      { q: "Relative אֲשֶׁר does not inflect for…", choices: ["Gender and number — it stays אֲשֶׁר", "Nothing; it takes ִים", "Person like אַתָּה"], answer: "Gender and number — it stays אֲשֶׁר", why: "Not an adjective." },
      { q: "Deut 6:6 הַדְּבָרִים … אֲשֶׁר stacks…", ref: "Deut 6:6", choices: ["Class דָּבָר, demonstrative אֵלֶּה, relative אֲשֶׁר, pronoun אָנֹכִי", "Only numbers", "Only inseparable preps"], answer: "Class דָּבָר, demonstrative אֵלֶּה, relative אֲשֶׁר, pronoun אָנֹכִי", why: "This chapter living in Torah." },
      { q: "Do not look up אֲשֶׁר under…", choices: ["אִישׁ or שַׁעַר", "אֲשֶׁר itself", "The particle list"], answer: "אִישׁ or שַׁעַר", why: "It is its own lemma." },
      { q: "כִּי־אִם in some verses is…", choices: ["A listed spelling variant of כִּי with a stronger “but / except”", "The dual of כִּי", "The article"], answer: "A listed spelling variant of כִּי with a stronger “but / except”", why: "Class hebrewAlts." },
      { q: "After you name אֲשֶׁר, next…", choices: ["Read the clause it introduces, then the class nouns in it", "Stop", "Always add “the”"], answer: "Read the clause it introduces, then the class nouns in it", why: "Glue, then vocabulary." },
      { q: "Which is a relative?", choices: ["אֲשֶׁר", "טוֹב", "מִן"], answer: "אֲשֶׁר", why: "Chapter 8." },
    ],
  },
];
