import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on binyan signatures. Masoretic examples and class verbs — not a textbook reprint. */
export const VERB_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "A verb, not a noun",
    short: "Does the word do something?",
    rule:
      "A Hebrew verb is a word that does, says, or happens. Nouns name people and things (אָב, בַּיִת, תּוֹרָה). Verbs wear person, gender, and number on the form itself — no extra “he / she / they” is required. First question on a new word: is this doing work, or naming a thing?",
    teach:
      "Class lemmas you already know as nouns (מֶלֶךְ, בֵּן) are not this path. Class verbs start from אָמַר, עָשָׂה, שָׁמַע, נָתַן, הָיָה. If it can answer “who did what?”, it is a verb.",
    samples: [
      { word: "אָמַר", gloss: "he said", tag: "verb", note: "Citation of “to say.”", ref: "Gen 12:1" },
      { word: "עָשָׂה", gloss: "he made", tag: "verb", note: "Citation of “to do, make.”", ref: "Gen 1:7" },
      { word: "מֶלֶךְ", gloss: "king", tag: "noun", note: "A person, not an action.", ref: "Ps 24:8" },
      { word: "בַּיִת", gloss: "house", tag: "noun", note: "A thing.", ref: "Josh 24:15" },
    ],
    verses: [
      { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר", en: "God said, “Let there be light.”", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "The first doing-word in the line is the verb. אֱלֹהִים is who; אוֹר is a thing named later." },
      { ref: "Gen 1:7", he: "וַיַּעַשׂ אֱלֹהִים אֶת־הָרָקִיעַ", en: "God made the expanse.", hit: "וַיַּעַשׂ", hitEn: "made", vocabId: "asah", why: "עָשָׂה “to make” is doing the creating. הָרָקִיעַ is the thing made." },
      { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד", en: "Who is this king of glory?", hit: "מֶלֶךְ", hitEn: "king", vocabId: "melek", why: "מֶלֶךְ names a person. No person-ending. This is a noun." },
    ],
    quiz: [
      { q: "A Hebrew verb is a word that…", choices: ["Does, says, or happens", "Only names a person", "Is always a construct chain"], answer: "Does, says, or happens", why: "Nouns name; verbs work." },
      { q: "Person and gender on a Hebrew verb…", choices: ["Ride on the form — you often do not write a separate “he”", "Always need אַתָּה in front", "Come from the article הַ"], answer: "Ride on the form — you often do not write a separate “he”", why: "The clothes tell you who." },
      { q: "אָמַר is…", he: "אָמַר", choices: ["A verb — “he said”", "A noun “word”", "The article"], answer: "A verb — “he said”", why: "Class lemma. Citation form." },
      { q: "מֶלֶךְ is…", he: "מֶלֶךְ", choices: ["A noun — king", "Qal perfect of “to reign”", "A preposition"], answer: "A noun — king", why: "מָלַךְ is the verb “he reigned.” Different lemma." },
      { q: "Do not mix מֶלֶךְ with…", choices: ["מָלַךְ “he reigned”", "בַּיִת", "אַחַר"], answer: "מָלַךְ “he reigned”", why: "Same letters, different job." },
      { q: "עָשָׂה is the class lemma for…", he: "עָשָׂה", choices: ["To do, make", "A noun “deed”", "The dual of עֵץ"], answer: "To do, make", why: "Verb." },
      { q: "שָׁמַע is…", he: "שָׁמַע", choices: ["A verb — to hear, listen, obey", "A noun “ear”", "The article on שֵׁם"], answer: "A verb — to hear, listen, obey", why: "Class." },
      { q: "נָתַן is…", he: "נָתַן", choices: ["A verb — to give, put, set", "A noun “gift”", "Niphal of תן"], answer: "A verb — to give, put, set", why: "Citation Qal." },
      { q: "In Gen 1:3 the doing-word is…", he: "וַיֹּאמֶר", ref: "Gen 1:3", choices: ["וַיֹּאמֶר — God said", "אוֹר — a noun “light”", "אֱלֹהִים as a verb"], answer: "וַיֹּאמֶר — God said", why: "Verb first." },
      { q: "בַּיִת in a line is…", he: "בַּיִת", choices: ["A noun — house", "Qal of “to build”", "A wayyiqtol"], answer: "A noun — house", why: "בָּנָה is the verb “he built.”" },
      { q: "First question on a new Hebrew word…", choices: ["Is it doing work, or naming a thing?", "Is it dual?", "Does it start with בְּ?"], answer: "Is it doing work, or naming a thing?", why: "Verb vs noun." },
      { q: "הָיָה is…", he: "הָיָה", choices: ["A verb — to be, become, happen", "A noun “life”", "The pronoun הִיא"], answer: "A verb — to be, become, happen", why: "Class. Not חַיִּים “life.”" },
    ],
  },
  {
    id: 2,
    title: "Qal perfect 3ms — the citation",
    short: "The dictionary form",
    rule:
      "Qal is the basic stem: no extra prefix, no extra doubling. The perfect 3ms (he did) is the citation form in the lexicon: אָמַר, עָשָׂה, שָׁמַר. Look that shape up. Other clothes (she did, they did, he will) still belong to the same lemma.",
    teach:
      "Qal perfect 3ms often looks like two qamets vowels on a strong verb (קָטַל pattern): שָׁמַר, כָּתַב, מָלַךְ. III-ה verbs end in ָה (עָשָׂה, הָיָה, רָאָה). Still Qal. Still citation.",
    samples: [
      { word: "אָמַר", gloss: "he said", tag: "Qal pf 3ms", note: "Citation.", ref: "Gen 12:1" },
      { word: "שָׁמַר", gloss: "he kept", tag: "Qal pf 3ms", note: "Strong pattern.", ref: "Exod 12:24" },
      { word: "כָּתַב", gloss: "he wrote", tag: "Qal pf 3ms", note: "Class.", ref: "Exod 24:4" },
      { word: "עָשָׂה", gloss: "he made", tag: "Qal pf 3ms", note: "III-ה still citation.", ref: "Gen 1:7" },
    ],
    verses: [
      { ref: "Exod 24:4", he: "וַיִּכְתֹּב מֹשֶׁה אֵת כָּל־דִּבְרֵי יְהוָה", en: "Moses wrote all the words of YHWH.", hit: "וַיִּכְתֹּב", hitEn: "wrote", vocabId: "katab", why: "The lexicon still lists כָּתַב. This line wears a different tense — next units." },
      { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה", en: "God saw all that he had made.", hit: "עָשָׂה", hitEn: "made", vocabId: "asah", why: "עָשָׂה here is Qal perfect 3ms — the citation sitting in the verse." },
      { ref: "Deut 5:12", he: "שָׁמוֹר אֶת־יוֹם הַשַּׁבָּת", en: "Keep the sabbath day.", hit: "שָׁמוֹר", hitEn: "Keep", vocabId: "shamar", why: "Related clothes of שָׁמַר. Citation is still שָׁמַר." },
    ],
    quiz: [
      { q: "Qal means…", choices: ["The basic stem — no extra prefix, no extra doubling", "Always Hiphil", "Always a noun"], answer: "The basic stem — no extra prefix, no extra doubling", why: "First stem to learn." },
      { q: "The lexicon lists a verb as…", choices: ["Qal perfect 3ms", "Wayyiqtol 3ms", "The English infinitive only"], answer: "Qal perfect 3ms", why: "אָמַר, not וַיֹּאמֶר." },
      { q: "שָׁמַר is…", he: "שָׁמַר", choices: ["Qal perfect 3ms — he kept / watched", "Piel of שמר", "A noun “guard”"], answer: "Qal perfect 3ms — he kept / watched", why: "Class citation." },
      { q: "כָּתַב is…", he: "כָּתַב", choices: ["Qal perfect 3ms — he wrote", "Hiphil", "Infinitive construct"], answer: "Qal perfect 3ms — he wrote", why: "Two-qamets look on a strong verb." },
      { q: "עָשָׂה ends in ָה because…", he: "עָשָׂה", choices: ["It is a III-ה verb — still Qal citation", "It is feminine singular of a noun", "It is dual"], answer: "It is a III-ה verb — still Qal citation", why: "הָיָה, רָאָה, בָּנָה same family." },
      { q: "Look up וַיִּכְתֹּב as…", he: "וַיִּכְתֹּב", choices: ["כָּתַב — strip the story prefix", "וַיִּכְתֹּב as its own lemma", "Always כְּתֹבֶת a noun"], answer: "כָּתַב — strip the story prefix", why: "Citation is 3ms perfect Qal." },
      { q: "מָלַךְ is…", he: "מָלַךְ", choices: ["Qal perfect — he reigned", "The noun מֶלֶךְ", "Piel"], answer: "Qal perfect — he reigned", why: "Verb, not “king.”" },
      { q: "Class אָמַר in the lexicon is…", he: "אָמַר", choices: ["He said — Qal 3ms", "They said", "I said"], answer: "He said — Qal 3ms", why: "3ms is the headword." },
      { q: "רָאָה is…", he: "רָאָה", choices: ["Qal citation — to see", "Niphal “he appeared”", "A noun “sight”"], answer: "Qal citation — to see", why: "נִרְאָה is a later stem." },
      { q: "A Qal perfect 3ms strong verb often shows…", choices: ["Qamets under the first root letter", "הִ as a prefix", "Dagesh in the middle root as the main tell"], answer: "Qamets under the first root letter", why: "קָטַל pattern. Piel is the doubled middle." },
      { q: "In Gen 1:31 עָשָׂה is…", he: "עָשָׂה", ref: "Gen 1:31", choices: ["Qal perfect 3ms sitting in the verse", "Wayyiqtol", "A noun"], answer: "Qal perfect 3ms sitting in the verse", why: "All that he had made." },
      { q: "Citation of “to hear” is…", choices: ["שָׁמַע", "וַיִּשְׁמַע", "הִשְׁמִיעַ"], answer: "שָׁמַע", why: "Qal 3ms. The others are clothes." },
    ],
  },
  {
    id: 3,
    title: "Perfect endings",
    short: "He, she, you, I, they — on the tail",
    rule:
      "The perfect talks about a complete act. Endings ride on the tail: ∅ he (3ms), ָה she (3fs), תָּ you ms, תְּ you fs, תִּי I, וּ they, תֶּם you mp, נוּ we. The stem is still Qal. Strip the ending and you are back at the citation.",
    teach:
      "אָמַר he said · אָמְרָה she said · אָמַרְתָּ you (ms) said · אָמַרְתִּי I said · אָמְרוּ they said. Do not mix 3fs ָה with the III-ה citation עָשָׂה — one is an ending, one is the root’s last letter.",
    samples: [
      { word: "אָמַר", gloss: "he said", tag: "3ms", note: "No extra ending.", ref: "Gen 12:1" },
      { word: "אָמְרָה", gloss: "she said", tag: "3fs", note: "ָה on the tail.", ref: "Gen 3:13" },
      { word: "אָמַרְתָּ", gloss: "you (ms) said", tag: "2ms", note: "תָּ.", ref: "Gen 3:17" },
      { word: "אָמַרְתִּי", gloss: "I said", tag: "1cs", note: "תִּי.", ref: "Gen 12:19" },
      { word: "אָמְרוּ", gloss: "they said", tag: "3cp", note: "וּ.", ref: "Gen 11:3" },
    ],
    verses: [
      { ref: "Gen 3:13", he: "וַתֹּאמֶר הָאִשָּׁה הַנָּחָשׁ הִשִּׁיאַנִי", en: "The woman said, “The snake deceived me.”", hit: "וַתֹּאמֶר", hitEn: "said", vocabId: "amar", why: "תֹּאמֶר is she-said clothes (imperfect/wayyiqtol 3fs). Perfect 3fs would be אָמְרָה. Same lemma." },
      { ref: "Gen 3:17", he: "וּלְאָדָם אָמַר כִּי־שָׁמַעְתָּ לְקוֹל אִשְׁתֶּךָ", en: "And to the man he said, “Because you listened to the voice of your wife.”", hit: "שָׁמַעְתָּ", hitEn: "you listened", vocabId: "shama", why: "תָּ on שָׁמַע is 2ms perfect: you heard." },
      { ref: "Gen 12:19", he: "לָמָה אָמַרְתָּ אֲחֹתִי הִוא", en: "Why did you say, “She is my sister”?", hit: "אָמַרְתָּ", hitEn: "did you say", vocabId: "amar", why: "תָּ = you (ms). Still Qal of אָמַר." },
    ],
    quiz: [
      { q: "Perfect endings sit…", choices: ["On the tail of the verb", "Always as a separate הוּא", "Only on nouns"], answer: "On the tail of the verb", why: "Suffixes, not a new lemma." },
      { q: "אָמְרָה is…", he: "אָמְרָה", choices: ["She said — Qal perfect 3fs", "He said", "They said"], answer: "She said — Qal perfect 3fs", why: "ָה." },
      { q: "אָמַרְתָּ is…", he: "אָמַרְתָּ", choices: ["You (ms) said", "I said", "She said"], answer: "You (ms) said", why: "תָּ. Close to תִּי." },
      { q: "אָמַרְתִּי is…", he: "אָמַרְתִּי", choices: ["I said", "You (ms) said", "We said"], answer: "I said", why: "תִּי not תָּ." },
      { q: "אָמְרוּ is…", he: "אָמְרוּ", choices: ["They said", "He said", "You (mp) said"], answer: "They said", why: "וּ." },
      { q: "שָׁמַעְתָּ in Gen 3:17 is…", he: "שָׁמַעְתָּ", ref: "Gen 3:17", choices: ["You (ms) heard — 2ms perfect of שָׁמַע", "She heard", "He will hear"], answer: "You (ms) heard — 2ms perfect of שָׁמַע", why: "תָּ on the class verb." },
      { q: "Do not treat עָשָׂה as 3fs just because of ָה…", he: "עָשָׂה", choices: ["III-ה citation can end in ָה — still 3ms “he made”", "It is always “she made”", "It is dual"], answer: "III-ה citation can end in ָה — still 3ms “he made”", why: "Root letter, not the 3fs ending." },
      { q: "אַתָּה is…", he: "אַתָּה", choices: ["An independent pronoun “you” — not a verb ending", "Qal 2ms of אתה", "The 3fs ending"], answer: "An independent pronoun “you” — not a verb ending", why: "Pronoun path vs verb tail." },
      { q: "Look up אָמַרְתֶּם as…", he: "אָמַרְתֶּם", choices: ["אָמַר — you (mp) said", "A new lemma אמרתם", "Niphal"], answer: "אָמַר — you (mp) said", why: "תֶּם is 2mp." },
      { q: "1cs “I” on the perfect is…", choices: ["תִּי", "תָּ", "וּ"], answer: "תִּי", why: "אָמַרְתִּי." },
      { q: "3ms perfect of a strong Qal has…", choices: ["No extra ending", "Always תִּי", "Always וּ"], answer: "No extra ending", why: "That is why it is the citation." },
      { q: "Strip שָׁמַרְנוּ to…", he: "שָׁמַרְנוּ", choices: ["שָׁמַר — we kept", "נָתַן", "A noun"], answer: "שָׁמַר — we kept", why: "נוּ = we." },
    ],
  },
  {
    id: 4,
    title: "Imperfect prefixes",
    short: "He will / she will — on the front",
    rule:
      "The imperfect talks about an open or future act. Prefixes ride on the front: י he (3ms), ת she or you (ms), א I, נ we. 3mp often adds וּ on the tail as well (יִשְׁמְרוּ). Same lemma as the perfect. Different clothes.",
    teach:
      "יִשְׁמֹר he will keep · תִּשְׁמֹר she/you will keep · אֶשְׁמֹר I will keep · נִשְׁמֹר we will keep. אֶשְׁמֹר is not Niphal. The א is “I,” not a stem prefix. Pe-alef אָמַר often shows יֹאמַר with holem after י.",
    samples: [
      { word: "יִשְׁמֹר", gloss: "he will keep", tag: "3ms", note: "י prefix.", ref: "Ps 121:7" },
      { word: "תִּשְׁמֹר", gloss: "she / you (ms) will keep", tag: "3fs / 2ms", note: "ת is two persons — context.", ref: "Deut 5:12" },
      { word: "אֶשְׁמֹר", gloss: "I will keep", tag: "1cs", note: "א is “I,” not Niphal.", ref: "Ps 119:17" },
      { word: "יֹאמַר", gloss: "he will say", tag: "3ms", note: "Pe-alef shape of אָמַר.", ref: "Exod 3:14" },
    ],
    verses: [
      { ref: "Ps 121:7", he: "יְהוָה יִשְׁמָרְךָ מִכָּל־רָע", en: "YHWH will keep you from all harm.", hit: "יִשְׁמָרְךָ", hitEn: "will keep you", vocabId: "shamar", why: "י on שָׁמַר is 3ms imperfect — he will keep. ךָ is “you,” a suffix on top." },
      { ref: "Gen 2:17", he: "כִּי בְּיוֹם אֲכָלְךָ מִמֶּנּוּ מוֹת תָּמוּת", en: "For in the day you eat from it, you will surely die.", hit: "תָּמוּת", hitEn: "you will die", vocabId: "mut", why: "תָּמוּת is imperfect of מוּת. Prefix ת = you." },
      { ref: "Exod 3:14", he: "וַיֹּאמֶר אֱלֹהִים אֶל־מֹשֶׁה אֶהְיֶה אֲשֶׁר אֶהְיֶה", en: "God said to Moses, “I will be who I will be.”", hit: "אֶהְיֶה", hitEn: "I will be", vocabId: "hayah", why: "אֶ on הָיָה is 1cs imperfect: I will be. Not a new lemma." },
    ],
    quiz: [
      { q: "Imperfect prefixes sit…", choices: ["On the front of the verb", "Only on the tail", "On the noun"], answer: "On the front of the verb", why: "י ת א נ." },
      { q: "יִשְׁמֹר is…", he: "יִשְׁמֹר", choices: ["He will keep — 3ms imperfect of שָׁמַר", "He kept — perfect", "They kept"], answer: "He will keep — 3ms imperfect of שָׁמַר", why: "י prefix." },
      { q: "אֶשְׁמֹר is…", he: "אֶשְׁמֹר", choices: ["I will keep — the א is “I”", "Niphal of שמר", "Hiphil"], answer: "I will keep — the א is “I”", why: "Do not call every א a stem." },
      { q: "תִּשְׁמֹר can be…", he: "תִּשְׁמֹר", choices: ["She will keep or you (ms) will keep — context decides", "Only “they will keep”", "Always 1cs"], answer: "She will keep or you (ms) will keep — context decides", why: "ת does two jobs." },
      { q: "נִשְׁמֹר (imperfect of שָׁמַר) is…", he: "נִשְׁמֹר", choices: ["We will keep — נ is “we,” not Niphal here", "Always Niphal perfect", "A noun"], answer: "We will keep — נ is “we,” not Niphal here", why: "Same letter, different job. Niphal perfect is נִשְׁמַר with different vowels." },
      { q: "יֹאמַר is…", he: "יֹאמַר", choices: ["He will say — imperfect of אָמַר", "Wayyiqtol", "Piel"], answer: "He will say — imperfect of אָמַר", why: "Pe-alef holem after י." },
      { q: "אֶהְיֶה in Exod 3:14 is…", he: "אֶהְיֶה", ref: "Exod 3:14", choices: ["I will be — 1cs imperfect of הָיָה", "He was", "A noun “being”"], answer: "I will be — 1cs imperfect of הָיָה", why: "אֶ = I." },
      { q: "תָּמוּת is…", he: "תָּמוּת", ref: "Gen 2:17", choices: ["You will die — imperfect of מוּת", "He died — perfect", "Hiphil “he killed”"], answer: "You will die — imperfect of מוּת", why: "Prefix ת." },
      { q: "Look up יִכְתֹּב as…", he: "יִכְתֹּב", choices: ["כָּתַב", "A new lemma יכתב", "The noun סֵפֶר"], answer: "כָּתַב", why: "Imperfect clothes, same citation." },
      { q: "3ms imperfect prefix is…", choices: ["י", "תִּי", "הִ"], answer: "י", why: "הִ is a stem tell, not person here." },
      { q: "Perfect vs imperfect, first glance…", choices: ["Ending on the tail vs prefix on the front", "Always different roots", "Only vowel length"], answer: "Ending on the tail vs prefix on the front", why: "Clothes." },
      { q: "יִשְׁמְרוּ is…", he: "יִשְׁמְרוּ", choices: ["They will keep — י plus וּ", "He will keep", "I kept"], answer: "They will keep — י plus וּ", why: "3mp imperfect." },
    ],
  },
  {
    id: 5,
    title: "Wayyiqtol — the story “and he…”",
    short: "וַ plus patah plus dagesh",
    rule:
      "Narrative “and he said / and he made” is wayyiqtol: וַ (patah) + dagesh in the prefix consonant + an imperfect-looking body. וַיֹּאמֶר, וַיַּעַשׂ, וַיִּשְׁמַע. It is not וְ plus a perfect, and it is not a plain imperfect. Strip וַ and the dagesh; the lemma is still the Qal citation.",
    teach:
      "וְאָמַר (shewa on ו) is “and he (will have) said” or a simple “and” plus perfect — different job. וַיֹּאמֶר is the story chain. Watch the vowel on ו: patah + dagesh = wayyiqtol.",
    samples: [
      { word: "וַיֹּאמֶר", gloss: "and he said", tag: "wayy 3ms", note: "Story chain.", ref: "Gen 1:3" },
      { word: "וַתֹּאמֶר", gloss: "and she said", tag: "wayy 3fs", note: "ת after וַ.", ref: "Gen 3:13" },
      { word: "וַיַּעַשׂ", gloss: "and he made", tag: "wayy 3ms", note: "Lemma עָשָׂה.", ref: "Gen 1:7" },
      { word: "וְאָמַר", gloss: "and he said / will have said", tag: "weqatal", note: "Shewa, no dagesh — not wayyiqtol.", ref: "Deut 6:21" },
    ],
    verses: [
      { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "וַ + dagesh in י = wayyiqtol of אָמַר. The next וַיְהִי is wayyiqtol of הָיָה." },
      { ref: "Gen 1:16", he: "וַיַּעַשׂ אֱלֹהִים אֶת־שְׁנֵי הַמְּאֹרֹת הַגְּדֹלִים", en: "God made the two great lights.", hit: "וַיַּעַשׂ", hitEn: "made", vocabId: "asah", why: "Story “and he made.” Citation עָשָׂה." },
      { ref: "Josh 1:1", he: "וַיְהִי אַחֲרֵי מוֹת מֹשֶׁה עֶבֶד יְהוָה וַיֹּאמֶר יְהוָה אֶל־יְהוֹשֻׁעַ", en: "After the death of Moses, servant of YHWH, YHWH said to Joshua.", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "Two wayyiqtols: וַיְהִי and וַיֹּאמֶר. Both story-chain." },
    ],
    quiz: [
      { q: "Wayyiqtol’s tell is…", choices: ["וַ (patah) plus dagesh in the next letter", "וְ (shewa) plus a perfect", "הִ on the front"], answer: "וַ (patah) plus dagesh in the next letter", why: "The story “and he…”." },
      { q: "וַיֹּאמֶר is…", he: "וַיֹּאמֶר", choices: ["Qal wayyiqtol 3ms of אָמַר — and he said", "Qal perfect 3ms", "Piel"], answer: "Qal wayyiqtol 3ms of אָמַר — and he said", why: "Look it up as אָמַר." },
      { q: "וְאָמַר (shewa on ו) is…", he: "וְאָמַר", choices: ["Not wayyiqtol — וְ plus perfect (weqatal / “and he said”)", "The same as וַיֹּאמֶר", "Hiphil"], answer: "Not wayyiqtol — וְ plus perfect (weqatal / “and he said”)", why: "Vowel on ו decides." },
      { q: "וַתֹּאמֶר is…", he: "וַתֹּאמֶר", choices: ["And she said — wayyiqtol 3fs", "And he said", "I said"], answer: "And she said — wayyiqtol 3fs", why: "ת after וַ." },
      { q: "וַיַּעַשׂ is…", he: "וַיַּעַשׂ", choices: ["And he made — wayyiqtol of עָשָׂה", "He will make — plain imperfect", "A noun"], answer: "And he made — wayyiqtol of עָשָׂה", why: "Gen 1:16." },
      { q: "וַיְהִי is…", he: "וַיְהִי", choices: ["And it was / and there was — wayyiqtol of הָיָה", "Perfect הָיָה", "Niphal"], answer: "And it was / and there was — wayyiqtol of הָיָה", why: "Story of becoming." },
      { q: "Look up וַיִּשְׁמַע as…", he: "וַיִּשְׁמַע", choices: ["שָׁמַע", "A new lemma וישמע", "Hiphil הִשְׁמִיעַ"], answer: "שָׁמַע", why: "Wayyiqtol clothes." },
      { q: "Does wayyiqtol change the class lemma?", choices: ["No — still the Qal citation", "Yes — each form is a new vocab word for Game", "Only for אָמַר"], answer: "No — still the Qal citation", why: "Game vocab stays אָמַר." },
      { q: "In Gen 1:3 both וַיֹּאמֶר and וַיְהִי are…", ref: "Gen 1:3", choices: ["Wayyiqtol story chain", "Two nouns", "Piel"], answer: "Wayyiqtol story chain", why: "Said, and there was." },
      { q: "וַ next to a verb without dagesh is…", choices: ["Check again — true wayyiqtol wants that dagesh (unless a guttural refuses it)", "Always a noun", "Always Hiphil"], answer: "Check again — true wayyiqtol wants that dagesh (unless a guttural refuses it)", why: "Gutturals cannot take dagesh; the patah on ו still marks the form." },
      { q: "Plain imperfect יֹאמַר vs וַיֹּאמֶר…", choices: ["Future/open vs story “and he said”", "Different roots", "One is a noun"], answer: "Future/open vs story “and he said”", why: "Same lemma, different aspect." },
      { q: "First vowel to check on a ו-verb in narrative…", choices: ["Patah (wayyiqtol) vs shewa (plain and)", "Always qamets", "The article"], answer: "Patah (wayyiqtol) vs shewa (plain and)", why: "The tell." },
    ],
  },
  {
    id: 6,
    title: "Qal vs Piel — middle dagesh",
    short: "The doubled middle letter",
    rule:
      "Piel’s tell is dagesh in the middle root letter. The vowels are often i-e: כִּבֵּד “he honored.” Qal כָּבֵד is “he was heavy.” Same letters, different stem, different gloss. Honor is not “be heavy.”",
    teach:
      "כַּבֵּד (Exod 20:12) is Piel imperative of כָּבֵד — honor. וַיְבָרֶךְ is Piel of בָּרַךְ — he blessed. If the middle letter is doubled, ask Piel (or later Pual) before you say Qal.",
    samples: [
      { word: "כָּבֵד", gloss: "he was heavy", tag: "Qal", note: "No middle dagesh.", ref: "Exod 9:7" },
      { word: "כִּבֵּד", gloss: "he honored", tag: "Piel", note: "Dagesh in ב.", ref: "Exod 20:12" },
      { word: "בָּרַךְ", gloss: "he blessed (citation)", tag: "Qal/Piel lemma", note: "Blessing is usually Piel in the text.", ref: "Gen 1:22" },
      { word: "וַיְבָרֶךְ", gloss: "and he blessed", tag: "Piel wayy", note: "Middle ר cannot take dagesh — vowels still Piel.", ref: "Gen 1:22" },
    ],
    verses: [
      { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "כַּבֵּד", hitEn: "Honor", vocabId: "kaved", why: "Dagesh in ב is Piel. The command is honor, not “be heavy.” Class lemma כָּבֵד." },
      { ref: "Gen 1:22", he: "וַיְבָרֶךְ אֹתָם אֱלֹהִים", en: "God blessed them.", hit: "וַיְבָרֶךְ", hitEn: "blessed", vocabId: "barak", why: "Piel wayyiqtol of בָּרַךְ. ר will not take dagesh; the stem is still Piel." },
      { ref: "Gen 2:3", he: "וַיְבָרֶךְ אֱלֹהִים אֶת־יוֹם הַשְּׁבִיעִי וַיְקַדֵּשׁ אֹתוֹ", en: "God blessed the seventh day and consecrated it.", hit: "וַיְקַדֵּשׁ", hitEn: "consecrated", vocabId: "qadash", why: "Dagesh in ד: Piel of קָדַשׁ — he made holy, not merely “was holy.”" },
    ],
    quiz: [
      { q: "Piel’s eye-catch is…", choices: ["Dagesh in the middle root letter", "נִ on the front", "הִ on the front"], answer: "Dagesh in the middle root letter", why: "Doubled middle." },
      { q: "כַּבֵּד in Exod 20:12 is…", he: "כַּבֵּד", ref: "Exod 20:12", choices: ["Piel — honor (your father)", "Qal — be heavy", "Hiphil — make heavy"], answer: "Piel — honor (your father)", why: "Dagesh in ב. Gloss shifts." },
      { q: "כָּבֵד without middle dagesh is…", he: "כָּבֵד", choices: ["Qal — be heavy / honored", "Always “honor!” as a command", "Niphal"], answer: "Qal — be heavy / honored", why: "Same letters, Qal job." },
      { q: "וַיְבָרֶךְ is…", he: "וַיְבָרֶךְ", choices: ["Piel wayyiqtol of בָּרַךְ — and he blessed", "Qal “he knelt” only", "Hiphil"], answer: "Piel wayyiqtol of בָּרַךְ — and he blessed", why: "ר skips dagesh; vowels still Piel." },
      { q: "וַיְקַדֵּשׁ is…", he: "וַיְקַדֵּשׁ", ref: "Gen 2:3", choices: ["Piel of קָדַשׁ — he consecrated", "Qal “he was holy”", "A noun קֹדֶשׁ"], answer: "Piel of קָדַשׁ — he consecrated", why: "Dagesh in ד. Makes holy." },
      { q: "Piel often shifts the gloss toward…", choices: ["Factitive / intensive — make X, do X thoroughly", "Always passive", "Always “to be”"], answer: "Factitive / intensive — make X, do X thoroughly", why: "Honor vs be heavy; consecrate vs be holy." },
      { q: "Look up כַּבֵּד as class…", choices: ["כָּבֵד", "A new lemma כבד with dagesh", "אָב"], answer: "כָּבֵד", why: "Citation stays the class verb." },
      { q: "Which is Piel?", choices: ["כִּבֵּד", "כָּבֵד", "הִכְבִּיד"], answer: "כִּבֵּד", why: "Middle dagesh. הִכְבִּיד is Hiphil." },
      { q: "If the middle letter is a guttural (no dagesh)…", choices: ["Watch the vowels — Piel can still be there", "It can never be Piel", "It is always a noun"], answer: "Watch the vowels — Piel can still be there", why: "בָּרַךְ / בֵּרַךְ family." },
      { q: "Game vocab for honor/heavy is still…", choices: ["כָּבֵד the citation", "Every Piel spelling as its own Game card", "רק כַּבֵּד"], answer: "כָּבֵד the citation", why: "This path teaches the clothes." },
      { q: "דִּבֶּר (he spoke) is…", he: "דִּבֶּר", choices: ["Piel — middle dagesh in ב", "Qal of דבר", "Niphal"], answer: "Piel — middle dagesh in ב", why: "Speaking in Tanakh is usually this stem." },
      { q: "First question when you see a doubled middle…", choices: ["Piel (or Pual) before Qal", "Always wayyiqtol", "Always the article"], answer: "Piel (or Pual) before Qal", why: "The tell." },
    ],
  },
  {
    id: 7,
    title: "Qal vs Hiphil — הִ and יַ…ִי",
    short: "Cause to hear, bring out",
    rule:
      "Hiphil’s tell is הִ on the perfect (הִשְׁמִיעַ he caused to hear) and often יַ plus a hireq-yod in the imperfect (יַשְׁמִיעַ). The sense is causative: not “he heard” but “he made (someone) hear.” Strip to the class lemma שָׁמַע, יָצָא, עָלָה.",
    teach:
      "הוֹצֵאתִיךָ (Exod 20:2) is Hiphil of יָצָא — I brought you out, not “I went out.” I-י verbs in Hiphil often show הוֹ… Perfect 1cs תִּי is still the person ending on a Hiphil body.",
    samples: [
      { word: "שָׁמַע", gloss: "he heard", tag: "Qal", note: "Citation.", ref: "Deut 6:4" },
      { word: "הִשְׁמִיעַ", gloss: "he caused to hear", tag: "Hiphil", note: "הִ + ִי.", ref: "Deut 4:36" },
      { word: "יָצָא", gloss: "he went out", tag: "Qal", note: "Citation.", ref: "Exod 13:8" },
      { word: "הוֹצֵאתִיךָ", gloss: "I brought you out", tag: "Hiphil 1cs", note: "הוֹ on I-י.", ref: "Exod 20:2" },
    ],
    verses: [
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "הוֹצֵאתִיךָ", hitEn: "brought you out", vocabId: "yatsa", why: "Hiphil of יָצָא. He did not “go out”; he caused you to go out. תִּי is “I”; ךָ is “you.”" },
      { ref: "Deut 4:36", he: "מִן־הַשָּׁמַיִם הִשְׁמִיעֲךָ אֶת־קֹלוֹ", en: "From the heavens he let you hear his voice.", hit: "הִשְׁמִיעֲךָ", hitEn: "he let you hear", vocabId: "shama", why: "הִשְׁמִיעַ is Hiphil of שָׁמַע — caused you to hear. Not Qal “he heard.”" },
      { ref: "Gen 2:19", he: "וַיָּבֵא אֶל־הָאָדָם לִרְאוֹת מַה־יִּקְרָא־לוֹ", en: "He brought them to the human to see what he would call each one.", hit: "וַיָּבֵא", hitEn: "brought", vocabId: "bo", why: "Hiphil wayyiqtol of בּוֹא — he brought in, not “he came.”" },
    ],
    quiz: [
      { q: "Hiphil’s perfect tell is…", choices: ["הִ (often with ִי later in the word)", "Middle dagesh only", "נִ"], answer: "הִ (often with ִי later in the word)", why: "Causative." },
      { q: "הִשְׁמִיעַ means…", he: "הִשְׁמִיעַ", choices: ["He caused to hear / proclaimed", "He heard (Qal)", "He was heard (Niphal)"], answer: "He caused to hear / proclaimed", why: "Gloss shifts with the stem." },
      { q: "הוֹצֵאתִיךָ is…", he: "הוֹצֵאתִיךָ", ref: "Exod 20:2", choices: ["Hiphil of יָצָא — I brought you out", "Qal “I went out”", "Piel"], answer: "Hiphil of יָצָא — I brought you out", why: "הוֹ + תִּי + ךָ." },
      { q: "וַיָּבֵא is…", he: "וַיָּבֵא", ref: "Gen 2:19", choices: ["Hiphil wayyiqtol of בּוֹא — he brought", "Qal “he came”", "Niphal"], answer: "Hiphil wayyiqtol of בּוֹא — he brought", why: "Cause to come = bring." },
      { q: "Qal יָצָא vs Hiphil הוֹצִיא…", choices: ["Go out vs bring out", "Same gloss", "Noun vs verb"], answer: "Go out vs bring out", why: "Causative." },
      { q: "Look up הוֹצֵאתִיךָ as…", choices: ["יָצָא", "A new Game lemma הוצאתיך", "מִצְרַיִם"], answer: "יָצָא", why: "Class citation." },
      { q: "Which is Hiphil?", choices: ["הִשְׁמִיעַ", "שָׁמַע", "נִשְׁמַע"], answer: "הִשְׁמִיעַ", why: "הִ + ִי. נִשְׁמַע is Niphal." },
      { q: "Imperfect Hiphil often shows…", choices: ["יַ under the prefix and ִי in the stem", "Only a shewa on ו", "Dual ַיִם"], answer: "יַ under the prefix and ִי in the stem", why: "יַשְׁמִיעַ pattern." },
      { q: "הִ on a verb is not the article because…", choices: ["The article sits on nouns; here הִ is the Hiphil prefix", "Articles never use ה", "It is always 3fs"], answer: "The article sits on nouns; here הִ is the Hiphil prefix", why: "Different job, same letter." },
      { q: "שָׁמַע in Deut 6:4 is…", he: "שְׁמַע", ref: "Deut 6:4", choices: ["Qal (imperative) — hear", "Hiphil — cause to hear", "Piel"], answer: "Qal (imperative) — hear", why: "No הִ, no middle dagesh. Later unit on commands." },
      { q: "Causative means…", choices: ["Make someone else do the Qal action", "Always passive", "Always reflexive"], answer: "Make someone else do the Qal action", why: "Hear → make hear; go out → bring out." },
      { q: "Hiphil of עָלָה “go up” is the idea…", he: "עָלָה", choices: ["Bring up / offer up", "Sit down", "Be heavy"], answer: "Bring up / offer up", why: "Cause to go up." },
    ],
  },
  {
    id: 8,
    title: "Qal vs Niphal — נִ",
    short: "Was seen, was heard",
    rule:
      "Niphal’s perfect tell is נִ on the front: נִרְאָה “he appeared / was seen.” The sense is often passive or reflexive of the Qal. וַיֵּרָא (and he appeared) is Niphal wayyiqtol of רָאָה — the נ hides, the vowels still tell you. Do not call every נ a “we” imperfect.",
    teach:
      "Qal רָאָה he saw · Niphal נִרְאָה he was seen / appeared. Qal שָׁמַע he heard · Niphal נִשְׁמַע it was heard. Same class lemma. Different voice.",
    samples: [
      { word: "רָאָה", gloss: "he saw", tag: "Qal", note: "Citation.", ref: "Gen 1:4" },
      { word: "נִרְאָה", gloss: "he appeared / was seen", tag: "Niphal", note: "נִ tell.", ref: "Gen 12:7" },
      { word: "וַיֵּרָא", gloss: "and he appeared", tag: "Niphal wayy", note: "נ hidden.", ref: "Gen 12:7" },
      { word: "נִשְׁמַע", gloss: "it was heard", tag: "Niphal", note: "Of שָׁמַע.", ref: "Gen 45:16" },
    ],
    verses: [
      { ref: "Gen 12:7", he: "וַיֵּרָא יְהוָה אֶל־אַבְרָם וַיֹּאמֶר", en: "YHWH appeared to Abram and said…", hit: "וַיֵּרָא", hitEn: "appeared", vocabId: "raah", why: "Niphal of רָאָה — he was seen / appeared. Not Qal “he saw.”" },
      { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "וַיַּרְא", hitEn: "saw", vocabId: "raah", why: "Qal wayyiqtol — he saw. Compare וַיֵּרָא in Gen 12:7. Same lemma, two stems." },
      { ref: "Gen 45:16", he: "וְהַקֹּל נִשְׁמַע בֵּית פַּרְעֹה", en: "The report was heard in Pharaoh’s house.", hit: "נִשְׁמַע", hitEn: "was heard", vocabId: "shama", why: "Niphal perfect of שָׁמַע. The voice was heard — not “he heard.”" },
    ],
    quiz: [
      { q: "Niphal perfect tell is…", choices: ["נִ on the front", "Middle dagesh", "הִ"], answer: "נִ on the front", why: "Passive / reflexive." },
      { q: "נִרְאָה is…", he: "נִרְאָה", choices: ["Niphal of רָאָה — he appeared / was seen", "Qal “he saw”", "Hiphil “he showed”"], answer: "Niphal of רָאָה — he appeared / was seen", why: "Voice shift." },
      { q: "וַיֵּרָא in Gen 12:7 is…", he: "וַיֵּרָא", ref: "Gen 12:7", choices: ["Niphal wayyiqtol — YHWH appeared", "Qal “and he saw” (that is וַיַּרְא)", "Piel"], answer: "Niphal wayyiqtol — YHWH appeared", why: "Vowels differ from וַיַּרְא." },
      { q: "וַיַּרְא in Gen 1:4 is…", he: "וַיַּרְא", ref: "Gen 1:4", choices: ["Qal — and he saw", "Niphal — and he appeared", "Hiphil"], answer: "Qal — and he saw", why: "Close pair. Look twice." },
      { q: "נִשְׁמַע is…", he: "נִשְׁמַע", choices: ["Niphal — it was heard", "We will hear (that needs imperfect vowels)", "Piel"], answer: "Niphal — it was heard", why: "נִ + perfect shape." },
      { q: "Do not mix Niphal נִ with…", choices: ["Imperfect “we” prefix נִשְׁמֹר", "The article הַ", "Dual ַיִם"], answer: "Imperfect “we” prefix נִשְׁמֹר", why: "Same letter, different clothes." },
      { q: "Look up וַיֵּרָא as…", choices: ["רָאָה", "A new lemma ירא always “fear”", "אוֹר"], answer: "רָאָה", why: "יָרֵא “fear” is a different class verb. Here the context is appeared." },
      { q: "Which is Niphal?", choices: ["נִרְאָה", "רָאָה", "הֶרְאָה"], answer: "נִרְאָה", why: "הֶרְאָה is Hiphil “he showed.”" },
      { q: "Niphal gloss is often…", choices: ["Passive or reflexive of the Qal", "Always causative", "Always a noun"], answer: "Passive or reflexive of the Qal", why: "Was seen / appeared." },
      { q: "Class lemma does not change when the stem is Niphal.", choices: ["True — still רָאָה, שָׁמַע", "False — each stem is a new Game word", "Only for names"], answer: "True — still רָאָה, שָׁמַע", why: "Clothes." },
      { q: "Qal vs Niphal of רָאָה in one glance…", choices: ["Saw vs appeared", "Heard vs caused to hear", "Blessed vs was blessed"], answer: "Saw vs appeared", why: "Gen 1:4 vs Gen 12:7." },
      { q: "If you see נִ on a perfect verb, ask…", choices: ["Niphal first", "Always “we”", "Always Piel"], answer: "Niphal first", why: "The tell." },
    ],
  },
  {
    id: 9,
    title: "Name the stem",
    short: "Four forms, one tell",
    rule:
      "On a living form, name the stem before the person. Qal: no extra prefix, no middle dagesh. Piel: middle dagesh. Hiphil: הִ / יַ…ִי. Niphal: נִ. Gutturals hide dagesh — then the vowels and the prefix decide.",
    teach:
      "Drill the four-way contrast with class verbs only: שָׁמַע / נִשְׁמַע / הִשְׁמִיעַ; רָאָה / נִרְאָה / וַיַּרְא; כָּבֵד / כִּבֵּד. One tell per glance.",
    samples: [
      { word: "שָׁמַע", gloss: "he heard", tag: "Qal", note: "No extra tell.", ref: "Deut 6:4" },
      { word: "נִשְׁמַע", gloss: "was heard", tag: "Niphal", note: "נִ.", ref: "Gen 45:16" },
      { word: "הִשְׁמִיעַ", gloss: "caused to hear", tag: "Hiphil", note: "הִ.", ref: "Deut 4:36" },
      { word: "כִּבֵּד", gloss: "he honored", tag: "Piel", note: "Middle dagesh.", ref: "Exod 20:12" },
    ],
    verses: [
      { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "שְׁמַע", hitEn: "Hear", vocabId: "shama", why: "Qal command of שָׁמַע. No נִ, no הִ, no middle dagesh." },
      { ref: "Deut 4:36", he: "מִן־הַשָּׁמַיִם הִשְׁמִיעֲךָ אֶת־קֹלוֹ", en: "From the heavens he let you hear his voice.", hit: "הִשְׁמִיעֲךָ", hitEn: "let you hear", vocabId: "shama", why: "Hiphil. Same lemma as the Shema." },
      { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "כַּבֵּד", hitEn: "Honor", vocabId: "kaved", why: "Piel. Not Hiphil, not Qal." },
    ],
    quiz: [
      { q: "Name the stem of שָׁמַע.", he: "שָׁמַע", choices: ["Qal", "Piel", "Hiphil"], answer: "Qal", why: "No extra tell." },
      { q: "Name the stem of נִשְׁמַע.", he: "נִשְׁמַע", choices: ["Niphal", "Qal", "Piel"], answer: "Niphal", why: "נִ." },
      { q: "Name the stem of הִשְׁמִיעַ.", he: "הִשְׁמִיעַ", choices: ["Hiphil", "Niphal", "Qal"], answer: "Hiphil", why: "הִ + ִי." },
      { q: "Name the stem of כִּבֵּד.", he: "כִּבֵּד", choices: ["Piel", "Qal", "Hiphil"], answer: "Piel", why: "Middle dagesh." },
      { q: "Name the stem of וַיֵּרָא.", he: "וַיֵּרָא", choices: ["Niphal (wayyiqtol of רָאָה)", "Qal “and he saw”", "Piel"], answer: "Niphal (wayyiqtol of רָאָה)", why: "Appeared, not saw." },
      { q: "Name the stem of וַיַּרְא.", he: "וַיַּרְא", choices: ["Qal (wayyiqtol of רָאָה)", "Niphal", "Hiphil"], answer: "Qal (wayyiqtol of רָאָה)", why: "Saw." },
      { q: "Name the stem of הוֹצֵאתִיךָ.", he: "הוֹצֵאתִיךָ", choices: ["Hiphil of יָצָא", "Qal of יָצָא", "Piel"], answer: "Hiphil of יָצָא", why: "הוֹ causative." },
      { q: "Name the stem of וַיְבָרֶךְ.", he: "וַיְבָרֶךְ", choices: ["Piel of בָּרַךְ", "Qal", "Niphal"], answer: "Piel of בָּרַךְ", why: "Blessed them." },
      { q: "Which form is Hiphil?", choices: ["הִשְׁמִיעַ", "שָׁמַע", "כִּבֵּד"], answer: "הִשְׁמִיעַ", why: "Close: Piel has dagesh, not הִ." },
      { q: "Which form is Piel?", choices: ["כַּבֵּד", "נִרְאָה", "הוֹצִיא"], answer: "כַּבֵּד", why: "Middle dagesh." },
      { q: "First parse step is…", choices: ["Name the stem, then person", "Name the English first", "Always dual"], answer: "Name the stem, then person", why: "Clothes, then who." },
      { q: "שְׁמַע in Deut 6:4 is…", he: "שְׁמַע", ref: "Deut 6:4", choices: ["Qal", "Hiphil", "Niphal"], answer: "Qal", why: "Hear, Israel." },
    ],
  },
  {
    id: 10,
    title: "One lemma, three aspects",
    short: "He said / he will say / and he said",
    rule:
      "Keep the stem still. Change only the aspect: perfect (complete), imperfect (open/future), wayyiqtol (story). אָמַר · יֹאמַר · וַיֹּאמֶר. שָׁמַר · יִשְׁמֹר · וַיִּשְׁמֹר. Same class verb. Three clocks.",
    teach:
      "If you mix stems here you will guess. Lock Qal. Then pick the clock. Perfect endings vs imperfect prefixes vs וַ + dagesh.",
    samples: [
      { word: "אָמַר", gloss: "he said", tag: "perfect", note: "Complete.", ref: "Gen 12:1" },
      { word: "יֹאמַר", gloss: "he will say", tag: "imperfect", note: "Open.", ref: "Exod 3:13" },
      { word: "וַיֹּאמֶר", gloss: "and he said", tag: "wayyiqtol", note: "Story.", ref: "Gen 1:3" },
      { word: "שָׁמַע", gloss: "he heard", tag: "perfect", note: "Qal.", ref: "Gen 3:17" },
    ],
    verses: [
      { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר", en: "God said, “Let there be light.”", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "Wayyiqtol clock of אָמַר. The next word יְהִי is jussive of הָיָה — let there be." },
      { ref: "Gen 3:17", he: "כִּי־שָׁמַעְתָּ לְקוֹל אִשְׁתֶּךָ", en: "Because you listened to the voice of your wife.", hit: "שָׁמַעְתָּ", hitEn: "you listened", vocabId: "shama", why: "Perfect clock — completed hearing. Same lemma as the Shema." },
      { ref: "Ps 121:7", he: "יְהוָה יִשְׁמָרְךָ מִכָּל־רָע", en: "YHWH will keep you from all harm.", hit: "יִשְׁמָרְךָ", hitEn: "will keep you", vocabId: "shamar", why: "Imperfect clock of שָׁמַר — he will keep." },
    ],
    quiz: [
      { q: "אָמַר vs יֹאמַר vs וַיֹּאמֶר differ in…", choices: ["Aspect (perfect / imperfect / wayyiqtol)", "Stem (Qal / Piel / Hiphil)", "Root"], answer: "Aspect (perfect / imperfect / wayyiqtol)", why: "All Qal of אָמַר." },
      { q: "שָׁמַעְתָּ is…", he: "שָׁמַעְתָּ", choices: ["Perfect — you heard", "Imperfect — you will hear", "Wayyiqtol"], answer: "Perfect — you heard", why: "Ending תָּ, no prefix." },
      { q: "יִשְׁמָרְךָ is…", he: "יִשְׁמָרְךָ", choices: ["Imperfect — he will keep you", "Perfect — he kept you", "Wayyiqtol"], answer: "Imperfect — he will keep you", why: "י prefix. ךָ = you." },
      { q: "וַיֹּאמֶר is…", he: "וַיֹּאמֶר", choices: ["Wayyiqtol — and he said", "Imperfect — he will say", "Perfect"], answer: "Wayyiqtol — and he said", why: "וַ + dagesh." },
      { q: "יְהִי in Gen 1:3 is…", he: "יְהִי", choices: ["A short imperfect / jussive of הָיָה — let there be", "Perfect הָיָה", "Niphal"], answer: "A short imperfect / jussive of הָיָה — let there be", why: "Still the class verb “to be.”" },
      { q: "Which is the story form?", choices: ["וַיִּשְׁמֹר", "יִשְׁמֹר", "שָׁמַר"], answer: "וַיִּשְׁמֹר", why: "Wayyiqtol." },
      { q: "Which is complete (perfect)?", choices: ["כָּתַב", "יִכְתֹּב", "וַיִּכְתֹּב"], answer: "כָּתַב", why: "No prefix." },
      { q: "Keep stem locked as Qal in this unit so you…", choices: ["Only pick the clock", "Also guess Piel", "Ignore the form"], answer: "Only pick the clock", why: "One variable." },
      { q: "וְשָׁמַר (shewa on ו) is not…", he: "וְשָׁמַר", choices: ["Wayyiqtol", "A possible weqatal / “and he will keep”", "A noun"], answer: "Wayyiqtol", why: "No patah-dagesh." },
      { q: "Look up all three אָמַר clothes as…", choices: ["אָמַר", "Three Game lemmas", "The noun דָּבָר"], answer: "אָמַר", why: "Citation." },
      { q: "Imperfect is the right name when you see…", choices: ["A person prefix י ת א נ without wayyiqtol’s וַ", "Only a tail תָּ", "הַ on a noun"], answer: "A person prefix י ת א נ without wayyiqtol’s וַ", why: "Front clothes." },
      { q: "In Ps 121:7 the clock is…", ref: "Ps 121:7", choices: ["Imperfect — will keep", "Wayyiqtol — and he kept", "Piel"], answer: "Imperfect — will keep", why: "יִשְׁמָרְךָ." },
    ],
  },
  {
    id: 11,
    title: "Person, gender, number",
    short: "Who is wearing the verb?",
    rule:
      "After stem and aspect, name who: 3ms he, 3fs she, 2ms you, 1cs I, 3mp they, 1cp we. Close pairs: תָּ vs תִּי, י vs ת, וַיֹּאמֶר vs וַתֹּאמֶר. One letter is the whole person.",
    teach:
      "2ms and 3fs imperfect can look the same (תִּשְׁמֹר). Use the subject in the verse. Suffixed ךָ “you” is an object, not the subject ending.",
    samples: [
      { word: "וַיֹּאמֶר", gloss: "and he said", tag: "3ms", note: "י after וַ.", ref: "Gen 1:3" },
      { word: "וַתֹּאמֶר", gloss: "and she said", tag: "3fs", note: "ת after וַ.", ref: "Gen 3:13" },
      { word: "אָמַרְתָּ", gloss: "you said", tag: "2ms", note: "תָּ.", ref: "Gen 12:19" },
      { word: "אָמַרְתִּי", gloss: "I said", tag: "1cs", note: "תִּי.", ref: "Gen 20:11" },
    ],
    verses: [
      { ref: "Gen 3:13", he: "וַתֹּאמֶר הָאִשָּׁה הַנָּחָשׁ הִשִּׁיאַנִי", en: "The woman said, “The snake deceived me.”", hit: "וַתֹּאמֶר", hitEn: "said", vocabId: "amar", why: "ת marks 3fs. The next word הָאִשָּׁה confirms she." },
      { ref: "Gen 12:19", he: "לָמָה אָמַרְתָּ אֲחֹתִי הִוא", en: "Why did you say, “She is my sister”?", hit: "אָמַרְתָּ", hitEn: "did you say", vocabId: "amar", why: "תָּ = 2ms. Pharaoh speaking to Abram." },
      { ref: "Gen 1:28", he: "וַיֹּאמֶר לָהֶם אֱלֹהִים פְּרוּ וּרְבוּ", en: "God said to them, “Be fruitful and multiply.”", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "3ms — he said. לָהֶם is the object “to them,” not the subject." },
    ],
    quiz: [
      { q: "וַיֹּאמֶר vs וַתֹּאמֶר differ in…", choices: ["3ms vs 3fs", "Qal vs Piel", "Perfect vs imperfect"], answer: "3ms vs 3fs", why: "י vs ת after וַ." },
      { q: "אָמַרְתָּ vs אָמַרְתִּי differ in…", choices: ["You (ms) vs I", "He vs she", "They vs we"], answer: "You (ms) vs I", why: "תָּ vs תִּי. Closest pair in the unit." },
      { q: "וַתֹּאמֶר הָאִשָּׁה…", he: "וַתֹּאמֶר", ref: "Gen 3:13", choices: ["She said — 3fs, and the noun agrees", "He said", "They said"], answer: "She said — 3fs, and the noun agrees", why: "Person matches the subject." },
      { q: "לָהֶם in Gen 1:28 is…", he: "לָהֶם", choices: ["“To them” — object, not the verb’s subject", "3mp subject ending", "A new verb"], answer: "“To them” — object, not the verb’s subject", why: "The verb is still 3ms וַיֹּאמֶר." },
      { q: "יִשְׁמְרוּ is…", he: "יִשְׁמְרוּ", choices: ["They will keep — 3mp", "He will keep", "You (ms) will keep"], answer: "They will keep — 3mp", why: "י + וּ." },
      { q: "נִשְׁמֹר as Qal imperfect is…", he: "נִשְׁמֹר", choices: ["We will keep — 1cp", "Niphal perfect", "3ms"], answer: "We will keep — 1cp", why: "Context and vowels. Not every נִ is Niphal." },
      { q: "2ms perfect ending is…", choices: ["תָּ", "תִּי", "וּ"], answer: "תָּ", why: "Close to 1cs." },
      { q: "A ךָ on יִשְׁמָרְךָ is…", he: "יִשְׁמָרְךָ", choices: ["Object “you” — the subject is still 3ms “he”", "2ms subject", "3fs subject"], answer: "Object “you” — the subject is still 3ms “he”", why: "YHWH will keep you." },
      { q: "When תִּשְׁמֹר could be 3fs or 2ms…", choices: ["Read the subject in the verse", "Always pick 3fs", "Always pick Piel"], answer: "Read the subject in the verse", why: "Form is ambiguous; the line is not." },
      { q: "1cs imperfect prefix is…", choices: ["א", "י", "תָּ"], answer: "א", why: "אֶשְׁמֹר, אֶהְיֶה." },
      { q: "Parse וַיֹּאמֶר fully…", he: "וַיֹּאמֶר", choices: ["Qal wayyiqtol 3ms of אָמַר", "Piel perfect 3fs of אמר", "Hiphil 1cs"], answer: "Qal wayyiqtol 3ms of אָמַר", why: "Stem + aspect + person." },
      { q: "Parse אָמַרְתִּי fully…", he: "אָמַרְתִּי", choices: ["Qal perfect 1cs of אָמַר", "Qal perfect 2ms", "Qal wayyiqtol 3ms"], answer: "Qal perfect 1cs of אָמַר", why: "תִּי." },
    ],
  },
  {
    id: 12,
    title: "Command, participle, infinitive",
    short: "Other Qal clothes",
    rule:
      "Imperative: the command — שְׁמַע hear!, לְךָ go!, זְכֹר remember. Participle: the -ing / the one who — שֹׁמֵר a keeper, עֹשֶׂה one who makes. Infinitive construct: the “to X” / “X-ing” — לִשְׁמֹר to keep, לִרְאוֹת to see. Still the same class lemma.",
    teach:
      "שְׁמַע (Deut 6:4) is Qal ms imperative, not perfect 3ms שָׁמַע (vowels differ). זָכוֹר (Exod 20:8) is infinitive absolute used as a command. לִרְאוֹת is לְ + infinitive of רָאָה.",
    samples: [
      { word: "שְׁמַע", gloss: "hear!", tag: "imperative", note: "Shewa under ש.", ref: "Deut 6:4" },
      { word: "שֹׁמֵר", gloss: "keeper / keeping", tag: "participle", note: "Holem after first root.", ref: "Gen 4:9" },
      { word: "לִשְׁמֹר", gloss: "to keep", tag: "inf. cst.", note: "לְ plus infinitive.", ref: "Exod 31:13" },
      { word: "זָכוֹר", gloss: "remember!", tag: "inf. abs.", note: "Used as a command.", ref: "Exod 20:8" },
    ],
    verses: [
      { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "שְׁמַע", hitEn: "Hear", vocabId: "shama", why: "Imperative. Not perfect שָׁמַע. The Shema is a command to hear." },
      { ref: "Exod 20:8", he: "זָכוֹר אֶת־יוֹם הַשַּׁבָּת לְקַדְּשׁוֹ", en: "Remember the sabbath day, to keep it holy.", hit: "זָכוֹר", hitEn: "Remember", vocabId: "zakar-v", why: "Infinitive absolute of זָכַר doing a command’s job. לְקַדְּשׁוֹ is Piel infinitive of קָדַשׁ — to consecrate it." },
      { ref: "Gen 2:19", he: "וַיָּבֵא אֶל־הָאָדָם לִרְאוֹת מַה־יִּקְרָא־לוֹ", en: "He brought them to the human to see what he would call each.", hit: "לִרְאוֹת", hitEn: "to see", vocabId: "raah", why: "Infinitive construct of רָאָה with לְ." },
    ],
    quiz: [
      { q: "שְׁמַע vs שָׁמַע…", choices: ["Imperative “hear!” vs perfect “he heard”", "Hiphil vs Qal", "Noun vs verb"], answer: "Imperative “hear!” vs perfect “he heard”", why: "Vowels. Same lemma." },
      { q: "A Qal ms participle often has…", choices: ["Holem after the first root letter (שֹׁמֵר)", "הִ prefix", "נִ prefix"], answer: "Holem after the first root letter (שֹׁמֵר)", why: "The one who keeps." },
      { q: "לִשְׁמֹר is…", he: "לִשְׁמֹר", choices: ["Infinitive construct — to keep", "Wayyiqtol", "3fs perfect"], answer: "Infinitive construct — to keep", why: "לְ + inf." },
      { q: "זָכוֹר in Exod 20:8 is…", he: "זָכוֹר", ref: "Exod 20:8", choices: ["Infinitive absolute used as a command — remember", "Perfect 3ms only", "Piel"], answer: "Infinitive absolute used as a command — remember", why: "Class זָכַר." },
      { q: "לִרְאוֹת is…", he: "לִרְאוֹת", choices: ["To see — inf. of רָאָה", "He saw", "Niphal"], answer: "To see — inf. of רָאָה", why: "Gen 2:19." },
      { q: "הֲשֹׁמֵר אָחִי in Gen 4:9 uses…", he: "הֲשֹׁמֵר", choices: ["Participle שֹׁמֵר — am I a keeper?", "Perfect “I kept”", "Wayyiqtol"], answer: "Participle שֹׁמֵר — am I a keeper?", why: "The one who keeps. הֲ is the question particle." },
      { q: "Look up לְקַדְּשׁוֹ as…", he: "לְקַדְּשׁוֹ", choices: ["קָדַשׁ — Piel infinitive “to consecrate” plus him", "A new lemma", "Qal perfect"], answer: "קָדַשׁ — Piel infinitive “to consecrate” plus him", why: "Dagesh in ד." },
      { q: "Imperative is missing…", choices: ["A subject prefix like י — the listener is “you”", "Any connection to the lemma", "Vowels"], answer: "A subject prefix like י — the listener is “you”", why: "Commands assume you." },
      { q: "Which is the participle?", choices: ["עֹשֶׂה", "עָשָׂה", "וַיַּעַשׂ"], answer: "עֹשֶׂה", why: "Holem — the one who makes." },
      { q: "Infinitive construct often wears…", choices: ["לְ in front", "וַ + dagesh", "The article הַ as its main tell"], answer: "לְ in front", why: "לִשְׁמֹר, לִרְאוֹת." },
      { q: "These clothes still look up as…", choices: ["The Qal citation (שָׁמַע, זָכַר, רָאָה)", "Separate Game lemmas for each infinitive", "Only English"], answer: "The Qal citation (שָׁמַע, זָכַר, רָאָה)", why: "Class list." },
      { q: "לֶךְ־לְךָ (Gen 12:1) is…", he: "לֶךְ", choices: ["Imperative of הָלַךְ — go", "Perfect “he walked”", "Hiphil"], answer: "Imperative of הָלַךְ — go", why: "I-weak short command. Lemma הָלַךְ." },
    ],
  },
  {
    id: 13,
    title: "Pual vs Piel",
    short: "The passive of the doubled stem",
    rule:
      "Pual is Piel’s passive. The middle letter still has dagesh; the first vowel is u (qibbuts or shureq): בֹּרַךְ / מְבֹרָךְ “blessed.” Piel בֵּרַךְ “he blessed.” Same doubling, different voice. מְ on a participle is a prefix, not a root letter.",
    teach:
      "Job 1:21 יְהִי שֵׁם יְהוָה מְבֹרָךְ — the name is blessed (Pual participle). Num 22:12 כִּי בָרוּךְ הוּא uses a related passive/qal-passive shape. If you see middle dagesh plus u, ask Pual before Piel.",
    samples: [
      { word: "בֵּרַךְ", gloss: "he blessed", tag: "Piel", note: "Active.", ref: "Gen 1:22" },
      { word: "מְבֹרָךְ", gloss: "blessed", tag: "Pual ptcp", note: "מְ + u-vowel.", ref: "Job 1:21" },
      { word: "כִּבֵּד", gloss: "he honored", tag: "Piel", note: "Active.", ref: "Exod 20:12" },
      { word: "מְקֻדָּשׁ", gloss: "consecrated", tag: "Pual ptcp", note: "Of קָדַשׁ.", ref: "Exod 29:21" },
    ],
    verses: [
      { ref: "Job 1:21", he: "יְהוָה נָתַן וַיהוָה לָקָח יְהִי שֵׁם יְהוָה מְבֹרָךְ", en: "YHWH gave and YHWH has taken; may the name of YHWH be blessed.", hit: "מְבֹרָךְ", hitEn: "blessed", vocabId: "barak", why: "Pual participle of בָּרַךְ. The name is blessed — not “he blessed.” נָתַן and לָקָח in the same line are Qal perfects of class verbs." },
      { ref: "Gen 1:22", he: "וַיְבָרֶךְ אֹתָם אֱלֹהִים לֵאמֹר", en: "God blessed them, saying…", hit: "וַיְבָרֶךְ", hitEn: "blessed", vocabId: "barak", why: "Piel active — he blessed. Pair with מְבֹרָךְ." },
      { ref: "Num 22:12", he: "לֹא תָאֹר אֶת־הָעָם כִּי בָרוּךְ הוּא", en: "You shall not curse the people, for they are blessed.", hit: "בָרוּךְ", hitEn: "blessed", vocabId: "barak", why: "Passive “blessed” on the people. Same lemma as the Piel “he blessed.”" },
    ],
    quiz: [
      { q: "Pual is…", choices: ["The passive of Piel — still a doubled middle", "The causative of Qal", "A noun ending"], answer: "The passive of Piel — still a doubled middle", why: "Voice pair." },
      { q: "מְבֹרָךְ is…", he: "מְבֹרָךְ", choices: ["Pual participle — blessed", "Piel “he blessed”", "Qal perfect"], answer: "Pual participle — blessed", why: "מְ + o/u." },
      { q: "וַיְבָרֶךְ vs מְבֹרָךְ…", choices: ["He blessed vs is blessed", "Two different roots", "Noun vs adjective only"], answer: "He blessed vs is blessed", why: "Piel vs Pual." },
      { q: "The מְ on מְבֹרָךְ is…", he: "מְבֹרָךְ", choices: ["Participle prefix, not the root", "The preposition מִן", "1cp “we”"], answer: "Participle prefix, not the root", why: "Strip מְ to see בּרך." },
      { q: "נָתַן in Job 1:21 is…", he: "נָתַן", ref: "Job 1:21", choices: ["Qal perfect of נָתַן — he gave", "Pual", "Hiphil"], answer: "Qal perfect of נָתַן — he gave", why: "Class verb in the same verse." },
      { q: "לָקָח in that line is…", he: "לָקָח", choices: ["Qal perfect of לָקַח — he took", "Piel", "Niphal"], answer: "Qal perfect of לָקַח — he took", why: "Gave / took — two Qals around a Pual." },
      { q: "Which is Pual?", choices: ["מְבֹרָךְ", "וַיְבָרֶךְ", "כַּבֵּד"], answer: "מְבֹרָךְ", why: "u-vowel + doubling." },
      { q: "Piel vs Pual first glance…", choices: ["i/e active vs u passive, both doubled", "Prefix הִ vs נִ", "Perfect vs wayyiqtol"], answer: "i/e active vs u passive, both doubled", why: "Same middle dagesh." },
      { q: "Look up מְבֹרָךְ as…", choices: ["בָּרַךְ", "A new lemma מברך", "שֵׁם"], answer: "בָּרַךְ", why: "Class." },
      { q: "בָרוּךְ in Num 22:12 means…", he: "בָרוּךְ", choices: ["Blessed (passive)", "He blessed (active Piel)", "To bless (infinitive)"], answer: "Blessed (passive)", why: "The people are blessed." },
      { q: "If the middle dagesh is there and the first vowel is u…", choices: ["Pual before Piel", "Always Qal", "Always Hiphil"], answer: "Pual before Piel", why: "The tell." },
      { q: "Pual does not get its own Game vocab card.", choices: ["True — still the class citation", "False — every participle is a new lemma", "Only in Psalms"], answer: "True — still the class citation", why: "This path." },
    ],
  },
  {
    id: 14,
    title: "Hophal vs Hiphil",
    short: "Was brought out",
    rule:
      "Hophal is Hiphil’s passive. Perfect often הָ / הֻ: הֻשְׁלַךְ “he was thrown,” הוּרַד “he was brought down.” Hiphil הוֹצִיא “he brought out”; Hophal “he was brought out.” Causative voice flipped to passive.",
    teach:
      "Gen 39:1 יוֹסֵף הוּרַד מִצְרָיְמָה — Joseph was brought down (Hophal of יָרַד). Qal יָרַד he went down; Hiphil he brought down; Hophal he was brought down.",
    samples: [
      { word: "יָרַד", gloss: "he went down", tag: "Qal", note: "Citation.", ref: "Gen 12:10" },
      { word: "הוּרַד", gloss: "he was brought down", tag: "Hophal", note: "Passive causative.", ref: "Gen 39:1" },
      { word: "הוֹצִיא", gloss: "he brought out", tag: "Hiphil", note: "Active causative.", ref: "Exod 20:2" },
      { word: "הָשְׁלַךְ", gloss: "he was thrown", tag: "Hophal", note: "Of שָׁלַךְ.", ref: "Exod 1:22" },
    ],
    verses: [
      { ref: "Gen 39:1", he: "וְיוֹסֵף הוּרַד מִצְרָיְמָה", en: "Joseph was brought down to Egypt.", hit: "הוּרַד", hitEn: "was brought down", vocabId: "yarad", why: "Hophal of יָרַד. He did not merely go down; he was brought down." },
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "הוֹצֵאתִיךָ", hitEn: "brought you out", vocabId: "yatsa", why: "Hiphil active of יָצָא. Pair with Hophal “was brought out.”" },
      { ref: "Gen 12:10", he: "וַיֵּרֶד אַבְרָם מִצְרַיְמָה", en: "Abram went down to Egypt.", hit: "וַיֵּרֶד", hitEn: "went down", vocabId: "yarad", why: "Qal wayyiqtol — he went down. Same lemma as הוּרַד, different stem." },
    ],
    quiz: [
      { q: "Hophal is…", choices: ["The passive of Hiphil", "The passive of Piel", "A dual ending"], answer: "The passive of Hiphil", why: "Causative flipped." },
      { q: "הוּרַד is…", he: "הוּרַד", choices: ["Hophal of יָרַד — was brought down", "Qal “he went down”", "Piel"], answer: "Hophal of יָרַד — was brought down", why: "Gen 39:1." },
      { q: "וַיֵּרֶד is…", he: "וַיֵּרֶד", choices: ["Qal wayyiqtol — he went down", "Hophal", "Hiphil “he brought down”"], answer: "Qal wayyiqtol — he went down", why: "Abram went." },
      { q: "הוֹצֵאתִיךָ vs a Hophal of יָצָא…", choices: ["I brought you out vs you were brought out", "Same voice", "Noun vs verb"], answer: "I brought you out vs you were brought out", why: "Hiphil vs Hophal." },
      { q: "Hophal perfect often shows…", choices: ["הָ or הֻ / וּ on the front", "Middle dagesh as the main tell", "Dual ַיִם"], answer: "הָ or הֻ / וּ on the front", why: "Passive Hiphil clothes." },
      { q: "Look up הוּרַד as…", choices: ["יָרַד", "A new lemma הורד", "מִצְרַיִם"], answer: "יָרַד", why: "Class." },
      { q: "Which is Hophal?", choices: ["הוּרַד", "וַיֵּרֶד", "הוֹצִיא"], answer: "הוּרַד", why: "הוֹצִיא is Hiphil active." },
      { q: "Qal / Hiphil / Hophal of “go down”…", choices: ["Went down / brought down / was brought down", "Three different roots", "Only nouns"], answer: "Went down / brought down / was brought down", why: "Voice ladder." },
      { q: "Do not mix Hophal הֻ with…", choices: ["Pual’s u-vowel on a doubled middle (no הֻ needed)", "The article הַ", "Shewa"], answer: "Pual’s u-vowel on a doubled middle (no הֻ needed)", why: "Two passives, two tells." },
      { q: "In Gen 39:1 Joseph…", ref: "Gen 39:1", choices: ["Was brought down — Hophal", "Went down by himself — Qal only", "Brought Egypt down — Hiphil"], answer: "Was brought down — Hophal", why: "הוּרַד." },
      { q: "Hiphil and Hophal share…", choices: ["The causative idea; they differ in who does it", "Nothing", "Only the dual"], answer: "The causative idea; they differ in who does it", why: "Active vs passive." },
      { q: "Parse הוּרַד…", he: "הוּרַד", choices: ["Hophal perfect 3ms of יָרַד", "Qal perfect 3ms", "Piel participle"], answer: "Hophal perfect 3ms of יָרַד", why: "Stem + aspect + person." },
    ],
  },
  {
    id: 15,
    title: "Hithpael — הִתְ",
    short: "Walk about, pray, hide yourself",
    rule:
      "Hithpael’s tell is הִתְ plus a doubled middle letter: הִתְהַלֵּךְ “he walked about.” The sense is often reflexive or iterative — do it to yourself, or do it back and forth. Strip הִתְ; the lemma is still the class verb (הָלַךְ).",
    teach:
      "Gen 3:8 מִתְהַלֵּךְ — walking about (Hithpael participle of הָלַךְ). Gen 17:1 הִתְהַלֵּךְ — walk before me. When ת of הִתְ meets a sibilant, they may swap (hitpael metathesis) — later fine print. First catch הִתְ.",
    samples: [
      { word: "הָלַךְ", gloss: "he walked", tag: "Qal", note: "Citation.", ref: "Gen 12:4" },
      { word: "הִתְהַלֵּךְ", gloss: "he walked about", tag: "Hithpael", note: "הִתְ + dagesh in ל.", ref: "Gen 17:1" },
      { word: "מִתְהַלֵּךְ", gloss: "walking about", tag: "Hithpael ptcp", note: "מִתְ prefix.", ref: "Gen 3:8" },
      { word: "לֶךְ", gloss: "go!", tag: "Qal impv", note: "Short command.", ref: "Gen 12:1" },
    ],
    verses: [
      { ref: "Gen 3:8", he: "וַיִּשְׁמְעוּ אֶת־קוֹל יְהוָה אֱלֹהִים מִתְהַלֵּךְ בַּגָּן", en: "They heard the sound of YHWH God walking about in the garden.", hit: "מִתְהַלֵּךְ", hitEn: "walking about", vocabId: "halak", why: "Hithpael participle of הָלַךְ. Not Qal “he walked” once — walking about. וַיִּשְׁמְעוּ is Qal wayyiqtol of שָׁמַע." },
      { ref: "Gen 17:1", he: "הִתְהַלֵּךְ לְפָנַי וֶהְיֵה תָמִים", en: "Walk before me and be blameless.", hit: "הִתְהַלֵּךְ", hitEn: "Walk", vocabId: "halak", why: "Hithpael imperative of הָלַךְ. וֶהְיֵה is imperative of הָיָה — be." },
      { ref: "Gen 12:4", he: "וַיֵּלֶךְ אַבְרָם כַּאֲשֶׁר דִּבֶּר אֵלָיו יְהוָה", en: "Abram went, as YHWH had spoken to him.", hit: "וַיֵּלֶךְ", hitEn: "went", vocabId: "halak", why: "Qal wayyiqtol of הָלַךְ — he went. Contrast the Hithpael “walk about.”" },
    ],
    quiz: [
      { q: "Hithpael’s tell is…", choices: ["הִתְ plus doubled middle", "נִ only", "וַ plus patah"], answer: "הִתְ plus doubled middle", why: "Reflexive / iterative." },
      { q: "הִתְהַלֵּךְ is…", he: "הִתְהַלֵּךְ", choices: ["Hithpael of הָלַךְ — walk about", "Qal “he walked”", "Hiphil"], answer: "Hithpael of הָלַךְ — walk about", why: "Gen 17:1." },
      { q: "מִתְהַלֵּךְ is…", he: "מִתְהַלֵּךְ", choices: ["Hithpael participle — walking about", "Pual", "Niphal"], answer: "Hithpael participle — walking about", why: "מִתְ = participle clothes of this stem." },
      { q: "וַיֵּלֶךְ is…", he: "וַיֵּלֶךְ", choices: ["Qal wayyiqtol of הָלַךְ — and he went", "Hithpael", "Hiphil"], answer: "Qal wayyiqtol of הָלַךְ — and he went", why: "One trip, not “walk about.”" },
      { q: "וַיִּשְׁמְעוּ in Gen 3:8 is…", he: "וַיִּשְׁמְעוּ", choices: ["Qal wayyiqtol 3mp of שָׁמַע — they heard", "Hithpael", "Piel"], answer: "Qal wayyiqtol 3mp of שָׁמַע — they heard", why: "Two class verbs in one line." },
      { q: "Look up הִתְהַלֵּךְ as…", choices: ["הָלַךְ", "A new lemma התהלך", "גַּן"], answer: "הָלַךְ", why: "Class." },
      { q: "Which is Hithpael?", choices: ["הִתְהַלֵּךְ", "וַיֵּלֶךְ", "הוֹצִיא"], answer: "הִתְהַלֵּךְ", why: "הִתְ." },
      { q: "Hithpael gloss is often…", choices: ["Reflexive or back-and-forth of the Qal", "Always causative", "Always a noun"], answer: "Reflexive or back-and-forth of the Qal", why: "Walk oneself about." },
      { q: "מִתְ on מִתְהַלֵּךְ is…", choices: ["The Hithpael participle prefix, not מִן “from”", "Always the preposition from", "The article"], answer: "The Hithpael participle prefix, not מִן “from”", why: "Do not strip it as a prep." },
      { q: "וֶהְיֵה in Gen 17:1 is…", he: "וֶהְיֵה", choices: ["Imperative of הָיָה — be", "Perfect “he was”", "Niphal"], answer: "Imperative of הָיָה — be", why: "Walk… and be blameless." },
      { q: "Qal vs Hithpael of הָלַךְ…", choices: ["Go / walk vs walk about (before God, in the garden)", "Hear vs cause to hear", "See vs appear"], answer: "Go / walk vs walk about (before God, in the garden)", why: "Same letters, extra הִתְ." },
      { q: "Parse מִתְהַלֵּךְ…", he: "מִתְהַלֵּךְ", choices: ["Hithpael participle of הָלַךְ", "Qal perfect 3ms", "Pual of הלך"], answer: "Hithpael participle of הָלַךְ", why: "Stem + form." },
    ],
  },
  {
    id: 16,
    title: "When the tell hides",
    short: "III-ה, I-י, I-נ",
    rule:
      "Some roots hide a letter. III-ה (עָשָׂה, הָיָה, רָאָה, בָּנָה) drop or change ה in many clothes (וַיַּעַשׂ, וַיְהִי, לִרְאוֹת). I-י (יָשַׁב, יָצָא, יָדַע, יָלַד) show וַיֵּשֶׁב, שֵׁב, צֵא. I-נ (נָתַן, נָגַשׁ, נָפַל) drop נ in the imperfect (יִתֵּן, גַּשׁ). Still the class lemma.",
    teach:
      "Do not invent a new root. וַיִּתֵּן is נָתַן. וַיֵּשֶׁב is יָשַׁב. וַיַּעַשׂ is עָשָׂה. The missing letter is a known weak pattern, not a different vocab word.",
    samples: [
      { word: "הָיָה", gloss: "he was", tag: "III-ה", note: "וַיְהִי hides ה.", ref: "Gen 1:3" },
      { word: "יָשַׁב", gloss: "he sat / dwelt", tag: "I-י", note: "וַיֵּשֶׁב.", ref: "Gen 13:12" },
      { word: "נָתַן", gloss: "he gave", tag: "I-נ", note: "יִתֵּן drops נ.", ref: "Gen 1:17" },
      { word: "עָשָׂה", gloss: "he made", tag: "III-ה", note: "וַיַּעַשׂ.", ref: "Gen 1:7" },
    ],
    verses: [
      { ref: "Gen 1:17", he: "וַיִּתֵּן אֹתָם אֱלֹהִים בִּרְקִיעַ הַשָּׁמָיִם", en: "God set them in the expanse of the heavens.", hit: "וַיִּתֵּן", hitEn: "set", vocabId: "natan", why: "I-נ: נ of נָתַן drops; dagesh in ת remembers it. Still “he gave / set.”" },
      { ref: "Gen 13:12", he: "אַבְרָם יָשַׁב בְּאֶרֶץ־כְּנָעַן", en: "Abram dwelt in the land of Canaan.", hit: "יָשַׁב", hitEn: "dwelt", vocabId: "yashab", why: "Citation of I-י יָשַׁב. Wayyiqtol will look like וַיֵּשֶׁב." },
      { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "וַיְהִי", hitEn: "there was", vocabId: "hayah", why: "III-ה הָיָה in short wayyiqtol clothes. Not a new verb." },
    ],
    quiz: [
      { q: "וַיִּתֵּן is…", he: "וַיִּתֵּן", choices: ["Qal wayyiqtol of נָתַן — the נ dropped", "A new root יתן", "Piel of תן"], answer: "Qal wayyiqtol of נָתַן — the נ dropped", why: "I-נ. Dagesh in ת." },
      { q: "וַיְהִי is…", he: "וַיְהִי", choices: ["Wayyiqtol of הָיָה", "Perfect הָיָה", "Hiphil"], answer: "Wayyiqtol of הָיָה", why: "III-ה short form." },
      { q: "וַיַּעַשׂ is…", he: "וַיַּעַשׂ", choices: ["Wayyiqtol of עָשָׂה — ה dropped", "A noun", "Niphal"], answer: "Wayyiqtol of עָשָׂה — ה dropped", why: "III-ה." },
      { q: "יָשַׁב vs וַיֵּשֶׁב…", choices: ["Citation vs wayyiqtol of the same I-י verb", "Two stems Qal vs Hiphil", "Noun vs verb"], answer: "Citation vs wayyiqtol of the same I-י verb", why: "Dwell / and he dwelt." },
      { q: "Look up וַיִּתֵּן as…", choices: ["נָתַן", "יִתֵּן as citation", "שָׁמַיִם"], answer: "נָתַן", why: "Class." },
      { q: "I-נ imperfect often…", choices: ["Drops נ and doubles the next letter", "Adds הִתְ", "Becomes dual"], answer: "Drops נ and doubles the next letter", why: "יִתֵּן, יִגַּשׁ." },
      { q: "III-ה infinitive of רָאָה is…", choices: ["לִרְאוֹת — וֹת clothes", "רָאָה unchanged", "נִרְאָה"], answer: "לִרְאוֹת — וֹת clothes", why: "Still רָאָה." },
      { q: "Do not treat וַיֵּשֶׁב as…", choices: ["A Hiphil of ישב just because it looks short", "Qal of יָשַׁב", "Wayyiqtol"], answer: "A Hiphil of ישב just because it looks short", why: "Weak Qal, not a new stem." },
      { q: "נָגַשׁ in the imperfect may look like…", he: "נָגַשׁ", choices: ["יִגַּשׁ — נ dropped", "הִגִּישׁ only (that is Hiphil)", "Always נִגַּשׁ Niphal"], answer: "יִגַּשׁ — נ dropped", why: "I-נ Qal. Hiphil is a different stem with its own tell." },
      { q: "Weak is not an eighth binyan.", choices: ["True — it is a root shape wearing the same stems", "False — weak is a stem like Piel", "Only for names"], answer: "True — it is a root shape wearing the same stems", why: "Qal of a weak root is still Qal." },
      { q: "Parse וַיִּתֵּן…", he: "וַיִּתֵּן", choices: ["Qal wayyiqtol 3ms of נָתַן", "Niphal perfect of נתן", "Hiphil of יתן"], answer: "Qal wayyiqtol 3ms of נָתַן", why: "Stem + aspect + person + weak." },
      { q: "הָיָה, עָשָׂה, רָאָה, בָּנָה are…", choices: ["III-ה class verbs — expect the ה to move", "All Piel", "All nouns"], answer: "III-ה class verbs — expect the ה to move", why: "Same weak family." },
    ],
  },
  {
    id: 17,
    title: "Parse the line",
    short: "Stem + aspect + who + lemma",
    rule:
      "On a Tanakh verb, say four things: stem (Qal/Piel/Hiphil/Niphal/…), aspect (perfect/imperfect/wayyiqtol/impv/ptcp/inf), person, class lemma. Then the gloss can move with the stem. No invented roots. If the tell hid, name the weak family too.",
    teach:
      "Work slowly: וַיֹּאמֶר → Qal · wayyiqtol · 3ms · אָמַר. כַּבֵּד → Piel · imperative · 2ms · כָּבֵד. הוֹצֵאתִיךָ → Hiphil · perfect · 1cs · יָצָא (+ you). That is mastery — the same reflex on any page.",
    samples: [
      { word: "וַיֹּאמֶר", gloss: "Qal wayy 3ms אָמַר", tag: "parse", note: "And he said.", ref: "Gen 1:3" },
      { word: "כַּבֵּד", gloss: "Piel impv כָּבֵד", tag: "parse", note: "Honor!", ref: "Exod 20:12" },
      { word: "הוֹצֵאתִיךָ", gloss: "Hiphil pf 1cs יָצָא", tag: "parse", note: "I brought you out.", ref: "Exod 20:2" },
      { word: "מִתְהַלֵּךְ", gloss: "Hithpael ptcp הָלַךְ", tag: "parse", note: "Walking about.", ref: "Gen 3:8" },
    ],
    verses: [
      { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "וַיֹּאמֶר", hitEn: "said", vocabId: "amar", why: "Two parses: וַיֹּאמֶר Qal wayyiqtol 3ms of אָמַר; וַיְהִי Qal wayyiqtol 3ms of הָיָה (III-ה)." },
      { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "כַּבֵּד", hitEn: "Honor", vocabId: "kaved", why: "Piel imperative of כָּבֵד. אָב and אֵם are class nouns as objects." },
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "הוֹצֵאתִיךָ", hitEn: "brought you out", vocabId: "yatsa", why: "Hiphil perfect 1cs of יָצָא + ךָ. Full parse in one word." },
      { ref: "Gen 12:7", he: "וַיֵּרָא יְהוָה אֶל־אַבְרָם", en: "YHWH appeared to Abram.", hit: "וַיֵּרָא", hitEn: "appeared", vocabId: "raah", why: "Niphal wayyiqtol 3ms of רָאָה. Not Qal “saw.”" },
    ],
    quiz: [
      { q: "Parse וַיֹּאמֶר.", he: "וַיֹּאמֶר", choices: ["Qal wayyiqtol 3ms of אָמַר", "Piel perfect 3ms of אמר", "Hiphil 1cs of אמר"], answer: "Qal wayyiqtol 3ms of אָמַר", why: "Four-part parse." },
      { q: "Parse כַּבֵּד.", he: "כַּבֵּד", choices: ["Piel imperative of כָּבֵד", "Qal perfect of כבד", "Niphal of כבד"], answer: "Piel imperative of כָּבֵד", why: "Honor!" },
      { q: "Parse הוֹצֵאתִיךָ.", he: "הוֹצֵאתִיךָ", choices: ["Hiphil perfect 1cs of יָצָא + you", "Qal perfect 3ms of יצא", "Hithpael of יצא"], answer: "Hiphil perfect 1cs of יָצָא + you", why: "I brought you out." },
      { q: "Parse מִתְהַלֵּךְ.", he: "מִתְהַלֵּךְ", choices: ["Hithpael participle of הָלַךְ", "Qal wayyiqtol of הלך", "Pual of הלך"], answer: "Hithpael participle of הָלַךְ", why: "Walking about." },
      { q: "Parse וַיֵּרָא.", he: "וַיֵּרָא", choices: ["Niphal wayyiqtol 3ms of רָאָה", "Qal wayyiqtol “and he saw”", "Hiphil of ירא “fear”"], answer: "Niphal wayyiqtol 3ms of רָאָה", why: "Appeared." },
      { q: "Parse וַיִּתֵּן.", he: "וַיִּתֵּן", choices: ["Qal wayyiqtol 3ms of נָתַן (I-נ)", "Niphal of נתן", "Piel of יתן"], answer: "Qal wayyiqtol 3ms of נָתַן (I-נ)", why: "Weak Qal, not a new stem." },
      { q: "Parse שְׁמַע.", he: "שְׁמַע", choices: ["Qal imperative of שָׁמַע", "Qal perfect 3ms", "Hiphil of שמע"], answer: "Qal imperative of שָׁמַע", why: "Hear, Israel." },
      { q: "Parse הִשְׁמִיעֲךָ.", he: "הִשְׁמִיעֲךָ", choices: ["Hiphil perfect of שָׁמַע + you", "Qal “he heard you”", "Niphal"], answer: "Hiphil perfect of שָׁמַע + you", why: "Caused you to hear." },
      { q: "Parse וַיְבָרֶךְ.", he: "וַיְבָרֶךְ", choices: ["Piel wayyiqtol 3ms of בָּרַךְ", "Qal wayyiqtol", "Pual participle"], answer: "Piel wayyiqtol 3ms of בָּרַךְ", why: "And he blessed." },
      { q: "Parse מְבֹרָךְ.", he: "מְבֹרָךְ", choices: ["Pual participle of בָּרַךְ", "Piel perfect", "Qal imperative"], answer: "Pual participle of בָּרַךְ", why: "Blessed." },
      { q: "Parse הוּרַד.", he: "הוּרַד", choices: ["Hophal perfect 3ms of יָרַד", "Qal of ירד", "Hiphil of ירד"], answer: "Hophal perfect 3ms of יָרַד", why: "Was brought down." },
      { q: "The four-part parse is…", choices: ["Stem, aspect, person, class lemma", "English only, then root guess", "Chapter number, then gloss"], answer: "Stem, aspect, person, class lemma", why: "That is the goal of this path." },
    ],
  },
];
