import type { GrammarUnit } from "@/lib/grammar";

/** Original teaching on Hebrew prepositions and the object marker. Masoretic examples. Not a textbook reprint. */
export const PREP_UNITS: GrammarUnit[] = [
  {
    id: 1,
    title: "Stand-alone and maqqef",
    short: "A word, or a word plus ־",
    rule:
      "A preposition names a relationship: place (on, under), time (after, until), or company (with). Many Hebrew prepositions stand alone, just as in English: עִם דָּוִד “with David.” Some almost always take a raised stroke, the maqqef: עַל־, אֶל־, עַד־, מִן־. The stroke is spelling, not extra meaning. The next word is the object of the preposition.",
    samples: [
      { word: "אַחַר", gloss: "after, behind", tag: "independent", note: "Stands alone. Class vocab.", ref: "Gen 15:1" },
      { word: "עִם", gloss: "with", tag: "independent", note: "Company. Do not mix with אֵת “with” until you see the verse.", ref: "Gen 39:2" },
      { word: "תַּחַת", gloss: "under, instead of", tag: "independent", note: "Place or substitution.", ref: "Exod 24:4" },
      { word: "עַל־", gloss: "on, upon, concerning", tag: "maqqef", note: "Usually written עַל־ plus its object.", ref: "Gen 1:2" },
      { word: "אֶל־", gloss: "to, toward", tag: "maqqef", note: "Motion toward a person or place.", ref: "Exod 3:4" },
      { word: "עַד־", gloss: "until, as far as", tag: "maqqef", note: "Limit in time or space.", ref: "Gen 6:7" },
    ],
    verses: [
      { ref: "Gen 15:1", he: "אַחַר הַדְּבָרִים הָאֵלֶּה הָיָה דְבַר־יְהוָה אֶל־אַבְרָם", en: "After these things, the word of YHWH came to Abram.", hit: "אַחַר", hitEn: "After", vocabId: "achar" },
      { ref: "Gen 1:2", he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם", en: "And the spirit of God was hovering over the face of the waters.", hit: "עַל־פְּנֵי", hitEn: "over", vocabId: "al" },
      { ref: "Gen 12:1", he: "וַיֹּאמֶר יְהוָה אֶל־אַבְרָם", en: "YHWH said to Abram.", hit: "אֶל־אַבְרָם", hitEn: "to Abram", vocabId: "el" },
      { ref: "Exod 24:4", he: "וַיִּבֶן מִזְבֵּחַ תַּחַת הָהָר", en: "He built an altar under the mountain.", hit: "תַּחַת", hitEn: "under", vocabId: "tahat" },
    ],
    quiz: [
      { q: "A Hebrew preposition’s object is…", choices: ["The word that follows it", "Always the verb", "Always a suffix"], answer: "The word that follows it", why: "Prep + object. Same job as English “on the altar.”" },
      { q: "An independent preposition…", choices: ["Stands as its own word", "Must prefix the next noun", "Is only מִן"], answer: "Stands as its own word", why: "עִם, אַחַר, תַּחַת." },
      { q: "The maqqef is…", he: "עַל־", choices: ["A raised stroke joining prep and object — not extra meaning", "The article", "A dual ending"], answer: "A raised stroke joining prep and object — not extra meaning", why: "Spelling glue." },
      { q: "עַל usually means…", he: "עַל", choices: ["On, upon, concerning", "Under", "Between"], answer: "On, upon, concerning", why: "Class vocab. Spatial or “about.”" },
      { q: "אֶל usually means…", he: "אֶל", choices: ["To, toward, into", "From", "Like"], answer: "To, toward, into", why: "Motion toward." },
      { q: "עַד usually means…", he: "עַד", choices: ["Until, as far as", "After", "In"], answer: "Until, as far as", why: "A limit." },
      { q: "אַחַר in Gen 15:1 is…", he: "אַחַר", ref: "Gen 15:1", choices: ["After — independent preposition", "The article", "A verb"], answer: "After — independent preposition", why: "אַחַר הַדְּבָרִים. Class lemma." },
      { q: "עִם is the class lemma for…", he: "עִם", choices: ["With, together with", "Direct object marker", "From"], answer: "With, together with", why: "Company. Later you will split אֵת “with” from אֵת the object marker." },
      { q: "תַּחַת can mean…", he: "תַּחַת", choices: ["Under, below, or instead of", "Above only", "Until"], answer: "Under, below, or instead of", why: "Place or substitution." },
      { q: "Which is typically written with maqqef?", choices: ["עַל־הָאָרֶץ", "עִם דָּוִד", "אַחַר הַמַּבּוּל"], answer: "עַל־הָאָרֶץ", why: "עַל, אֶל, עַד, מִן love the stroke." },
      { q: "In Gen 1:2 עַל־פְּנֵי is…", he: "עַל־פְּנֵי", ref: "Gen 1:2", choices: ["Upon the face of — עַל plus construct פָּנִים", "The article on water", "A dual of עַל"], answer: "Upon the face of — עַל plus construct פָּנִים", why: "Compound you will meet again: “in front of / over the face of.”" },
      { q: "Class vocab for “to, toward” is…", choices: ["אֶל", "עַל", "עִם"], answer: "אֶל", why: "Citation form אֶל. Often אֶל־ in the text." },
    ],
  },
  {
    id: 2,
    title: "Inseparable בְּ כְּ לְ",
    short: "Glued to the next word",
    rule:
      "Three prepositions never stand alone: בְּ in/by/with, כְּ like/as, לְ to/for. Before most letters they take vocal shewa. Before a ḥateph they copy that short vowel (בֶּאֱמֶת). Before another vocal shewa they take hireq (the rule of shewa). When the noun already has the article, the ה drops and the preposition keeps the article’s vowel and dagesh: הַמֶּלֶךְ → לַמֶּלֶךְ “to the king.” The noun is still definite.",
    samples: [
      { word: "בְּ", gloss: "in, at, with, by", tag: "inseparable", note: "Citation form with shewa.", ref: "Gen 1:1" },
      { word: "כְּ", gloss: "as, like", tag: "inseparable", note: "Comparison.", ref: "Gen 1:26" },
      { word: "לְ", gloss: "to, for", tag: "inseparable", note: "Direction or benefit. Not the same job as אֶל.", ref: "Gen 1:5" },
      { word: "בֶּאֱמֶת", gloss: "in truth", tag: "ḥateph", note: "Prep takes the ḥateph’s vowel.", ref: "Ps 145:18" },
      { word: "בַּמִּדְבָּר", gloss: "in the wilderness", tag: "prep + article", note: "בַּ = בְּ + הַ. Noun stays definite.", ref: "Exod 3:1" },
      { word: "לָאוֹר", gloss: "to the light", tag: "prep + article", note: "לָ on a guttural article.", ref: "Gen 1:5" },
    ],
    verses: [
      { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "בְּרֵאשִׁית", hitEn: "In the beginning", vocabId: "rosh" },
      { ref: "Gen 1:5", he: "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם וְלַחֹשֶׁךְ קָרָא לָיְלָה", en: "God called the light Day, and the darkness he called Night.", hit: "לָאוֹר", hitEn: "the light", vocabId: "le" },
      { ref: "Gen 1:26", he: "וַיֹּאמֶר אֱלֹהִים נַעֲשֶׂה אָדָם בְּצַלְמֵנוּ כִּדְמוּתֵנוּ", en: "God said, “Let us make humankind in our image, according to our likeness.”", hit: "אָדָם", hitEn: "humankind", vocabId: "adam" },
      { ref: "Deut 6:5", he: "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל־לְבָבְךָ", en: "You shall love YHWH your God with all your heart.", hit: "בְּכָל", hitEn: "with all", vocabId: "kol" },
    ],
    quiz: [
      { q: "The three inseparable prepositions are…", choices: ["בְּ, כְּ, לְ", "עַל, אֶל, עַד", "מִן, עִם, אֵת"], answer: "בְּ, כְּ, לְ", why: "They prefix. They never walk alone." },
      { q: "Citation בְּ means…", he: "בְּ", choices: ["In, at, with, by, against", "Like", "From"], answer: "In, at, with, by, against", why: "Class vocab, chapter 6." },
      { q: "Citation כְּ means…", he: "כְּ", choices: ["As, like, according to", "To, for", "Under"], answer: "As, like, according to", why: "Comparison." },
      { q: "Citation לְ means…", he: "לְ", choices: ["To, toward, for", "On", "After"], answer: "To, toward, for", why: "Not the same as אֶל, though both can gloss “to.”" },
      { q: "Before a ḥateph, inseparable preps…", choices: ["Take that ḥateph’s short vowel", "Always stay shewa", "Drop out"], answer: "Take that ḥateph’s short vowel", why: "Same pattern you learned on וְ." },
      { q: "Two vocal shewas cannot open a word, so בְּ + shewa becomes…", choices: ["Hireq — בִּ", "Qamets", "A maqqef"], answer: "Hireq — בִּ", why: "Rule of shewa." },
      { q: "הַמֶּלֶךְ plus לְ is…", he: "לַמֶּלֶךְ", choices: ["לַמֶּלֶךְ — the ה of the article drops, vowel and dagesh stay", "לְהַמֶּלֶךְ", "הַלְמֶּלֶךְ"], answer: "לַמֶּלֶךְ — the ה of the article drops, vowel and dagesh stay", why: "The noun is still “the king.”" },
      { q: "בַּמִּדְבָּר is…", he: "בַּמִּדְבָּר", choices: ["In the wilderness — בְּ + הַ + מִדְבָּר", "In a wilderness (indefinite)", "From the wilderness"], answer: "In the wilderness — בְּ + הַ + מִדְבָּר", why: "Pathach and dagesh are the article’s. Class lemma מִדְבָּר." },
      { q: "לָאוֹר in Gen 1:5 is…", he: "לָאוֹר", ref: "Gen 1:5", choices: ["To the light — לְ plus the article on אוֹר", "Like light", "No preposition"], answer: "To the light — לְ plus the article on אוֹר", why: "He named the light Day." },
      { q: "בְּכָל in Deut 6:5 uses class vocab…", he: "בְּכָל", ref: "Deut 6:5", choices: ["בְּ + כֹּל “with all”", "The article on heart", "A dual"], answer: "בְּ + כֹּל “with all”", why: "Love with all your heart." },
      { q: "Does the inseparable prep replace the article’s meaning?", choices: ["No — the noun stays definite; the ה is just not written", "Yes — it becomes indefinite", "Only with כְּ"], answer: "No — the noun stays definite; the ה is just not written", why: "לַמֶּלֶךְ is still “the king.”" },
      { q: "Look up בַּמִּדְבָּר in the lexicon as…", he: "בַּמִּדְבָּר", choices: ["מִדְבָּר — strip prep and article", "בַּמִּדְבָּר as one lemma", "הַמִּדְבָּר only"], answer: "מִדְבָּר — strip prep and article", why: "Citation form is the noun." },
    ],
  },
  {
    id: 3,
    title: "מִן — from, than, some",
    short: "Maqqef, or the נ hides",
    rule:
      "מִן can stand with maqqef (מִן־הַבַּיִת) or prefix. When it prefixes, the נ assimilates and shows as dagesh in the next letter: מִן + מֶלֶךְ → מִמֶּלֶךְ. A guttural will not take that dagesh, so hireq often lengthens to tsere: מֵאִישׁ, מֵעִיר. With the article the ה stays: מֵהָאָרֶץ. מִן also does extra jobs: comparative (“better than”), with כֹּל a superlative flavor (“from all” → most), and partitive (“some of”).",
    samples: [
      { word: "מִן", gloss: "from, out of", tag: "citation", note: "Class vocab. Also “than.”", ref: "Gen 2:7" },
      { word: "מִן־הָאָרֶץ", gloss: "from the land", tag: "maqqef + article", note: "ה stays when מִן is not fused.", ref: "Gen 2:6" },
      { word: "מֵאִישׁ", gloss: "from a man", tag: "compensatory", note: "א rejects dagesh; hireq → tsere.", ref: "Gen 2:23" },
      { word: "מִכֹּל", gloss: "from all / more than all", tag: "superlative flavor", note: "מִן + כֹּל.", ref: "Gen 3:1" },
      { word: "מִזָּהָב", gloss: "than gold", tag: "comparative", note: "טוֹב … מִן “better than.”", ref: "Ps 19:11" },
    ],
    verses: [
      { ref: "Gen 2:7", he: "וַיִּיצֶר יְהוָה אֱלֹהִים אֶת־הָאָדָם עָפָר מִן־הָאֲדָמָה", en: "YHWH God formed the human of dust from the ground.", hit: "מִן־הָאֲדָמָה", hitEn: "from the ground", vocabId: "adamah" },
      { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "מֵאֶרֶץ", hitEn: "from the land", vocabId: "erets" },
      { ref: "Gen 3:1", he: "וְהַנָּחָשׁ הָיָה עָרוּם מִכֹּל חַיַּת הַשָּׂדֶה", en: "The serpent was more shrewd than every living thing of the field.", hit: "מִכֹּל", hitEn: "than every", vocabId: "kol" },
      { ref: "Gen 2:23", he: "לְזֹאת יִקָּרֵא אִשָּׁה כִּי מֵאִישׁ לֻקֳחָה־זֹּאת", en: "This one shall be called woman, for from man this one was taken.", hit: "מֵאִישׁ", hitEn: "from man", vocabId: "ish" },
    ],
    quiz: [
      { q: "Citation מִן means…", he: "מִן", choices: ["From, out of (also “than”)", "In", "With"], answer: "From, out of (also “than”)", why: "Class vocab." },
      { q: "When מִן prefixes, the נ…", choices: ["Assimilates; you see dagesh in the next letter", "Always stays written", "Turns into the article"], answer: "Assimilates; you see dagesh in the next letter", why: "מִמֶּלֶךְ." },
      { q: "מֵאִישׁ has tsere because…", he: "מֵאִישׁ", ref: "Gen 2:23", choices: ["א will not take dagesh, so the vowel lengthens", "It is dual", "It is the article"], answer: "א will not take dagesh, so the vowel lengthens", why: "Compensatory lengthening. Class lemma אִישׁ." },
      { q: "מֵאֶרֶץ in Exod 20:2 is…", he: "מֵאֶרֶץ", ref: "Exod 20:2", choices: ["From the land — מִן fused to אֶרֶץ", "In the land", "The land as object marker"], answer: "From the land — מִן fused to אֶרֶץ", why: "Out of the land of Egypt." },
      { q: "With the article, מִן often keeps the ה…", he: "מִן־הָאֲדָמָה", ref: "Gen 2:7", choices: ["מִן־הָאֲדָמָה “from the ground”", "מֵאֲדָמָה only", "בָּאֲדָמָה"], answer: "מִן־הָאֲדָמָה “from the ground”", why: "Dust from the ground. Class אֲדָמָה." },
      { q: "Comparative מִן is the Hebrew way to say…", choices: ["Better / greater than", "Always “from a place”", "The dual"], answer: "Better / greater than", why: "טוֹב … מִן. Wisdom is better than gold." },
      { q: "מִכֹּל in Gen 3:1 is…", he: "מִכֹּל", ref: "Gen 3:1", choices: ["From/than all — מִן + כֹּל, here “more than every”", "The article", "A name"], answer: "From/than all — מִן + כֹּל, here “more than every”", why: "Shrewd more than every living thing." },
      { q: "Partitive מִן can mean…", choices: ["Some of / a portion from", "Always “under”", "The object marker"], answer: "Some of / a portion from", why: "מִפְּרִי “some fruit.”" },
      { q: "מֵהָאָרֶץ keeps ה because…", he: "מֵהָאָרֶץ", choices: ["מִן plus the article does not swallow the ה the way בְּ does", "There is no article", "It is a dual"], answer: "מִן plus the article does not swallow the ה the way בְּ does", why: "Different fusion rule than בַּ / לַ / כַּ." },
      { q: "Look up מֵאִישׁ as…", he: "מֵאִישׁ", choices: ["אִישׁ — strip מִן", "מֵאִישׁ as the lemma", "אִשָּׁה"], answer: "אִישׁ — strip מִן", why: "Citation is the noun." },
      { q: "Begadkephat after prefixed מִן often shows…", choices: ["Dagesh forte (the hidden נ) which also closes lene", "No dagesh ever", "Maqqef only"], answer: "Dagesh forte (the hidden נ) which also closes lene", why: "מִבַּיִת." },
      { q: "Class vocab for “all, each, every” is…", he: "כֹּל", choices: ["כֹּל (construct כָּל־)", "כְּ", "קוֹל"], answer: "כֹּל (construct כָּל־)", why: "Chapter 6 lemma. Pairs with מִן in מִכֹּל." },
    ],
  },
  {
    id: 4,
    title: "Object marker and compounds",
    short: "אֵת the marker vs אֵת “with”",
    rule:
      "In prose, a definite direct object is usually marked with אֵת / אֶת־. It is not translated. Definite means: article, a name, or a suffix. Indefinite objects take no marker. The preposition אֵת “with” looks the same in many spellings — the verse tells you which job it has. Compounds are just two pieces: לִפְנֵי (לְ + פָּנִים) “before”; בְּתוֹךְ “in the midst of”; מֵעַל “from upon.”",
    samples: [
      { word: "אֵת", gloss: "object marker (not translated)", tag: "marker", note: "Class particle. Marks a definite object.", ref: "Gen 1:1" },
      { word: "אֵת", gloss: "with, beside", tag: "preposition", note: "Same letters, different job. Context decides.", ref: "Gen 39:2" },
      { word: "לִפְנֵי", gloss: "before, in the presence of", tag: "compound", note: "לְ + construct of פָּנִים.", ref: "Exod 34:6" },
      { word: "בְּתוֹךְ", gloss: "in the midst of", tag: "compound", note: "בְּ + תָּוֶךְ. Class vocab.", ref: "Gen 1:6" },
      { word: "כֹּל", gloss: "all, each, every", tag: "noun", note: "Often construct כָּל־.", ref: "Deut 6:5" },
    ],
    verses: [
      { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "אֵת", hitEn: "the heavens", vocabId: "et" },
      { ref: "Gen 39:2", he: "וַיְהִי יְהוָה אֶת־יוֹסֵף", en: "YHWH was with Joseph.", hit: "אֶת־יוֹסֵף", hitEn: "with Joseph", vocabId: "et-with" },
      { ref: "Gen 1:6", he: "וַיֹּאמֶר אֱלֹהִים יְהִי רָקִיעַ בְּתוֹךְ הַמָּיִם", en: "God said, “Let there be an expanse in the midst of the waters.”", hit: "בְּתוֹךְ", hitEn: "in the midst", vocabId: "betokh" },
      { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "יִשְׂרָאֵל", hitEn: "Israel", vocabId: "israel" },
    ],
    quiz: [
      { q: "The definite object marker אֵת is…", he: "אֵת", choices: ["Not translated — it flags a definite object", "Always “with”", "The article"], answer: "Not translated — it flags a definite object", why: "Grammar word. Class particle." },
      { q: "You expect אֵת before an object that is…", choices: ["Definite — article, name, or suffix", "Any noun at all", "Only indefinite nouns"], answer: "Definite — article, name, or suffix", why: "הַשָּׁמַיִם, יְהוֹנָתָן, תּוֹרֹתָיו." },
      { q: "In Gen 1:1 אֵת הַשָּׁמַיִם is…", he: "אֵת הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Object marker + the heavens (definite)", "“With the heavens”", "A preposition “in”"], answer: "Object marker + the heavens (definite)", why: "Created the heavens. Class שָׁמַיִם." },
      { q: "In Gen 39:2 אֶת־יוֹסֵף is…", he: "אֶת־יוֹסֵף", ref: "Gen 39:2", choices: ["“With Joseph” — the preposition, because YHWH was with him", "Object marker on a verb “created Joseph”", "The article"], answer: "“With Joseph” — the preposition, because YHWH was with him", why: "Same letters, different job. The verse decides." },
      { q: "An indefinite object (a temple, a house) usually…", choices: ["Takes no object marker", "Must have אֵת", "Must have הַ"], answer: "Takes no object marker", why: "No “the,” no name, no suffix — no marker." },
      { q: "לִפְנֵי is built from…", he: "לִפְנֵי", choices: ["לְ + פָּנִים (face) in construct", "מִן + עַל", "The article"], answer: "לְ + פָּנִים (face) in construct", why: "Before / in the presence of. Class פָּנִים." },
      { q: "בְּתוֹךְ means…", he: "בְּתוֹךְ", choices: ["In the midst of, inside", "From under", "Until"], answer: "In the midst of, inside", why: "Class vocab." },
      { q: "כֹּל / כָּל־ means…", he: "כֹּל", choices: ["All, each, every", "Like", "Holy"], answer: "All, each, every", why: "Chapter 6 noun." },
      { q: "Proper names as objects (David loved Jonathan) take אֵת because…", choices: ["Names are definite", "Names are indefinite", "All objects take אֵת"], answer: "Names are definite", why: "A name is already “the” person." },
      { q: "Two אֵת in Gen 1:1 mark…", ref: "Gen 1:1", choices: ["Two definite objects: the heavens and the earth", "Two prepositions “with”", "The dual"], answer: "Two definite objects: the heavens and the earth", why: "וְאֵת stacks the marker with ו." },
      { q: "מֵעַל is the compound…", choices: ["מִן + עַל “from upon”", "בְּ + תָּוֶךְ", "לְ + פָּנִים"], answer: "מִן + עַל “from upon”", why: "Two preps, one idea." },
      { q: "First move on אֵת in a verse…", choices: ["Ask: object marker or “with”? Then name the noun", "Always skip it", "Always gloss “with”"], answer: "Ask: object marker or “with”? Then name the noun", why: "Same spelling, two class lemmas." },
    ],
  },
];
