import type { NounQuiz } from "@/lib/nouns";

export const NOUN_QUIZ_EXTRA: Record<number, NounQuiz[]> = {
  1: [
    { q: "סוּס is…", he: "סוּס", choices: ["Masculine singular", "Feminine singular", "Dual"], answer: "Masculine singular", why: "Endingless masculine." },
    { q: "סוּסִים is…", he: "סוּסִים", choices: ["Masculine plural", "Feminine plural", "Dual"], answer: "Masculine plural", why: "ִים." },
    { q: "תּוֹרָה is…", he: "תּוֹרָה", choices: ["Feminine singular", "Masculine singular", "Plural"], answer: "Feminine singular", why: "ָה ending." },
    { q: "תּוֹרוֹת is…", he: "תּוֹרוֹת", choices: ["Feminine plural", "Masculine plural", "Dual"], answer: "Feminine plural", why: "וֹת." },
    { q: "סוּסַיִם is…", he: "סוּסַיִם", choices: ["Dual — ay diphthong plus ם", "Masculine plural", "Feminine plural"], answer: "Dual — ay diphthong plus ם", why: "The diphthong is required." },
    { q: "Gender in Hebrew is…", choices: ["Masculine or feminine (a few both)", "Only natural sex", "Neuter as a third class"], answer: "Masculine or feminine (a few both)", why: "Grammatical gender." },
    { q: "Number in Hebrew is…", choices: ["Singular, plural, or dual", "Only singular and plural", "Only dual"], answer: "Singular, plural, or dual", why: "Dual is the pair." },
    { q: "Masculine singular nouns are typically…", choices: ["Endingless", "Marked with ָה", "Marked with ַיִם"], answer: "Endingless", why: "No distinctive ending." },
    { q: "Look up a noun in the lexicon by…", choices: ["The singular form", "The plural you saw", "The English gloss"], answer: "The singular form", why: "Lexical form is singular." },
    { q: "Dual typically marks…", choices: ["A pair (eyes, hands)", "Any large number", "Feminine only"], answer: "A pair (eyes, hands)", why: "Two." },
    { q: "ִים without the ay diphthong is…", choices: ["Plural (many), not dual", "Always dual", "Always feminine"], answer: "Plural (many), not dual", why: "Dual needs ַיִם." },
    { q: "וֹת on a noun you do not know yet is first read as…", choices: ["Feminine plural", "Masculine dual", "Construct only"], answer: "Feminine plural", why: "Then check exceptions (אָבוֹת)." },
  ],
  2: [
    { q: "Hireq-י + מ (ִים) is the…", choices: ["Masculine plural ending", "Feminine singular", "Dual required mark"], answer: "Masculine plural ending", why: "Then check dual vs crossings." },
    { q: "סוּס → סוּסִים shows…", he: "סוּסִים", choices: ["Masculine plural on an endingless stem", "Feminine plural", "A new root"], answer: "Masculine plural on an endingless stem", why: "Add ִים." },
    { q: "נְבִיאִים is plural of…", he: "נְבִיאִים", choices: ["נָבִיא (prophet)", "נְבִיאָה only", "A dual of prophet"], answer: "נָבִיא (prophet)", why: "Masculine plural." },
    { q: "דְּבָרִים is plural of…", he: "דְּבָרִים", ref: "Gen 15:1", choices: ["דָּבָר", "דְּבֹרָה", "Dual of word"], answer: "דָּבָר", why: "Masculine plural; vowels reduce." },
    { q: "מְלָכִים is plural of…", he: "מְלָכִים", choices: ["מֶלֶךְ", "מַלְכָּה", "Dual of king"], answer: "מֶלֶךְ", why: "Masculine plural of king." },
    { q: "If you see ִים, first say…", choices: ["Masculine plural — then check dual and crossings", "Always ‘two’", "Always feminine"], answer: "Masculine plural — then check dual and crossings", why: "Ending first." },
    { q: "Construct masculine plural often shows…", choices: ["ֵי instead of ִים", "וֹת", "No change ever"], answer: "ֵי instead of ִים", why: "דִּבְרֵי, מַלְכֵי." },
    { q: "אֱלֹהִים looks like…", he: "אֱלֹהִים", ref: "Gen 1:1", choices: ["Masculine plural ending, sometimes singular in sense (God)", "Feminine dual", "A verb"], answer: "Masculine plural ending, sometimes singular in sense (God)", why: "Ending vs meaning." },
    { q: "שָׁנִים (years) takes ִים though…", he: "שָׁנִים", choices: ["The singular שָׁנָה is feminine", "It is dual of tooth", "It is masculine singular"], answer: "The singular שָׁנָה is feminine", why: "Crossing plural." },
    { q: "Do not call ִים dual unless…", choices: ["You can point to the ay diphthong", "The gloss is a body part", "There is a י anywhere"], answer: "You can point to the ay diphthong", why: "Requirement." },
    { q: "נָבִיא without an ending is…", he: "נָבִיא", choices: ["Masculine singular", "Plural", "Feminine"], answer: "Masculine singular", why: "Endingless." },
    { q: "מַלְכֵי יִשְׂרָאֵל uses…", he: "מַלְכֵי", choices: ["Construct plural ֵי", "Absolute ִים", "Dual ַיִם"], answer: "Construct plural ֵי", why: "Kings of…" },
  ],
  3: [
    { q: "ָה on a noun is first…", choices: ["Feminine singular", "Masculine plural", "Dual"], answer: "Feminine singular", why: "תּוֹרָה, מַלְכָּה." },
    { q: "וֹת is first…", choices: ["Feminine plural", "Masculine singular", "Dual"], answer: "Feminine plural", why: "Then exceptions." },
    { q: "תּוֹרָה → תּוֹרוֹת", he: "תּוֹרוֹת", choices: ["Feminine singular to feminine plural", "Masculine", "Dual"], answer: "Feminine singular to feminine plural", why: "ָה to וֹת." },
    { q: "מַלְכָּה is…", he: "מַלְכָּה", ref: "Esth 1:9", choices: ["Feminine singular (queen)", "Masculine plural", "Dual"], answer: "Feminine singular (queen)", why: "ָה." },
    { q: "עֵדֹת vs עֵדוֹת", choices: ["Same feminine plural, defective vs full וֹת", "Different numbers", "Dual vs plural"], answer: "Same feminine plural, defective vs full וֹת", why: "Holem vs holem-ו." },
    { q: "אֶרֶץ is feminine though…", he: "אֶרֶץ", ref: "Gen 1:1", choices: ["Endingless (no ָה)", "It has וֹת in the singular", "It is dual"], answer: "Endingless (no ָה)", why: "Some feminines have no ending." },
    { q: "עִיר (city) is…", he: "עִיר", choices: ["Feminine, often endingless in the singular", "Masculine plural", "Always dual"], answer: "Feminine, often endingless in the singular", why: "Plural עָרִים." },
    { q: "Construct feminine singular ָה often becomes…", choices: ["ַת", "ִים", "ַיִם"], answer: "ַת", why: "תּוֹרַת." },
    { q: "תּוֹרַת מֹשֶׁה is…", he: "תּוֹרַת", choices: ["Construct feminine singular", "Plural", "Dual"], answer: "Construct feminine singular", why: "ת of construct." },
    { q: "מִצְוָה is…", he: "מִצְוָה", choices: ["Feminine singular", "Masculine", "Dual"], answer: "Feminine singular", why: "ָה." },
    { q: "מִצְוֺת is…", he: "מִצְוֺת", choices: ["Feminine plural", "Masculine singular", "A verb"], answer: "Feminine plural", why: "וֹת / defective." },
    { q: "A final ת on a feminine may be…", choices: ["The feminine ending itself (not only ָה)", "Always a suffix ‘you’", "Always dual"], answer: "The feminine ending itself (not only ָה)", why: "בַּת, עֵת." },
  ],
  4: [
    { q: "אָב → אָבוֹת", he: "אָבוֹת", choices: ["Masculine noun with feminine plural ending", "Feminine noun", "Dual"], answer: "Masculine noun with feminine plural ending", why: "Crossing." },
    { q: "אֵם → אִמּוֹת", he: "אִמּוֹת", choices: ["Feminine noun, feminine plural", "Masculine plural ִים", "Dual of mother"], answer: "Feminine noun, feminine plural", why: "Mother, mothers." },
    { q: "אִישׁ → אֲנָשִׁים", he: "אֲנָשִׁים", choices: ["Irregular stem change in the plural", "Regular ִים on אִישׁ written out", "Dual"], answer: "Irregular stem change in the plural", why: "Look up אִישׁ." },
    { q: "אִשָּׁה → נָשִׁים", he: "נָשִׁים", choices: ["Irregular pair — look up אִשָּׁה", "Regular ִים on אִשָּׁה", "Masculine"], answer: "Irregular pair — look up אִשָּׁה", why: "Women." },
    { q: "מַיִם is…", he: "מַיִם", ref: "Gen 1:2", choices: ["Special dual form, usually singular in meaning (‘water’)", "Masculine plural ‘days’", "Feminine ָה"], answer: "Special dual form, usually singular in meaning (‘water’)", why: "Always dual-shaped." },
    { q: "שָׁמַיִם is…", he: "שָׁמַיִם", ref: "Gen 1:1", choices: ["Special dual form (‘heaven’)", "True ‘two heavens’ only", "Feminine singular"], answer: "Special dual form (‘heaven’)", why: "Dual in form." },
    { q: "עִיר → עָרִים", he: "עָרִים", choices: ["Feminine noun, masculine-looking plural", "Regular וֹת", "Dual of city"], answer: "Feminine noun, masculine-looking plural", why: "Crossing + stem change." },
    { q: "Lexical form of אֲנָשִׁים is…", he: "אֲנָשִׁים", choices: ["אִישׁ", "אֲנָשׁ", "אִישִׁים"], answer: "אִישׁ", why: "Singular in the lexicon." },
    { q: "יוֹם → יָמִים (days) is plural, not dual, because…", he: "יָמִים", ref: "Gen 1:14", choices: ["ִים has hireq, not the ay diphthong", "All ים are dual", "It is feminine וֹת"], answer: "ִים has hireq, not the ay diphthong", why: "Dual would be יוֹמַיִם." },
    { q: "בַּת (daughter) is feminine though…", he: "בַּת", choices: ["It does not use ָה", "It is dual", "It is masculine ִים"], answer: "It does not use ָה", why: "ת ending." },
    { q: "When gender of the ending and the noun disagree, you…", choices: ["Learn the word as an exception pair", "Always trust the ending only", "Always trust English"], answer: "Learn the word as an exception pair", why: "אָב / אָבוֹת." },
    { q: "Heaven and earth in Gen 1:1 are…", he: "הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Special dual + endingless feminine", "Two masculine plurals", "Two true ‘two’ duals"], answer: "Special dual + endingless feminine", why: "שָׁמַיִם and אֶרֶץ." },
  ],
  5: [
    { q: "Plural of דָּבָר reduces the first vowel toward…", he: "דְּבָרִים", choices: ["Vocal shewa (דְּבָרִים)", "Hireq always", "Holem"], answer: "Vocal shewa (דְּבָרִים)", why: "Propretonic reduction." },
    { q: "Plural of מֶלֶךְ is…", he: "מְלָכִים", choices: ["מְלָכִים", "מֶלֶכִים", "מַלְכּוֹת"], answer: "מְלָכִים", why: "Vowels move." },
    { q: "Guttural in the reduced plural prefers…", choices: ["A hateph, not plain shewa", "Hireq", "No vowel"], answer: "A hateph, not plain shewa", why: "עֲנָנִים." },
    { q: "You still look up מְלָכִים under…", he: "מְלָכִים", choices: ["מֶלֶךְ", "מְלָךְ", "מַלְכָּה"], answer: "מֶלֶךְ", why: "Singular lexical form." },
    { q: "Segolate מֶלֶךְ in singular has stress on…", he: "מֶלֶךְ", choices: ["The first slice (penult)", "The last letter only as a furtive", "A prefix"], answer: "The first slice (penult)", why: "Segolates." },
    { q: "In the plural, that segolate pattern…", choices: ["Usually breaks — vowels reduce and shift", "Never changes", "Becomes dual only"], answer: "Usually breaks — vowels reduce and shift", why: "מְלָכִים." },
    { q: "דָּבָר → דְּבָרִים shows reduction in…", he: "דְּבָרִים", choices: ["The propretonic slice", "The accented last vowel becoming shewa", "The loss of ים"], answer: "The propretonic slice", why: "Two seats before the accent." },
    { q: "Hateph in עֲנָנִים is there because…", he: "עֲנָנִים", choices: ["ע will not take vocal shewa", "ע takes dagesh", "It is hatuf"], answer: "ע will not take vocal shewa", why: "Guttural." },
    { q: "Construct דְּבַר vs absolute דָּבָר: the first vowel…", he: "דְּבַר", choices: ["Reduces (shewa) in construct singular too, in this pattern", "Always stays qamets", "Becomes dual"], answer: "Reduces (shewa) in construct singular too, in this pattern", why: "Word of…" },
    { q: "Do not hunt a new root when vowels shrink. First…", choices: ["Strip the ending, restore a known singular", "Guess a verb", "Ignore consonants"], answer: "Strip the ending, restore a known singular", why: "Lexicon form." },
    { q: "מַלְכֵי is construct plural of…", he: "מַלְכֵי", choices: ["מֶלֶךְ", "מַלְכָּה", "מֹלֶךְ as a new noun"], answer: "מֶלֶךְ", why: "Kings of." },
    { q: "Vocal shewa in דְּבָרִים is allowed because…", he: "דְּבָרִים", choices: ["ד is not a guttural", "All first letters take hateph", "It is silent"], answer: "ד is not a guttural", why: "Non-guttural propretonic shewa." },
  ],
  6: [
    { q: "On a page, first name…", choices: ["The ending, then the singular to look up", "The English word order", "Only the vowels"], answer: "The ending, then the singular to look up", why: "Whole chapter in one move." },
    { q: "הַשָּׁמַיִם on Gen 1:1 is…", he: "הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Article + special dual", "Feminine וֹת", "Masculine singular"], answer: "Article + special dual", why: "Heaven." },
    { q: "הָאָרֶץ on Gen 1:1 is…", he: "הָאָרֶץ", ref: "Gen 1:1", choices: ["Article + endingless feminine", "Masculine plural", "Dual of land"], answer: "Article + endingless feminine", why: "Earth." },
    { q: "בְּרֵאשִׁית starts with…", he: "בְּרֵאשִׁית", ref: "Gen 1:1", choices: ["Preposition בְּ + a feminine noun", "A masculine plural", "A dual ending"], answer: "Preposition בְּ + a feminine noun", why: "In beginning of." },
    { q: "אֱלֹהִים as subject in Gen 1:1: ending says…", he: "אֱלֹהִים", ref: "Gen 1:1", choices: ["Plural shape; here God (singular verb)", "Must be many gods in the grammar of this verse’s verb", "Feminine"], answer: "Plural shape; here God (singular verb)", why: "Ending vs agreement." },
    { q: "מַלְכוּתְךָ: number lives in…", he: "מַלְכוּתְךָ", ref: "Ps 145:13", choices: ["וּת (singular) — suffix is not the number", "The suffix ךָ", "The article"], answer: "וּת (singular) — suffix is not the number", why: "Strip suffix after the noun ending." },
    { q: "יָמִים in Gen 1:14 is…", he: "יָמִים", ref: "Gen 1:14", choices: ["Days — plural of יוֹם", "Two days (dual)", "Feminine וֹת"], answer: "Days — plural of יוֹם", why: "No ay diphthong." },
    { q: "עֵינַיִם is dual because…", he: "עֵינַיִם", ref: "Prov 6:17", choices: ["Ay diphthong plus ם", "It means a body part, so any ים works", "It is וֹת"], answer: "Ay diphthong plus ם", why: "Required cluster." },
    { q: "If both article and ending appear, you…", choices: ["Name both, then the stem", "Ignore the article", "Ignore the ending"], answer: "Name both, then the stem", why: "הַ + ending + singular." },
    { q: "נָשִׁים on a page: look up…", he: "נָשִׁים", choices: ["אִשָּׁה", "נָשׁ", "אִישׁ"], answer: "אִשָּׁה", why: "Irregular." },
    { q: "אֲנָשִׁים: look up…", he: "אֲנָשִׁים", choices: ["אִישׁ", "אֱנוֹשׁ only", "אֲנָשׁ as the noun"], answer: "אִישׁ", why: "Irregular men." },
    { q: "Best check that a form is dual…", he: "יָדַיִם", ref: "Prov 6:17", choices: ["See the ay diphthong plus ם", "See any י", "See a pair in English first, ignore the letters"], answer: "See the ay diphthong plus ם", why: "Letters first." },
  ],
};
