import { CONSONANTS } from "@/lib/alphabet";

export type Psalm119Stanza = {
  letterId: string;
  letter: string;
  name: string;
  v1: number;
  v2: number;
  head: string;
  he: string;
  en: string;
  note: string;
};

/** 22 stanzas of Psalm 119. WLC + WEB, public domain. ש is one stanza (not shin then sin). */
export const PSALM_119_STANZAS: Psalm119Stanza[] = [
  {
    letterId: "alef",
    letter: "א",
    name: "Alef",
    v1: 1,
    v2: 8,
    head: "אַשְׁרֵ֥י",
    he: "אַשְׁרֵ֥י תְמִֽימֵי דָ֑רֶךְ הַֽ֝הֹלְכִ֗ים בְּתוֹרַ֥ת יְהוָֽה",
    en: "Blessed are those whose ways are blameless, who walk according to Yahweh’s law.",
    note: "Every verse in this stanza begins with א. This is how the Book itself lined the letters.",
  },
  {
    letterId: "bet",
    letter: "ב",
    name: "Bet",
    v1: 9,
    v2: 16,
    head: "בַּמֶּ֣ה",
    he: "בַּמֶּ֣ה יְזַכֶּה נַּ֭עַר אֶת אָרְח֑וֹ לִ֝שְׁמֹ֗ר כִּדְבָרֶֽךָ",
    en: "How can a young man keep his way pure? By living according to your word.",
    note: "The stanza of ב. Eight verses, each opening with this letter.",
  },
  {
    letterId: "gimel",
    letter: "ג",
    name: "Gimel",
    v1: 17,
    v2: 24,
    head: "גְּמֹ֖ל",
    he: "גְּמֹ֖ל עַֽל עַבְדְּךָ֥ אֶֽחְיֶ֗ה וְאֶשְׁמְרָ֥ה דְבָרֶֽךָ",
    en: "Do good to your servant. I will live and I will obey your word.",
    note: "The stanza of ג. Stay with the first word before you name a rule.",
  },
  {
    letterId: "dalet",
    letter: "ד",
    name: "Dalet",
    v1: 25,
    v2: 32,
    head: "דָּֽבְקָ֣ה",
    he: "דָּֽבְקָ֣ה לֶעָפָ֣ר נַפְשִׁ֑י חַ֝יֵּ֗נִי כִּדְבָרֶֽךָ",
    en: "My soul is laid low in the dust. Revive me according to your word!",
    note: "The stanza of ד. Hear the name, then look at the first word.",
  },
  {
    letterId: "he",
    letter: "ה",
    name: "He",
    v1: 33,
    v2: 40,
    head: "הוֹרֵ֣נִי",
    he: "הוֹרֵ֣נִי יְ֭הוָה דֶּ֥רֶךְ חֻקֶּ֗יךָ וְאֶצְּרֶ֥נָּה עֵֽקֶב",
    en: "Teach me, Yahweh, the way of your statutes. I will keep them to the end.",
    note: "The stanza of ה. Same letter you will write later — here it opens the line.",
  },
  {
    letterId: "vav",
    letter: "ו",
    name: "Vav",
    v1: 41,
    v2: 48,
    head: "וִֽיבֹאֻ֣נִי",
    he: "וִֽיבֹאֻ֣נִי חֲסָדֶ֣ךָ יְהוָ֑ה תְּ֝שֽׁוּעָתְךָ֗ כְּאִמְרָתֶֽךָ",
    en: "Let your loving kindness also come to me, Yahweh, your salvation, according to your word.",
    note: "The stanza of ו. Eight verses in a row begin with this letter.",
  },
  {
    letterId: "zayin",
    letter: "ז",
    name: "Zayin",
    v1: 49,
    v2: 56,
    head: "זְכֹר",
    he: "זְכֹר דָּבָ֥ר לְעַבְדֶּ֑ךָ עַ֝֗ל אֲשֶׁ֣ר יִֽחַלְתָּֽנִי",
    en: "Remember your word to your servant, because you gave me hope.",
    note: "The stanza of ז.",
  },
  {
    letterId: "het",
    letter: "ח",
    name: "Het",
    v1: 57,
    v2: 64,
    head: "חֶלְקִ֖י",
    he: "חֶלְקִ֖י יְהוָ֥ה אָמַ֗רְתִּי לִשְׁמֹ֥ר דְּבָרֶֽיךָ",
    en: "Yahweh is my portion. I promised to obey your words.",
    note: "The stanza of ח. Do not mix it with ה — look at the first word.",
  },
  {
    letterId: "tet",
    letter: "ט",
    name: "Tet",
    v1: 65,
    v2: 72,
    head: "ט֭וֹב",
    he: "ט֭וֹב עָשִׂ֣יתָ עִֽם עַבְדְּךָ֑ יְ֝הוָ֗ה כִּדְבָרֶֽךָ",
    en: "Do good to your servant, according to your word, Yahweh.",
    note: "The stanza of ט.",
  },
  {
    letterId: "yod",
    letter: "י",
    name: "Yod",
    v1: 73,
    v2: 80,
    head: "יָדֶ֣יךָ",
    he: "יָדֶ֣יךָ עָ֭שׂוּנִי וַֽיְכוֹנְנ֑וּנִי הֲ֝בִינֵ֗נִי וְאֶלְמְדָ֥ה מִצְוֺתֶֽיךָ",
    en: "Your hands have made me and formed me. Give me understanding, that I may learn your commandments.",
    note: "The stanza of י. The small letter, eight times at the head of a verse.",
  },
  {
    letterId: "kaf",
    letter: "כ",
    name: "Kaf",
    v1: 81,
    v2: 88,
    head: "כָּלְתָ֣ה",
    he: "כָּלְתָ֣ה לִתְשׁוּעָתְךָ֣ נַפְשִׁ֑י לִדְבָרְךָ֥ יִחָֽלְתִּי",
    en: "My soul faints for your salvation. I hope in your word.",
    note: "The stanza of כ. Here it is the ordinary form, not the final ך.",
  },
  {
    letterId: "lamed",
    letter: "ל",
    name: "Lamed",
    v1: 89,
    v2: 96,
    head: "לְעוֹלָ֥ם",
    he: "לְעוֹלָ֥ם יְהוָ֑ה דְּ֝בָרְךָ֗ נִצָּ֥ב בַּשָּׁמָֽיִם",
    en: "Yahweh, your word is settled in heaven forever.",
    note: "The stanza of ל.",
  },
  {
    letterId: "mem",
    letter: "מ",
    name: "Mem",
    v1: 97,
    v2: 104,
    head: "מָֽה",
    he: "מָֽה אָהַ֥בְתִּי תוֹרָתֶ֑ךָ כָּל הַ֝יּ֗וֹם הִ֣יא שִׂיחָתִֽי",
    en: "How I love your law! It is my meditation all day.",
    note: "The stanza of מ. Ordinary מ, not final ם.",
  },
  {
    letterId: "nun",
    letter: "נ",
    name: "Nun",
    v1: 105,
    v2: 112,
    head: "נֵר",
    he: "נֵר לְרַגְלִ֥י דְבָרֶ֑ךָ וְ֝א֗וֹר לִנְתִיבָתִֽי",
    en: "Your word is a lamp to my feet, and a light for my path.",
    note: "The stanza of נ.",
  },
  {
    letterId: "samekh",
    letter: "ס",
    name: "Samekh",
    v1: 113,
    v2: 120,
    head: "סֵעֲפִ֥ים",
    he: "סֵעֲפִ֥ים שָׂנֵ֑אתִי וְֽתוֹרָתְךָ֥ אָהָֽבְתִּי",
    en: "I hate double-minded men, but I love your law.",
    note: "The stanza of ס. Compare it with ש later — different letter.",
  },
  {
    letterId: "ayin",
    letter: "ע",
    name: "Ayin",
    v1: 121,
    v2: 128,
    head: "עָ֭שִׂיתִי",
    he: "עָ֭שִׂיתִי מִשְׁפָּ֣ט וָצֶ֑דֶק בַּל תַּ֝נִּיחֵ֗נִי לְעֹֽשְׁקָֽי",
    en: "I have done what is just and righteous. Don’t leave me to my oppressors.",
    note: "The stanza of ע.",
  },
  {
    letterId: "pe",
    letter: "פ",
    name: "Pe",
    v1: 129,
    v2: 136,
    head: "פְּלָא֥וֹת",
    he: "פְּלָא֥וֹת עֵדְוֺתֶ֑יךָ עַל כֵּ֝֗ן נְצָרָ֥תַם נַפְשִֽׁי",
    en: "Your testimonies are wonderful, therefore my soul keeps them.",
    note: "The stanza of פ. Ordinary פ, not final ף.",
  },
  {
    letterId: "tsade",
    letter: "צ",
    name: "Tsade",
    v1: 137,
    v2: 144,
    head: "צַדִּ֣יק",
    he: "צַדִּ֣יק אַתָּ֣ה יְהוָ֑ה וְ֝יָשָׁ֗ר מִשְׁפָּטֶֽיךָ",
    en: "You are righteous, Yahweh. Your judgments are upright.",
    note: "The stanza of צ.",
  },
  {
    letterId: "qof",
    letter: "ק",
    name: "Qof",
    v1: 145,
    v2: 152,
    head: "קָרָ֣אתִי",
    he: "קָרָ֣אתִי בְכָל לֵ֭ב עֲנֵ֥נִי יְהוָ֗ה חֻקֶּ֥יךָ אֶצֹּֽרָה",
    en: "I have called with my whole heart. Answer me, Yahweh! I will keep your statutes.",
    note: "The stanza of ק.",
  },
  {
    letterId: "resh",
    letter: "ר",
    name: "Resh",
    v1: 153,
    v2: 160,
    head: "רְאֵֽה",
    he: "רְאֵֽה עָנְיִ֥י וְחַלְּצֵ֑נִי כִּי תֽ֝וֹרָתְךָ֗ לֹ֣א שָׁכָֽחְתִּי",
    en: "Consider my affliction, and deliver me, for I don’t forget your law.",
    note: "The stanza of ר.",
  },
  {
    letterId: "shin",
    letter: "ש",
    name: "Shin",
    v1: 161,
    v2: 168,
    head: "שָׂ֭רִים",
    he: "שָׂ֭רִים רְדָפ֣וּנִי חִנָּ֑ם … לִבִּֽי",
    en: "Princes have persecuted me without a cause, but my heart stands in awe of your words.",
    note: "The stanza of ש. The first word here is שׂ (dot on the left). The Book keeps one stanza for ש, not two.",
  },
  {
    letterId: "tav",
    letter: "ת",
    name: "Tav",
    v1: 169,
    v2: 176,
    head: "תִּקְרַ֤ב",
    he: "תִּקְרַ֤ב רִנָּתִ֣י לְפָנֶ֣יךָ יְהוָ֑ה כִּדְבָרְךָ֥ הֲבִינֵֽנִי",
    en: "Let my cry come before you, Yahweh. Give me understanding according to your word.",
    note: "The stanza of ת. Last letter. Twenty-two stanzas, alef to tav.",
  },
];

export function acrosticLetters() {
  return CONSONANTS.filter((l) => l.id !== "sin");
}
