import type { SyllableQuiz } from "@/lib/syllables";

/** Extra Tanakh items so a 12-question play is a sample, not the whole pool. */
export const SYLLABLE_QUIZ_EXTRA: Record<number, SyllableQuiz[]> = {
  1: [
    { q: "How should אוֹר split?", he: "אוֹר", ref: "Gen 1:3", choices: ["אוֹר (one closed slice)", "א | וֹר", "אוֹ | ר"], answer: "אוֹר (one closed slice)", why: "One vowel (holem). Ends in a consonant." },
    { q: "How should אֶרֶץ split?", he: "אֶרֶץ", ref: "Gen 1:1", choices: ["אֶ | רֶץ", "אֶר | ֶץ", "אֶרֶץ (one)"], answer: "אֶ | רֶץ", why: "Two vowels: open, then closed." },
    { q: "How should כֹּהֵן split?", he: "כֹּהֵן", ref: "Exod 3:1", choices: ["כֹּ | הֵן", "כֹּה | ֵן", "כֹּהֵן (one)"], answer: "כֹּ | הֵן", why: "Holem, then tsere. Second slice is closed." },
    { q: "How should סֵפֶר split?", he: "סֵפֶר", ref: "Exod 24:7", choices: ["סֵ | פֶר", "סֵפ | ֶר", "סֵפֶר (one)"], answer: "סֵ | פֶר", why: "Two vowels: open, then closed." },
    { q: "בֵּן is…", he: "בֵּן", ref: "Gen 4:17", choices: ["One closed syllable", "Two syllables", "Open"], answer: "One closed syllable", why: "One vowel (tsere). Ends in nun." },
    { q: "שֵׁם is…", he: "שֵׁם", ref: "Gen 2:19", choices: ["One closed syllable", "Two syllables שֵׁ | ם", "Open"], answer: "One closed syllable", why: "One vowel. Ends in a consonant." },
    { q: "קוֹל is…", he: "קוֹל", ref: "Gen 3:8", choices: ["One closed syllable", "קוֹ | ל", "Open then closed"], answer: "One closed syllable", why: "Holem-vav is one vowel. Ends in lamed." },
    { q: "How should לֵבָב split?", he: "לֵבָב", ref: "Deut 6:5", choices: ["לֵ | בָב", "לֵב | ָב", "לֵבָב (one)"], answer: "לֵ | בָב", why: "Tsere, then qamets. Second slice is closed." },
    { q: "יָד is…", he: "יָד", ref: "Exod 17:11", choices: ["One closed syllable", "Two open slices", "Not a syllable"], answer: "One closed syllable", why: "One vowel. Ends in dalet." },
    { q: "עַם is…", he: "עַם", ref: "Exod 19:5", choices: ["One closed syllable", "Open", "Two syllables"], answer: "One closed syllable", why: "Pathach plus mem." },
    { q: "How should הַר split?", he: "הַר", ref: "Exod 19:2", choices: ["הַר (one closed)", "הַ | ר", "Open"], answer: "הַר (one closed)", why: "One vowel. Ends in resh." },
    { q: "How should פֶּה split?", he: "פֶּה", ref: "Exod 4:10", choices: ["פֶּה (one open slice)", "פֶּ | ה", "Two closed"], answer: "פֶּה (one open slice)", why: "One vowel. Ends in he — open." },
    { q: "דָּם is…", he: "דָּם", ref: "Gen 4:10", choices: ["One closed syllable", "Two syllables", "Open"], answer: "One closed syllable", why: "Qamets plus mem." },
    { q: "How should אֵל split?", he: "אֵל", ref: "Gen 14:18", choices: ["אֵל (one closed)", "אֵ | ל", "Two vowels"], answer: "אֵל (one closed)", why: "One tsere. Ends in lamed." },
    { q: "How should בֹּקֶר split?", he: "בֹּקֶר", ref: "Gen 1:5", choices: ["בֹּ | קֶר", "בֹּק | ֶר", "בֹּקֶר (one)"], answer: "בֹּ | קֶר", why: "Holem, then segol. Second slice closed." },
    { q: "How should עֶרֶב split?", he: "עֶרֶב", ref: "Gen 1:5", choices: ["עֶ | רֶב", "עֶר | ֶב", "עֶרֶב (one)"], answer: "עֶ | רֶב", why: "Two segols: open, then closed." },
    { q: "How should זֶרַע split?", he: "זֶרַע", ref: "Gen 1:11", choices: ["זֶ | רַע", "זֶר | ַע", "זֶרַע (one)"], answer: "זֶ | רַע", why: "Two vowels. Second slice closed." },
    { q: "In אָדָם the first slice is…", he: "אָדָם", ref: "Gen 1:26", choices: ["Open", "Closed", "A prefix"], answer: "Open", why: "אָ ends in a vowel." },
    { q: "In שָׁלוֹם the second slice is…", he: "שָׁלוֹם", ref: "Num 6:26", choices: ["Closed", "Open", "Furtive"], answer: "Closed", why: "לוֹם ends in mem." },
    { q: "Count vowels in מֶלֶךְ. How many slices?", he: "מֶלֶךְ", ref: "Ps 24:8", choices: ["Two", "One", "Three"], answer: "Two", why: "Two vowels, two syllables." },
    { q: "A one-vowel word that ends in a consonant is…", choices: ["One closed syllable", "Always two slices", "Open"], answer: "One closed syllable", why: "One vowel, consonant closer." },
  ],
  2: [
    { q: "In בַּיִת, the dagesh in ב is…", he: "בַּיִת", ref: "Prov 24:3", choices: ["Lene — it starts the word", "Forte — split through it", "Not a dagesh"], answer: "Lene — it starts the word", why: "Word-initial begadkephat takes lene. Do not split." },
    { q: "In כָּתַב, the dagesh in כ is…", he: "כָּתַב", ref: "Exod 24:4", choices: ["Lene — start of the word", "Forte", "Mappiq"], answer: "Lene — start of the word", why: "Initial kaf. Hard k, not a double." },
    { q: "In שַׁבָּת, the dagesh in ב is…", he: "שַׁבָּת", ref: "Exod 20:8", choices: ["Forte — a vowel stands before it", "Lene", "Shin-dot"], answer: "Forte — a vowel stands before it", why: "Pathach under shin. Bet doubles: שַׁבְ | בָת." },
    { q: "How does שַׁבָּת split?", he: "שַׁבָּת", ref: "Exod 20:8", choices: ["שַׁבְ | בָת", "שַׁ | בָּת", "שַׁבָּת (one)"], answer: "שַׁבְ | בָת", why: "Forte: first bet shewa-closes (no dagesh); second takes the vowel." },
    { q: "In הַמֶּלֶךְ, the dagesh in מ is…", he: "הַמֶּלֶךְ", ref: "2 Sam 11:1", choices: ["Forte — article + vowel before it", "Lene", "Not a dagesh"], answer: "Forte — article + vowel before it", why: "Pathach of הַ. Mem doubles." },
    { q: "How does הַמֶּלֶךְ split?", he: "הַמֶּלֶךְ", ref: "2 Sam 11:1", choices: ["הַמְ | מֶ | לֶךְ", "הַ | מֶלֶךְ", "הַמֶּלֶךְ (one)"], answer: "הַמְ | מֶ | לֶךְ", why: "Forte mem: first shewa-closes (no dagesh); second takes segol." },
    { q: "In תּוֹרָה, the dagesh in ת is…", he: "תּוֹרָה", ref: "Exod 12:49", choices: ["Lene — start of the word", "Forte — split it", "None"], answer: "Lene — start of the word", why: "Initial tav. Hard t, one slice start." },
    { q: "In פַּרְעֹה, the dagesh in פ is…", he: "פַּרְעֹה", ref: "Exod 5:1", choices: ["Lene — start of the word", "Forte", "Furtive"], answer: "Lene — start of the word", why: "Initial pe." },
    { q: "In מִדְבַּר, dagesh in ב is…", he: "מִדְבַּר", ref: "Num 1:1", choices: ["Lene — silent shewa under dalet stands before it", "Forte — split the bet", "Mappiq"], answer: "Lene — silent shewa under dalet stands before it", why: "Silent shewa is a consonant closer. Do not split." },
    { q: "After silent shewa, a begadkephat dagesh is…", choices: ["Lene — do not split", "Forte — always split", "Mappiq"], answer: "Lene — do not split", why: "Silent shewa is not a vowel." },
    { q: "After a full vowel, a begadkephat dagesh is…", choices: ["Forte — split through it", "Lene", "Never written"], answer: "Forte — split through it", why: "Vowel + dagesh = double." },
    { q: "How does חַטָּאת split?", he: "חַטָּאת", ref: "Ps 51:5", choices: ["חַטְ | טָאת", "חַ | טָּאת", "חַטָּאת (one)"], answer: "חַטְ | טָאת", why: "Forte tet: first shewa-closes; second takes qamets. Quiet alef stays." },
    { q: "In אַתָּה, after the split the first tav is written…", he: "אַתָּה", ref: "Gen 49:8", choices: ["With shewa, no dagesh", "With dagesh still on it", "As a vowel letter"], answer: "With shewa, no dagesh", why: "The two taves show the double." },
    { q: "Lene never…", choices: ["Adds a syllable by doubling", "Changes the sound to a stop", "Appears on begadkephat"], answer: "Adds a syllable by doubling", why: "Lene is sound, not a split." },
    { q: "Which of these can take dagesh lene?", choices: ["ב ג ד כ פ ת", "א ה ח ע ר", "Only shin"], answer: "ב ג ד כ פ ת", why: "Begadkephat only." },
    { q: "In וַיַּרְא the dagesh in yod is…", he: "וַיַּרְא", ref: "Gen 1:4", choices: ["Forte (wayyiqtol)", "Lene", "Shin-dot"], answer: "Forte (wayyiqtol)", why: "Vowel before it. Split וַיְ | יַרְא." },
    { q: "Does ע take dagesh?", choices: ["No — it is a guttural", "Yes, lene", "Only in verbs"], answer: "No — it is a guttural", why: "א ה ח ע and ר refuse the dot." },
    { q: "Does ח take dagesh?", choices: ["No", "Yes, freely", "Only forte"], answer: "No", why: "Guttural." },
    { q: "Initial dagesh on ב at the start of בְּרֵאשִׁית is…", he: "בְּרֵאשִׁית", ref: "Gen 1:1", choices: ["Lene (and the shewa is vocal)", "Forte — split the bet", "Not a dagesh"], answer: "Lene (and the shewa is vocal)", why: "Word-initial. Do not split through it." },
    { q: "Forte vs lene: the test is…", choices: ["Vowel before the dot → forte; otherwise lene", "Every dagesh is forte", "Every dagesh is lene"], answer: "Vowel before the dot → forte; otherwise lene", why: "Silent shewa counts as a consonant, not a vowel." },
    { q: "In Gen 3:17 שָׁמַעְתָּ you do not split תּ because…", he: "שָׁמַעְתָּ", ref: "Gen 3:17", choices: ["The dagesh is lene after silent shewa", "Tav never splits", "There is no dagesh"], answer: "The dagesh is lene after silent shewa", why: "עְ is silent. Lene stays in תָּ." },
  ],
  3: [
    { q: "In יִשְׂרָאֵל the shewa under sin is…", he: "יִשְׂרָאֵל", ref: "Deut 6:4", choices: ["Silent — hireq is short before it", "Vocal", "Hateph"], answer: "Silent — hireq is short before it", why: "Short vowel + shewa = silent." },
    { q: "In שְׁמַע the shewa is…", he: "שְׁמַע", ref: "Deut 6:4", choices: ["Vocal — first letter", "Silent", "Hateph"], answer: "Vocal — first letter", why: "Initial shewa is vocal." },
    { q: "In לְקוֹל the shewa under lamed is…", he: "לְקוֹל", ref: "Gen 3:17", choices: ["Vocal — start of the word", "Silent", "Hateph"], answer: "Vocal — start of the word", why: "Prefix לְ is vocal shewa." },
    { q: "How does לְקוֹל split?", he: "לְקוֹל", ref: "Gen 3:17", choices: ["לְ | קוֹל", "לְק | וֹל", "לְקוֹל (one)"], answer: "לְ | קוֹל", why: "Vocal shewa opens; holem-vav is the next vowel." },
    { q: "In וּלְאָדָם the shewa under lamed is…", he: "וּלְאָדָם", ref: "Gen 3:17", choices: ["Vocal — after a long vowel (shureq)", "Silent — after every prefix", "Hateph"], answer: "Vocal — after a long vowel (shureq)", why: "Shewa after unaccented long vowel is vocal. Resh is not involved; this is the shewa rule." },
    { q: "How does וּלְאָדָם split?", he: "וּלְאָדָם", ref: "Gen 3:17", choices: ["וּ | לְ | אָ | דָם", "וּלְ | אָדָם", "וּלְאָדָם (one)"], answer: "וּ | לְ | אָ | דָם", why: "Shureq; vocal shewa; qamets; qamets closed." },
    { q: "In אַבְרָהָם the shewa under bet is…", he: "אַבְרָהָם", ref: "Gen 17:5", choices: ["Silent — pathach is short", "Vocal", "Hateph"], answer: "Silent — pathach is short", why: "Short vowel before shewa." },
    { q: "In מִשְׁפַּט the shewa under shin is…", he: "מִשְׁפַּט", ref: "Deut 16:18", choices: ["Silent — hireq is short", "Vocal", "Hateph"], answer: "Silent — hireq is short", why: "מִשְׁ is a closed first slice." },
    { q: "How does מִשְׁפַּט split?", he: "מִשְׁפַּט", ref: "Deut 16:18", choices: ["מִשְׁ | פַּט", "מִ | שְׁפַּט", "מִשְׁפַּט (one)"], answer: "מִשְׁ | פַּט", why: "Silent shewa closes the first slice." },
    { q: "In הַמְּלָכִים the shewa under the second mem is…", he: "הַמְּלָכִים", ref: "1 Kgs 1:9", choices: ["Vocal — under dagesh forte", "Silent", "Hateph"], answer: "Vocal — under dagesh forte", why: "Shewa on a doubled letter is vocal." },
    { q: "Second of two shewas in a row is…", choices: ["Vocal", "Silent", "Always hateph"], answer: "Vocal", why: "First closes; second opens." },
    { q: "In דְּבַר the shewa is…", he: "דְּבַר", ref: "Gen 15:1", choices: ["Vocal — start of the (construct) word", "Silent", "Hatuf"], answer: "Vocal — start of the (construct) word", why: "Initial shewa." },
    { q: "In מַלְכָּה the shewa under lamed is…", he: "מַלְכָּה", ref: "Esth 1:9", choices: ["Silent — pathach is short", "Vocal", "Hateph"], answer: "Silent — pathach is short", why: "מַלְ is closed." },
    { q: "Shewa after an unaccented long vowel is…", choices: ["Vocal", "Silent", "Never written"], answer: "Vocal", why: "That is one of the vocal seats." },
    { q: "In בָּרְכִי the shewa under resh is…", he: "בָּרְכִי", ref: "Ps 103:1", choices: ["Vocal — after unaccented long qamets (shewa rule)", "Hateph — resh is a guttural", "Always silent on resh"], answer: "Vocal — after unaccented long qamets (shewa rule)", why: "Resh follows shewa tests, not hateph." },
    { q: "In רְאוּבֵן the shewa is…", he: "רְאוּבֵן", ref: "Gen 29:32", choices: ["Vocal — it starts the word", "Silent", "Hateph"], answer: "Vocal — it starts the word", why: "Initial shewa. Ordinary shewa rule." },
    { q: "A shewa at the end of a word is…", choices: ["Silent", "Vocal", "Hateph"], answer: "Silent", why: "Final shewa closes." },
    { q: "How does בְּרֵאשִׁית split?", he: "בְּרֵאשִׁית", ref: "Gen 1:1", choices: ["בְּ | רֵא | שִׁית", "בְּרֵא | שִׁית", "בְּרֵאשִׁית (one)"], answer: "בְּ | רֵא | שִׁית", why: "Vocal shewa; tsere with quiet alef; hireq-yod closed." },
    { q: "Silent shewa under ayin in שָׁמַעְתָּ is allowed because…", he: "שָׁמַעְתָּ", ref: "Gen 3:17", choices: ["Silent shewa is not a vowel", "Ayin prefers vocal shewa", "Gutturals never take shewa of any kind"], answer: "Silent shewa is not a vowel", why: "They refuse vocal shewa (hateph). Silent is fine." },
    { q: "In יִשְׁמְעוּ, two shewas: which is vocal?", he: "יִשְׁמְעוּ", ref: "Gen 3:8", choices: ["The second (מְ)", "The first (שְׁ)", "Neither"], answer: "The second (מְ)", why: "First silent after hireq; second vocal." },
    { q: "How does יִשְׁמְעוּ split?", he: "יִשְׁמְעוּ", ref: "Gen 3:8", choices: ["יִשְׁ | מְ | עוּ", "יִ | שְׁמְעוּ", "יִשְׁמְעוּ (one)"], answer: "יִשְׁ | מְ | עוּ", why: "Silent, then vocal, then shureq slice." },
  ],
  4: [
    { q: "In חָכְמָה the last ָ is…", he: "חָכְמָה", ref: "Prov 1:7", choices: ["Qamets (accented)", "Hatuf", "Hateph"], answer: "Qamets (accented)", why: "Accented last slice. Not hatuf." },
    { q: "In כָּל־הָעַמִּים the ָ of כָּל is…", he: "כָּל", ref: "Exod 19:5", choices: ["Hatuf (short o)", "Qamets (long a)", "Pathach"], answer: "Hatuf (short o)", why: "Construct ‘all of’ — closed, unaccented." },
    { q: "In מִכָּל the ָ is…", he: "מִכָּל", ref: "Exod 19:5", choices: ["Hatuf", "Qamets", "Hireq"], answer: "Hatuf", why: "Same construct כָּל after מִ." },
    { q: "In קָרְבָּן the first ָ is…", he: "קָרְבָּן", ref: "Lev 1:2", choices: ["Hatuf — closed unaccented קָרְ", "Qamets — it is open", "Hateph"], answer: "Hatuf — closed unaccented קָרְ", why: "Silent shewa closes it; accent is on בָּן." },
    { q: "How does קָרְבָּן split?", he: "קָרְבָּן", ref: "Lev 1:2", choices: ["קָרְ | בָּן", "קָ | רְבָּן", "קָרְבָּן (one)"], answer: "קָרְ | בָּן", why: "Hatuf first; qamets on the accented slice." },
    { q: "In דָּוִד the first ָ is…", he: "דָּוִד", ref: "1 Sam 16:13", choices: ["Qamets (open pretonic)", "Hatuf", "Hateph"], answer: "Qamets (open pretonic)", why: "Open syllable. Cannot be hatuf." },
    { q: "In בָּרָא the first ָ is…", he: "בָּרָא", ref: "Gen 1:1", choices: ["Qamets (open)", "Hatuf", "Shewa"], answer: "Qamets (open)", why: "בָּ is open." },
    { q: "A metheg next to ָ means…", choices: ["Read long a, not short o", "Read hatuf", "Ignore the sign"], answer: "Read long a, not short o", why: "Metheg marks qamets." },
    { q: "In אָכְלָה the first ָ is…", he: "אָכְלָה", ref: "Gen 1:29", choices: ["Hatuf", "Qamets", "Pathach"], answer: "Hatuf", why: "Closed, unaccented, silent shewa." },
    { q: "In הָאָרֶץ the ָ under he is…", he: "הָאָרֶץ", ref: "Gen 1:1", choices: ["Qamets (article lengthened)", "Hatuf", "Hateph"], answer: "Qamets (article lengthened)", why: "Open / compensatory length. Not hatuf." },
    { q: "Hatuf never sits in…", choices: ["An open syllable", "A closed unaccented syllable", "Construct כָּל"], answer: "An open syllable", why: "Open → qamets or another vowel, not hatuf." },
    { q: "In שָׁמַר the ָ is…", he: "שָׁמַר", ref: "Gen 2:15", choices: ["Qamets (accented / open enough — not hatuf)", "Hatuf because shewa follows", "Hateph"], answer: "Qamets (accented / open enough — not hatuf)", why: "שָׁ is open. Pathach is under mem." },
    { q: "How does חָכְמָה read?", he: "חָכְמָה", ref: "Prov 1:7", choices: ["ḥokh-māh", "ḥakh-māh", "ḥā-khəmāh"], answer: "ḥokh-māh", why: "First sign is short o." },
    { q: "How does כָּל read in construct?", he: "כָּל", ref: "Deut 6:5", choices: ["kol", "kāl", "kal with pathach"], answer: "kol", why: "Hatuf." },
    { q: "In לָיְלָה the first ָ is…", he: "לָיְלָה", ref: "Gen 1:5", choices: ["Qamets in the ay-cluster / not hatuf as a separate short o", "Hatuf because shewa follows yod", "Hateph"], answer: "Qamets in the ay-cluster / not hatuf as a separate short o", why: "That ָ is part of the diphthong seat, not a closed unaccented hatuf word like כָּל." },
    { q: "Closed + accented ָ is…", choices: ["Qamets (long a)", "Hatuf", "Always shewa"], answer: "Qamets (long a)", why: "Accent keeps it long." },
    { q: "Closed + unaccented ָ is…", choices: ["Hatuf (short o)", "Qamets", "Pathach"], answer: "Hatuf (short o)", why: "The only hatuf seat." },
    { q: "Open + pretonic ָ is…", choices: ["Qamets (long a)", "Hatuf", "Hireq"], answer: "Qamets (long a)", why: "Open forbids hatuf." },
    { q: "In קָדְשׁוֹ the first ָ is…", he: "קָדְשׁוֹ", ref: "Ps 103:1", choices: ["Hatuf — קָדְ closed unaccented", "Qamets", "Hateph"], answer: "Hatuf — קָדְ closed unaccented", why: "Same test as חָכְמָה." },
    { q: "Hateph qamets ֳ is not hatuf because…", choices: ["Hatephs are reduced vowels in open slices", "They are the same sound", "Hatephs are silent"], answer: "Hatephs are reduced vowels in open slices", why: "Different sign, different seat." },
    { q: "In דָּבָר neither ָ is hatuf because…", he: "דָּבָר", ref: "Deut 4:2", choices: ["First is open; second is closed and accented", "The word has no shewa so it cannot be qamets", "Hatuf needs a guttural"], answer: "First is open; second is closed and accented", why: "Both seats of long a." },
  ],
  5: [
    { q: "How many syllables in מוֹשִׁיעַ?", he: "מוֹשִׁיעַ", ref: "Isa 19:20", choices: ["Two", "Three", "One"], answer: "Two", why: "Holem and hireq-yod. Furtive pathach does not add a third." },
    { q: "How many syllables in רָקִיעַ?", he: "רָקִיעַ", ref: "Gen 1:6", choices: ["Two", "Three", "One"], answer: "Two", why: "Furtive on ע is not a slice." },
    { q: "נֹחַ is pronounced…", he: "נֹחַ", ref: "Gen 6:9", choices: ["nōaḥ — pathach before ḥet, still one syllable", "nō-ḥa two slices", "nōḥ with no a"], answer: "nōaḥ — pathach before ḥet, still one syllable", why: "Furtive." },
    { q: "רוּחַ is pronounced…", he: "רוּחַ", ref: "Gen 1:2", choices: ["rûaḥ, one syllable", "rû-ḥa two syllables", "rûḥ"], answer: "rûaḥ, one syllable", why: "Furtive pathach." },
    { q: "Can furtive pathach sit on א?", choices: ["No — ח and ע only", "Yes, any guttural", "Only resh"], answer: "No — ח and ע only", why: "Word-final ח / ע." },
    { q: "Can furtive pathach sit on ר?", choices: ["No", "Yes", "Only in verbs"], answer: "No", why: "Not ח or ע." },
    { q: "In יָדַע you do not call the pathach furtive because…", he: "יָדַע", ref: "Gen 4:1", choices: ["It sits under ד, a real vowel", "Ayin never takes pathach", "The word has no pathach"], answer: "It sits under ד, a real vowel", why: "Furtive is under the final guttural itself." },
    { q: "Split of יָדַע?", he: "יָדַע", ref: "Gen 4:1", choices: ["יָ | דַע", "יָדַע (one, furtive)", "יָ | דַ | ע"], answer: "יָ | דַע", why: "Two real vowels." },
    { q: "In שָׁמֵעַ if pathach is under ע at the end after a long vowel, treat it as…", choices: ["Furtive — do not add a slice", "A new syllable", "Qamets hatuf"], answer: "Furtive — do not add a slice", why: "Classic furtive seat." },
    { q: "Furtive pathach is written…", choices: ["Under the last letter", "Before the last letter as its own sign", "Above the word"], answer: "Under the last letter", why: "Mouth says it first; spelling puts it last." },
    { q: "Does furtive pathach close a syllable?", choices: ["No — it is not counted", "Yes — it is a silent shewa", "Yes — it is hatuf"], answer: "No — it is not counted", why: "Heard, not a cut." },
    { q: "וְרוּחַ has how many counted slices?", he: "וְרוּחַ", ref: "Gen 1:2", choices: ["Two: וְ | רוּחַ", "Three", "One"], answer: "Two: וְ | רוּחַ", why: "Vocal shewa prefix + one furtive-bearing slice." },
    { q: "רָקִיעַ furtive letter is…", he: "רָקִיעַ", ref: "Gen 1:6", choices: ["ע", "ק", "ר"], answer: "ע", why: "Final ayin." },
    { q: "If the last letter is ח with pathach and the previous vowel is already in that same written cluster, the pathach is…", choices: ["Furtive", "Always a new open syllable", "Shewa"], answer: "Furtive", why: "Do not split on it." },
    { q: "Which pair takes furtive pathach?", choices: ["ח and ע", "א and ה", "ב and כ"], answer: "ח and ע", why: "Those two at word-end." },
    { q: "In English gloss, furtive pathach often shows up as…", choices: ["An a before the last guttural (ruach, Noach)", "An extra syllable count in Hebrew", "A silent letter"], answer: "An a before the last guttural (ruach, Noach)", why: "That is the mouth. The split stays tight." },
    { q: "Holem + final חַ is typically…", choices: ["One syllable with furtive pathach", "Two syllables", "Qamets hatuf"], answer: "One syllable with furtive pathach", why: "נֹחַ, כֹּחַ." },
    { q: "כֹּחַ (strength) is…", he: "כֹּחַ", ref: "Exod 15:6", choices: ["One syllable", "Two", "Three"], answer: "One syllable", why: "Furtive on ḥet." },
    { q: "Do you use furtive pathach in the middle of a word?", choices: ["No — word-final ח / ע", "Yes, any guttural", "Only under alef"], answer: "No — word-final ח / ע", why: "End of the word." },
    { q: "If you split רוּחַ as רוּ | חַ you have…", he: "רוּחַ", ref: "Gen 1:2", choices: ["Counted a furtive pathach as a vowel-seat", "The correct split", "Dropped shureq"], answer: "Counted a furtive pathach as a vowel-seat", why: "Do not." },
    { q: "True or the trap: furtive pathach is a full vowel in the split.", choices: ["Trap — heard, not counted", "True — always a new slice", "True for ayin only"], answer: "Trap — heard, not counted", why: "Pronounce it; do not tally it." },
  ],
  6: [
    { q: "How does רֹאשׁ split?", he: "רֹאשׁ", ref: "Gen 2:10", choices: ["רֹאשׁ (one)", "רֹ | אשׁ", "רֹא | שׁ"], answer: "רֹאשׁ (one)", why: "Quiet alef. One holem." },
    { q: "How does בָּרָא split?", he: "בָּרָא", ref: "Gen 1:1", choices: ["בָּ | רָא", "בָּרָא (one)", "בָּ | רָ | א"], answer: "בָּ | רָא", why: "Quiet final alef." },
    { q: "How does מָצָא split?", he: "מָצָא", ref: "Gen 2:20", choices: ["מָ | צָא", "מָצ | אָ", "מָ | צָ | א"], answer: "מָ | צָא", why: "Two qamets; quiet alef." },
    { q: "In בְּרֵאשִׁית the alef after tsere is…", he: "בְּרֵאשִׁית", ref: "Gen 1:1", choices: ["Quiescent", "A new onset", "Furtive"], answer: "Quiescent", why: "No vowel on that alef." },
    { q: "רָאשִׁים keeps quiet alef. Split starts…", he: "רָאשִׁים", ref: "Gen 2:10", choices: ["רָ | שִׁים (alef quiet in the first bundle)", "רָ | א | שִׁים", "ראש | ים"], answer: "רָ | שִׁים (alef quiet in the first bundle)", why: "Do not give alef its own slice." },
    { q: "In וַיַּרְא you keep א in…", he: "וַיַּרְא", ref: "Gen 1:4", choices: ["The last slice יַרְא", "Its own slice א", "The prefix"], answer: "The last slice יַרְא", why: "Quiet. Forte is on yod." },
    { q: "If alef has hireq under it, it is…", choices: ["A real onset", "Still quiescent", "Furtive"], answer: "A real onset", why: "A vowel makes it live." },
    { q: "אֱלֹהִים first letter is not quiescent because…", he: "אֱלֹהִים", ref: "Gen 1:1", choices: ["Hateph is a vowel", "Alef is always quiet", "There is no mark"], answer: "Hateph is a vowel", why: "אֱ opens a slice." },
    { q: "חַטָּאת last alef…", he: "חַטָּאת", ref: "Ps 51:5", choices: ["Quiet, stays with טָאת", "Starts את", "Furtive pathach"], answer: "Quiet, stays with טָאת", why: "No vowel on א." },
    { q: "Quiescent means…", choices: ["Written, not sounded as a consonant in the split", "Deleted from the spelling", "Always a glottal stop that counts"], answer: "Written, not sounded as a consonant in the split", why: "Spelling vs mouth." },
    { q: "Which alef is quiescent?", choices: ["The one with no vowel", "Every alef", "Only initial alef"], answer: "The one with no vowel", why: "That is the test." },
    { q: "In מַלְאָךְ the alef has a vowel, so…", he: "מַלְאָךְ", ref: "Gen 16:7", choices: ["It starts the last slice אָךְ", "It is quiet", "It is furtive"], answer: "It starts the last slice אָךְ", why: "Qamets under alef." },
    { q: "How does מַלְאָךְ split?", he: "מַלְאָךְ", ref: "Gen 16:7", choices: ["מַלְ | אָךְ", "מַ | לָאָךְ", "מַלְאָךְ (one)"], answer: "מַלְ | אָךְ", why: "Silent shewa; then live alef." },
    { q: "Quiet alef after holem (רֹאשׁ) does not…", he: "רֹאשׁ", ref: "Gen 2:10", choices: ["Create a second syllable", "Belong in the spelling", "Sit in the same slice"], answer: "Create a second syllable", why: "One vowel." },
    { q: "In יֵצֵא final alef is…", he: "יֵצֵא", ref: "Gen 2:10", choices: ["Quiescent", "A third syllable", "Dagesh"], answer: "Quiescent", why: "Tsere is on tsade." },
    { q: "How does יֵצֵא split?", he: "יֵצֵא", ref: "Gen 2:10", choices: ["יֵ | צֵא", "יֵצֵ | א", "יֵצֵא (one)"], answer: "יֵ | צֵא", why: "Two tseres; quiet alef on the second slice." },
    { q: "Do not confuse quiescent alef with…", choices: ["Furtive pathach (that is ח/ע at word-end)", "Dagesh lene", "Shin-dot"], answer: "Furtive pathach (that is ח/ע at word-end)", why: "Different letters, different rule." },
    { q: "בָּרָא vs בָּרָאתִי: alef stays quiet; the extra letters…", choices: ["Join the last slice or add suffixes", "Wake the alef", "Make forte on alef"], answer: "Join the last slice or add suffixes", why: "Alef still has no vowel of its own in that seat." },
    { q: "Alef with shewa: is it quiescent?", choices: ["No — shewa is a mark; then apply shewa tests (or hateph if vocal is needed)", "Yes — any alef is quiet", "Yes if it is the last letter only"], answer: "No — shewa is a mark; then apply shewa tests (or hateph if vocal is needed)", why: "Quiet alef has nothing under it." },
    { q: "In וַיַּרְא the forte split is through…", he: "וַיַּרְא", ref: "Gen 1:4", choices: ["Yod, not alef", "Alef", "Resh"], answer: "Yod, not alef", why: "Quiet alef does not take the cut." },
    { q: "If you split בָּרָא as בָּר | א you have…", he: "בָּרָא", ref: "Gen 1:1", choices: ["Given quiet alef its own onset — wrong", "The only correct split", "Marked furtive pathach"], answer: "Given quiet alef its own onset — wrong", why: "No vowel on that alef." },
  ],
  7: [
    { q: "How does עֵינַיִם split?", he: "עֵינַיִם", ref: "Prov 6:17", choices: ["עֵי | נַיִם", "עֵ | ינַ | יִם", "עֵינַ | יִם"], answer: "עֵי | נַיִם", why: "Dual ay-cluster stays closed on נַיִם. First slice has tsere-yod." },
    { q: "How does מַיִם split?", he: "מַיִם", ref: "Gen 1:2", choices: ["מַיִם (one closed — special dual form)", "מַ | יִם", "מַי | ִם"], answer: "מַיִם (one closed — special dual form)", why: "The ay-group plus ם. Do not cut it. Special dual meaning ‘water’, often singular in sense." },
    { q: "How does שָׁמַיִם split (without the article)?", he: "שָׁמַיִם", ref: "Gen 1:1", choices: ["שָׁ | מַ | יִם", "שָׁמַיִם (one)", "שָׁ | מַיִם as dual-required cluster only"], answer: "שָׁ | מַ | יִם", why: "Not the dual ending here the same way as יָדַיִם: three vowels." },
    { q: "סוּסַיִם is dual because…", he: "סוּסַיִם", choices: ["The ending is the ay diphthong plus ם", "Any ים is dual", "The word means many horses, so dual"], answer: "The ending is the ay diphthong plus ם", why: "Requirement." },
    { q: "סוּסִים (horses, many) vs סוּסַיִם (two): the difference is…", choices: ["Hireq-yod ִים vs ay-diphthong ַיִם", "Nothing — same ending", "Only the vowels of the stem"], answer: "Hireq-yod ִים vs ay-diphthong ַיִם", why: "Dual needs the diphthong." },
    { q: "בַּיִת if split בַּ | יִת is…", he: "בַּיִת", ref: "Prov 24:3", choices: ["Wrong — diphthong cut", "Correct", "Optional"], answer: "Wrong — diphthong cut", why: "Keep ay together." },
    { q: "מָוֶת if split מָ | וֶת is…", he: "מָוֶת", ref: "Ps 23:4", choices: ["Wrong — aw cut", "Correct", "Required"], answer: "Wrong — aw cut", why: "Keep aw together." },
    { q: "יַיִן is…", he: "יַיִן", ref: "Gen 9:21", choices: ["One closed syllable", "Two", "Open then closed"], answer: "One closed syllable", why: "Ay cluster." },
    { q: "לַיְלָה first slice is closed because…", he: "לַיְלָה", ref: "Gen 1:5", choices: ["The ay cluster ends with a consonant (yod + shewa closer)", "Every first slice is closed", "Hateph"], answer: "The ay cluster ends with a consonant (yod + shewa closer)", why: "לַיְ | לָה." },
    { q: "Dual of יָד is…", he: "יָדַיִם", ref: "Prov 6:17", choices: ["יָדַיִם", "יָדִים", "יָדוֹת"], answer: "יָדַיִם", why: "Ay + ם." },
    { q: "Dual of עַיִן is…", he: "עֵינַיִם", ref: "Prov 6:17", choices: ["עֵינַיִם", "עֵינִים", "עֲיָנוֹת as the dual"], answer: "עֵינַיִם", why: "Ay diphthong required." },
    { q: "הַשָּׁמַיִם has four slices because…", he: "הַשָּׁמַיִם", ref: "Gen 1:1", choices: ["Forte shin splits, then מַ | יִם", "It is a dual you must not cut at all", "Furtive pathach"], answer: "Forte shin splits, then מַ | יִם", why: "הַשְׁ | שָׁ | מַ | יִם." },
    { q: "A diphthong syllable counts as…", choices: ["Closed", "Open", "Not a syllable"], answer: "Closed", why: "Ends with a consonant sound." },
    { q: "צַלְמָוֶת: do not cut…", he: "צַלְמָוֶת", ref: "Ps 23:4", choices: ["The aw in מָוֶת", "The tsade from lamed", "The furtive pathach"], answer: "The aw in מָוֶת", why: "צַלְ | מָוֶת." },
    { q: "How does צַלְמָוֶת split?", he: "צַלְמָוֶת", ref: "Ps 23:4", choices: ["צַלְ | מָוֶת", "צַלְ | מָ | וֶת", "צַלְמָוֶת (one)"], answer: "צַלְ | מָוֶת", why: "Silent shewa; then the aw word." },
    { q: "The dual ending is the same cluster as…", choices: ["בַּיִת’s ay-group plus ם", "Any plural ים", "וֹת"], answer: "בַּיִת’s ay-group plus ם", why: "Required diphthong." },
    { q: "If you see ַיִם, first ask…", choices: ["Is this the dual diphthong?", "Is this always ‘water’?", "Is it feminine plural?"], answer: "Is this the dual diphthong?", why: "Then name the pair (hands, eyes) or a special dual (water, heaven)." },
    { q: "מָוֶת cluster letters are…", he: "מָוֶת", ref: "Ps 23:4", choices: ["Qamets + vav + segol", "Holem-vav", "Two shewas"], answer: "Qamets + vav + segol", why: "aw." },
    { q: "בַּיִת cluster is…", he: "בַּיִת", ref: "Prov 24:3", choices: ["Pathach + yod + hireq", "Two qamets", "Holem + yod"], answer: "Pathach + yod + hireq", why: "ay." },
    { q: "You may cut a diphthong when…", choices: ["You may not — keep it", "The word is long", "A guttural is near"], answer: "You may not — keep it", why: "One closed slice." },
    { q: "יָדַיִם vs יָדִים: only the first is dual because…", choices: ["Only the first has the ay diphthong", "Both are dual", "Neither is dual"], answer: "Only the first has the ay diphthong", why: "ִים without ay is many." },
  ],
  8: [
    { q: "How does עֶבֶד illustrate short-vowel seats?", he: "עֶבֶד", ref: "Josh 1:1", choices: ["Open accented-style short, then closed short", "Two long vowels", "Hatephs"], answer: "Open accented-style short, then closed short", why: "Segol likes those seats." },
    { q: "Hateph appears under gutturals instead of…", choices: ["Vocal shewa", "Silent shewa", "Qamets hatuf"], answer: "Vocal shewa", why: "א ה ח ע." },
    { q: "How does אֲשֶׁר split?", he: "אֲשֶׁר", ref: "Gen 1:7", choices: ["אֲ | שֶׁר", "אַשְׁ | ֶר", "אֲשֶׁר (one)"], answer: "אֲ | שֶׁר", why: "Hateph pathach under alef." },
    { q: "How does אֲנִי split?", he: "אֲנִי", ref: "Exod 3:6", choices: ["אֲ | נִי", "אַנְ | י", "אֲנִי (one)"], answer: "אֲ | נִי", why: "Hateph, then hireq-yod." },
    { q: "How does יַעֲקֹב prove hateph?", he: "יַעֲקֹב", ref: "Gen 32:29", choices: ["עֲ is a reduced vowel under ayin, its own slice", "The shewa is silent under ayin", "Ayin takes dagesh"], answer: "עֲ is a reduced vowel under ayin, its own slice", why: "יַ | עֲ | קֹב." },
    { q: "How does אַהֲרֹן prove hateph under he?", he: "אַהֲרֹן", ref: "Exod 4:14", choices: ["הֲ opens a slice", "He takes silent shewa only", "He takes dagesh"], answer: "הֲ opens a slice", why: "אַ | הֲ | רֹן." },
    { q: "דְּבָרִים propretonic shewa is allowed because…", he: "דְּבָרִים", ref: "Gen 15:1", choices: ["Dalet is not a guttural", "All letters take hateph", "Shewa is silent here"], answer: "Dalet is not a guttural", why: "Vocal shewa on a non-guttural." },
    { q: "אֱלֹהִים propretonic reduced vowel is…", he: "אֱלֹהִים", ref: "Gen 1:1", choices: ["Hateph segol", "Vocal shewa", "Hatuf"], answer: "Hateph segol", why: "Guttural." },
    { q: "Short vowels like…", choices: ["Closed unaccented or open accented", "Only open pretonic", "Only hateph seats"], answer: "Closed unaccented or open accented", why: "Their usual pair." },
    { q: "Long vowels like…", choices: ["Closed accented or open pretonic", "Closed unaccented", "Only hateph"], answer: "Closed accented or open pretonic", why: "Their usual pair." },
    { q: "Propretonic reduced: non-guttural takes…", choices: ["Vocal shewa", "Hateph", "Hatuf"], answer: "Vocal shewa", why: "דְּבָרִים." },
    { q: "Propretonic reduced: guttural takes…", choices: ["Hateph", "Vocal shewa", "Nothing"], answer: "Hateph", why: "אֱלֹהִים." },
    { q: "May ר take dagesh forte to lengthen a short vowel?", choices: ["No — compensation often lengthens the previous vowel instead", "Yes, freely", "Only in nouns"], answer: "No — compensation often lengthens the previous vowel instead", why: "No dagesh on resh." },
    { q: "הָאָרֶץ lengthened article is compensation because…", he: "הָאָרֶץ", ref: "Gen 1:1", choices: ["Alef will not take forte", "Alef takes dagesh", "The article never lengthens"], answer: "Alef will not take forte", why: "Guttural. הָ not הַ." },
    { q: "Gutturals prefer which vowel class?", choices: ["a-class (pathach, qamets, hateph pathach)", "i-class only", "u-class only"], answer: "a-class (pathach, qamets, hateph pathach)", why: "Characteristic lean." },
    { q: "In עֶבֶד first vowel is…", he: "עֶבֶד", ref: "Josh 1:1", choices: ["Short e in an open slice", "Hateph", "Hatuf"], answer: "Short e in an open slice", why: "Segol." },
    { q: "Silent shewa under a guttural (שָׁמַעְתָּ) does not break the guttural rule because…", he: "שָׁמַעְתָּ", ref: "Gen 3:17", choices: ["The forbidden thing is vocal shewa, not silent", "Gutturals never take shewa, so the pointing is wrong", "It is actually a hateph"], answer: "The forbidden thing is vocal shewa, not silent", why: "Bible proof." },
    { q: "Pretonic means…", choices: ["One seat before the accent", "Two seats before", "The last letter"], answer: "One seat before the accent", why: "Propretonic is two." },
    { q: "How does אֲשֶׁר show a-class + hateph?", he: "אֲשֶׁר", ref: "Gen 1:7", choices: ["Hateph pathach under alef", "Vocal shewa under alef", "Dagesh in alef"], answer: "Hateph pathach under alef", why: "Guttural reduced a-class." },
    { q: "If you put vocal shewa under ayin you should have written…", choices: ["A hateph", "Dagesh forte", "Qamets hatuf"], answer: "A hateph", why: "That is the replacement." },
    { q: "Resh with shewa in פַּרְעֹה is silent because…", he: "פַּרְעֹה", ref: "Exod 5:1", choices: ["Short pathach before it — shewa rule", "Resh is a guttural that cannot take shewa", "It is a hateph written wrong"], answer: "Short pathach before it — shewa rule", why: "Not the guttural hateph rule." },
  ],
};
