export type VerseEx = {
  ref: string;
  he: string;
  en: string;
  hit: string;
  /** English span to mark when gloss/alts would miss or pick the wrong word. */
  hitEn?: string;
};

/** Public-domain Hebrew (Masoretic) with short original English glosses. `hit` is the span to highlight. */
export const VERSES: Record<string, VerseEx> = {
  yhwh: { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "יְהוָה" },
  israel: { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "יִשְׂרָאֵל" },
  david: { ref: "1 Sam 16:13", he: "וַיִּמְשַׁח אֹתוֹ בְּקֶרֶב אֶחָיו וַתִּצְלַח רוּחַ יְהוָה אֶל־דָּוִד", en: "He anointed him among his brothers, and the spirit of YHWH rushed upon David.", hit: "דָּוִד" },
  judah: { ref: "Gen 49:8", he: "יְהוּדָה אַתָּה יוֹדוּךָ אַחֶיךָ", en: "Judah, your brothers will praise you.", hit: "יְהוּדָה" },
  moses: { ref: "Exod 3:4", he: "וַיֹּאמֶר הִנֵּנִי וַיֹּאמֶר מֹשֶׁה מֹשֶׁה", en: "He said, “Here I am.” And he said, “Moses, Moses.”", hit: "מֹשֶׁה" },
  egypt: { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "מִצְרַיִם" },
  jerusalem: { ref: "Ps 122:6", he: "שַׁאֲלוּ שְׁלוֹם יְרוּשָׁלַ͏ִם", en: "Pray for the peace of Jerusalem.", hit: "יְרוּשָׁלַ͏ִם" },
  aaron: { ref: "Exod 4:14", he: "הֲלֹא אַהֲרֹן אָחִיךָ הַלֵּוִי", en: "Is not Aaron your brother, the Levite?", hit: "אַהֲרֹן" },
  jacob: { ref: "Gen 32:29", he: "לֹא יַעֲקֹב יֵאָמֵר עוֹד שִׁמְךָ כִּי אִם־יִשְׂרָאֵל", en: "Your name shall no longer be said Jacob, but Israel.", hit: "יַעֲקֹב" },
  joshua: { ref: "Josh 1:1", he: "וַיְהִי אַחֲרֵי מוֹת מֹשֶׁה עֶבֶד יְהוָה וַיֹּאמֶר יְהוָה אֶל־יְהוֹשֻׁעַ", en: "After the death of Moses, servant of YHWH, YHWH spoke to Joshua.", hit: "יְהוֹשֻׁעַ" },
  joseph: { ref: "Gen 39:2", he: "וַיְהִי יְהוָה אֶת־יוֹסֵף וַיְהִי אִישׁ מַצְלִיחַ", en: "YHWH was with Joseph, and he became a man who prospered.", hit: "יוֹסֵף" },
  abraham: { ref: "Gen 17:5", he: "וְלֹא־יִקָּרֵא עוֹד אֶת־שִׁמְךָ אַבְרָם וְהָיָה שִׁמְךָ אַבְרָהָם", en: "You shall no longer be called Abram; your name shall be Abraham.", hit: "אַבְרָהָם" },
  jeremiah: { ref: "Jer 1:1", he: "דִּבְרֵי יִרְמְיָהוּ בֶּן־חִלְקִיָּהוּ", en: "The words of Jeremiah son of Hilkiah.", hit: "יִרְמְיָהוּ" },
  isaac: { ref: "Gen 21:3", he: "וַיִּקְרָא אַבְרָהָם אֶת־שֶׁם־בְּנוֹ הַנּוֹלַד־לוֹ יִצְחָק", en: "Abraham named the son born to him Isaac.", hit: "יִצְחָק" },
  canaan: { ref: "Gen 12:5", he: "וַיֵּצְאוּ לָלֶכֶת אַרְצָה כְּנַעַן וַיָּבֹאוּ אַרְצָה כְּנָעַן", en: "They set out to go to the land of Canaan, and they came to the land of Canaan.", hit: "כְּנַעַן" },
  samuel: { ref: "1 Sam 3:10", he: "וַיֹּאמֶר שְׁמוּאֵל דַּבֵּר כִּי שֹׁמֵעַ עַבְדֶּךָ", en: "Samuel said, “Speak, for your servant is listening.”", hit: "שְׁמוּאֵל" },
  esau: { ref: "Gen 25:25", he: "וַיֵּצֵא הָרִאשׁוֹן אַדְמוֹנִי כֻּלּוֹ כְּאַדֶּרֶת שֵׂעָר וַיִּקְרְאוּ שְׁמוֹ עֵשָׂו", en: "The first came out red, all of him like a hairy cloak, and they named him Esau.", hit: "עֵשָׂו" },
  pharaoh: { ref: "Exod 5:1", he: "וְאַחַר בָּאוּ מֹשֶׁה וְאַהֲרֹן וַיֹּאמְרוּ אֶל־פַּרְעֹה", en: "Afterward Moses and Aaron came and said to Pharaoh.", hit: "פַּרְעֹה" },
  zion: { ref: "Ps 125:1", he: "הַבֹּטְחִים בַּיהוָה כְּהַר־צִיּוֹן לֹא־יִמּוֹט", en: "Those who trust in YHWH are like Mount Zion, which cannot be moved.", hit: "צִיּוֹן" },
  saul: { ref: "1 Sam 9:2", he: "וּלוֹ הָיָה בֵן וּשְׁמוֹ שָׁאוּל בָּחוּר וָטוֹב", en: "He had a son whose name was Saul, a young man and good.", hit: "שָׁאוּל" },
  solomon: { ref: "Prov 1:1", he: "מִשְׁלֵי שְׁלֹמֹה בֶן־דָּוִד מֶלֶךְ יִשְׂרָאֵל", en: "The proverbs of Solomon son of David, king of Israel.", hit: "שְׁלֹמֹה" },

  elohim: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "אֱלֹהִים" },
  ben: { ref: "Gen 22:2", he: "קַח־נָא אֶת־בִּנְךָ אֶת־יְחִידְךָ אֲשֶׁר־אָהַבְתָּ", en: "Take your son, your only one, whom you love.", hit: "בִּנְךָ" },
  melek: { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד יְהוָה עִזּוּז וְגִבּוֹר", en: "Who is this king of glory? YHWH, strong and mighty.", hit: "מֶלֶךְ" },
  erets: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "הָאָרֶץ" },
  yom: { ref: "Gen 1:5", he: "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם וְלַחֹשֶׁךְ קָרָא לָיְלָה", en: "God called the light Day, and the darkness he called Night.", hit: "יוֹם" },
  ish: { ref: "Gen 2:24", he: "עַל־כֵּן יַעֲזָב־אִישׁ אֶת־אָבִיו וְאֶת־אִמּוֹ", en: "Therefore a man leaves his father and his mother.", hit: "אִישׁ" },
  bayit: { ref: "Josh 24:15", he: "וְאָנֹכִי וּבֵיתִי נַעֲבֹד אֶת־יְהוָה", en: "As for me and my house, we will serve YHWH.", hit: "וּבֵיתִי" },
  am: { ref: "Exod 19:5", he: "וִהְיִיתֶם לִי סְגֻלָּה מִכָּל־הָעַמִּים", en: "You shall be my treasured possession out of all the peoples.", hit: "הָעַמִּים" },
  dabar: { ref: "Gen 15:1", he: "הָיָה דְבַר־יְהוָה אֶל־אַבְרָם בַּמַּחֲזֶה", en: "The word of YHWH came to Abram in a vision.", hit: "דְבַר" },
  ab: { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "אָבִיךָ" },
  ir: { ref: "Gen 11:4", he: "הָבָה נִבְנֶה־לָּנוּ עִיר וּמִגְדָּל", en: "Come, let us build ourselves a city and a tower.", hit: "עִיר" },
  shem: { ref: "Gen 12:2", he: "וְאֶעֶשְׂךָ לְגוֹי גָּדוֹל וַאֲבָרֶכְךָ וַאֲגַדְּלָה שְׁמֶךָ", en: "I will make you a great nation, and I will bless you and make your name great.", hit: "שְׁמֶךָ" },
  ishah: { ref: "Gen 2:23", he: "לְזֹאת יִקָּרֵא אִשָּׁה כִּי מֵאִישׁ לֻקֳחָה־זֹּאת", en: "This one shall be called woman, for from man this one was taken.", hit: "אִשָּׁה" },
  ah: { ref: "Gen 4:9", he: "וַיֹּאמֶר יְהוָה אֶל־קַיִן אֵי הֶבֶל אָחִיךָ", en: "YHWH said to Cain, “Where is Abel your brother?”", hit: "אָחִיךָ" },
  bat: { ref: "Exod 2:5", he: "וַתֵּרֶד בַּת־פַּרְעֹה לִרְחֹץ עַל־הַיְאֹר", en: "The daughter of Pharaoh came down to bathe at the Nile.", hit: "בַּת" },
  em: { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "אִמֶּךָ" },
  adamah: { ref: "Gen 2:7", he: "וַיִּיצֶר יְהוָה אֱלֹהִים אֶת־הָאָדָם עָפָר מִן־הָאֲדָמָה", en: "YHWH God formed the human of dust from the ground.", hit: "הָאֲדָמָה" },
  laylah: { ref: "Gen 1:5", he: "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם וְלַחֹשֶׁךְ קָרָא לָיְלָה", en: "God called the light Day, and the darkness he called Night.", hit: "לָיְלָה" },
  rosh: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "בְּרֵאשִׁית" },
  panim: { ref: "Num 6:25", he: "יָאֵר יְהוָה פָּנָיו אֵלֶיךָ וִיחֻנֶּךָּ", en: "YHWH make his face shine upon you and be gracious to you.", hit: "פָּנָיו" },
  "et-time": { ref: "Eccl 3:1", he: "לַכֹּל זְמָן וְעֵת לְכָל־חֵפֶץ תַּחַת הַשָּׁמָיִם", en: "For everything a season, and a time for every matter under heaven.", hit: "וְעֵת" },
  shanah: { ref: "Gen 1:14", he: "וְהָיוּ לְאֹתֹת וּלְמוֹעֲדִים וּלְיָמִים וְשָׁנִים", en: "Let them be for signs, for appointed times, for days and years.", hit: "וְשָׁנִים" },
  hodesh: { ref: "Exod 12:2", he: "הַחֹדֶשׁ הַזֶּה לָכֶם רֹאשׁ חֳדָשִׁים", en: "This month shall be for you the head of months.", hit: "הַחֹדֶשׁ" },
  shaar: { ref: "Ps 118:19", he: "פִּתְחוּ־לִי שַׁעֲרֵי־צֶדֶק אָבֹא־בָם אוֹדֶה יָהּ", en: "Open to me the gates of righteousness; I will enter them and give thanks to Yah.", hit: "שַׁעֲרֵי" },
  sadeh: { ref: "Gen 2:5", he: "וְכֹל שִׂיחַ הַשָּׂדֶה טֶרֶם יִהְיֶה בָאָרֶץ", en: "No shrub of the field was yet on the earth.", hit: "הַשָּׂדֶה" },
  yam: { ref: "Exod 14:21", he: "וַיּוֹלֶךְ יְהוָה אֶת־הַיָּם בְּרוּחַ קָדִים עַזָּה", en: "YHWH drove the sea back by a strong east wind.", hit: "הַיָּם" },
  kesef: { ref: "Gen 23:16", he: "וַיִּשְׁקֹל אַבְרָהָם לְעֶפְרֹן אֶת־הַכֶּסֶף", en: "Abraham weighed out for Ephron the silver.", hit: "הַכֶּסֶף" },
  zahav: { ref: "Exod 25:11", he: "וְצִפִּיתָ אֹתוֹ זָהָב טָהוֹר מִבַּיִת וּמִחוּץ תְּצַפֶּנּוּ", en: "You shall overlay it with pure gold; inside and outside you shall overlay it.", hit: "זָהָב" },

  tov: { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "טוֹב" },
  gadol: { ref: "Deut 7:21", he: "כִּי יְהוָה אֱלֹהֶיךָ בְּקִרְבֶּךָ אֵל גָּדוֹל וְנוֹרָא", en: "For YHWH your God is in your midst, a great and fearsome God.", hit: "גָּדוֹל" },
  ra: { ref: "Gen 8:21", he: "כִּי יֵצֶר לֵב הָאָדָם רַע מִנְּעֻרָיו", en: "For the inclination of the human heart is evil from youth.", hit: "רַע" },
  qadosh: { ref: "Lev 19:2", he: "קְדֹשִׁים תִּהְיוּ כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם", en: "You shall be holy, for I, YHWH your God, am holy.", hit: "קָדוֹשׁ" },
  rasha: { ref: "Ps 1:1", he: "אַשְׁרֵי־הָאִישׁ אֲשֶׁר לֹא הָלַךְ בַּעֲצַת רְשָׁעִים", en: "Happy is the one who has not walked in the counsel of the wicked.", hit: "רְשָׁעִים" },
  tsaddiq: { ref: "Ps 1:6", he: "כִּי־יוֹדֵעַ יְהוָה דֶּרֶךְ צַדִּיקִים וְדֶרֶךְ רְשָׁעִים תֹּאבֵד", en: "For YHWH knows the way of the righteous, but the way of the wicked perishes.", hit: "צַדִּיקִים" },
  hakam: { ref: "Prov 1:5", he: "יִשְׁמַע חָכָם וְיוֹסֶף לֶקַח", en: "Let the wise hear and add learning.", hit: "חָכָם" },
  qaton: { ref: "1 Sam 9:21", he: "הֲלוֹא בֶן־יְמִינִי אָנֹכִי מִקַּטַנֵּי שִׁבְטֵי יִשְׂרָאֵל", en: "Am I not a Benjaminite, from the smallest of the tribes of Israel?", hit: "מִקַּטַנֵּי", hitEn: "the smallest" },
  hadash: { ref: "Ezek 36:26", he: "וְנָתַתִּי לָכֶם לֵב חָדָשׁ וְרוּחַ חֲדָשָׁה אֶתֵּן בְּקִרְבְּכֶם", en: "I will give you a new heart, and a new spirit I will put within you.", hit: "חָדָשׁ" },
  hay: { ref: "Deut 5:26", he: "כִּי מִי כָל־בָּשָׂר אֲשֶׁר שָׁמַע קוֹל אֱלֹהִים חַיִּים", en: "For who of all flesh has heard the voice of the living God?", hit: "חַיִּים" },
  rab: { ref: "Gen 6:5", he: "וַיַּרְא יְהוָה כִּי רַבָּה רָעַת הָאָדָם בָּאָרֶץ", en: "YHWH saw that the evil of humankind was great on the earth.", hit: "רַבָּה" },
  zakar: { ref: "Gen 1:27", he: "זָכָר וּנְקֵבָה בָּרָא אֹתָם", en: "Male and female he created them.", hit: "זָכָר" },
  neqebah: { ref: "Gen 1:27", he: "זָכָר וּנְקֵבָה בָּרָא אֹתָם", en: "Male and female he created them.", hit: "וּנְקֵבָה" },
  naar: { ref: "1 Sam 3:1", he: "וְהַנַּעַר שְׁמוּאֵל מְשָׁרֵת אֶת־יְהוָה לִפְנֵי עֵלִי", en: "The boy Samuel was ministering to YHWH before Eli.", hit: "וְהַנַּעַר" },
  adam: { ref: "Gen 1:26", he: "וַיֹּאמֶר אֱלֹהִים נַעֲשֶׂה אָדָם בְּצַלְמֵנוּ כִּדְמוּתֵנוּ", en: "God said, “Let us make humankind in our image, according to our likeness.”", hit: "אָדָם" },
  achot: { ref: "Exod 2:4", he: "וַתֵּתַצַּב אֲחֹתוֹ מֵרָחֹק לְדֵעָה מַה־יֵּעָשֶׂה לוֹ", en: "His sister stood at a distance to know what would be done to him.", hit: "אֲחֹתוֹ" },
  "el-god": { ref: "Gen 33:20", he: "וַיַּצֶּב־שָׁם מִזְבֵּחַ וַיִּקְרָא־לוֹ אֵל אֱלֹהֵי יִשְׂרָאֵל", en: "He set up an altar there and called it El, God of Israel.", hit: "אֵל" },
  naarah: { ref: "2 Kgs 5:2", he: "וַתֵּצֵא נַעֲרָה קְטַנָּה מֵאֶרֶץ יִשְׂרָאֵל", en: "A young girl from the land of Israel went out.", hit: "נַעֲרָה" },
  goy: { ref: "Gen 12:2", he: "וְאֶעֶשְׂךָ לְגוֹי גָּדוֹל וַאֲבָרֶכְךָ וַאֲגַדְּלָה שְׁמֶךָ", en: "I will make you a great nation, and I will bless you and make your name great.", hit: "לְגוֹי" },
  sus: { ref: "Exod 15:1", he: "סוּס וְרֹכְבוֹ רָמָה בַיָּם", en: "Horse and its rider he hurled into the sea.", hit: "סוּס" },
  sefer: { ref: "Josh 1:8", he: "לֹא־יָמוּשׁ סֵפֶר הַתּוֹרָה הַזֶּה מִפִּיךָ", en: "This book of the instruction shall not depart from your mouth.", hit: "סֵפֶר" },
  tsaba: { ref: "Ps 24:10", he: "יְהוָה צְבָאוֹת הוּא מֶלֶךְ הַכָּבוֹד סֶלָה", en: "YHWH of hosts — he is the king of glory.", hit: "צְבָאוֹת" },
  yeled: { ref: "Isa 9:5", he: "כִּי־יֶלֶד יֻלַּד־לָנוּ בֵּן נִתַּן־לָנוּ", en: "For a child is born to us, a son is given to us.", hit: "יֶלֶד" },
  maqom: { ref: "Gen 28:17", he: "וַיִּירָא וַיֹּאמַר מַה־נּוֹרָא הַמָּקוֹם הַזֶּה", en: "He was afraid and said, “How fearsome is this place.”", hit: "הַמָּקוֹם" },
  neum: { ref: "Gen 22:16", he: "וַיֹּאמֶר בִּי נִשְׁבַּעְתִּי נְאֻם־יְהוָה", en: "He said, “By myself I have sworn, declares YHWH.”", hit: "נְאֻם" },
  anan: { ref: "Exod 13:21", he: "וַיהוָה הֹלֵךְ לִפְנֵיהֶם יוֹמָם בְּעַמּוּד עָנָן", en: "YHWH went before them by day in a pillar of cloud.", hit: "עָנָן" },
  sar: { ref: "Exod 2:14", he: "וַיֹּאמֶר מִי שָׂמְךָ לְאִישׁ שַׂר וְשֹׁפֵט עָלֵינוּ", en: "He said, “Who made you a man, a prince and a judge over us?”", hit: "שַׂר" },
  achar: { ref: "Gen 22:13", he: "וְהִנֵּה־אַיִל אַחַר נֶאֱחַז בַּסְּבַךְ בְּקַרְנָיו", en: "And behold, a ram behind, caught in the thicket by its horns.", hit: "אַחַר" },
  "et-with": { ref: "Gen 5:22", he: "וַיִּתְהַלֵּךְ חֲנוֹךְ אֶת־הָאֱלֹהִים אַחֲרֵי הוֹלִידוֹ אֶת־מְתוּשֶׁלַח", en: "Enoch walked with God after he fathered Methuselah.", hit: "אֶת־הָאֱלֹהִים" },
  betokh: { ref: "Gen 2:9", he: "וְעֵץ הַחַיִּים בְּתוֹךְ הַגָּן", en: "And the tree of life in the midst of the garden.", hit: "בְּתוֹךְ" },
  ke: { ref: "Ps 1:3", he: "וְהָיָה כְּעֵץ שָׁתוּל עַל־פַּלְגֵי מָיִם", en: "He is like a tree planted by streams of water.", hit: "כְּעֵץ" },
  lemaan: { ref: "Ps 23:3", he: "נַפְשִׁי יְשׁוֹבֵב יַנְחֵנִי בְמַעְגְּלֵי־צֶדֶק לְמַעַן שְׁמוֹ", en: "He restores my soul; he leads me in paths of righteousness for his name’s sake.", hit: "לְמַעַן", hitEn: "for his name’s sake" },
  maal: { ref: "Deut 28:13", he: "וּנְתָנְךָ יְהוָה לְרֹאשׁ וְלֹא לְזָנָב וְהָיִיתָ רַק לְמַעְלָה", en: "YHWH will make you the head and not the tail, and you shall be only above.", hit: "לְמַעְלָה" },
  ever: { ref: "Deut 1:1", he: "אֵלֶּה הַדְּבָרִים אֲשֶׁר דִּבֶּר מֹשֶׁה אֶל־כָּל־יִשְׂרָאֵל בְּעֵבֶר הַיַּרְדֵּן", en: "These are the words Moses spoke to all Israel beyond the Jordan.", hit: "בְּעֵבֶר" },
  "raah-evil": { ref: "Gen 19:19", he: "פֶּן־תִּדְבָּקַנִי הָרָעָה וָמַתִּי", en: "lest the disaster overtake me and I die.", hit: "הָרָעָה" },
  zar: { ref: "Exod 29:33", he: "וְזָר לֹא־יֹאכַל בָּם כִּי־קֹדֶשׁ הֵם", en: "A stranger shall not eat of them, for they are holy.", hit: "וְזָר" },
  yashar: { ref: "Ps 25:8", he: "טוֹב־וְיָשָׁר יְהוָה עַל־כֵּן יוֹרֶה חַטָּאִים בַּדָּרֶךְ", en: "Good and upright is YHWH; therefore he instructs sinners in the way.", hit: "וְיָשָׁר" },
  meat: { ref: "Deut 7:7", he: "כִּי אַתֶּם הַמְעַט מִכָּל־הָעַמִּים", en: "For you are the fewest of all the peoples.", hit: "הַמְעַט", hitEn: "the fewest" },
  qarov: { ref: "Ps 34:19", he: "קָרוֹב יְהוָה לְנִשְׁבְּרֵי־לֵב", en: "YHWH is near to the brokenhearted.", hit: "קָרוֹב" },
  rachoq: { ref: "Prov 15:29", he: "רָחוֹק יְהוָה מֵרְשָׁעִים וּתְפִלַּת צַדִּיקִים יִשְׁמָע", en: "YHWH is far from the wicked, but the prayer of the righteous he hears.", hit: "רָחוֹק" },
  meod: { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד", en: "God saw all that he had made, and behold, it was very good.", hit: "מְאֹד" },
  "ha-int": { ref: "Gen 4:9", he: "וַיֹּאמֶר קַיִן אֶל־יְהוָה הֲשֹׁמֵר אָחִי אָנֹכִי", en: "Cain said to YHWH, “Am I my brother’s keeper?”", hit: "הֲשֹׁמֵר", hitEn: "Am I" },
  maddua: { ref: "Gen 26:27", he: "וַיֹּאמֶר אֲלֵהֶם יִצְחָק מַדּוּעַ בָּאתֶם אֵלָי", en: "Isaac said to them, “Why have you come to me?”", hit: "מַדּוּעַ" },
  acher: { ref: "Exod 20:3", he: "לֹא יִהְיֶה־לְךָ אֱלֹהִים אֲחֵרִים עַל־פָּנָיַ", en: "You shall not have other gods before me.", hit: "אֲחֵרִים" },
  she: { ref: "Eccl 1:9", he: "מַה־שֶּׁהָיָה הוּא שֶׁיִּהְיֶה", en: "What has been is what will be.", hit: "שֶּׁהָיָה", hitEn: "What has been" },
  aph: { ref: "Exod 4:14", he: "וַיִּחַר־אַף יְהוָה בְּמֹשֶׁה", en: "And the anger of YHWH burned against Moses.", hit: "אַף" },
  baqar: { ref: "Gen 18:7", he: "וְאֶל־הַבָּקָר רָץ אַבְרָהָם וַיִּקַּח בֶּן־בָּקָר רַךְ וָטוֹב", en: "Abraham ran to the herd and took a tender and good calf.", hit: "הַבָּקָר" },
  boqer: { ref: "Gen 1:5", he: "וַיְהִי־עֶרֶב וַיְהִי־בֹקֶר יוֹם אֶחָד", en: "There was evening and there was morning, one day.", hit: "בֹקֶר" },
  berakah: { ref: "Deut 11:26", he: "רְאֵה אָנֹכִי נֹתֵן לִפְנֵיכֶם הַיּוֹם בְּרָכָה וּקְלָלָה", en: "See, I am setting before you today a blessing and a curse.", hit: "בְּרָכָה" },
  keli: { ref: "Gen 24:53", he: "וַיּוֹצֵא הָעֶבֶד כְּלֵי־כֶסֶף וּכְלֵי זָהָב וּבְגָדִים", en: "The servant brought out vessels of silver and vessels of gold and garments.", hit: "כְּלֵי" },
  mishpahah: { ref: "Gen 12:3", he: "וְנִבְרְכוּ בְךָ כֹּל מִשְׁפְּחֹת הָאֲדָמָה", en: "And in you all the families of the earth shall be blessed.", hit: "מִשְׁפְּחֹת" },
  hen: { ref: "Gen 3:22", he: "וַיֹּאמֶר יְהוָה אֱלֹהִים הֵן הָאָדָם הָיָה כְּאַחַד מִמֶּנּוּ", en: "YHWH God said, “Behold, the human has become like one of us.”", hit: "הֵן" },
  levad: { ref: "Gen 2:18", he: "וַיֹּאמֶר יְהוָה אֱלֹהִים לֹא־טוֹב הֱיוֹת הָאָדָם לְבַדּוֹ", en: "YHWH God said, “It is not good for the human to be alone.”", hit: "לְבַדּוֹ" },
  saviv: { ref: "Exod 19:12", he: "וְהִגְבַּלְתָּ אֶת־הָעָם סָבִיב לֵאמֹר", en: "You shall set bounds for the people all around, saying.", hit: "סָבִיב" },
  eben: { ref: "Ps 118:22", he: "אֶבֶן מָאֲסוּ הַבּוֹנִים הָיְתָה לְרֹאשׁ פִּנָּה", en: "The stone the builders rejected has become the head of the corner.", hit: "אֶבֶן" },
  oyeb: { ref: "Exod 15:6", he: "יְמִינְךָ יְהוָה נֶאְדָּרִי בַּכֹּחַ יְמִינְךָ יְהוָה תִּרְעַץ אוֹיֵב", en: "Your right hand, YHWH, glorious in power; your right hand, YHWH, shatters the enemy.", hit: "אוֹיֵב" },
  gebul: { ref: "Deut 19:14", he: "לֹא תַסִּיג גְּבוּל רֵעֲךָ אֲשֶׁר גָּבְלוּ רִאשֹׁנִים", en: "You shall not move your neighbor’s boundary, which the first ones set.", hit: "גְּבוּל" },
  hayil: { ref: "Exod 18:21", he: "וְאַתָּה תֶחֱזֶה מִכָּל־הָעָם אַנְשֵׁי־חַיִל יִרְאֵי אֱלֹהִים", en: "You shall look out from all the people men of valor who fear God.", hit: "חַיִל" },
  matteh: { ref: "Exod 4:2", he: "וַיֹּאמֶר אֵלָיו יְהוָה מַה־זֶּה בְיָדֶךָ וַיֹּאמֶר מַטֶּה", en: "YHWH said to him, “What is that in your hand?” And he said, “A staff.”", hit: "מַטֶּה" },
  olah: { ref: "Lev 1:3", he: "אִם־עֹלָה קָרְבָּנוֹ מִן־הַבָּקָר זָכָר תָּמִים יַקְרִיבֶנּוּ", en: "If his offering is a burnt offering from the herd, he shall offer a male without blemish.", hit: "עֹלָה" },
  tson: { ref: "Exod 3:1", he: "וּמֹשֶׁה הָיָה רֹעֶה אֶת־צֹאן יִתְרוֹ חֹתְנוֹ", en: "Moses was shepherding the flock of Jethro his father-in-law.", hit: "צֹאן" },
  regel: { ref: "Exod 3:5", he: "וַיֹּאמֶר אַל־תִּקְרַב הֲלֹם שַׁל־נְעָלֶיךָ מֵעַל רַגְלֶיךָ", en: "He said, “Do not come near; take your sandals off your feet.”", hit: "רַגְלֶיךָ" },
  ammah: { ref: "Gen 6:15", he: "שְׁלֹשׁ מֵאוֹת אַמָּה אֹרֶךְ הַתֵּבָה חֲמִשִּׁים אַמָּה רָחְבָּהּ", en: "Three hundred cubits the length of the ark, fifty cubits its width.", hit: "אַמָּה" },
  orek: { ref: "Exod 26:2", he: "אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁמֹנֶה וְעֶשְׂרִים בָּאַמָּה", en: "The length of each curtain is twenty-eight cubits.", hit: "אֹרֶךְ" },
  hatsi: { ref: "Exod 25:10", he: "אַמָּתַיִם וָחֵצִי אָרְכּוֹ וְאַמָּה וָחֵצִי רָחְבּוֹ", en: "Two cubits and a half its length, and a cubit and a half its width.", hit: "וָחֵצִי" },
  rohab: { ref: "Exod 26:2", he: "וְרֹחַב אַרְבַּע בָּאַמָּה הַיְרִיעָה הָאֶחָת", en: "And the width of each curtain is four cubits.", hit: "וְרֹחַב" },
  shemoneh: { ref: "Exod 26:2", he: "אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁמֹנֶה וְעֶשְׂרִים בָּאַמָּה", en: "The length of each curtain is twenty-eight cubits.", hit: "שְׁמֹנֶה" },
  tesha: { ref: "Deut 3:11", he: "תֵּשַׁע אַמּוֹת אָרְכָּהּ וְאַרְבַּע אַמּוֹת רָחְבָּהּ", en: "Nine cubits its length and four cubits its width.", hit: "תֵּשַׁע" },
  rishon: { ref: "Isa 41:4", he: "אֲנִי יְהוָה רִאשׁוֹן וְאֶת־אַחֲרֹנִים אֲנִי־הוּא", en: "I, YHWH, am the first, and with the last I am he.", hit: "רִאשׁוֹן" },
  sheni: { ref: "Gen 1:8", he: "וַיְהִי־עֶרֶב וַיְהִי־בֹקֶר יוֹם שֵׁנִי", en: "There was evening and there was morning, a second day.", hit: "שֵׁנִי" },
  shelishi: { ref: "Gen 1:13", he: "וַיְהִי־עֶרֶב וַיְהִי־בֹקֶר יוֹם שְׁלִישִׁי", en: "There was evening and there was morning, a third day.", hit: "שְׁלִישִׁי" },
  shebii: { ref: "Gen 2:2", he: "וַיְכַל אֱלֹהִים בַּיּוֹם הַשְּׁבִיעִי מְלַאכְתּוֹ אֲשֶׁר עָשָׂה", en: "God finished on the seventh day his work that he had done.", hit: "הַשְּׁבִיעִי" },
  ak: { ref: "Gen 9:4", he: "אַךְ־בָּשָׂר בְּנַפְשׁוֹ דָמוֹ לֹא תֹאכֵלוּ", en: "Only flesh with its life, its blood, you shall not eat.", hit: "אַךְ" },
  bal: { ref: "Ps 16:8", he: "שִׁוִּיתִי יְהוָה לְנֶגְדִּי תָמִיד כִּי מִימִינִי בַּל־אֶמּוֹט", en: "I have set YHWH before me continually; because he is at my right hand, I shall not be shaken.", hit: "בַּל" },
  tamid: { ref: "Exod 25:30", he: "וְנָתַתָּ עַל־הַשֻּׁלְחָן לֶחֶם פָּנִים לְפָנַי תָּמִיד", en: "You shall set the bread of the Presence on the table before me continually.", hit: "תָּמִיד" },
  "zakar-v": { ref: "Exod 20:8", he: "זָכוֹר אֶת־יוֹם הַשַּׁבָּת לְקַדְּשׁוֹ", en: "Remember the sabbath day, to keep it holy.", hit: "זָכוֹר" },
  kaved: { ref: "Exod 20:12", he: "כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ", en: "Honor your father and your mother.", hit: "כַּבֵּד" },
  koh: { ref: "Exod 4:22", he: "וְאָמַרְתָּ אֶל־פַּרְעֹה כֹּה אָמַר יְהוָה", en: "You shall say to Pharaoh, “Thus says YHWH.”", hit: "כֹּה" },
  sim: { ref: "Gen 4:15", he: "וַיָּשֶׂם יְהוָה לְקַיִן אוֹת לְבִלְתִּי הַכּוֹת־אֹתוֹ כָּל־מֹצְאוֹ", en: "YHWH put a mark on Cain, so that no one who found him would strike him.", hit: "וַיָּשֶׂם" },
  poh: { ref: "Gen 19:12", he: "וַיֹּאמְרוּ הָאֲנָשִׁים אֶל־לוֹט עֹד מִי־לְךָ פֹה", en: "The men said to Lot, “Whom else do you have here?”", hit: "פֹה" },
  "hayah-live": { ref: "Deut 8:3", he: "כִּי לֹא עַל־הַלֶּחֶם לְבַדּוֹ יִחְיֶה הָאָדָם", en: "For not by bread alone shall the human live.", hit: "יִחְיֶה" },
  sur: { ref: "Exod 32:8", he: "סָרוּ מַהֵר מִן־הַדֶּרֶךְ אֲשֶׁר צִוִּיתִם", en: "They have turned aside quickly from the way that I commanded them.", hit: "סָרוּ" },
  ozen: { ref: "Ps 34:16", he: "עֵינֵי יְהוָה אֶל־צַדִּיקִים וְאָזְנָיו אֶל־שַׁוְעָתָם", en: "The eyes of YHWH are toward the righteous, and his ears toward their cry.", hit: "וְאָזְנָיו" },
  ayil: { ref: "Gen 22:13", he: "וַיִּשָּׂא אַבְרָהָם אֶת־עֵינָיו וַיַּרְא וְהִנֵּה־אַיִל אַחַר נֶאֱחַז בַּסְּבַךְ בְּקַרְנָיו", en: "Abraham lifted his eyes and looked, and behold, a ram behind, caught in the thicket by its horns.", hit: "אַיִל" },
  zebah: { ref: "Lev 3:1", he: "וְאִם־זֶבַח שְׁלָמִים קָרְבָּנוֹ אִם מִן־הַבָּקָר הוּא מַקְרִיב", en: "If his offering is a sacrifice of peace offerings, if he offers it from the herd.", hit: "זֶבַח" },
  tsaphon: { ref: "Jer 1:14", he: "מִצָּפוֹן תִּפָּתַח הָרָעָה עַל כָּל־יֹשְׁבֵי הָאָרֶץ", en: "From the north disaster will be opened on all the inhabitants of the land.", hit: "מִצָּפוֹן" },
  az: { ref: "Gen 4:26", he: "אָז הוּחַל לִקְרֹא בְּשֵׁם יְהוָה", en: "Then people began to call on the name of YHWH.", hit: "אָז" },
  "aph-also": { ref: "Gen 40:16", he: "וַיֹּאמֶר אֶל־יוֹסֵף אַף־אֲנִי בַּחֲלוֹמִי", en: "He said to Joseph, “I also was in my dream.”", hit: "אַף" },
  gibbor: { ref: "Ps 24:8", he: "מִי זֶה מֶלֶךְ הַכָּבוֹד יְהוָה עִזּוּז וְגִבּוֹר", en: "Who is this king of glory? YHWH, strong and mighty.", hit: "וְגִבּוֹר" },
  pen: { ref: "Gen 3:3", he: "לֹא תֹאכְלוּ מִמֶּנּוּ וְלֹא תִגְּעוּ בּוֹ פֶּן־תְּמֻתוּן", en: "You shall not eat from it, nor touch it, lest you die.", hit: "פֶּן" },
  natah: { ref: "Exod 9:22", he: "וַיֹּאמֶר יְהוָה אֶל־מֹשֶׁה נְטֵה אֶת־יָדְךָ עַל־הַשָּׁמַיִם וִיהִי בָרָד", en: "YHWH said to Moses, “Stretch out your hand toward the heavens, that there may be hail.”", hit: "נְטֵה" },
  kaph: { ref: "Ps 24:4", he: "נְקִי כַפַּיִם וּבַר־לֵבָב", en: "The one clean of palms and pure of heart.", hit: "כַפַּיִם" },
  rea: { ref: "Lev 19:18", he: "וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ", en: "You shall love your neighbor as yourself.", hit: "לְרֵעֲךָ" },
  neged: { ref: "Exod 19:2", he: "וַיִּחַן־שָׁם יִשְׂרָאֵל נֶגֶד הָהָר", en: "Israel camped there in front of the mountain.", hit: "נֶגֶד" },
  "abad-perish": { ref: "Ps 1:6", he: "כִּי־יוֹדֵעַ יְהוָה דֶּרֶךְ צַדִּיקִים וְדֶרֶךְ רְשָׁעִים תֹּאבֵד", en: "For YHWH knows the way of the righteous, but the way of the wicked perishes.", hit: "תֹּאבֵד" },
  rum: { ref: "Exod 17:11", he: "וְהָיָה כַּאֲשֶׁר יָרִים מֹשֶׁה יָדוֹ וְגָבַר יִשְׂרָאֵל", en: "Whenever Moses would raise his hand, Israel prevailed.", hit: "יָרִים" },
  kisse: { ref: "Isa 6:1", he: "וָאֶרְאֶה אֶת־אֲדֹנָי יֹשֵׁב עַל־כִּסֵּא רָם וְנִשָּׂא", en: "I saw the Lord sitting on a throne, high and lifted up.", hit: "כִּסֵּא" },
  mispar: { ref: "Ps 147:4", he: "מוֹנֶה מִסְפָּר לַכּוֹכָבִים לְכֻלָּם שֵׁמוֹת יִקְרָא", en: "He counts the number of the stars; he calls them all by names.", hit: "מִסְפָּר" },
  shemesh: { ref: "Gen 15:12", he: "וַיְהִי הַשֶּׁמֶשׁ לָבוֹא וְתַרְדֵּמָה נָפְלָה עַל־אַבְרָם", en: "As the sun was going down, a deep sleep fell upon Abram.", hit: "הַשֶּׁמֶשׁ" },
  "raah-pasture": { ref: "Ps 23:1", he: "מִזְמוֹר לְדָוִד יְהוָה רֹעִי לֹא אֶחְסָר", en: "A psalm of David. YHWH is my shepherd; I shall not lack.", hit: "רֹעִי" },
  baal: { ref: "Exod 21:3", he: "אִם־בְּעַל אִשָּׁה הוּא וְיָצְאָה אִשְׁתּוֹ עִמּוֹ", en: "If he is the husband of a wife, then his wife shall go out with him.", hit: "בְּעַל" },
  shebet: { ref: "Gen 49:10", he: "לֹא־יָסוּר שֵׁבֶט מִיהוּדָה וּמְחֹקֵק מִבֵּין רַגְלָיו", en: "The scepter shall not depart from Judah, nor the ruler’s staff from between his feet.", hit: "שֵׁבֶט" },
  baad: { ref: "Gen 7:16", he: "וַיִּסְגֹּר יְהוָה בַּעֲדוֹ", en: "And YHWH shut him in.", hit: "בַּעֲדוֹ", hitEn: "shut him in" },
  yaan: { ref: "Num 20:12", he: "וַיֹּאמֶר יְהוָה אֶל־מֹשֶׁה וְאֶל־אַהֲרֹן יַעַן לֹא־הֶאֱמַנְתֶּם בִּי", en: "YHWH said to Moses and to Aaron, “Because you did not trust in me.”", hit: "יַעַן" },
  saraf: { ref: "Exod 32:20", he: "וַיִּקַּח אֶת־הָעֵגֶל אֲשֶׁר עָשׂוּ וַיִּשְׂרֹף בָּאֵשׁ", en: "He took the calf that they had made and burned it with fire.", hit: "וַיִּשְׂרֹף" },
  dor: { ref: "Ps 145:4", he: "דּוֹר לְדוֹר יְשַׁבַּח מַעֲשֶׂיךָ וּגְבוּרֹתֶיךָ יַגִּידוּ", en: "Generation to generation will praise your works, and they will declare your mighty acts.", hit: "דּוֹר" },
  huts: { ref: "Exod 33:7", he: "וּמֹשֶׁה יִקַּח אֶת־הָאֹהֶל וְנָטָה־לוֹ מִחוּץ לַמַּחֲנֶה", en: "Moses would take the tent and pitch it outside the camp.", hit: "מִחוּץ" },
  melakah: { ref: "Exod 20:9", he: "שֵׁשֶׁת יָמִים תַּעֲבֹד וְעָשִׂיתָ כָּל־מְלַאכְתֶּךָ", en: "Six days you shall labor and do all your work.", hit: "מְלַאכְתֶּךָ" },
  avon: { ref: "Exod 34:7", he: "נֹצֵר חֶסֶד לָאֲלָפִים נֹשֵׂא עָוֹן וָפֶשַׁע וְחַטָּאָה", en: "Keeping loyalty for thousands, forgiving iniquity and transgression and sin.", hit: "עָוֹן" },
  par: { ref: "Exod 29:1", he: "לְקַח פַּר אֶחָד בֶּן־בָּקָר וְאֵילִם שְׁנַיִם תְּמִימִם", en: "Take one bull, a son of the herd, and two rams without blemish.", hit: "פַּר" },
  petah: { ref: "Gen 4:7", he: "וְאִם לֹא תֵיטִיב לַפֶּתַח חַטָּאת רֹבֵץ", en: "And if you do not do well, sin is crouching at the door.", hit: "לַפֶּתַח" },
  rob: { ref: "Ps 5:8", he: "וַאֲנִי בְּרֹב חַסְדְּךָ אָבוֹא בֵיתֶךָ", en: "But I, in the abundance of your loyalty, will enter your house.", hit: "בְּרֹב" },
  safah: { ref: "Gen 11:1", he: "וַיְהִי כָל־הָאָרֶץ שָׂפָה אֶחָת וּדְבָרִים אֲחָדִים", en: "Now all the earth was one language and the same words.", hit: "שָׂפָה" },

  we: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "וְ" },
  ha: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "הַשָּׁמַיִם", hitEn: "the heavens" },
  lo: { ref: "Exod 20:3", he: "לֹא יִהְיֶה־לְךָ אֱלֹהִים אֲחֵרִים עַל־פָּנָיַ", en: "You shall not have other gods before me.", hit: "לֹא" },
  kol: { ref: "Gen 1:31", he: "וַיַּרְא אֱלֹהִים אֶת־כָּל־אֲשֶׁר עָשָׂה וְהִנֵּה־טוֹב מְאֹד", en: "God saw all that he had made, and behold, it was very good.", hit: "כָּל" },
  asher: { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ אֲשֶׁר הוֹצֵאתִיךָ מֵאֶרֶץ מִצְרַיִם", en: "I am YHWH your God, who brought you out from the land of Egypt.", hit: "אֲשֶׁר" },
  ki: { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "כִּי" },
  le: { ref: "Gen 1:5", he: "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם", en: "God called the light Day.", hit: "לָאוֹר", hitEn: "the light" },
  be: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "בְּרֵאשִׁית", hitEn: "In the beginning" },
  et: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "אֵת" },
  min: { ref: "Gen 2:7", he: "וַיִּיצֶר יְהוָה אֱלֹהִים אֶת־הָאָדָם עָפָר מִן־הָאֲדָמָה", en: "YHWH God formed the human of dust from the ground.", hit: "מִן" },
  al: { ref: "Gen 1:2", he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם", en: "And the spirit of God was hovering over the face of the waters.", hit: "עַל" },
  el: { ref: "Gen 4:8", he: "וַיֹּאמֶר קַיִן אֶל־הֶבֶל אָחִיו", en: "Cain spoke to Abel his brother.", hit: "אֶל" },
  im: { ref: "Exod 17:8", he: "וַיָּבֹא עֲמָלֵק וַיִּלָּחֶם עִם־יִשְׂרָאֵל בִּרְפִידִם", en: "Amalek came and fought with Israel at Rephidim.", hit: "עִם" },
  ad: { ref: "Gen 8:5", he: "וְהַמַּיִם הָיוּ הָלוֹךְ וְחָסוֹר עַד הַחֹדֶשׁ הָעֲשִׂירִי", en: "The waters were going and receding until the tenth month.", hit: "עַד" },
  gam: { ref: "Gen 3:6", he: "וַתִּתֵּן גַּם־לְאִישָׁהּ עִמָּהּ וַיֹּאכַל", en: "She also gave some to her husband with her, and he ate.", hit: "גַּם" },
  tahat: { ref: "Exod 24:4", he: "וַיִּבֶן מִזְבֵּחַ תַּחַת הָהָר", en: "He built an altar at the foot of the mountain.", hit: "תַּחַת", hitEn: "the foot" },
  lifne: { ref: "Gen 18:22", he: "וְאַבְרָהָם עוֹדֶנּוּ עֹמֵד לִפְנֵי יְהוָה", en: "Abraham was still standing before YHWH.", hit: "לִפְנֵי" },
  "ben-prep": { ref: "Gen 1:4", he: "וַיַּבְדֵּל אֱלֹהִים בֵּין הָאוֹר וּבֵין הַחֹשֶׁךְ", en: "God separated between the light and the darkness.", hit: "בֵּין" },
  hinneh: { ref: "Gen 22:1", he: "וַיֹּאמֶר אֵלָיו אַבְרָהָם וַיֹּאמֶר הִנֵּנִי", en: "He said to him, “Abraham,” and he said, “Here I am.”", hit: "הִנֵּנִי" },
  "attah-now": { ref: "Exod 19:5", he: "וְעַתָּה אִם־שָׁמוֹעַ תִּשְׁמְעוּ בְּקֹלִי", en: "And now, if you will surely listen to my voice.", hit: "וְעַתָּה" },
  sham: { ref: "Gen 2:8", he: "וַיָּשֶׂם שָׁם אֶת־הָאָדָם אֲשֶׁר יָצָר", en: "He placed there the human he had formed.", hit: "שָׁם" },
  mah: { ref: "Gen 4:10", he: "וַיֹּאמֶר מֶה עָשִׂיתָ", en: "He said, “What have you done?”", hit: "מֶה" },
  mi: { ref: "Exod 3:11", he: "מִי אָנֹכִי כִּי אֵלֵךְ אֶל־פַּרְעֹה", en: "Who am I, that I should go to Pharaoh?", hit: "מִי" },
  ein: { ref: "Exod 5:10", he: "אֵין נִתָּן תֶּבֶן לַעֲבָדֵיכֶם", en: "No straw is given to your servants.", hit: "אֵין", hitEn: "No" },
  yesh: { ref: "Gen 18:24", he: "אוּלַי יֵשׁ חֲמִשִּׁים צַדִּיקִם בְּתוֹךְ הָעִיר", en: "Suppose there are fifty righteous in the city.", hit: "יֵשׁ" },
  od: { ref: "Gen 8:10", he: "וַיָּחֶל עוֹד שִׁבְעַת יָמִים אֲחֵרִים", en: "He waited still another seven days.", hit: "עוֹד" },
  raq: { ref: "Gen 6:5", he: "וְכָל־יֵצֶר מַחְשְׁבֹת לִבּוֹ רַק רַע כָּל־הַיּוֹם", en: "Every inclination of the thoughts of his heart was only evil all the day.", hit: "רַק" },
  "im-if": { ref: "Exod 19:5", he: "וְעַתָּה אִם־שָׁמוֹעַ תִּשְׁמְעוּ בְּקֹלִי", en: "And now, if you will surely listen to my voice.", hit: "אִם" },
  "al-neg": { ref: "Exod 20:19", he: "אַל־יְדַבֵּר עִמָּנוּ אֱלֹהִים פֶּן־נָמוּת", en: "Do not let God speak with us, lest we die.", hit: "אַל" },
  na: { ref: "Gen 22:2", he: "קַח־נָא אֶת־בִּנְךָ אֶת־יְחִידְךָ", en: "Take, please, your son, your only one.", hit: "נָא" },
  o: { ref: "Exod 21:33", he: "וְכִי־יִפְתַּח אִישׁ בּוֹר אוֹ כִּי־יִכְרֶה אִישׁ בֹּר", en: "If a man opens a pit, or if a man digs a pit.", hit: "אוֹ" },
  ken: { ref: "Gen 1:7", he: "וַיְהִי־כֵן", en: "And it was so.", hit: "כֵן" },
  lama: { ref: "Exod 5:22", he: "לָמָה זֶה שְׁלַחְתָּנִי", en: "Why have you sent me?", hit: "לָמָה" },
  ani: { ref: "Gen 6:17", he: "וַאֲנִי הִנְנִי מֵבִיא אֶת־הַמַּבּוּל מַיִם עַל־הָאָרֶץ", en: "And I, behold, I am bringing the flood of water upon the earth.", hit: "וַאֲנִי" },
  anoki: { ref: "Exod 20:2", he: "אָנֹכִי יְהוָה אֱלֹהֶיךָ", en: "I am YHWH your God.", hit: "אָנֹכִי" },
  attah: { ref: "Gen 3:19", he: "כִּי־עָפָר אַתָּה וְאֶל־עָפָר תָּשׁוּב", en: "For dust you are, and to dust you shall return.", hit: "אַתָּה" },
  at: { ref: "Gen 24:23", he: "בַּת־מִי אַתְּ הַגִּידִי נָא לִי", en: "Whose daughter are you? Please tell me.", hit: "אַתְּ" },
  hu: { ref: "Deut 4:35", he: "יְהוָה הוּא הָאֱלֹהִים אֵין עוֹד מִלְבַדּוֹ", en: "YHWH, he is God; there is no other besides him.", hit: "הוּא" },
  hi: { ref: "Exod 1:16", he: "אִם־בֵּן הוּא וַהֲמִתֶּן אֹתוֹ וְאִם־בַּת הִיא וָחָיָה", en: "If it is a son, you shall kill him; but if it is a daughter, she shall live.", hit: "הִיא" },
  anahnu: { ref: "Exod 10:26", he: "וַאֲנַחְנוּ לֹא־נֵדַע מַה־נַּעֲבֹד אֶת־יְהוָה", en: "And we do not know with what we shall serve YHWH.", hit: "וַאֲנַחְנוּ" },
  attem: { ref: "Deut 4:4", he: "וְאַתֶּם הַדְּבֵקִים בַּיהוָה אֱלֹהֵיכֶם חַיִּים כֻּלְּכֶם הַיּוֹם", en: "But you who clung to YHWH your God are alive, all of you, today.", hit: "וְאַתֶּם" },
  hem: { ref: "Exod 5:8", he: "כִּי־נִרְפִּים הֵם עַל־כֵּן הֵם צֹעֲקִים", en: "For they are idle; that is why they are crying out.", hit: "הֵם" },
  zeh: { ref: "Exod 3:15", he: "זֶה־שְּׁמִי לְעֹלָם וְזֶה זִכְרִי לְדֹר דֹּר", en: "This is my name forever, and this is my memorial from generation to generation.", hit: "זֶה" },
  zot: { ref: "Gen 2:23", he: "זֹאת הַפַּעַם עֶצֶם מֵעֲצָמַי", en: "This time, bone from my bones.", hit: "זֹאת" },
  elleh: { ref: "Gen 2:4", he: "אֵלֶּה תוֹלְדוֹת הַשָּׁמַיִם וְהָאָרֶץ בְּהִבָּרְאָם", en: "These are the generations of the heavens and the earth when they were created.", hit: "אֵלֶּה" },

  shamayim: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "הַשָּׁמַיִם" },
  mayim: { ref: "Gen 1:2", he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם", en: "And the spirit of God was hovering over the face of the waters.", hit: "הַמָּיִם" },
  ruah: { ref: "Gen 1:2", he: "וְרוּחַ אֱלֹהִים מְרַחֶפֶת עַל־פְּנֵי הַמָּיִם", en: "And the spirit of God was hovering over the face of the waters.", hit: "וְרוּחַ" },
  nephesh: { ref: "Gen 2:7", he: "וַיְהִי הָאָדָם לְנֶפֶשׁ חַיָּה", en: "And the human became a living person.", hit: "לְנֶפֶשׁ" },
  leb: { ref: "Deut 6:5", he: "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל־לְבָבְךָ", en: "You shall love YHWH your God with all your heart.", hit: "לְבָבְךָ" },
  yad: { ref: "Exod 6:1", he: "עַתָּה תִרְאֶה אֲשֶׁר אֶעֱשֶׂה לְפַרְעֹה כִּי בְּיָד חֲזָקָה יְשַׁלְּחֵם", en: "Now you will see what I will do to Pharaoh: by a strong hand he will send them out.", hit: "בְּיָד" },
  ayin: { ref: "Ps 33:18", he: "הִנֵּה עֵין יְהוָה אֶל־יְרֵאָיו", en: "Behold, the eye of YHWH is toward those who fear him.", hit: "עֵין" },
  peh: { ref: "Deut 8:3", he: "כִּי לֹא עַל־הַלֶּחֶם לְבַדּוֹ יִחְיֶה הָאָדָם כִּי עַל־כָּל־מוֹצָא פִי־יְהוָה", en: "A human does not live on bread alone, but on every going-out of the mouth of YHWH.", hit: "פִי" },
  qol: { ref: "Gen 3:8", he: "וַיִּשְׁמְעוּ אֶת־קוֹל יְהוָה אֱלֹהִים מִתְהַלֵּךְ בַּגָּן", en: "They heard the sound of YHWH God walking in the garden.", hit: "קוֹל" },
  derek: { ref: "Ps 1:6", he: "כִּי־יוֹדֵעַ יְהוָה דֶּרֶךְ צַדִּיקִים", en: "For YHWH knows the way of the righteous.", hit: "דֶּרֶךְ" },
  har: { ref: "Exod 19:3", he: "וּמֹשֶׁה עָלָה אֶל־הָאֱלֹהִים וַיִּקְרָא אֵלָיו יְהוָה מִן־הָהָר", en: "Moses went up to God, and YHWH called to him from the mountain.", hit: "הָהָר" },
  midbar: { ref: "Exod 3:1", he: "וַיִּנְהַג אֶת־הַצֹּאן אַחַר הַמִּדְבָּר", en: "He led the flock to the far side of the wilderness.", hit: "הַמִּדְבָּר" },
  ets: { ref: "Gen 2:9", he: "וַיַּצְמַח יְהוָה אֱלֹהִים מִן־הָאֲדָמָה כָּל־עֵץ נֶחְמָד לְמַרְאֶה", en: "YHWH God caused to spring up from the ground every tree pleasant to the sight.", hit: "עֵץ" },
  lehem: { ref: "Exod 16:4", he: "הִנְנִי מַמְטִיר לָכֶם לֶחֶם מִן־הַשָּׁמָיִם", en: "I am about to rain down for you bread from heaven.", hit: "לֶחֶם" },
  basar: { ref: "Gen 2:23", he: "עֶצֶם מֵעֲצָמַי וּבָשָׂר מִבְּשָׂרִי", en: "Bone from my bones, and flesh from my flesh.", hit: "וּבָשָׂר" },
  dam: { ref: "Gen 9:6", he: "שֹׁפֵךְ דַּם הָאָדָם בָּאָדָם דָּמוֹ יִשָּׁפֵךְ", en: "Whoever sheds the blood of a human, by a human shall that one’s blood be shed.", hit: "דַּם" },
  kohen: { ref: "Exod 28:1", he: "וְאַתָּה הַקְרֵב אֵלֶיךָ אֶת־אַהֲרֹן אָחִיךָ ... לְכַהֲנוֹ־לִי", en: "Bring near to yourself Aaron your brother … to serve as priest to me.", hit: "לְכַהֲנוֹ" },
  nabi: { ref: "Deut 18:15", he: "נָבִיא מִקִּרְבְּךָ מֵאַחֶיךָ כָּמֹנִי יָקִים לְךָ יְהוָה אֱלֹהֶיךָ", en: "A prophet from your midst, from your brothers, like me, YHWH your God will raise up for you.", hit: "נָבִיא" },
  mizbeah: { ref: "Gen 8:20", he: "וַיִּבֶן נֹחַ מִזְבֵּחַ לַיהוָה", en: "Noah built an altar to YHWH.", hit: "מִזְבֵּחַ" },
  ohel: { ref: "Exod 33:7", he: "וּמֹשֶׁה יִקַּח אֶת־הָאֹהֶל וְנָטָה־לוֹ מִחוּץ לַמַּחֲנֶה", en: "Moses would take the tent and pitch it outside the camp.", hit: "הָאֹהֶל" },

  shalom: { ref: "Num 6:26", he: "יִשָּׂא יְהוָה פָּנָיו אֵלֶיךָ וְיָשֵׂם לְךָ שָׁלוֹם", en: "YHWH lift his face toward you and set peace for you.", hit: "שָׁלוֹם" },
  hesed: { ref: "Exod 34:6", he: "יְהוָה יְהוָה אֵל רַחוּם וְחַנּוּן אֶרֶךְ אַפַּיִם וְרַב־חֶסֶד וֶאֱמֶת", en: "YHWH, YHWH, a God compassionate and gracious, slow to anger, and abundant in loyalty and faithfulness.", hit: "חֶסֶד" },
  emet: { ref: "Exod 34:6", he: "יְהוָה יְהוָה אֵל רַחוּם וְחַנּוּן אֶרֶךְ אַפַּיִם וְרַב־חֶסֶד וֶאֱמֶת", en: "YHWH, YHWH, a God compassionate and gracious, slow to anger, and abundant in loyalty and faithfulness.", hit: "וֶאֱמֶת" },
  mishpat: { ref: "Mic 6:8", he: "עֲשׂוֹת מִשְׁפָּט וְאַהֲבַת חֶסֶד וְהַצְנֵעַ לֶכֶת עִם־אֱלֹהֶיךָ", en: "To do justice, to love loyalty, and to walk humbly with your God.", hit: "מִשְׁפָּט" },
  tsedaqah: { ref: "Gen 15:6", he: "וְהֶאֱמִן בַּיהוָה וַיַּחְשְׁבֶהָ לּוֹ צְדָקָה", en: "He trusted in YHWH, and he counted it to him as righteousness.", hit: "צְדָקָה" },
  torah: { ref: "Josh 1:8", he: "לֹא־יָמוּשׁ סֵפֶר הַתּוֹרָה הַזֶּה מִפִּיךָ", en: "This book of the instruction shall not depart from your mouth.", hit: "הַתּוֹרָה" },
  berit: { ref: "Gen 9:9", he: "וַאֲנִי הִנְנִי מֵקִים אֶת־בְּרִיתִי אִתְּכֶם", en: "As for me, I am establishing my covenant with you.", hit: "בְּרִיתִי" },
  hattat: { ref: "Ps 51:4", he: "כִּי־פְשָׁעַי אֲנִי אֵדָע וְחַטָּאתִי נֶגְדִּי תָמִיד", en: "For I know my rebellions, and my sin is continually before me.", hit: "וְחַטָּאתִי" },
  kavod: { ref: "Exod 24:16", he: "וַיִּשְׁכֹּן כְּבוֹד יְהוָה עַל־הַר סִינַי", en: "The glory of YHWH dwelt on Mount Sinai.", hit: "כְּבוֹד" },
  or: { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "אוֹר" },
  hoshek: { ref: "Gen 1:2", he: "וְחֹשֶׁךְ עַל־פְּנֵי תְהוֹם", en: "And darkness was over the face of the deep.", hit: "וְחֹשֶׁךְ" },
  hayyim: { ref: "Deut 30:19", he: "הַחַיִּים וְהַמָּוֶת נָתַתִּי לְפָנֶיךָ הַבְּרָכָה וְהַקְּלָלָה", en: "Life and death I have set before you, the blessing and the curse.", hit: "הַחַיִּים" },
  mavet: { ref: "Deut 30:19", he: "הַחַיִּים וְהַמָּוֶת נָתַתִּי לְפָנֶיךָ", en: "Life and death I have set before you.", hit: "וְהַמָּוֶת" },
  ebed: { ref: "Isa 42:1", he: "הֵן עַבְדִּי אֶתְמָךְ־בּוֹ בְּחִירִי רָצְתָה נַפְשִׁי", en: "Behold my servant, whom I uphold, my chosen, in whom my soul delights.", hit: "עַבְדִּי" },
  adon: { ref: "Isa 1:24", he: "לָכֵן נְאֻם הָאָדוֹן יְהוָה צְבָאוֹת אֲבִיר יִשְׂרָאֵל", en: "Therefore the oracle of the Lord, YHWH of hosts, the Mighty One of Israel.", hit: "הָאָדוֹן" },
  esh: { ref: "Exod 3:2", he: "וַיֵּרָא מַלְאַךְ יְהוָה אֵלָיו בְּלַבַּת־אֵשׁ מִתּוֹךְ הַסְּנֶה", en: "The messenger of YHWH appeared to him in a flame of fire from the midst of the bush.", hit: "אֵשׁ" },
  olam: { ref: "Ps 90:2", he: "מֵעוֹלָם עַד־עוֹלָם אַתָּה אֵל", en: "From everlasting to everlasting, you are God.", hit: "עוֹלָם" },
  mitsvah: { ref: "Deut 6:1", he: "וְזֹאת הַמִּצְוָה הַחֻקִּים וְהַמִּשְׁפָּטִים", en: "This is the commandment, the statutes and the judgments.", hit: "הַמִּצְוָה" },
  milhamah: { ref: "Exod 15:3", he: "יְהוָה אִישׁ מִלְחָמָה יְהוָה שְׁמוֹ", en: "YHWH is a man of war; YHWH is his name.", hit: "מִלְחָמָה" },
  hereb: { ref: "Gen 3:24", he: "וְאֵת לַהַט הַחֶרֶב הַמִּתְהַפֶּכֶת לִשְׁמֹר אֶת־דֶּרֶךְ עֵץ הַחַיִּים", en: "And the flame of the whirling sword to guard the way of the tree of life.", hit: "הַחֶרֶב" },
  zera: { ref: "Gen 3:15", he: "וְאֵיבָה אָשִׁית בֵּינְךָ וּבֵין הָאִשָּׁה וּבֵין זַרְעֲךָ וּבֵין זַרְעָהּ", en: "I will put enmity between you and the woman, and between your seed and her seed.", hit: "זַרְעֲךָ" },
  qodesh: { ref: "Exod 3:5", he: "כִּי הַמָּקוֹם אֲשֶׁר אַתָּה עוֹמֵד עָלָיו אַדְמַת־קֹדֶשׁ הוּא", en: "For the place on which you are standing is holy ground.", hit: "קֹדֶשׁ" },
  hekal: { ref: "Isa 6:1", he: "וָאֶרְאֶה אֶת־אֲדֹנָי יֹשֵׁב עַל־כִּסֵּא רָם וְנִשָּׂא וְשׁוּלָיו מְלֵאִים אֶת־הַהֵיכָל", en: "I saw the Lord sitting on a throne, high and lifted up, and his train filled the temple.", hit: "הַהֵיכָל" },
  shabbat: { ref: "Exod 20:8", he: "זָכוֹר אֶת־יוֹם הַשַּׁבָּת לְקַדְּשׁוֹ", en: "Remember the Sabbath day, to keep it holy.", hit: "הַשַּׁבָּת" },
  ehad: { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "אֶחָד" },
  shenayim: { ref: "Gen 1:16", he: "וַיַּעַשׂ אֱלֹהִים אֶת־שְׁנֵי הַמְּאֹרֹת הַגְּדֹלִים", en: "God made the two great lights.", hit: "שְׁנֵי" },
  shalosh: { ref: "Exod 23:14", he: "שָׁלֹשׁ רְגָלִים תָּחֹג לִי בַּשָּׁנָה", en: "Three times you shall keep a feast to me in the year.", hit: "שָׁלֹשׁ" },
  arba: { ref: "Gen 2:10", he: "וּמִשָּׁם יִפָּרֵד וְהָיָה לְאַרְבָּעָה רָאשִׁים", en: "From there it divides and becomes four heads.", hit: "לְאַרְבָּעָה" },
  hamesh: { ref: "Gen 18:28", he: "אוּלַי יַחְסְרוּן חֲמִשִּׁים הַצַּדִּיקִם חֲמִשָּׁה", en: "Suppose the fifty righteous lack five.", hit: "חֲמִשָּׁה" },
  shesh: { ref: "Exod 20:9", he: "שֵׁשֶׁת יָמִים תַּעֲבֹד וְעָשִׂיתָ כָּל־מְלַאכְתֶּךָ", en: "Six days you shall labor and do all your work.", hit: "שֵׁשֶׁת" },
  sheba: { ref: "Gen 29:18", he: "וַיֶּאֱהַב יַעֲקֹב אֶת־רָחֵל וַיֹּאמֶר אֶעֱבָדְךָ שֶׁבַע שָׁנִים", en: "Jacob loved Rachel and said, “I will serve you seven years.”", hit: "שֶׁבַע" },
  eser: { ref: "Exod 34:28", he: "וַיִּכְתֹּב עַל־הַלֻּחֹת אֵת דִּבְרֵי הַבְּרִית עֲשֶׂרֶת הַדְּבָרִים", en: "He wrote on the tablets the words of the covenant, the ten words.", hit: "עֲשֶׂרֶת" },
  meah: { ref: "Gen 5:3", he: "וַיְחִי אָדָם שְׁלֹשִׁים וּמְאַת שָׁנָה", en: "Adam lived one hundred and thirty years.", hit: "וּמְאַת" },
  eleph: { ref: "Exod 18:21", he: "וְשַׂמְתָּ עֲלֵהֶם שָׂרֵי אֲלָפִים שָׂרֵי מֵאוֹת", en: "You shall set over them chiefs of thousands, chiefs of hundreds.", hit: "אֲלָפִים" },

  amar: { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "וַיֹּאמֶר" },
  hayah: { ref: "Gen 1:3", he: "וַיֹּאמֶר אֱלֹהִים יְהִי אוֹר וַיְהִי־אוֹר", en: "God said, “Let there be light,” and there was light.", hit: "וַיְהִי" },
  asah: { ref: "Gen 1:7", he: "וַיַּעַשׂ אֱלֹהִים אֶת־הָרָקִיעַ", en: "God made the expanse.", hit: "וַיַּעַשׂ" },
  bo: { ref: "Gen 7:7", he: "וַיָּבֹא נֹחַ וּבָנָיו וְאִשְׁתּוֹ וּנְשֵׁי־בָנָיו אִתּוֹ אֶל־הַתֵּבָה", en: "Noah went in, and his sons and his wife and his sons’ wives with him, into the ark.", hit: "וַיָּבֹא" },
  natan: { ref: "Gen 1:29", he: "הִנֵּה נָתַתִּי לָכֶם אֶת־כָּל־עֵשֶׂב זֹרֵעַ זֶרַע", en: "See, I have given you every plant yielding seed.", hit: "נָתַתִּי" },
  halak: { ref: "Gen 5:24", he: "וַיִּתְהַלֵּךְ חֲנוֹךְ אֶת־הָאֱלֹהִים וְאֵינֶנּוּ כִּי־לָקַח אֹתוֹ אֱלֹהִים", en: "Enoch walked with God, and he was not, for God took him.", hit: "וַיִּתְהַלֵּךְ" },
  raah: { ref: "Gen 1:4", he: "וַיַּרְא אֱלֹהִים אֶת־הָאוֹר כִּי־טוֹב", en: "God saw the light, that it was good.", hit: "וַיַּרְא" },
  shama: { ref: "Deut 6:4", he: "שְׁמַע יִשְׂרָאֵל יְהוָה אֱלֹהֵינוּ יְהוָה אֶחָד", en: "Hear, Israel: YHWH our God, YHWH is one.", hit: "שְׁמַע" },
  diber: { ref: "Exod 20:1", he: "וַיְדַבֵּר אֱלֹהִים אֵת כָּל־הַדְּבָרִים הָאֵלֶּה לֵאמֹר", en: "God spoke all these words, saying.", hit: "וַיְדַבֵּר" },
  yashab: { ref: "Gen 4:16", he: "וַיֵּצֵא קַיִן מִלִּפְנֵי יְהוָה וַיֵּשֶׁב בְּאֶרֶץ־נוֹד", en: "Cain went out from before YHWH and dwelt in the land of Nod.", hit: "וַיֵּשֶׁב" },
  yatsa: { ref: "Exod 12:41", he: "וַיְהִי מִקֵּץ שְׁלֹשִׁים שָׁנָה וְאַרְבַּע מֵאוֹת שָׁנָה ... יָצְאוּ כָּל־צִבְאוֹת יְהוָה מֵאֶרֶץ מִצְרָיִם", en: "At the end of four hundred thirty years, all the hosts of YHWH went out from the land of Egypt.", hit: "יָצְאוּ" },
  shub: { ref: "Gen 3:19", he: "כִּי־עָפָר אַתָּה וְאֶל־עָפָר תָּשׁוּב", en: "For dust you are, and to dust you shall return.", hit: "תָּשׁוּב" },
  yada: { ref: "Gen 3:5", he: "וִהְיִיתֶם כֵּאלֹהִים יֹדְעֵי טוֹב וָרָע", en: "You will be like God, knowers of good and evil.", hit: "יֹדְעֵי", hitEn: "knowers" },
  laqah: { ref: "Gen 5:24", he: "וְאֵינֶנּוּ כִּי־לָקַח אֹתוֹ אֱלֹהִים", en: "And he was not, for God took him.", hit: "לָקַח" },
  alah: { ref: "Exod 19:3", he: "וּמֹשֶׁה עָלָה אֶל־הָאֱלֹהִים", en: "And Moses went up to God.", hit: "עָלָה" },
  qara: { ref: "Gen 1:5", he: "וַיִּקְרָא אֱלֹהִים לָאוֹר יוֹם", en: "God called the light Day.", hit: "וַיִּקְרָא" },
  shalach: { ref: "Exod 3:10", he: "וְעַתָּה לְכָה וְאֶשְׁלָחֲךָ אֶל־פַּרְעֹה", en: "And now go; I will send you to Pharaoh.", hit: "וְאֶשְׁלָחֲךָ" },
  qum: { ref: "Gen 13:17", he: "קוּם הִתְהַלֵּךְ בָּאָרֶץ לְאָרְכָּהּ וּלְרָחְבָּהּ", en: "Arise, walk through the land, its length and its breadth.", hit: "קוּם" },

  akol: { ref: "Gen 3:6", he: "וַתִּקַּח מִפִּרְיוֹ וַתֹּאכַל", en: "She took from its fruit and she ate.", hit: "וַתֹּאכַל" },
  mut: { ref: "Gen 2:17", he: "כִּי בְּיוֹם אֲכָלְךָ מִמֶּנּוּ מוֹת תָּמוּת", en: "For on the day you eat from it, you shall surely die.", hit: "תָּמוּת" },
  natsa: { ref: "Gen 2:20", he: "וּלְאָדָם לֹא־מָצָא עֵזֶר כְּנֶגְדּוֹ", en: "But for the human he did not find a help corresponding to him.", hit: "מָצָא" },
  shamar: { ref: "Gen 2:15", he: "וַיַּנִּחֵהוּ בְגַן־עֵדֶן לְעָבְדָהּ וּלְשָׁמְרָהּ", en: "He set him in the garden of Eden to work it and to keep it.", hit: "וּלְשָׁמְרָהּ" },
  "natan-nasa": { ref: "Num 6:26", he: "יִשָּׂא יְהוָה פָּנָיו אֵלֶיךָ וְיָשֵׂם לְךָ שָׁלוֹם", en: "YHWH lift his face toward you and set peace for you.", hit: "יִשָּׂא" },
  naphal: { ref: "Josh 5:14", he: "וַיִּפֹּל יְהוֹשֻׁעַ אֶל־פָּנָיו אַרְצָה וַיִּשְׁתָּחוּ", en: "Joshua fell on his face to the ground and bowed down.", hit: "וַיִּפֹּל" },
  yare: { ref: "Prov 1:7", he: "יִרְאַת יְהוָה רֵאשִׁית דָּעַת", en: "The fear of YHWH is the beginning of knowledge.", hit: "יִרְאַת" },
  ahab: { ref: "Deut 6:5", he: "וְאָהַבְתָּ אֵת יְהוָה אֱלֹהֶיךָ בְּכָל־לְבָבְךָ", en: "You shall love YHWH your God with all your heart.", hit: "וְאָהַבְתָּ" },
  barak: { ref: "Gen 1:28", he: "וַיְבָרֶךְ אֹתָם אֱלֹהִים", en: "God blessed them.", hit: "וַיְבָרֶךְ" },
  bara: { ref: "Gen 1:1", he: "בְּרֵאשִׁית בָּרָא אֱלֹהִים אֵת הַשָּׁמַיִם וְאֵת הָאָרֶץ", en: "In the beginning God created the heavens and the earth.", hit: "בָּרָא" },
  banah: { ref: "Gen 2:22", he: "וַיִּבֶן יְהוָה אֱלֹהִים אֶת־הַצֵּלָע ... לְאִשָּׁה", en: "YHWH God built the rib … into a woman.", hit: "וַיִּבֶן" },
  katab: { ref: "Exod 24:4", he: "וַיִּכְתֹּב מֹשֶׁה אֵת כָּל־דִּבְרֵי יְהוָה", en: "Moses wrote down all the words of YHWH.", hit: "וַיִּכְתֹּב" },
  abad: { ref: "Exod 3:12", he: "תַּעַבְדוּן אֶת־הָאֱלֹהִים עַל הָהָר הַזֶּה", en: "You shall serve God on this mountain.", hit: "תַּעַבְדוּן" },
  malak: { ref: "Ps 93:1", he: "יְהוָה מָלָךְ גֵּאוּת לָבֵשׁ", en: "YHWH reigns; he is clothed with majesty.", hit: "מָלָךְ" },
  hata: { ref: "Exod 32:31", he: "אָנָּא חָטָא הָעָם הַזֶּה חֲטָאָה גְדֹלָה", en: "Alas, this people has sinned a great sin.", hit: "חָטָא" },

  yarad: { ref: "Exod 19:20", he: "וַיֵּרֶד יְהוָה עַל־הַר סִינַי", en: "YHWH came down on Mount Sinai.", hit: "וַיֵּרֶד", hitEn: "came down" },
  amad: { ref: "Exod 3:5", he: "כִּי הַמָּקוֹם אֲשֶׁר אַתָּה עוֹמֵד עָלָיו אַדְמַת־קֹדֶשׁ הוּא", en: "For the place on which you are standing is holy ground.", hit: "עוֹמֵד" },
  gadal: { ref: "Gen 12:2", he: "וַאֲגַדְּלָה שְׁמֶךָ וֶהְיֵה בְּרָכָה", en: "I will make your name great, and you shall be a blessing.", hit: "וַאֲגַדְּלָה" },
  hazaq: { ref: "Josh 1:9", he: "חֲזַק וֶאֱמָץ אַל־תַּעֲרֹץ וְאַל־תֵּחָת", en: "Be strong and courageous; do not be terrified and do not be dismayed.", hit: "חֲזַק" },
  yakol: { ref: "Gen 32:26", he: "וַיַּרְא כִּי לֹא יָכֹל לוֹ", en: "He saw that he could not prevail against him.", hit: "יָכֹל" },
  qarab: { ref: "Lev 1:2", he: "אָדָם כִּי־יַקְרִיב מִכֶּם קָרְבָּן לַיהוָה", en: "When a person from among you brings near an offering to YHWH.", hit: "יַקְרִיב" },
  lamad: { ref: "Deut 4:1", he: "וְעַתָּה יִשְׂרָאֵל שְׁמַע אֶל־הַחֻקִּים ... לְלַמֵּד אֶתְכֶם", en: "And now, Israel, listen to the statutes … to teach you.", hit: "לְלַמֵּד" },
  shaphat: { ref: "Gen 18:25", he: "הֲשֹׁפֵט כָּל־הָאָרֶץ לֹא יַעֲשֶׂה מִשְׁפָּט", en: "Shall the judge of all the earth not do justice?", hit: "הֲשֹׁפֵט" },
  male: { ref: "Isa 6:3", he: "קָדוֹשׁ קָדוֹשׁ קָדוֹשׁ יְהוָה צְבָאוֹת מְלֹא כָל־הָאָרֶץ כְּבוֹדוֹ", en: "Holy, holy, holy is YHWH of hosts; the fullness of all the earth is his glory.", hit: "מְלֹא", hitEn: "the fullness" },
  rabah: { ref: "Gen 1:22", he: "פְּרוּ וּרְבוּ וּמִלְאוּ אֶת־הַמַּיִם בַּיַּמִּים", en: "Be fruitful and multiply and fill the waters in the seas.", hit: "וּרְבוּ" },
  bahar: { ref: "Deut 7:6", he: "בְּךָ בָּחַר יְהוָה אֱלֹהֶיךָ לִהְיוֹת לוֹ לְעַם סְגֻלָּה", en: "YHWH your God has chosen you to be for him a people of treasure.", hit: "בָּחַר" },
  paqad: { ref: "Gen 21:1", he: "וַיהוָה פָּקַד אֶת־שָׂרָה כַּאֲשֶׁר אָמָר", en: "YHWH visited Sarah as he had said.", hit: "פָּקַד" },
  yalad: { ref: "Gen 4:1", he: "וַתַּהַר וַתֵּלֶד אֶת־קַיִן", en: "She conceived and bore Cain.", hit: "וַתֵּלֶד" },
  shatah: { ref: "Exod 17:6", he: "וְהִכִּיתָ בַצּוּר וְיָצְאוּ מִמֶּנּוּ מַיִם וְשָׁתָה הָעָם", en: "You shall strike the rock, and water will come out from it, and the people will drink.", hit: "וְשָׁתָה" },
  sane: { ref: "Exod 20:5", he: "כִּי אָנֹכִי יְהוָה אֱלֹהֶיךָ אֵל קַנָּא פֹּקֵד עֲוֹן אָבֹת עַל־בָּנִים ... לְשֹׂנְאָי", en: "For I, YHWH your God, am a jealous God … of those who hate me.", hit: "לְשֹׂנְאָי" },

  yasha: { ref: "Exod 14:30", he: "וַיּוֹשַׁע יְהוָה בַּיּוֹם הַהוּא אֶת־יִשְׂרָאֵל מִיַּד מִצְרָיִם", en: "YHWH saved Israel that day from the hand of Egypt.", hit: "וַיּוֹשַׁע" },
  azar: { ref: "Ps 121:1", he: "אֶשָּׂא עֵינַי אֶל־הֶהָרִים מֵאַיִן יָבֹא עֶזְרִי", en: "I lift my eyes to the mountains: from where will my help come?", hit: "עֶזְרִי" },
  baqash: { ref: "Deut 4:29", he: "וּבִקַּשְׁתֶּם מִשָּׁם אֶת־יְהוָה אֱלֹהֶיךָ וּמָצָאתָ", en: "From there you will seek YHWH your God, and you will find him.", hit: "וּבִקַּשְׁתֶּם" },
  darash: { ref: "Deut 4:29", he: "כִּי תִדְרְשֶׁנּוּ בְּכָל־לְבָבְךָ וּבְכָל־נַפְשֶׁךָ", en: "When you search for him with all your heart and with all your person.", hit: "תִדְרְשֶׁנּוּ", hitEn: "search" },
  hithpallel: { ref: "Gen 20:17", he: "וַיִּתְפַּלֵּל אַבְרָהָם אֶל־הָאֱלֹהִים וַיִּרְפָּא אֱלֹהִים אֶת־אֲבִימֶלֶךְ", en: "Abraham prayed to God, and God healed Abimelech.", hit: "וַיִּתְפַּלֵּל" },
  hishtahawah: { ref: "Gen 24:26", he: "וַיִּקֹּד הָאִישׁ וַיִּשְׁתַּחוּ לַיהוָה", en: "The man bowed and worshiped YHWH.", hit: "וַיִּשְׁתַּחוּ" },
  hallel: { ref: "Ps 113:1", he: "הַלְלוּ יָהּ הַלְלוּ עַבְדֵי יְהוָה הַלְלוּ אֶת־שֵׁם יְהוָה", en: "Praise Yah! Praise, servants of YHWH, praise the name of YHWH.", hit: "הַלְלוּ" },
  bakah: { ref: "Gen 21:16", he: "וַתֵּשֶׁב מִנֶּגֶד וַתִּשָּׂא אֶת־קֹלָהּ וַתֵּבְךְּ", en: "She sat opposite and lifted her voice and wept.", hit: "וַתֵּבְךְּ" },
  gaal: { ref: "Exod 6:6", he: "וְגָאַלְתִּי אֶתְכֶם בִּזְרוֹעַ נְטוּיָה", en: "I will redeem you with an outstretched arm.", hit: "וְגָאַלְתִּי" },
  salah: { ref: "Exod 34:9", he: "וְסָלַחְתָּ לַעֲוֹנֵנוּ וּלְחַטָּאתֵנוּ וּנְחַלְתָּנוּ", en: "And you will forgive our iniquity and our sin, and take us as your inheritance.", hit: "וְסָלַחְתָּ" },
  shakah: { ref: "Deut 4:9", he: "רַק הִשָּׁמֶר לְךָ וּשְׁמֹר נַפְשְׁךָ מְאֹד פֶּן־תִּשְׁכַּח אֶת־הַדְּבָרִים", en: "Only take care, and watch yourself closely, lest you forget the things.", hit: "תִּשְׁכַּח" },
  tsaaq: { ref: "Exod 2:23", he: "וַיִּזְעֲקוּ וַתַּעַל שַׁוְעָתָם אֶל־הָאֱלֹהִים", en: "They cried out, and their plea went up to God.", hit: "וַיִּזְעֲקוּ" },
  "nathan-natsal": { ref: "Exod 3:8", he: "וָאֵרֵד לְהַצִּילוֹ מִיַּד מִצְרַיִם", en: "I have come down to deliver him from the hand of Egypt.", hit: "לְהַצִּילוֹ" },
  qadash: { ref: "Exod 20:8", he: "זָכוֹר אֶת־יוֹם הַשַּׁבָּת לְקַדְּשׁוֹ", en: "Remember the Sabbath day, to keep it holy.", hit: "לְקַדְּשׁוֹ" },

  patah: { ref: "Gen 8:6", he: "וַיִּפְתַּח נֹחַ אֶת־חַלּוֹן הַתֵּבָה אֲשֶׁר עָשָׂה", en: "Noah opened the window of the ark that he had made.", hit: "וַיִּפְתַּח" },
  sagar: { ref: "Gen 7:16", he: "וַיִּסְגֹּר יְהוָה בַּעֲדוֹ", en: "And YHWH shut him in.", hit: "וַיִּסְגֹּר" },
  kasah: { ref: "Gen 7:19", he: "וְהַמַּיִם גָּבְרוּ מְאֹד מְאֹד עַל־הָאָרֶץ וַיְכֻסּוּ כָּל־הֶהָרִים הַגְּבֹהִים", en: "The waters prevailed very greatly on the earth, and all the high mountains were covered.", hit: "וַיְכֻסּוּ" },
  galah: { ref: "1 Sam 3:21", he: "וַיֹּסֶף יְהוָה לְהֵרָאֹה בְשִׁלֹה כִּי־נִגְלָה יְהוָה אֶל־שְׁמוּאֵל", en: "YHWH continued to appear in Shiloh, for YHWH revealed himself to Samuel.", hit: "נִגְלָה" },
  asaph: { ref: "Gen 29:3", he: "וְנֶאֶסְפוּ־שָׁמָּה כָל־הָעֲדָרִים", en: "All the flocks would be gathered there.", hit: "וְנֶאֶסְפוּ" },
  karat: { ref: "Gen 15:18", he: "בַּיּוֹם הַהוּא כָּרַת יְהוָה אֶת־אַבְרָם בְּרִית", en: "On that day YHWH cut a covenant with Abram.", hit: "כָּרַת" },
  zabah: { ref: "Gen 31:54", he: "וַיִּזְבַּח יַעֲקֹב זֶבַח בָּהָר", en: "Jacob sacrificed a sacrifice on the mountain.", hit: "וַיִּזְבַּח" },
  mashah: { ref: "1 Sam 16:13", he: "וַיִּקַּח שְׁמוּאֵל אֶת־קֶרֶן הַשֶּׁמֶן וַיִּמְשַׁח אֹתוֹ", en: "Samuel took the horn of oil and anointed him.", hit: "וַיִּמְשַׁח" },
  taher: { ref: "Lev 14:20", he: "וְכִפֶּר עָלָיו הַכֹּהֵן וְטָהֵר", en: "The priest shall make atonement for him, and he shall be clean.", hit: "וְטָהֵר" },
  tame: { ref: "Lev 11:24", he: "וּלְאֵלֶּה תִּטַּמָּאוּ כָּל־הַנֹּגֵעַ בְּנִבְלָתָם יִטְמָא עַד־הָעָרֶב", en: "By these you shall become unclean; whoever touches their carcass shall be unclean until evening.", hit: "יִטְמָא" },
  labash: { ref: "Gen 3:21", he: "וַיַּעַשׂ יְהוָה אֱלֹהִים לְאָדָם וּלְאִשְׁתּוֹ כָּתְנוֹת עוֹר וַיַּלְבִּשֵׁם", en: "YHWH God made for the human and his wife garments of skin and clothed them.", hit: "וַיַּלְבִּשֵׁם" },
  qabar: { ref: "Gen 23:19", he: "וְאַחֲרֵי־כֵן קָבַר אַבְרָהָם אֶת־שָׂרָה אִשְׁתּוֹ", en: "After this Abraham buried Sarah his wife.", hit: "קָבַר" },
  yarash: { ref: "Gen 15:7", he: "אֲנִי יְהוָה אֲשֶׁר הוֹצֵאתִיךָ מֵאוּר כַּשְׂדִּים לָתֶת לְךָ אֶת־הָאָרֶץ הַזֹּאת לְרִשְׁתָּהּ", en: "I am YHWH who brought you from Ur of the Chaldeans to give you this land to possess it.", hit: "לְרִשְׁתָּהּ" },
  nata: { ref: "Gen 2:8", he: "וַיִּטַּע יְהוָה אֱלֹהִים גַּן בְּעֵדֶן מִקֶּדֶם", en: "YHWH God planted a garden in Eden, in the east.", hit: "וַיִּטַּע" },

  laham: { ref: "Exod 17:8", he: "וַיָּבֹא עֲמָלֵק וַיִּלָּחֶם עִם־יִשְׂרָאֵל בִּרְפִידִם", en: "Amalek came and fought with Israel at Rephidim.", hit: "וַיִּלָּחֶם" },
  nakah: { ref: "Exod 2:12", he: "וַיַּךְ אֶת־הַמִּצְרִי וַיִּטְמְנֵהוּ בַּחוֹל", en: "He struck the Egyptian and hid him in the sand.", hit: "וַיַּךְ" },
  harag: { ref: "Gen 4:8", he: "וַיָּקָם קַיִן אֶל־הֶבֶל אָחִיו וַיַּהַרְגֵהוּ", en: "Cain rose up against Abel his brother and killed him.", hit: "וַיַּהַרְגֵהוּ" },
  shabar: { ref: "Exod 32:19", he: "וַיַּשְׁלֵךְ מִיָּדָיו אֶת־הַלֻּחֹת וַיְשַׁבֵּר אֹתָם תַּחַת הָהָר", en: "He threw the tablets from his hands and broke them at the foot of the mountain.", hit: "וַיְשַׁבֵּר" },
  radaph: { ref: "Exod 14:8", he: "וַיִּרְדֹּף אַחֲרֵי בְּנֵי יִשְׂרָאֵל", en: "He pursued after the children of Israel.", hit: "וַיִּרְדֹּף" },
  nus: { ref: "Gen 39:12", he: "וַיַּעֲזֹב בִּגְדוֹ בְּיָדָהּ וַיָּנָס וַיֵּצֵא הַחוּצָה", en: "He left his garment in her hand and fled and went outside.", hit: "וַיָּנָס" },
  lakad: { ref: "Josh 6:20", he: "וַיַּעַל הָעָם הָעִירָה אִישׁ נֶגְדּוֹ וַיִּלְכְּדוּ אֶת־הָעִיר", en: "The people went up into the city, each straight ahead, and they captured the city.", hit: "וַיִּלְכְּדוּ" },
  shaal: { ref: "1 Sam 1:20", he: "כִּי מֵיְהוָה שְׁאִלְתִּיו", en: "Because from YHWH I asked him.", hit: "שְׁאִלְתִּיו" },
  anah: { ref: "Gen 18:27", he: "וַיַּעַן אַבְרָהָם וַיֹּאמַר הִנֵּה־נָא הוֹאַלְתִּי לְדַבֵּר אֶל־אֲדֹנָי", en: "Abraham answered and said, “Behold, I have ventured to speak to my Lord.”", hit: "וַיַּעַן" },
  ganab: { ref: "Exod 20:15", he: "לֹא תִּגְנֹב", en: "You shall not steal.", hit: "תִּגְנֹב" },
  shamad: { ref: "Deut 9:3", he: "וְהוּא יַשְׁמִידֵם וְהוּא יַכְנִיעֵם לְפָנֶיךָ", en: "He will destroy them, and he will subdue them before you.", hit: "יַשְׁמִידֵם" },
  asar: { ref: "Gen 40:3", he: "וַיִּתֵּן אֹתָם בְּמִשְׁמַר בֵּית שַׂר הַטַבָּחִים", en: "He put them in custody in the house of the captain of the guard.", hit: "בְּמִשְׁמַר", hitEn: "custody" },
  natsar: { ref: "Ps 119:9", he: "בַּמֶּה יְזַכֶּה־נַּעַר אֶת־אָרְחוֹ לִשְׁמֹר כִּדְבָרֶךָ", en: "How can a young man keep his way pure? By guarding it according to your word.", hit: "לִשְׁמֹר" },

  kalah: { ref: "Gen 2:1", he: "וַיְכֻלּוּ הַשָּׁמַיִם וְהָאָרֶץ וְכָל־צְבָאָם", en: "The heavens and the earth were finished, and all their host.", hit: "וַיְכֻלּוּ" },
  yasaph: { ref: "Gen 4:2", he: "וַתֹּסֶף לָלֶדֶת אֶת־אָחִיו אֶת־הָבֶל", en: "She continued and bore his brother Abel.", hit: "וַתֹּסֶף" },
  makar: { ref: "Gen 37:28", he: "וַיִּמְכְּרוּ אֶת־יוֹסֵף לַיִּשְׁמְעֵאלִים בְּעֶשְׂרִים כָּסֶף", en: "They sold Joseph to the Ishmaelites for twenty of silver.", hit: "וַיִּמְכְּרוּ" },
  qanah: { ref: "Gen 25:10", he: "הַשָּׂדֶה אֲשֶׁר־קָנָה אַבְרָהָם מֵאֵת בְּנֵי־חֵת", en: "The field that Abraham bought from the sons of Heth.", hit: "קָנָה" },
  saphar: { ref: "Gen 15:5", he: "הַבֶּט־נָא הַשָּׁמַיְמָה וּסְפֹר הַכּוֹכָבִים אִם־תּוּכַל לִסְפֹּר אֹתָם", en: "Look, please, toward the heavens, and count the stars, if you are able to count them.", hit: "וּסְפֹר" },
  hashab: { ref: "Gen 15:6", he: "וְהֶאֱמִן בַּיהוָה וַיַּחְשְׁבֶהָ לּוֹ צְדָקָה", en: "He trusted in YHWH, and he counted it to him as righteousness.", hit: "וַיַּחְשְׁבֶהָ", hitEn: "counted" },
  naba: { ref: "Jer 1:5", he: "נָבִיא לַגּוֹיִם נְתַתִּיךָ", en: "A prophet to the nations I have appointed you. (נבא in the call of Jeremiah)", hit: "נָבִיא", hitEn: "A prophet" },
  halam: { ref: "Gen 37:5", he: "וַיַּחֲלֹם יוֹסֵף חֲלוֹם וַיַּגֵּד לְאֶחָיו", en: "Joseph dreamed a dream and told it to his brothers.", hit: "וַיַּחֲלֹם" },
  zaqen: { ref: "Gen 18:12", he: "אַחֲרֵי בְלֹתִי הָיְתָה־לִּי עֶדְנָה וַאדֹנִי זָקֵן", en: "After I am worn out, shall I have pleasure, and my lord is old?", hit: "זָקֵן" },
  "zaqen-v": { ref: "Gen 18:11", he: "וְאַבְרָהָם וְשָׂרָה זְקֵנִים בָּאִים בַּיָּמִים", en: "Abraham and Sarah were old, advanced in days.", hit: "זְקֵנִים" },
  hadal: { ref: "Gen 18:11", he: "חָדַל לִהְיוֹת לְשָׂרָה אֹרַח כַּנָּשִׁים", en: "The way of women had ceased to be for Sarah.", hit: "חָדַל" },
  madad: { ref: "Exod 16:18", he: "וַיָּמֹדּוּ בָעֹמֶר וְלֹא הֶעְדִּיף הַמַּרְבֶּה", en: "They measured it by the omer, and the one who gathered much had no surplus.", hit: "וַיָּמֹדּוּ" },
  yaats: { ref: "Exod 18:19", he: "עַתָּה שְׁמַע בְּקֹלִי אִיעָצְךָ", en: "Now listen to my voice; I will advise you.", hit: "אִיעָצְךָ" },

  nagash: { ref: "Gen 18:23", he: "וַיִּגַּשׁ אַבְרָהָם וַיֹּאמַר הַאַף תִּסְפֶּה צַדִּיק עִם־רָשָׁע", en: "Abraham drew near and said, “Will you indeed sweep away the righteous with the wicked?”", hit: "וַיִּגַּשׁ" },
  naga: { ref: "Gen 3:3", he: "וְלֹא תִגְּעוּ בּוֹ פֶּן־תְּמֻתוּן", en: "And you shall not touch it, lest you die.", hit: "תִגְּעוּ" },
  abar: { ref: "Exod 12:12", he: "וְעָבַרְתִּי בְאֶרֶץ־מִצְרַיִם בַּלַּיְלָה הַזֶּה", en: "I will pass through the land of Egypt this night.", hit: "וְעָבַרְתִּי" },
  haphak: { ref: "Gen 19:25", he: "וַיַּהֲפֹךְ אֶת־הֶעָרִים הָאֵל", en: "He overthrew those cities.", hit: "וַיַּהֲפֹךְ", hitEn: "overthrew" },
  sabab: { ref: "Josh 6:3", he: "וְסַבֹּתֶם אֶת־הָעִיר כֹּל אַנְשֵׁי הַמִּלְחָמָה", en: "You shall go around the city, all the men of war.", hit: "וְסַבֹּתֶם" },
  azab: { ref: "Gen 2:24", he: "עַל־כֵּן יַעֲזָב־אִישׁ אֶת־אָבִיו וְאֶת־אִמּוֹ", en: "Therefore a man leaves his father and his mother.", hit: "יַעֲזָב" },
  shakan: { ref: "Exod 25:8", he: "וְעָשׂוּ לִי מִקְדָּשׁ וְשָׁכַנְתִּי בְּתוֹכָם", en: "They shall make me a sanctuary, and I will dwell in their midst.", hit: "וְשָׁכַנְתִּי" },
  dabaq: { ref: "Gen 2:24", he: "וְדָבַק בְּאִשְׁתּוֹ וְהָיוּ לְבָשָׂר אֶחָד", en: "And he shall cling to his wife, and they shall become one flesh.", hit: "וְדָבַק" },
  parad: { ref: "Gen 2:10", he: "וּמִשָּׁם יִפָּרֵד וְהָיָה לְאַרְבָּעָה רָאשִׁים", en: "From there it divides and becomes four heads.", hit: "יִפָּרֵד" },
  qarah: { ref: "Gen 42:29", he: "וַיַּגִּידוּ לוֹ אֵת כָּל־הַקֹּרֹת אֹתָם", en: "They told him all that had happened to them.", hit: "הַקֹּרֹת" },
  nuah: { ref: "Gen 8:4", he: "וַתָּנַח הַתֵּבָה בַּחֹדֶשׁ הַשְּׁבִיעִי ... עַל הָרֵי אֲרָרָט", en: "The ark came to rest in the seventh month … on the mountains of Ararat.", hit: "וַתָּנַח" },
  shakab: { ref: "Gen 19:4", he: "טֶרֶם יִשְׁכָּבוּ וְאַנְשֵׁי הָעִיר ... נָסַבּוּ עַל־הַבַּיִת", en: "Before they lay down, the men of the city … surrounded the house.", hit: "יִשְׁכָּבוּ" },

  tsiwwah: { ref: "Gen 2:16", he: "וַיְצַו יְהוָה אֱלֹהִים עַל־הָאָדָם לֵאמֹר", en: "YHWH God commanded the human, saying.", hit: "וַיְצַו" },
  higgid: { ref: "Gen 3:11", he: "מִי הִגִּיד לְךָ כִּי עֵירֹם אָתָּה", en: "Who told you that you were naked?", hit: "הִגִּיד" },
  nishba: { ref: "Gen 22:16", he: "בִּי נִשְׁבַּעְתִּי נְאֻם־יְהוָה", en: "By myself I have sworn, oracle of YHWH.", hit: "נִשְׁבַּעְתִּי" },
  nadar: { ref: "Gen 28:20", he: "וַיִּדַּר יַעֲקֹב נֶדֶר לֵאמֹר", en: "Jacob vowed a vow, saying.", hit: "וַיִּדַּר" },
  shillem: { ref: "Isa 38:12", he: "מִיּוֹם עַד־לַיְלָה תַּשְׁלִימֵנִי", en: "From day until night you make an end of me. (שלם / complete)", hit: "תַּשְׁלִימֵנִי", hitEn: "make an end" },
  qillel: { ref: "Exod 21:17", he: "וּמְקַלֵּל אָבִיו וְאִמּוֹ מוֹת יוּמָת", en: "Whoever curses his father or his mother shall surely be put to death.", hit: "וּמְקַלֵּל" },
  arar: { ref: "Gen 3:14", he: "כִּי עָשִׂיתָ זֹּאת אָרוּר אַתָּה מִכָּל־הַבְּהֵמָה", en: "Because you have done this, cursed are you from all the livestock.", hit: "אָרוּר" },
  kipper: { ref: "Lev 16:34", he: "וְהָיְתָה־זֹּאת לָכֶם לְחֻקַּת עוֹלָם לְכַפֵּר עַל־בְּנֵי יִשְׂרָאֵל", en: "This shall be for you a statute forever, to make atonement for the children of Israel.", hit: "לְכַפֵּר" },
  hodia: { ref: "Exod 18:20", he: "וְהִזְהַרְתָּה אֶתְהֶם אֶת־הַחֻקִּים וְאֶת־הַתּוֹרֹת וְהוֹדַעְתָּ לָהֶם אֶת־הַדֶּרֶךְ", en: "You shall warn them of the statutes and the instructions, and make known to them the way.", hit: "וְהוֹדַעְתָּ" },
  sipper: { ref: "Exod 10:2", he: "וּלְמַעַן תְּסַפֵּר בְּאָזְנֵי בִנְךָ וּבֶן־בִּנְךָ", en: "And so that you may recount in the hearing of your son and your son’s son.", hit: "תְּסַפֵּר" },
  yadah: { ref: "Ps 118:21", he: "אוֹדְךָ כִּי עֲנִיתָנִי וַתְּהִי־לִי לִישׁוּעָה", en: "I thank you, for you answered me and became salvation for me.", hit: "אוֹדְךָ", hitEn: "thank you" },
  "anah-sing": { ref: "Exod 15:21", he: "וַתַּעַן לָהֶם מִרְיָם שִׁירוּ לַיהוָה כִּי־גָאֹה גָּאָה", en: "Miriam sang to them: “Sing to YHWH, for he is highly exalted.”", hit: "וַתַּעַן" },

  batah: { ref: "Ps 13:6", he: "וַאֲנִי בְּחַסְדְּךָ בָטַחְתִּי יָגֵל לִבִּי בִּישׁוּעָתֶךָ", en: "But I have trusted in your loyalty; my heart will exult in your salvation.", hit: "בָטַחְתִּי" },
  hasah: { ref: "Ps 2:12", he: "אַשְׁרֵי כָּל־חוֹסֵי בוֹ", en: "Happy are all who take refuge in him.", hit: "חוֹסֵי" },
  qawah: { ref: "Isa 40:31", he: "וְקוֹיֵ יְהוָה יַחֲלִיפוּ כֹחַ", en: "Those who wait for YHWH will renew strength.", hit: "וְקוֹיֵ" },
  bin: { ref: "Prov 2:5", he: "אָז תָּבִין יִרְאַת יְהוָה וְדַעַת אֱלֹהִים תִּמְצָא", en: "Then you will understand the fear of YHWH, and the knowledge of God you will find.", hit: "תָּבִין" },
  sakal: { ref: "Josh 1:8", he: "כִּי־אָז תַּצְלִיחַ אֶת־דְּרָכֶךָ וְאָז תַּשְׂכִּיל", en: "Then you will make your way prosperous, and then you will have insight.", hit: "תַּשְׂכִּיל", hitEn: "insight" },
  pachad: { ref: "Exod 15:16", he: "תִּפֹּל עֲלֵיהֶם אֵימָתָה וָפַחַד", en: "Terror and dread fall upon them.", hit: "וָפַחַד" },
  kashal: { ref: "Isa 8:15", he: "וְכָשְׁלוּ בָם רַבִּים וְנָפְלוּ וְנִשְׁבָּרוּ", en: "Many will stumble on them and fall and be broken.", hit: "וְכָשְׁלוּ" },
  taah: { ref: "Isa 53:6", he: "כֻּלָּנוּ כַּצֹּאן תָּעִינוּ", en: "All of us like sheep have gone astray.", hit: "תָּעִינוּ" },
  ragaz: { ref: "Ps 4:5", he: "רִגְזוּ וְאַל־תֶּחֱטָאוּ", en: "Tremble, and do not sin.", hit: "רִגְזוּ" },
  "hakam-v": { ref: "Prov 9:9", he: "תֵּן לְחָכָם וְיֶחְכַּם־עוֹד", en: "Give to a wise person, and he will become still wiser.", hit: "וְיֶחְכַּם" },
  yahal: { ref: "Ps 42:6", he: "הוֹחִילִי לֵאלֹהִים כִּי־עוֹד אוֹדֶנּוּ", en: "Hope in God, for I will yet praise him.", hit: "הוֹחִילִי" },
  shaqad: { ref: "Jer 1:12", he: "הֵיטַבְתָּ לִרְאוֹת כִּי־שֹׁקֵד אֲנִי עַל־דְּבָרִי לַעֲשֹׂתוֹ", en: "You have seen well, for I am watching over my word to do it.", hit: "שֹׁקֵד" },

  haphets: { ref: "Ps 37:4", he: "וְהִתְעַנַּג עַל־יְהוָה וְיִתֶּן־לְךָ מִשְׁאֲלֹת לִבֶּךָ", en: "Delight yourself in YHWH, and he will give you the requests of your heart.", hit: "וְהִתְעַנַּג" },
  ratsah: { ref: "Ps 51:18", he: "כִּי לֹא־תַחְפֹּץ זֶבַח וְאֶתֵּנָה עוֹלָה לֹא תִרְצֶה", en: "For you do not delight in sacrifice, or I would give it; a burnt offering you will not accept.", hit: "תִרְצֶה" },
  hanan: { ref: "Num 6:25", he: "יָאֵר יְהוָה פָּנָיו אֵלֶיךָ וִיחֻנֶּךָּ", en: "YHWH make his face shine upon you and be gracious to you.", hit: "וִיחֻנֶּךָּ" },
  raham: { ref: "Exod 33:19", he: "וְרִחַמְתִּי אֶת־אֲשֶׁר אֲרַחֵם", en: "I will have compassion on whom I have compassion.", hit: "וְרִחַמְתִּי" },
  naham: { ref: "Gen 6:6", he: "וַיִּנָּחֶם יְהוָה כִּי־עָשָׂה אֶת־הָאָדָם בָּאָרֶץ", en: "YHWH regretted that he had made humankind on the earth.", hit: "וַיִּנָּחֶם", hitEn: "regretted" },
  samah: { ref: "Ps 97:1", he: "יְהוָה מָלָךְ תָּגֵל הָאָרֶץ יִשְׂמְחוּ אִיִּים רַבִּים", en: "YHWH reigns; let the earth exult; let many coastlands rejoice.", hit: "יִשְׂמְחוּ" },
  qana: { ref: "Exod 20:5", he: "כִּי אָנֹכִי יְהוָה אֱלֹהֶיךָ אֵל קַנָּא", en: "For I, YHWH your God, am a jealous God.", hit: "קַנָּא" },
  harah: { ref: "Exod 32:11", he: "לָמָה יְהוָה יֶחֱרֶה אַפְּךָ בְּעַמֶּךָ", en: "Why, YHWH, should your anger burn against your people?", hit: "יֶחֱרֶה" },
  abal: { ref: "Gen 37:34", he: "וַיִּקְרַע יַעֲקֹב שִׂמְלֹתָיו וַיָּשֶׂם שַׂק בְּמָתְנָיו וַיִּתְאַבֵּל עַל־בְּנוֹ יָמִים רַבִּים", en: "Jacob tore his garments, put sackcloth on his loins, and mourned for his son many days.", hit: "וַיִּתְאַבֵּל" },
  shir: { ref: "Exod 15:1", he: "אָז יָשִׁיר־מֹשֶׁה וּבְנֵי יִשְׂרָאֵל אֶת־הַשִּׁירָה הַזֹּאת לַיהוָה", en: "Then Moses and the children of Israel sang this song to YHWH.", hit: "יָשִׁיר" },
  gil: { ref: "Ps 2:11", he: "עִבְדוּ אֶת־יְהוָה בְּיִרְאָה וְגִילוּ בִּרְעָדָה", en: "Serve YHWH with fear, and rejoice with trembling.", hit: "וְגִילוּ" },
  ranan: { ref: "Isa 12:6", he: "צַהֲלִי וָרֹנִּי יוֹשֶׁבֶת צִיּוֹן", en: "Cry out and shout for joy, dweller of Zion.", hit: "וָרֹנִּי" },

  mashal: { ref: "Gen 1:18", he: "וְלִמְשֹׁל בַּיּוֹם וּבַלַּיְלָה וּלְהַבְדִּיל בֵּין הָאוֹר וּבֵין הַחֹשֶׁךְ", en: "To rule over the day and over the night, and to separate the light from the darkness.", hit: "וְלִמְשֹׁל" },
  nahag: { ref: "Exod 3:1", he: "וּמֹשֶׁה הָיָה רֹעֶה ... וַיִּנְהַג אֶת־הַצֹּאן אַחַר הַמִּדְבָּר", en: "Moses was shepherding … and he led the flock to the far side of the wilderness.", hit: "וַיִּנְהַג" },
  nahah: { ref: "Ps 23:3", he: "יַנְחֵנִי בְמַעְגְּלֵי־צֶדֶק לְמַעַן שְׁמוֹ", en: "He leads me in tracks of righteousness for his name’s sake.", hit: "יַנְחֵנִי" },
  kun: { ref: "Ps 93:1", he: "אַף־תִּכּוֹן תֵּבֵל בַּל־תִּמּוֹט", en: "The world is established; it will not be moved.", hit: "תִּכּוֹן" },
  haras: { ref: "Exod 15:7", he: "תַּהֲרֹס קָמֶיךָ תְּשַׁלַּח חֲרֹנְךָ יֹאכְלֵמוֹ כַּקַּשׁ", en: "You tear down those who rise against you; you send out your burning anger; it consumes them like stubble.", hit: "תַּהֲרֹס" },
  samak: { ref: "Lev 1:4", he: "וְסָמַךְ יָדוֹ עַל רֹאשׁ הָעֹלָה", en: "He shall lay his hand on the head of the burnt offering.", hit: "וְסָמַךְ", hitEn: "lay his hand" },
  yasad: { ref: "Ps 24:2", he: "כִּי־הוּא עַל־יַמִּים יְסָדָהּ וְעַל־נְהָרוֹת יְכוֹנְנֶהָ", en: "For he founded it upon the seas, and established it upon the rivers.", hit: "יְסָדָהּ" },
  radah: { ref: "Gen 1:28", he: "וּמִלְאוּ אֶת־הָאָרֶץ וְכִבְשֻׁהָ וּרְדוּ בִּדְגַת הַיָּם", en: "Fill the earth and subdue it, and have dominion over the fish of the sea.", hit: "וּרְדוּ" },
  amets: { ref: "Josh 1:9", he: "חֲזַק וֶאֱמָץ אַל־תַּעֲרֹץ וְאַל־תֵּחָת", en: "Be strong and courageous; do not be terrified and do not be dismayed.", hit: "וֶאֱמָץ" },
  sabal: { ref: "Isa 53:4", he: "אָכֵן חֳלָיֵנוּ הוּא נָשָׂא וּמַכְאֹבֵינוּ סְבָלָם", en: "Surely he has borne our sicknesses, and our pains — he carried them.", hit: "סְבָלָם" },
  nathats: { ref: "Exod 34:13", he: "כִּי אֶת־מִזְבְּחֹתָם תִּתֹּצוּן וְאֶת־מַצֵּבֹתָם תְּשַׁבֵּרוּן", en: "You shall tear down their altars and break their standing stones.", hit: "תִּתֹּצוּן" },
  "shakan-mishkan": { ref: "Exod 25:9", he: "כְּכֹל אֲשֶׁר אֲנִי מַרְאֶה אוֹתְךָ אֵת תַּבְנִית הַמִּשְׁכָּן", en: "According to all that I show you, the pattern of the tabernacle.", hit: "הַמִּשְׁכָּן" },
};

export function verseFor(id: string): VerseEx | undefined {
  return VERSES[id];
}
