/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlphabetRouteImport } from './routes/alphabet'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as KeepRouteImport } from './routes/keep'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as ListenIndexRouteImport } from './routes/listen/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GameChapterIndexRouteImport } from './routes/game/$chapter/index'
import { Route as GameChapterStageRouteImport } from './routes/game/$chapter/$stage'
import { Route as GameAlefbetIndexRouteImport } from './routes/game/alefbet/index'
import { Route as GameAlefbetLevelRouteImport } from './routes/game/alefbet/$level'
import { Route as GameArticleIndexRouteImport } from './routes/game/article/index'
import { Route as GameArticleUnitRouteImport } from './routes/game/article/$unit'
import { Route as GameCustomIndexRouteImport } from './routes/game/custom/index'
import { Route as GameCustomPlayRouteImport } from './routes/game/custom/play'
import { Route as GameLessonsIndexRouteImport } from './routes/game/lessons/index'
import { Route as GameNounsIndexRouteImport } from './routes/game/nouns/index'
import { Route as GameNounsUnitRouteImport } from './routes/game/nouns/$unit'
import { Route as GameSyllablesIndexRouteImport } from './routes/game/syllables/index'
import { Route as GameSyllablesUnitRouteImport } from './routes/game/syllables/$unit'
import { Route as ListenReadIndexRouteImport } from './routes/listen/read/index'
import { Route as GameLessonsTrackIndexRouteImport } from './routes/game/lessons/$track/index'
import { Route as GameLessonsTrackUnitRouteImport } from './routes/game/lessons/$track/$unit'
import { Route as ListenReadBookIndexRouteImport } from './routes/listen/read/$book/index'
import { Route as ListenReadBookChRouteImport } from './routes/listen/read/$book/$ch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphabetRoute = AlphabetRouteImport.update({
  id: '/alphabet',
  path: '/alphabet',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepRoute = KeepRouteImport.update({
  id: '/keep',
  path: '/keep',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenIndexRoute = ListenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListenRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterIndexRoute = GameChapterIndexRouteImport.update({
  id: '/game/$chapter/',
  path: '/game/$chapter/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameChapterStageRoute = GameChapterStageRouteImport.update({
  id: '/game/$chapter/$stage',
  path: '/game/$chapter/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAlefbetIndexRoute = GameAlefbetIndexRouteImport.update({
  id: '/game/alefbet/',
  path: '/game/alefbet/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameAlefbetLevelRoute = GameAlefbetLevelRouteImport.update({
  id: '/game/alefbet/$level',
  path: '/game/alefbet/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const GameArticleIndexRoute = GameArticleIndexRouteImport.update({
  id: '/game/article/',
  path: '/game/article/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameArticleUnitRoute = GameArticleUnitRouteImport.update({
  id: '/game/article/$unit',
  path: '/game/article/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCustomIndexRoute = GameCustomIndexRouteImport.update({
  id: '/game/custom/',
  path: '/game/custom/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCustomPlayRoute = GameCustomPlayRouteImport.update({
  id: '/game/custom/play',
  path: '/game/custom/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLessonsIndexRoute = GameLessonsIndexRouteImport.update({
  id: '/game/lessons/',
  path: '/game/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNounsIndexRoute = GameNounsIndexRouteImport.update({
  id: '/game/nouns/',
  path: '/game/nouns/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNounsUnitRoute = GameNounsUnitRouteImport.update({
  id: '/game/nouns/$unit',
  path: '/game/nouns/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSyllablesIndexRoute = GameSyllablesIndexRouteImport.update({
  id: '/game/syllables/',
  path: '/game/syllables/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSyllablesUnitRoute = GameSyllablesUnitRouteImport.update({
  id: '/game/syllables/$unit',
  path: '/game/syllables/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenReadIndexRoute = ListenReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => ListenRoute,
} as any)
const GameLessonsTrackIndexRoute = GameLessonsTrackIndexRouteImport.update({
  id: '/game/lessons/$track/',
  path: '/game/lessons/$track/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameLessonsTrackUnitRoute = GameLessonsTrackUnitRouteImport.update({
  id: '/game/lessons/$track/$unit',
  path: '/game/lessons/$track/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenReadBookIndexRoute = ListenReadBookIndexRouteImport.update({
  id: '/read/$book/',
  path: '/read/$book/',
  getParentRoute: () => ListenRoute,
} as any)
const ListenReadBookChRoute = ListenReadBookChRouteImport.update({
  id: '/read/$book/$ch',
  path: '/read/$book/$ch',
  getParentRoute: () => ListenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/ideas': typeof IdeasRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/listen': typeof ListenRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/rules': typeof RulesRoute
  '/write': typeof WriteRoute
  '/api/health': typeof ApiHealthRoute
  '/game/': typeof GameIndexRoute
  '/listen/': typeof ListenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/article/$unit': typeof GameArticleUnitRoute
  '/game/custom/play': typeof GameCustomPlayRoute
  '/game/nouns/$unit': typeof GameNounsUnitRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
  '/game/alefbet/': typeof GameAlefbetIndexRoute
  '/game/article/': typeof GameArticleIndexRoute
  '/game/custom/': typeof GameCustomIndexRoute
  '/game/lessons/': typeof GameLessonsIndexRoute
  '/game/nouns/': typeof GameNounsIndexRoute
  '/game/syllables/': typeof GameSyllablesIndexRoute
  '/listen/read/': typeof ListenReadIndexRoute
  '/game/lessons/$track/$unit': typeof GameLessonsTrackUnitRoute
  '/listen/read/$book/$ch': typeof ListenReadBookChRoute
  '/game/lessons/$track/': typeof GameLessonsTrackIndexRoute
  '/listen/read/$book/': typeof ListenReadBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/ideas': typeof IdeasRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/rules': typeof RulesRoute
  '/write': typeof WriteRoute
  '/api/health': typeof ApiHealthRoute
  '/game': typeof GameIndexRoute
  '/listen': typeof ListenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/article/$unit': typeof GameArticleUnitRoute
  '/game/custom/play': typeof GameCustomPlayRoute
  '/game/nouns/$unit': typeof GameNounsUnitRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter': typeof GameChapterIndexRoute
  '/game/alefbet': typeof GameAlefbetIndexRoute
  '/game/article': typeof GameArticleIndexRoute
  '/game/custom': typeof GameCustomIndexRoute
  '/game/lessons': typeof GameLessonsIndexRoute
  '/game/nouns': typeof GameNounsIndexRoute
  '/game/syllables': typeof GameSyllablesIndexRoute
  '/listen/read': typeof ListenReadIndexRoute
  '/game/lessons/$track/$unit': typeof GameLessonsTrackUnitRoute
  '/listen/read/$book/$ch': typeof ListenReadBookChRoute
  '/game/lessons/$track': typeof GameLessonsTrackIndexRoute
  '/listen/read/$book': typeof ListenReadBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alphabet': typeof AlphabetRoute
  '/ask': typeof AskRoute
  '/browse': typeof BrowseRoute
  '/challenge': typeof ChallengeRoute
  '/drill': typeof DrillRoute
  '/guide': typeof GuideRoute
  '/ideas': typeof IdeasRoute
  '/keep': typeof KeepRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/listen': typeof ListenRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/rules': typeof RulesRoute
  '/write': typeof WriteRoute
  '/api/health': typeof ApiHealthRoute
  '/game/': typeof GameIndexRoute
  '/listen/': typeof ListenIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/game/$chapter/$stage': typeof GameChapterStageRoute
  '/game/alefbet/$level': typeof GameAlefbetLevelRoute
  '/game/article/$unit': typeof GameArticleUnitRoute
  '/game/custom/play': typeof GameCustomPlayRoute
  '/game/nouns/$unit': typeof GameNounsUnitRoute
  '/game/syllables/$unit': typeof GameSyllablesUnitRoute
  '/game/$chapter/': typeof GameChapterIndexRoute
  '/game/alefbet/': typeof GameAlefbetIndexRoute
  '/game/article/': typeof GameArticleIndexRoute
  '/game/custom/': typeof GameCustomIndexRoute
  '/game/lessons/': typeof GameLessonsIndexRoute
  '/game/nouns/': typeof GameNounsIndexRoute
  '/game/syllables/': typeof GameSyllablesIndexRoute
  '/listen/read/': typeof ListenReadIndexRoute
  '/game/lessons/$track/$unit': typeof GameLessonsTrackUnitRoute
  '/listen/read/$book/$ch': typeof ListenReadBookChRoute
  '/game/lessons/$track/': typeof GameLessonsTrackIndexRoute
  '/listen/read/$book/': typeof ListenReadBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/ask'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/ideas'
    | '/keep'
    | '/leaderboard'
    | '/legal'
    | '/listen'
    | '/login'
    | '/match'
    | '/quiz'
    | '/reset-password'
    | '/rewards'
    | '/rules'
    | '/write'
    | '/api/health'
    | '/game/'
    | '/listen/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/article/$unit'
    | '/game/custom/play'
    | '/game/nouns/$unit'
    | '/game/syllables/$unit'
    | '/game/$chapter/'
    | '/game/alefbet/'
    | '/game/article/'
    | '/game/custom/'
    | '/game/lessons/'
    | '/game/nouns/'
    | '/game/syllables/'
    | '/listen/read/'
    | '/game/lessons/$track/$unit'
    | '/listen/read/$book/$ch'
    | '/game/lessons/$track/'
    | '/listen/read/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alphabet'
    | '/ask'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/ideas'
    | '/keep'
    | '/leaderboard'
    | '/legal'
    | '/login'
    | '/match'
    | '/quiz'
    | '/reset-password'
    | '/rewards'
    | '/rules'
    | '/write'
    | '/api/health'
    | '/game'
    | '/listen'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/article/$unit'
    | '/game/custom/play'
    | '/game/nouns/$unit'
    | '/game/syllables/$unit'
    | '/game/$chapter'
    | '/game/alefbet'
    | '/game/article'
    | '/game/custom'
    | '/game/lessons'
    | '/game/nouns'
    | '/game/syllables'
    | '/listen/read'
    | '/game/lessons/$track/$unit'
    | '/listen/read/$book/$ch'
    | '/game/lessons/$track'
    | '/listen/read/$book'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alphabet'
    | '/ask'
    | '/browse'
    | '/challenge'
    | '/drill'
    | '/guide'
    | '/ideas'
    | '/keep'
    | '/leaderboard'
    | '/legal'
    | '/listen'
    | '/login'
    | '/match'
    | '/quiz'
    | '/reset-password'
    | '/rewards'
    | '/rules'
    | '/write'
    | '/api/health'
    | '/game/'
    | '/listen/'
    | '/api/auth/$'
    | '/game/$chapter/$stage'
    | '/game/alefbet/$level'
    | '/game/article/$unit'
    | '/game/custom/play'
    | '/game/nouns/$unit'
    | '/game/syllables/$unit'
    | '/game/$chapter/'
    | '/game/alefbet/'
    | '/game/article/'
    | '/game/custom/'
    | '/game/lessons/'
    | '/game/nouns/'
    | '/game/syllables/'
    | '/listen/read/'
    | '/game/lessons/$track/$unit'
    | '/listen/read/$book/$ch'
    | '/game/lessons/$track/'
    | '/listen/read/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlphabetRoute: typeof AlphabetRoute
  AskRoute: typeof AskRoute
  BrowseRoute: typeof BrowseRoute
  ChallengeRoute: typeof ChallengeRoute
  DrillRoute: typeof DrillRoute
  GuideRoute: typeof GuideRoute
  IdeasRoute: typeof IdeasRoute
  KeepRoute: typeof KeepRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRoute
  ListenRoute: typeof ListenRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  RulesRoute: typeof RulesRoute
  WriteRoute: typeof WriteRoute
  ApiHealthRoute: typeof ApiHealthRoute
  GameIndexRoute: typeof GameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GameChapterStageRoute: typeof GameChapterStageRoute
  GameAlefbetLevelRoute: typeof GameAlefbetLevelRoute
  GameArticleUnitRoute: typeof GameArticleUnitRoute
  GameCustomPlayRoute: typeof GameCustomPlayRoute
  GameNounsUnitRoute: typeof GameNounsUnitRoute
  GameSyllablesUnitRoute: typeof GameSyllablesUnitRoute
  GameChapterIndexRoute: typeof GameChapterIndexRoute
  GameAlefbetIndexRoute: typeof GameAlefbetIndexRoute
  GameArticleIndexRoute: typeof GameArticleIndexRoute
  GameCustomIndexRoute: typeof GameCustomIndexRoute
  GameLessonsIndexRoute: typeof GameLessonsIndexRoute
  GameNounsIndexRoute: typeof GameNounsIndexRoute
  GameSyllablesIndexRoute: typeof GameSyllablesIndexRoute
  GameLessonsTrackUnitRoute: typeof GameLessonsTrackUnitRoute
  GameLessonsTrackIndexRoute: typeof GameLessonsTrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphabet': {
      id: '/alphabet'
      path: '/alphabet'
      fullPath: '/alphabet'
      preLoaderRoute: typeof AlphabetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keep': {
      id: '/keep'
      path: '/keep'
      fullPath: '/keep'
      preLoaderRoute: typeof KeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/': {
      id: '/listen/'
      path: '/'
      fullPath: '/listen/'
      preLoaderRoute: typeof ListenIndexRouteImport
      parentRoute: typeof ListenRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/': {
      id: '/game/$chapter/'
      path: '/game/$chapter'
      fullPath: '/game/$chapter/'
      preLoaderRoute: typeof GameChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$chapter/$stage': {
      id: '/game/$chapter/$stage'
      path: '/game/$chapter/$stage'
      fullPath: '/game/$chapter/$stage'
      preLoaderRoute: typeof GameChapterStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/alefbet/': {
      id: '/game/alefbet/'
      path: '/game/alefbet'
      fullPath: '/game/alefbet/'
      preLoaderRoute: typeof GameAlefbetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/alefbet/$level': {
      id: '/game/alefbet/$level'
      path: '/game/alefbet/$level'
      fullPath: '/game/alefbet/$level'
      preLoaderRoute: typeof GameAlefbetLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/article/': {
      id: '/game/article/'
      path: '/game/article'
      fullPath: '/game/article/'
      preLoaderRoute: typeof GameArticleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/article/$unit': {
      id: '/game/article/$unit'
      path: '/game/article/$unit'
      fullPath: '/game/article/$unit'
      preLoaderRoute: typeof GameArticleUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/custom/': {
      id: '/game/custom/'
      path: '/game/custom'
      fullPath: '/game/custom/'
      preLoaderRoute: typeof GameCustomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/custom/play': {
      id: '/game/custom/play'
      path: '/game/custom/play'
      fullPath: '/game/custom/play'
      preLoaderRoute: typeof GameCustomPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/lessons/': {
      id: '/game/lessons/'
      path: '/game/lessons'
      fullPath: '/game/lessons/'
      preLoaderRoute: typeof GameLessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/nouns/': {
      id: '/game/nouns/'
      path: '/game/nouns'
      fullPath: '/game/nouns/'
      preLoaderRoute: typeof GameNounsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/nouns/$unit': {
      id: '/game/nouns/$unit'
      path: '/game/nouns/$unit'
      fullPath: '/game/nouns/$unit'
      preLoaderRoute: typeof GameNounsUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/syllables/': {
      id: '/game/syllables/'
      path: '/game/syllables'
      fullPath: '/game/syllables/'
      preLoaderRoute: typeof GameSyllablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/syllables/$unit': {
      id: '/game/syllables/$unit'
      path: '/game/syllables/$unit'
      fullPath: '/game/syllables/$unit'
      preLoaderRoute: typeof GameSyllablesUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/read/': {
      id: '/listen/read/'
      path: '/read'
      fullPath: '/listen/read/'
      preLoaderRoute: typeof ListenReadIndexRouteImport
      parentRoute: typeof ListenRoute
    }
    '/game/lessons/$track/': {
      id: '/game/lessons/$track/'
      path: '/game/lessons/$track'
      fullPath: '/game/lessons/$track/'
      preLoaderRoute: typeof GameLessonsTrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/lessons/$track/$unit': {
      id: '/game/lessons/$track/$unit'
      path: '/game/lessons/$track/$unit'
      fullPath: '/game/lessons/$track/$unit'
      preLoaderRoute: typeof GameLessonsTrackUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/read/$book/': {
      id: '/listen/read/$book/'
      path: '/read/$book'
      fullPath: '/listen/read/$book/'
      preLoaderRoute: typeof ListenReadBookIndexRouteImport
      parentRoute: typeof ListenRoute
    }
    '/listen/read/$book/$ch': {
      id: '/listen/read/$book/$ch'
      path: '/read/$book/$ch'
      fullPath: '/listen/read/$book/$ch'
      preLoaderRoute: typeof ListenReadBookChRouteImport
      parentRoute: typeof ListenRoute
    }
  }
}

interface ListenRouteChildren {
  ListenIndexRoute: typeof ListenIndexRoute
  ListenReadIndexRoute: typeof ListenReadIndexRoute
  ListenReadBookChRoute: typeof ListenReadBookChRoute
  ListenReadBookIndexRoute: typeof ListenReadBookIndexRoute
}

const ListenRouteChildren: ListenRouteChildren = {
  ListenIndexRoute: ListenIndexRoute,
  ListenReadIndexRoute: ListenReadIndexRoute,
  ListenReadBookChRoute: ListenReadBookChRoute,
  ListenReadBookIndexRoute: ListenReadBookIndexRoute,
}

const ListenRouteWithChildren =
  ListenRoute._addFileChildren(ListenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlphabetRoute: AlphabetRoute,
  AskRoute: AskRoute,
  BrowseRoute: BrowseRoute,
  ChallengeRoute: ChallengeRoute,
  DrillRoute: DrillRoute,
  GuideRoute: GuideRoute,
  IdeasRoute: IdeasRoute,
  KeepRoute: KeepRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRoute,
  ListenRoute: ListenRouteWithChildren,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  RulesRoute: RulesRoute,
  WriteRoute: WriteRoute,
  ApiHealthRoute: ApiHealthRoute,
  GameIndexRoute: GameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GameChapterStageRoute: GameChapterStageRoute,
  GameAlefbetLevelRoute: GameAlefbetLevelRoute,
  GameArticleUnitRoute: GameArticleUnitRoute,
  GameCustomPlayRoute: GameCustomPlayRoute,
  GameNounsUnitRoute: GameNounsUnitRoute,
  GameSyllablesUnitRoute: GameSyllablesUnitRoute,
  GameChapterIndexRoute: GameChapterIndexRoute,
  GameAlefbetIndexRoute: GameAlefbetIndexRoute,
  GameArticleIndexRoute: GameArticleIndexRoute,
  GameCustomIndexRoute: GameCustomIndexRoute,
  GameLessonsIndexRoute: GameLessonsIndexRoute,
  GameNounsIndexRoute: GameNounsIndexRoute,
  GameSyllablesIndexRoute: GameSyllablesIndexRoute,
  GameLessonsTrackUnitRoute: GameLessonsTrackUnitRoute,
  GameLessonsTrackIndexRoute: GameLessonsTrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
